feat(@astral/ui, Theme): Декларация темы и styled через module augmentation
kaluga-astral/frontend pull request #100
Opened 2022-02-17 13:29 UTC by Nikita-Smirnov

2022-02-17 13:34 UTC, merkelAlbert approved these changes

2022-02-18 08:01 UTC, merkelAlbert approved these changes

2022-02-18 08:02 UTC, merkelAlbert approved these changes

2022-02-18 08:05 UTC, merkelAlbert approved these changes

2022-02-18 08:08 UTC, merkelAlbert approved these changes

2022-02-18 08:12 UTC, merkelAlbert approved these changes

2022-02-18 08:20 UTC, merkelAlbert approved these changes

2022-02-18 08:29 UTC, merkelAlbert approved these changes

2022-02-18 08:35 UTC, merkelAlbert approved these changes

2022-02-18 08:36 UTC, merkelAlbert approved these changes

2022-02-18 08:53 UTC, merkelAlbert commented
test

2022-02-18 08:56 UTC, merkelAlbert commented
test2

2022-02-18 09:09 UTC, merkelAlbert commented
test 5

2022-02-18 09:10 UTC, merkelAlbert reviewed
test

2022-02-18 09:10 UTC, merkelAlbert commented on packages/ui/src/declaration/emotion.d.ts
> +declare module '@emotion/react' {
test

2022-02-18 09:10 UTC, merkelAlbert commented on packages/ui/src/declaration/materialUi.d.ts
> +
test

2022-02-18 09:21 UTC, AndTem requested changes
Request

2022-02-18 09:22 UTC, AndTem commented on packages/ui/src/declaration/materialUi.d.ts
> +declare module '@mui/material/styles' {
test

2022-02-18 09:28 UTC, merkelAlbert commented
test

2022-02-18 11:18 UTC, AndTem commented on packages/ui/src/declaration/materialUi.d.ts
> +  export interface Theme
Здесь точно также надо сделать, как в emotion.d.ts.
И название файла в данной директории должно совпадать с названием модуля. То есть mui-material

2022-02-18 11:28 UTC, AndTem commented on packages/ui/src/declaration/materialUi.d.ts
> +  export interface Theme
@Nikita-Smirnov подумай, может быть можно как разрулить circle deps, а то код не синхронизированный получается

2022-02-18 11:29 UTC, Nikita-Smirnov commented on packages/ui/src/declaration/materialUi.d.ts
> +  export interface Theme
Хорошо

2022-02-18 11:30 UTC, AndTem commented on packages/ui/src/declaration/materialUi.d.ts
> +  export interface Theme
можно здесь оставить переопределение, а из theme нашего экспортить тему mui (которая здесь уже модифицирована)

2022-02-18 13:41 UTC, Nikita-Smirnov commented on packages/ui/src/declaration/materialUi.d.ts
> +  export interface Theme
Ок, поправил, но тогда тоже к самому первому замечанию вернемся, просто мне показалось, что при таком варианте неявная логика присвоения и может кого-то запутать.

2022-02-21 08:54 UTC, AndTem approved these changes

2022-02-21 08:54 UTC, merged