feat(UIKIT-571,Description): Изменены сценарии переноса текста
kaluga-astral/frontend pull request #1000
Opened 2024-06-13 07:59 UTC by pan1caisreal

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-06-13 09:27 UTC, mfrolov89 requested changes
1. Проговаривали что стоит добавить новые примеры в сторибук, где будет пример как для label, так и для value в многострочной вариации
2. Для label не должен применятся перенос текста, если он влезает и ширина контейнера не ограничена 
<img width="787" alt="Снимок экрана 2024-06-13 в 12 23 54" src="https://github.com/kaluga-astral/frontend/assets/47597207/596aa8f1-2836-4131-a240-608c71411046">

3. Не реализован перенос длинного неразрывного слова
<img width="734" alt="Снимок экрана 2024-06-13 в 12 25 49" src="https://github.com/kaluga-astral/frontend/assets/47597207/26b8d7c9-29e1-4216-882f-13fc0e008e5f">

2024-06-14 09:55 UTC, mfrolov89 requested changes

2024-06-14 09:55 UTC, mfrolov89 commented on packages/components/src/Description/Value/styles.ts
> +  min-width: 0;
какую проблему решает данное св-во?

2024-06-14 09:55 UTC, mfrolov89 commented on packages/components/src/Description/Value/styles.ts
> +  $canCopy: ValueProps['canCopy'];
сделай пропс опциональным, тогда не нужно будет прокидывать его когда он отсутствует или false
Секция   if (!canCopy) { ...

2024-06-14 09:55 UTC, mfrolov89 commented on packages/components/src/Description/Value/styles.ts
> +  $canCopy: ValueProps['canCopy'];
```suggestion
  $canCopy?: boolean;
```
https://kaluga-astral.github.io/style-guide/docs/rules/react/styled#%D1%82%D0%B8%D0%BF%D1%8B-%D0%B4%D0%BB%D1%8F-props-styled-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0-%D0%BD%D0%B5-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D1%8B-%D0%B7%D0%B0%D0%B2%D0%B8%D1%81%D0%B5%D1%82%D1%8C-%D0%BE%D1%82-props-%D0%BA%D0%BE%D1%80%D0%BD%D0%B5%D0%B2%D0%BE%D0%B3%D0%BE-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0

2024-06-14 09:55 UTC, mfrolov89 commented on packages/components/src/Description/styles.ts
> +  text-align: ${({ leader }) => (leader ? 'right' : 'left')};
```suggestion
  text-align: ${({ $leader }) => ($leader ? 'right' : 'left')};
```

Все пропсы, которые не должны попадать в dom помечаем символом $

2024-06-14 09:55 UTC, mfrolov89 commented on packages/components/src/Description/styles.ts
>    justifyContent?: 'space-between' | 'start';
добавь shouldForwardProp

2024-06-14 09:55 UTC, mfrolov89 commented on packages/components/src/Description/Name/styles.ts
> +  display: flex;
для чего нужен?

2024-06-14 09:55 UTC, mfrolov89 commented on packages/components/src/Description/Name/styles.ts
> +  text-align: left;
для чего нужен?

2024-06-14 09:55 UTC, mfrolov89 commented on packages/components/src/Description/Name/styles.ts
> +  flex-shrink: 0;
max-width не ограничил, проблема переполнения контейнера не решена

2024-06-14 09:55 UTC, mfrolov89 commented on packages/components/src/Description/Description.tsx
> +      <Wrapper leader={leader} justifyContent={justifyContent}>
```suggestion
      <Wrapper $leader={leader} $justifyContent={justifyContent}>
```

2024-06-14 09:55 UTC, mfrolov89 commented on packages/components/src/Description/Description.stories.tsx
> +const Label = styled('div')`
обертка не нужна, нужно стилизовать Description.Name

2024-06-14 11:30 UTC, pan1caisreal commented on packages/components/src/Description/Name/styles.ts
> +  text-align: left;
для кейса с leader
![image](https://github.com/kaluga-astral/frontend/assets/105650840/42d5e745-2806-4cb3-9764-a7b3ffa964da)

2024-06-14 13:11 UTC, mfrolov89 commented on packages/components/src/Description/Value/styles.ts
> +  cursor: ${({ $canCopy }) => ($canCopy ? 'pointer' : 'default')};
здесь тоже нужно добавить shouldForwardProp

2024-06-14 13:16 UTC, mfrolov89 commented on packages/components/src/Description/Name/styles.ts
> +  max-width: 93%;
с дизайнером обсудил это значение?

2024-06-14 13:22 UTC, mfrolov89 commented on packages/components/src/faker/fakerDescription.ts
> +import { faker } from '@faker-js/faker/locale/ru';
можно импортировать из корня
import { fakerRU } from '@faker-js/faker';

2024-06-14 13:32 UTC, mfrolov89 commented on packages/components/src/Description/Name/styles.ts
> +  text-align: left;
Стоит переделать, проблема в том, что на уровне обертки применяется text-aligh: right:
  text-align: ${({ $leader }) => ($leader ? 'right' : 'left')};
Удали оттуда этот код, тогда необходимость в этом костыле здесь отпадет. А это правило выравнивания задай для value, так как для него оно и нужно

2024-06-17 11:13 UTC, mfrolov89 approved these changes

2024-06-17 13:04 UTC, AndTem approved these changes

2024-06-17 13:40 UTC, merged