wip(UIKIT-1075,Description): Добавлен DescriptionList
kaluga-astral/frontend pull request #1009
Opened 2024-06-21 08:28 UTC by pan1caisreal

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-06-21 10:10 UTC, AndTem commented on packages/components/src/DescriptionList/DescriptionList.stories.tsx
> + * По дефолту ширина Label не ограничена, можно задать maxWidth для фиксированной длины
```suggestion
 * По дефолту ширина Name не ограничена, можно задать maxWidth для фиксированной длины
```

2024-06-21 10:11 UTC, AndTem commented on packages/components/src/DescriptionList/DescriptionList.stories.tsx
> +export const MaxWidth = () => {
```suggestion
export const NameMaxWidth = () => {
```

2024-06-21 10:12 UTC, AndTem commented on packages/components/src/DescriptionList/DescriptionList.stories.tsx
> +import { type Meta, type StoryObj } from '@storybook/react';
Не хватает еще story с separator

2024-06-21 10:15 UTC, AndTem commented on packages/components/src/DescriptionList/DescriptionList.stories.tsx
> +      value: 'ИНН юридического лица — последовательность из 10 арабских цифр',
Лучше продублируй кейс от сюда: https://main--61baeff6f06230003a88ef8a.chromatic.com/?path=/docs/components-description--docs#short%20label%20with%20long%20value
И описание story в этом же направлении сделай

2024-06-21 10:16 UTC, AndTem commented on packages/components/src/DescriptionList/DescriptionList.stories.tsx
> +  const items: DescriptionListProps['items'] = [
Для красоты можешь использовать вместо DescriptionListProps['items'] -> DescriptionItem[]

2024-06-21 10:17 UTC, AndTem requested changes

2024-06-21 10:17 UTC, AndTem commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +export type DescriptionItem = {
```suggestion
export type DescriptionListItem = {
```

2024-06-21 10:17 UTC, AndTem commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +export type DescriptionItem = {
Этот тип из пакета будет экспортироваться, нужен указатель на принадлежность к конкретному компоненту

2024-06-21 10:20 UTC, AndTem commented on packages/components/src/DescriptionList/DescriptionList.stories.tsx
> +/**
И сделать ссылку на компонент Description - пример: https://github.com/kaluga-astral/frontend/blob/main/packages/form/src/FormCodeField/FormCodeField.stories.tsx#L14

Что-то вроде: Компонент для упрощенного построения UI name: value, использующий внутри компонент Description (ссылка)

2024-06-21 10:21 UTC, AndTem commented on packages/components/src/DescriptionList/DescriptionList.stories.tsx
> +/**
И в самом компоненте Description тоже надо сделать ссылку на DexcriptionList, написать: используйте DescriptionList

2024-06-21 10:54 UTC, mfrolov89 commented on packages/components/src/DescriptionList/styles.ts
> +  row-gap: 8px;
По макету 4px

2024-06-21 10:57 UTC, mfrolov89 commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +export type DescriptionOptions = Pick<TypographyProps, 'color'> & {
Думаю нужно пикнуть пропсы из Description, а не описывать отдельно. Это связано с тем, что этот компонент использует Description и если там что-то изменится, то это должно отразиться и на DescriptionList

@AndTem

2024-06-21 10:58 UTC, AndTem commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +export type DescriptionOptions = Pick<TypographyProps, 'color'> & {
Согласен

2024-06-21 10:59 UTC, mfrolov89 commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +      {items.map((item, index) => (
деструктурируй item, чтобы каждый раз не ссылаться на него

2024-06-21 11:07 UTC, mfrolov89 commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +  justifyContent = 'start',
Если следовать логике из комментария про separator, то можно по аналогии поступить так же с justifyContent и leader. В этом случае нет необходимости получать пропсы, можно все засунуть в рест-оператор

Или в теории мы по умолчанию для листа могут быть другие параметры для списка? @AndTem, что думаешь?

2024-06-21 12:53 UTC, mfrolov89 commented on packages/components/src/index.ts
> +export * from './DescriptionList';
явный экспорт сделай
export {  DescriptionList, type ... } from './DescriptionList';

2024-06-21 12:54 UTC, AndTem requested changes

2024-06-21 12:54 UTC, AndTem commented on packages/components/src/DescriptionList/DescriptionList.stories.tsx
> +    <GridWrapper rowSpacing={3} container>
Обертка до сих пор осталась. Зачем?

2024-06-21 13:03 UTC, pan1caisreal commented on packages/components/src/DescriptionList/DescriptionList.stories.tsx
> +    <GridWrapper rowSpacing={3} container>
![image](https://github.com/kaluga-astral/frontend/assets/105650840/35d43d70-62ee-4a6d-a0c1-f2ebf8bd9ab2)
Убрал вроде

2024-06-21 13:06 UTC, AndTem commented on packages/components/src/DescriptionList/DescriptionList.stories.tsx
> +    <GridWrapper rowSpacing={3} container>
Зачем в Grid оборачивать?

2024-06-21 13:09 UTC, pan1caisreal commented on packages/components/src/DescriptionList/DescriptionList.stories.tsx
> +    <GridWrapper rowSpacing={3} container>
Я уже понял про что имелось ввиду, поправил

2024-06-21 13:11 UTC, AndTem commented on packages/components/src/index.ts
> +  DescriptionListItem,
Этого не нужно экспортировать

2024-06-24 11:41 UTC, mfrolov89 commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +   * @default tag
tag не может быть значением по умолчанию, так как это означает что по умолчанию сразу теги отображаем
Убери его

2024-06-24 11:42 UTC, mfrolov89 commented on packages/components/src/index.ts
> +  DescriptionListItem,
```suggestion
  type DescriptionListItem,
```

2024-06-24 11:43 UTC, mfrolov89 commented on packages/components/src/DescriptionList/styles.ts
> +export const Wrapper = styled.dl`
обнули дефолтные отступы

2024-06-24 11:44 UTC, mfrolov89 commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +   * Отображение Value в виде компонента Tag
```suggestion
   * Вариант отображения Value в списке
```

2024-06-24 12:04 UTC, mfrolov89 requested changes

2024-06-24 12:04 UTC, mfrolov89 commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +          key: `description-item-${index}`,
передача пропса key будет не нужна, в качестве ключа возьми например связку name:value

2024-06-24 12:04 UTC, mfrolov89 commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +          {variant ? (
когда будешь править логику, то задай приоритет для рендер пропса. Если он есть, то применяется он, потом уже проверка на variant

2024-06-24 12:04 UTC, mfrolov89 commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +          leader={props.leader}
используй деструктуризацию и сразу извлекай нужные тебе пропсы

2024-06-24 12:04 UTC, mfrolov89 commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +              canCopy={options?.canCopy}
деструктурировал options, все что не пришодилось поместил в рест и тут спредом прокинул

2024-06-24 12:05 UTC, mfrolov89 requested changes
Поправь название pr: wip нужно заменить на feat, указано не верное название компонента

2024-06-24 13:42 UTC, AndTem commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +  variant?: 'tag';
variant должен задаваться отдельно для каждого item

2024-06-25 08:54 UTC, AndTem commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +    value: ReactNode,
value должно быть первым параметром. Так DX приятнее потому, что value точно всегда будет использоваться, а вот options нет

2024-06-25 08:55 UTC, AndTem commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +  variant?: 'tag';
'tag' | 'default' должно быть

2024-06-25 09:02 UTC, mfrolov89 commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +  justifyContent,
justifyContent,
  leader,
  separator,
  
 замени на рест оператор, ты их в Description прокидываешь как есть, они больше нигде не используются

2024-06-25 09:03 UTC, mfrolov89 commented on packages/components/src/DescriptionList/DescriptionList.tsx
> +      value: ReactNode,
value лучше сделать первым аргументом

2024-06-25 10:38 UTC, mfrolov89 commented on packages/components/src/DescriptionList/DescriptionList.test.tsx
> +describe('DescriptionList', () => {
названия тестов не по гайду https://kaluga-astral.github.io/style-guide/docs/rules/tests/structure

2024-06-26 06:42 UTC, mfrolov89 requested changes

2024-06-26 06:42 UTC, mfrolov89 commented on packages/components/src/DescriptionList/DescriptionList.test.tsx
> +  it('Отображается указанный разделитель, если задан separator', () => {
```suggestion
  it('Разделитель, заданный через separator, отображается', () => {
```

2024-06-26 06:42 UTC, mfrolov89 commented on packages/components/src/DescriptionList/DescriptionList.test.tsx
> +    expect(renderProps[0].tagName).toBe('P');
Один тест должен стремиться к одной проверке, у тебя их тут 3. Достаточно прокинуть 1 элемент в компонент и проверить у него тэг.

2024-06-26 06:42 UTC, mfrolov89 commented on packages/components/src/DescriptionList/DescriptionList.test.tsx
> +    FAKE_ITEMS.forEach(({ value }) => {
Думаю можно сократить массив до 1 элемента. Нам главное проверить что пропс попал куда нужно и применился

2024-06-26 11:41 UTC, mfrolov89 approved these changes

2024-06-26 13:15 UTC, merged