feat(UIKIT-1324): Реализация кастомного хука счетчика секунд
kaluga-astral/frontend pull request #1026
Opened 2024-07-02 09:22 UTC by Ofigelov

Выделил отдельный сервис SecondsCountDown, для упрощения тестирования и для возможности его интеграции c mobx

# Чеклист

- [x] Написать тесты для реализованного функционала
- [x] Описать jsdoc для экспортируемых функций, компонентов
- [x] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [x] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-07-03 07:54 UTC, mfrolov89 requested changes

2024-07-03 07:54 UTC, mfrolov89 commented on packages/components/src/utils/date/format/formatDate/formatDate.ts
> -    .filter(Boolean)
уверен что можно убрать этот этап? если в маску прокинуь что-то не корректное, то код упадет на zeroPad

2024-07-03 07:54 UTC, mfrolov89 commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +export class SecondsCountDown {
Расположение в utils сомнительно, это должен быть сервис, в названии так же нужно указать такой постфикс

2024-07-03 07:54 UTC, mfrolov89 commented on packages/components/src/index.ts
> +export { SecondsCountDown } from './utils';
Кажется что хука вполне достаточно.

2024-07-03 07:54 UTC, mfrolov89 commented on packages/components/src/CodeField/ResendСodeButton/ResendСodeButton.tsx
> +   * метод вызываемый при перезапросе кода по кнопке
С большой буквы:
1. Единая стилистика
2. По правилам русского языка все таки предложения с большой буквы начинают

2024-07-03 07:54 UTC, mfrolov89 commented on packages/components/src/hooks/useSecondsCountDown/useSecondsCountDown.ts
> +type UseSecondsTimerOptions = Pick<
```suggestion
type UseSecondsTimerParams = Pick<
```

https://kaluga-astral.github.io/style-guide/docs/rules/react/hooks#%D1%82%D0%B8%D0%BF-%D0%B2%D1%85%D0%BE%D0%B4%D0%BD%D1%8B%D1%85-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2-%D1%85%D1%83%D0%BA%D0%B0-%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD-%D0%B8%D0%BC%D0%B5%D1%82%D1%8C-%D0%BF%D0%BE%D1%81%D1%82%D1%84%D0%B8%D0%BA%D1%81-params

2024-07-03 07:54 UTC, mfrolov89 commented on packages/components/src/hooks/useSecondsCountDown/useSecondsCountDown.ts
> +    /**
Типизацию нужно вынести в  type UseSecondsCountDownResult

2024-07-03 07:54 UTC, mfrolov89 commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +    return Math.max(+this.targetDate - +new Date(), 0);
```suggestion
    return Math.max(+this.targetDate - Date.now(), 0);
```

2024-07-03 07:54 UTC, mfrolov89 commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +  public reset = (value: Date | number) => {
может restart или rerun?

2024-07-03 07:54 UTC, mfrolov89 commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +  public reset = (value: Date | number) => {
Не луше ли принимать объект с targetDate и seconds, чтобы был тот же функционал, что и при инициализации?

2024-07-03 07:54 UTC, mfrolov89 commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +    this.targetDate =
по хорошему для targetDate стоит делать проверку на валидность даты

2024-07-03 07:54 UTC, mfrolov89 commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +    return formatDate(new Date(this.difference), 'mm:ss', ':');
формат лучше сделать настраиваемым, могут быть кейсы где минутами дело не обойдется

2024-07-03 07:54 UTC, mfrolov89 commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.test.ts
> +describe('SecondsCountDown tests', () => {
tests не нужен

2024-07-03 07:54 UTC, mfrolov89 commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.test.ts
> +  it('Значение seconds игнорируется и значение таймера при создании равно разнице текущей даты и указанной даты, и значение seconds игнорируется', () => {
```suggestion
  it('Значение seconds игнорируется при наличии targetDate', () => {
```

Может так?
Текущее название до конца не понял, очень много 'и'

2024-07-03 07:54 UTC, mfrolov89 commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.test.ts
> +  it('Флаг активности false при targetDate меньше текущей', () => {
Можно дописать слово "таймера" => "Флаг активности таймера" и вынести эти проверки в вложенный describe

2024-07-03 08:12 UTC, Ofigelov commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +export class SecondsCountDown {
кмк это не совсем сервис, т.к. для работы требуется создавать отдельный инстанс для каждого счетчика, а сервис это все таки то, что должно быть почти как синглтон сущность, и надо экземпляры сервиса раскидывать по приложению.

2024-07-03 08:15 UTC, Ofigelov commented on packages/components/src/utils/date/format/formatDate/formatDate.ts
> -    .filter(Boolean)
В данной задаче эта фильтрация помешала, т.к. результатом вычисления может быть число 0, и фильтрация через Boolean выкидывает его, хотя 0 это вполне валидное значение

2024-07-03 08:16 UTC, Ofigelov commented on packages/components/src/hooks/useSecondsCountDown/useSecondsCountDown.ts
> +    /**
А у нас разве есть в стайл гайде требование для того, чтобы типы для результатов хука всегда были бы отдельными?

2024-07-03 08:30 UTC, Ofigelov commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +  public reset = (value: Date | number) => {
1. ок
2. Будет слишком сложная заморочка с типизацией, которая будет сводиться к тому, что нужно передать либо число, либо дату. А это вполне неплохо выполняет юнион даты и числа. Результат тот же самый, сильно проще в реализации и поддержки

2024-07-03 08:31 UTC, Ofigelov commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +    return formatDate(new Date(this.difference), 'mm:ss', ':');
Тогда это будет счетчик времени, а задача на счетчик секунд. 
Когда будет требования, тогда и давай сделаем это, сейчас это будет просто нарушение принципа YAGNI

2024-07-03 08:37 UTC, Ofigelov commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.test.ts
> +  it('Флаг активности false при targetDate меньше текущей', () => {
Слово допишу, а вот группировку давай не будем делать? Это же не обязательное условие, там не так уж и много кейсов туда уйдет.

2024-07-04 06:11 UTC, mfrolov89 commented on packages/components/src/utils/date/format/formatDate/formatDate.ts
> -    .filter(Boolean)
Использовать Number.isInteger ?

2024-07-04 06:14 UTC, mfrolov89 commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.test.ts
> +  it('Флаг активности false при targetDate меньше текущей', () => {
Нет, просто предложение

2024-07-04 06:21 UTC, Ofigelov commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +    this.targetDate =
А точно нужно? Мы тогда ради этого станем зависимыми от dayjs(т.к. наша имющаяся проверка сделана через него), как будто ради такой мелочи не хотелось бы. Все таки не пользователь будет тут работать с датами, а разработчик.

2024-07-04 06:24 UTC, mfrolov89 commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +    return formatDate(new Date(this.difference), 'mm:ss', ':');
Либо  по коду что-то упускаю, но у тебя сейчас и без этого несоответствие названия класса и результата выполнения этого метода. Счетчик секунд должен возвращать одно значение, кол-во секунд,  а возвращаешь минуты:секунды. Согласно названию класса этот метод даже не нужен, метод difference должен просто возвращать разницу в секундах тогда

2024-07-04 06:42 UTC, Ofigelov commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +    return formatDate(new Date(this.difference), 'mm:ss', ':');
По моему опыту, счетчик секунд всегда отображается в формате минуты:секунды. Отображать тикающую число например от "300" не имеет смысла. В текущей ситуации, счетчик нужен для того, чтобы отображать оставшееся кол-во секунд до момента новой попытки повторной отправки смс с кодом/уведомлением. Я вижу, что максимально возможное значение, это 10минут, т.е. пользователь увидит "09:59".  И ключевое то, что секунды должны тикать. 
А в варианте который ты предложил, я бы тогда рассматривал то, что там вообще секунд может не быть. Например "До открытия нового функционала осталось 2 месяца, 5 дней". Но задачи такой нет, следовательно и поддерживать сейчас это я не вижу смысла.

2024-07-04 06:46 UTC, Ofigelov commented on packages/components/src/utils/date/format/formatDate/formatDate.ts
> -    .filter(Boolean)
Добавил

2024-07-04 08:42 UTC, mfrolov89 requested changes

2024-07-04 08:42 UTC, mfrolov89 commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +    this.targetDate =
Разработчик тоже человек) А так дата может быть и с бэка получена, например они могут присылать дату действия кода подверждения.

Вообще дата может быть и строкой, а с бэка она наверняка так и будет приходить, но ты не указал в типах string. Если все таки перекладывать на разработчика подготовку даты, и оставлять такую типизацию, то можно как минимум проверить что получили либо число, либо инстанс Date.

Не защитит от всего конечно, но хотя бы строку и прочу ерунду сразу сможем фильтровать.

2024-07-04 08:42 UTC, mfrolov89 commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +    return formatDate(new Date(this.difference), 'mm:ss', ':');
Класс должен быть более абстрактный, особенно с учетом того где он сейчас находится. Форматирование либо должно быть гибким (mm:ss может быть формат по дефолту), либо убирать такой функционал вообще. Иначе этот класс будет подвержен изменениям, так как требования могут меняться. То есть как минимум мы нарушим Open-Closed прицип.

2024-07-04 09:27 UTC, Ofigelov commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +    return formatDate(new Date(this.difference), 'mm:ss', ':');
Невозможно создать такой компонент, который совсем не будет меняться, к этому надо стремиться, но окончательно это невозможно. Нужно просто руководствоваться здравым смыслом, текущими требованиями, и возможными будущими требованиями.
Сейчас он выполняет ровно то, ради чего задумывался. Если сейчас его расширять, то придется решить довольно много разносторонних кейсов, например тот, что с помощью имеющегося метода создания текста в дате, мы не сможем показать нулевой день счетчика, это потребует менять formatDate, а ведь это же уже нарушение OCP. А что делать с тем, что для счетчика другого формата, потребуется выводить текстовую дату вообще в другом виде, т.е. чтобы можно было бы показать "2дня 5часов"? А что делать с тем, что нам наврядтли потребуется тикающие секунды в таком счетчике, тогда надо уменьшать период времени, раз в который это должно меняться. Считаю, что для умного счетчика времени надо делать куда больше функционала, и он будет сильно сложнее, и скорее всего это должен быть совсем другой класс.
Нам же это сейчас не надо? Вот и скажи, зачем нам сейчас решать проблемы, которые никого не беспокоят и скорее всего не побеспокоят?

2024-07-04 09:50 UTC, mfrolov89 commented on packages/components/src/index.ts
> +export { SecondsCountDown } from './utils';
нужно будет обсудить с @AndTem потому что класс в утилах это странновато, а текущее название без постфиксов не подходит, так как его легко перепутать с компонентом. Может у него будут какие мысли

2024-07-08 07:16 UTC, AndTem requested changes

2024-07-08 07:16 UTC, AndTem commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +    return formatDate(new Date(this.difference), 'mm:ss', ':');
Можно оставить как есть. В будущем просто опциональный параметр добавить, по необходимости

2024-07-08 07:16 UTC, AndTem commented on packages/components/src/utils/date/format/formatDate/formatDate.ts
> -    .filter(Boolean)
Тесты есть? ничего не сломал?

2024-07-08 07:16 UTC, AndTem commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +export type SecondsCountDownParams = {
countdown вроде как слитно пишется

2024-07-08 07:16 UTC, AndTem commented on packages/components/src/hooks/useSecondsCountDown/useSecondsCountDown.ts
> + *  хук, предоставляющий функционал с текстом убывающего времени
Максим оставлял коммент, что по правилам русского языка предложения с большой буквы начинаются

2024-07-08 07:16 UTC, AndTem commented on packages/components/src/hooks/useSecondsCountDown/useSecondsCountDown.ts
> +  )[0];
Стилистически крайне странная запись у тебя.
Ипользуй деструктуризацию

const [countDown] = useState()

2024-07-08 07:16 UTC, AndTem commented on packages/components/src/hooks/useSecondsCountDown/useSecondsCountDown.ts
> +export const useSecondsCountDown = ({
Надо stories реализовать для хука

2024-07-08 07:16 UTC, AndTem commented on packages/components/src/index.ts
> +export { SecondsCountDown } from './utils';
@Ofigelov когда тебе понадобиться этот сервис?
Есть планы создать пакет services, тогда он там должен будет находиться

2024-07-08 07:16 UTC, AndTem commented on packages/components/src/index.ts
> +export { SecondsCountDown } from './utils';
Если нужен уже сейчас, то добавь при экспорте префикс и постфикс: UNSTABLE_SecondsCountdownService

2024-07-08 07:24 UTC, Ofigelov commented on packages/components/src/index.ts
> +export { SecondsCountDown } from './utils';
У нас в проекте есть реализация по сути того же самого, я бы в рамках техдолга переехал бы на эту реализацию.

2024-07-08 07:29 UTC, AndTem commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +    this.targetDate =
@mfrolov89 тут же тип указан, не вижу смысла делать в js проверки типов.
Ответсвенность разраба будет.
Единственное, что можно проверить - это InvalidDate. Проверка простая - isNaN(Number(date))

2024-07-08 07:31 UTC, AndTem commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +  public reset = (value: Date | number) => {
Укажи везде в jsdoc number - это секунды или миллисекунды

2024-07-08 09:24 UTC, Ofigelov commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +  onUpdateText?: (text: string) => void;
Если в названии, то хотел подсветить, что работа будет именно с текстовым представлением счетчика.
Если в аргументе, то для упрощения взаимодействия с компонентом при интеграции, т.к. я ожидаю от него в результате именно готовый формат "мм:сс"

2024-07-08 09:28 UTC, AndTem commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +  onUpdateText?: (text: string) => void;
Название сейчас очень запутывает

2024-07-08 09:30 UTC, Ofigelov commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +    if (!this.isActive) {
Вроде итак решают снаружи, если передадут `isInitialActive: false`, то счетчик не будет тикать. Для возобновления надо будет запустить restart, и именно рестарт, потому что значение целевой даты может к этому моменту устареть.

2024-07-08 09:43 UTC, Ofigelov commented on packages/components/src/utils/date/format/formatDate/formatDate.ts
> -    .filter(Boolean)
В дата пикере есть тесты проверяющие текстовую дату, вроде все норм

2024-07-08 13:45 UTC, AndTem commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +  onUpdateText?: (text: string) => void;
up

2024-07-08 13:45 UTC, AndTem commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +    if (!this.isActive) {
Если будешь использовать в store, то может стать проблемой

2024-07-08 13:57 UTC, Ofigelov commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +  onUpdateText?: (text: string) => void;
не понимаю, в чем проблема? запутывает чем? какое название по твоему мнению подойдет лучше?

2024-07-08 14:18 UTC, Ofigelov commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +    if (!this.isActive) {
Не понимаю сути проблемы. Создать такой реактивный стор оч просто:
```ts
export const createCountDown = () => makeAutoObservable(new SecondsCountdown({ seconds: 90 }));
```

вот пример быстро на коленке накидал https://playcode.io/1931257

2024-07-10 06:30 UTC, AndTem commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +  onUpdateText?: (text: string) => void;
У тебя счетчик секунд. И тут какое то обновление текста

2024-07-12 05:28 UTC, Ofigelov commented on packages/components/src/utils/SecondsCountDown/SecondsCountDown.ts
> +  onUpdateText?: (text: string) => void;
переименовал в `onUpdateTextTime`

2024-07-12 11:40 UTC, AndTem approved these changes

2024-07-12 12:33 UTC, mfrolov89 approved these changes

2024-07-15 09:43 UTC, merged