wip(UIKIT-1565,PageHeader): Добавлена обработка обрезки названий файлов
kaluga-astral/frontend pull request #1028
Opened 2024-07-02 13:22 UTC by pan1caisreal

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-07-02 15:38 UTC, mfrolov89 requested changes
Забыл реэкспорт в корне

2024-07-02 15:38 UTC, mfrolov89 commented on packages/components/src/PageHeader/PageHeader.stories.tsx
> +export const fileExtension = () => (
Название с большой буквы

2024-07-02 15:38 UTC, mfrolov89 commented on packages/components/src/PageHeader/Filename/constants.ts
> +  '.example.conf',
начиная с этой строчки можно удалить все остальное

2024-07-02 15:38 UTC, mfrolov89 commented on packages/components/src/PageHeader/Filename/styles.ts
> +import { styled } from '../../styles/';
```suggestion
import { styled } from '../../styles';
```

2024-07-02 15:38 UTC, mfrolov89 commented on packages/components/src/PageHeader/Filename/Filename.tsx
> +export const Filename = ({ title }: FileProps) => {
```suggestion
export const FileName = ({ name }: FileNameProps) => {
```

2024-07-02 15:38 UTC, mfrolov89 commented on packages/components/src/PageHeader/Filename/Filename.tsx
> +export type FileProps = {
тип по названию должен совпадать с названием компонента и иметь постфикс Props

2024-07-02 15:38 UTC, mfrolov89 commented on packages/components/src/PageHeader/Filename/Filename.tsx
> +  const { getFileExtension } = useLogic();
хук лишний, достаточно было в utils вынести функцию

2024-07-02 15:38 UTC, mfrolov89 commented on packages/components/src/PageHeader/Filename/constants.ts
> +export const priorityExtensions: string[] = [
1. Название константы не по стандарту https://kaluga-astral.github.io/style-guide/docs/rules/constants
2. Название константы не соответствует содержимому, complex extensions подходит больше

2024-07-03 06:43 UTC, AndTem requested changes

2024-07-03 06:43 UTC, AndTem commented on packages/components/src/PageHeader/Filename/Filename.tsx
> +export const Filename = ({ name }: FileNameProps) => {
Storybook нужен свой компоненту

2024-07-03 06:43 UTC, AndTem commented on packages/components/src/PageHeader/Filename/Filename.tsx
> +      <OverflowTypography variant="inherit">{name}</OverflowTypography>
У тебя сейчас расширение попадает сюда. Не должно попадать

2024-07-03 06:43 UTC, AndTem commented on packages/components/src/PageHeader/Filename/styles.ts
> +export const Wrapper = styled.div`
Должен быть инлайн элемент мне кажется

2024-07-03 06:43 UTC, AndTem commented on packages/components/src/PageHeader/Filename/Filename.tsx
> +  name: string;
Считаю, что лучше использовать children

2024-07-03 06:43 UTC, AndTem commented on packages/components/src/PageHeader/Filename/Filename.tsx
> +export const Filename = ({ title }: FileProps) => {
@mfrolov89 допустимо использоваь одним словом filename: https://en.wikipedia.org/wiki/Filename

2024-07-03 06:44 UTC, AndTem commented on packages/components/src/PageHeader/PageHeader.stories.tsx
> +        <Filename
Возьми пример имени файла из комментария к задаче

2024-07-03 06:46 UTC, AndTem commented on packages/components/src/PageHeader/PageHeader.stories.tsx
> +    <PageHeader
Добавь кнопки, чтобы было более приближено к реальности

2024-07-03 06:46 UTC, AndTem commented on packages/components/src/PageHeader/Filename/Filename.tsx
> +      <OverflowTypography variant="inherit">{name}</OverflowTypography>
Сейчас лишний пробел добавляется после троеточия

2024-07-03 06:47 UTC, AndTem commented on packages/components/src/PageHeader/Filename/styles.ts
> +export const Wrapper = styled.div`
Или p тэг

2024-07-03 06:51 UTC, AndTem commented on packages/components/src/PageHeader/Filename/Filename.tsx
> +      <OverflowTypography variant="inherit">{name}</OverflowTypography>
Если имя файла будет короткое, то получишь дублирование.
В storybook кейс с котортким именем файла тоже покажи

2024-07-03 11:01 UTC, AndTem requested changes

2024-07-03 11:01 UTC, AndTem commented on packages/components/src/Filename/styles.ts
> +  max-width: 90%;
Не уверен, что это правильно. 10% - это на больших экранах большая величина

2024-07-03 11:01 UTC, AndTem commented on packages/components/src/Filename/styles.ts
> +  max-width: 90%;
Нужно вообще это ограничение на ширину?

2024-07-03 11:01 UTC, AndTem commented on packages/components/src/Filename/Filename.stories.tsx
> + * Filename аналогичен компоненту [OverflowTypography](/story/components-overflowtypography--docs)
Не аналогичен он.
Напиши для чего применяется и как работает

2024-07-03 11:02 UTC, AndTem commented on packages/components/src/Filename/Filename.stories.tsx
> +      '25.04.2024 г.txt',
```suggestion
      '25.04.2024.pdf',
```

2024-07-03 11:02 UTC, AndTem commented on packages/components/src/Filename/Filename.stories.tsx
> +      25.04.2024 г.xml.dist
```suggestion
      25.04.2024 г.pdf
```

2024-07-03 11:02 UTC, AndTem commented on packages/components/src/Filename/Filename.stories.tsx
> +      25.04.2024 г.xml.dist
Сначала надо прямые кейсы показать

2024-07-05 07:23 UTC, mfrolov89 requested changes

2024-07-05 07:23 UTC, mfrolov89 commented on packages/components/src/Filename/hooks/useLogic/useLogic.ts
> +  const [truncatedChildren, setTruncatedChildren] = useState<string>(children);
постфикс Children лучше заменить на что-то более говорящее

2024-07-05 07:23 UTC, mfrolov89 commented on packages/components/src/Filename/hooks/useLogic/useLogic.ts
> +    if (ref.current) {
если нет рефа, то вообще не вызывай функцию в еффекте

2024-07-05 07:23 UTC, mfrolov89 commented on packages/components/src/Filename/Filename.tsx
> +type FileElementProps = TooltipCustomizable & TypographyProps;
```suggestion
type FileElementProps = TypographyProps & {
  /**
   * Cпособ кастомизировать тултип при необходимости
   * @example <OverflowTypography tooltipProps={{placement: 'top-start'}} />
   */
  tooltipProps?: Omit<TooltipProps, 'children'>;
};
```

В данному случае нет необходимости создавать тип

2024-07-05 07:23 UTC, mfrolov89 commented on packages/components/src/Filename/Filename.tsx
> +export type FileNameProps = FileElementProps & {
Зачем нужен отдельный тип FileElementProps? Можно сразу описать FileNameProps

2024-07-05 07:23 UTC, mfrolov89 commented on packages/components/src/Filename/Filename.tsx
> +    const { ref } = useOverflowed(forwardedRef);
должен находится внутри useLogic

2024-07-05 07:23 UTC, mfrolov89 commented on packages/components/src/Filename/Filename.tsx
> +    if (truncatedChildren !== children) {
Вынеси как флаг в useLogic, а в рендере используй флаг в title. Если title не будет, то тултип не будет отображаться

2024-07-05 07:23 UTC, mfrolov89 commented on packages/components/src/Filename/Filename.tsx
> +    const typographyProps = {
инкарсулируй в useLogic

2024-07-09 08:52 UTC, mfrolov89 requested changes

2024-07-09 08:52 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/useLogic.ts
> +      const handleResize = debounce(
debounce не нужен, это дополнительная задержка для рассчета, в том числе и при первичном рендере

2024-07-09 08:52 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/useLogic.ts
> +    if (ref.current) {
удали проверку

2024-07-09 08:52 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/useLogic.ts
> +  const { ref } = useOverflowed(forwardedRef);
использовать этот хук для хранения  рефа не нужно, просто useRef

2024-07-12 08:59 UTC, mfrolov89 requested changes

2024-07-12 08:59 UTC, mfrolov89 commented on .cspell-ignore
> +еисжс
для этого слова локально отключи проверку, глобально его добавлять не нужно

2024-07-12 08:59 UTC, mfrolov89 commented on .cspell-ignore
> +еисжс
или замени название файла в примере

2024-07-12 08:59 UTC, mfrolov89 commented on packages/components/src/PageHeader/PageHeader.stories.tsx
> +export const PageHeaderFilenameDashboardStory = () => {
```suggestion
export const WithUseFilename = () => {
```

2024-07-12 08:59 UTC, mfrolov89 commented on packages/components/src/PageHeader/PageHeader.stories.tsx
> +export const PageHeaderFilenameDashboardStory = () => {
Думаю тут должен быть пример именно с PageHeader, а не такая огромная сторя

2024-07-12 08:59 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/utils/truncateString/truncateString.ts
> +  } else {
else не нужен

2024-07-12 08:59 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/utils/truncateString/truncateString.ts
> +    const baseName = fileName.slice(0, fileName.length - 2);
```suggestion
    const baseName = fileName.slice(0,  -2);
```

2024-07-12 08:59 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/utils/findExtension/findExtension.ts
> +      return ext;
fileExtension

2024-07-12 08:59 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/utils/findExtension/findExtension.ts
> +    const extension = filename.slice(extensionIndex);
```suggestion
    const fileExtension = filename.slice(extensionIndex);
```

2024-07-12 08:59 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/utils/truncateString/truncateString.ts
> +    return { baseName, ext };
ext в текущем контексте это сокращение от extension? Дай более явное название

2024-07-12 08:59 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/useLogic.ts
> +  forwardedRef: Ref<HTMLElement>,
лучше назвать просто ref

2024-07-12 08:59 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/useLogic.ts
> +  props: Omit<FileNameProps, 'children' | 'tooltipProps'>,
всю типизацию вынеси в UseLogicParams

2024-07-12 08:59 UTC, mfrolov89 commented on packages/components/src/Filename/Filename.stories.tsx
> +export const DataGridFilename = () => {
Можно переименовать в Example и сделать первой сторей

2024-07-12 09:05 UTC, pan1caisreal commented on packages/components/src/PageHeader/PageHeader.stories.tsx
> +export const PageHeaderFilenameDashboardStory = () => {
Тут сторя с sidebar, и показывает как при взаимодействии с ним работает filename. Пример с PageHeader он ниже есть File Extension

2024-07-12 12:34 UTC, mfrolov89 commented on packages/components/src/Filename/Filename.stories.tsx
> +import { styled } from '../styles/styled';
```suggestion
import { styled } from '../styles';
```

2024-07-12 12:37 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/utils/findExtension/findExtension.ts
> +      return ext;
UP!

2024-07-12 12:39 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/utils/truncateString/truncateString.ts
> +      fileName.length - fileExtension.length - SUFFIX_LENGTH,
```suggestion
      - fileExtension.length - SUFFIX_LENGTH,
```

2024-07-12 12:50 UTC, mfrolov89 requested changes

2024-07-12 12:50 UTC, mfrolov89 commented on packages/components/src/Filename/Filename.tsx
> +    const { typographyProps, isOverflowed, ExtensionProps } = useLogic({
```suggestion
    const { typographyProps, isOverflowed, extensionProps } = useLogic({
```

2024-07-12 12:50 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/useLogic.ts
> +  const ExtensionProps = {
лучше Wrapper сделай  typography и ему пробрасывай настройки, а внутри используй обычные span, которые унаследуют стили

2024-07-12 12:50 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/useLogic.ts
> +  props: Omit<FileNameProps, 'children' | 'tooltipProps' | 'style'>;
выглядит так себе, убери эту вложенность из props

2024-07-12 12:50 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/useLogic.ts
> +type UseLogicParams = {
попробуй подход, где прокидываешь все пропсы базового компонента и его тип берешь за основу

type UseLogicParams  = FileNameProps & { ref ... };

2024-07-15 09:28 UTC, mfrolov89 commented on packages/components/src/Filename/styles.ts
> +export const Wrapper = styled(Typography)`
```suggestion
export const StyledTypography = styled(Typography)`
```

2024-07-15 09:30 UTC, mfrolov89 commented on packages/components/src/Filename/Filename.tsx
> +        <Wrapper {...typographyProps}>
wrapper и typographyProps не соотносятся между собой никак, либо компонент должен называться StyledTypography или объект с пропсами wrapperProps, тогда связь что к чему относится будет видна. Конкретно в этом случае наверно лучше StyledTypography

2024-07-15 09:31 UTC, mfrolov89 commented on packages/components/src/Filename/styles.ts
> +export const Extension = styled.span`
откуда у span margin дефолтный? Думаю нужно сразу указывать span в компоненте

2024-07-15 09:32 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/useLogic.ts
> +    children: suffixWithExtension,
верни suffixWithExtension из хука, заворачивать один children не очень прозрачно

2024-07-15 09:34 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/useLogic.ts
> +    ...props,
возвращай из хука вычисляемые пропсы, все остальное сразу прокидывай в целевой компонент

2024-07-15 09:35 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/useLogic.ts
> +import { type FileNameProps } from '../Filename';
кажется порядок импортов нарушен
../ должен идти после ../../

2024-07-15 09:36 UTC, mfrolov89 commented on packages/components/src/Filename/useLogic/useLogic.ts
> +    baseNameProps,
```suggestion
    baseNameProps: { ... }
```

2024-07-16 06:27 UTC, mfrolov89 approved these changes

2024-07-16 06:29 UTC, merged