doc(UIKIT-1480): Отрефакторены все stories в новый формат
kaluga-astral/frontend pull request #1032
Opened 2024-07-05 08:49 UTC by MaksFett

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-07-05 11:24 UTC, KVPlotnikov commented on packages/components/src/Checkbox/Checkbox.stories.tsx
> +export const Checkbox_Basic = () => (
Именование stories - PascalCase

2024-07-05 11:24 UTC, KVPlotnikov commented on packages/components/src/Checkbox/Checkbox.stories.tsx
> +export const Checkbox_Label = () => (
аналогично - неправильное именование

2024-07-05 11:33 UTC, KVPlotnikov commented on packages/components/src/LegacyGrid/LegacyGrid.stories.tsx
> +export const Grid_Container_Props = () => (
PascalCase

2024-07-05 11:57 UTC, KVPlotnikov commented on packages/components/src/CheckableTag/CheckableTag.stories.tsx
> +export const ShowcaseColor = () => {
Первая стори должна быть Example
https://github.com/kaluga-astral/frontend/blob/main/CONTRIBUTING.md#example

2024-07-05 11:58 UTC, KVPlotnikov commented on packages/components/src/Checkbox/Checkbox.stories.tsx
> + * Checkbox — это элемент графического пользовательского интерфейса, позволяющий пользователю управлять параметром с двумя состояниями — ☑ включено и ☐ отключено.
Описание не обязательно

2024-07-05 12:10 UTC, KVPlotnikov commented on packages/components/src/DatePicker/DatePicker.stories.tsx
> +export const Showcase = () => (
лучше было просто Showcase переименовать в Example

2024-07-05 12:14 UTC, KVPlotnikov commented on packages/components/src/DateRangePicker/DateRangePicker.stories.tsx
> +export const Example = Template.bind({});
тоже лучше было Showcase переименовать в Example

2024-07-05 12:18 UTC, KVPlotnikov commented on packages/components/src/IconDropdownButton/IconDropdownButton.stories.tsx
> +export const Example = () => (
Это основная стори для IconDropDownButton, а внутри только DataGrid?

2024-07-05 12:18 UTC, MaksFett commented on packages/components/src/DatePicker/DatePicker.stories.tsx
> +export const Showcase = () => (
В коде до этого уже был Example, его убрать или Showcase как-то по-другому переименовать?

2024-07-05 12:19 UTC, KVPlotnikov commented on packages/components/src/LegacyGrid/LegacyGrid.stories.tsx
> +export const Grid_Children_Props = () => (
PascalCase

2024-07-05 12:19 UTC, KVPlotnikov commented on packages/components/src/LegacyGrid/LegacyGrid.stories.tsx
> +export const Breakpoints_Props = () => (
PascalCase

2024-07-05 12:24 UTC, MaksFett commented on packages/components/src/IconDropdownButton/IconDropdownButton.stories.tsx
> +export const Example = () => (
Изначально так было, до моей правки. В самом DataGrid, в columns, есть IconDropdownButton, наверное поэтому он тут как пример

2024-07-10 07:06 UTC, pan1caisreal requested changes

2024-07-10 07:06 UTC, pan1caisreal commented on packages/components/src/DateRangePicker/DateRangePicker.stories.tsx
> +import { type Meta, type StoryFn, type StoryObj } from '@storybook/react';
storyFn

2024-07-12 06:09 UTC, pan1caisreal approved these changes

2024-07-12 06:51 UTC, pan1caisreal commented on packages/components/src/Autocomplete/Autocomplete.stories.tsx
> +    getOptionLabel: (params: IOption) => params.title,
Исправь название типа, должно быть без буквы I

2024-07-17 09:25 UTC, mfrolov89 requested changes

2024-07-17 09:25 UTC, mfrolov89 commented on packages/components/src/IconDropdownButton/IconDropdownButton.stories.tsx
> +    <IconDropdownButton
Disabled и Loading в отдельные стори нужно оформить

2024-07-17 09:25 UTC, mfrolov89 commented on packages/components/src/LegacyGrid/LegacyGrid.stories.tsx
LegacyGrid пометь как deprecated и в описании укажи что компонент устарел. Пример оформления можно посмотреть здесь https://main--61baeff6f06230003a88ef8a.chromatic.com/?path=/docs/components-datagrid--docs

2024-07-17 09:25 UTC, mfrolov89 commented on packages/form/src/FormCheckbox/FormCheckbox.stories.tsx
Сделай отдельные стори на disabled и required

2024-07-22 05:54 UTC, mfrolov89 commented on packages/components/src/Avatar/Avatar.stories.tsx
> +    <Avatar style={{ width: 24, height: 24 }}>АЛ</Avatar>
речь шла про пропс size, который есть у аватара. но кажется он не принимает small,medium и large, в таком случае удали сторю

2024-07-22 05:55 UTC, mfrolov89 commented on packages/form/src/FormCheckbox/FormCheckbox.stories.tsx
up

2024-07-22 05:56 UTC, mfrolov89 commented on packages/components/src/LegacyGrid/LegacyGrid.stories.tsx
> + * **Используйте [NewDataGrid](/story/components-newdatagrid--docs), который построен на css grid.**
```suggestion
```

2024-07-22 05:56 UTC, mfrolov89 commented on packages/components/src/LegacyGrid/LegacyGrid.tsx
> + * Используйте NewDateGrid
```suggestion
 * Используйте Grid
```

2024-07-22 11:20 UTC, mfrolov89 approved these changes

2024-07-22 11:24 UTC, merged