feat(UIKIT-1554,NewDataGrid): Реализован новый компонент NewDataGrid
kaluga-astral/frontend pull request #1035
Opened 2024-07-08 13:23 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-07-09 06:40 UTC, AndTem commented
- Полоска в футере пропала:
<img width="1088" alt="Снимок экрана 2024-07-09 в 09 37 10" src="https://github.com/kaluga-astral/frontend/assets/23665108/db215222-6e65-4758-8154-c13ce66664cf">
<img width="1048" alt="Снимок экрана 2024-07-09 в 09 37 36" src="https://github.com/kaluga-astral/frontend/assets/23665108/04ea4cf0-dbf9-45fd-b6a3-f2a19bb91875">

- При переходе в пагинации по страницам не отображается лоадер в футере
<img width="1056" alt="Снимок экрана 2024-07-09 в 09 38 22" src="https://github.com/kaluga-astral/frontend/assets/23665108/c6980c82-66fb-484f-b3d3-261356298f99">

- Макетов для ошибки еще нет, но думаю, что хедер рендерить не нужно
- 
<img width="1036" alt="Снимок экрана 2024-07-09 в 09 39 40" src="https://github.com/kaluga-astral/frontend/assets/23665108/996e7857-f2c8-4cc7-9437-d655ab73e96f">

2024-07-09 06:44 UTC, mfrolov89 commented
>>> При переходе в пагинации по страницам не отображается лоадер в футере
Я его вообще удалил и заменил на стадартный из ContentState

>>> Макетов для ошибки еще нет, но думаю, что хедер рендерить не нужно
Тогда мы не сможем использовать ContentState, так как лоадер должен быть под заголовком

2024-07-09 07:01 UTC, AndTem requested changes

2024-07-09 07:01 UTC, AndTem commented on packages/components/src/NewDataGrid/Row/useLogic/useLogic.ts
> +      title: isDisabled && disabledReason,
А это нормально, что в title может false попасть?

2024-07-09 07:01 UTC, AndTem commented on packages/components/src/NewDataGrid/types.ts
> +   * CSS свойство ширины ячейки
В storybook надо отдельную story по работе с шириной

2024-07-09 07:02 UTC, AndTem commented
> > > > При переходе в пагинации по страницам не отображается лоадер в футере
> > > > Я его вообще удалил и заменил на стадартный из ContentState
> 
> > > > Макетов для ошибки еще нет, но думаю, что хедер рендерить не нужно
> > > > Тогда мы не сможем использовать ContentState, так как лоадер должен быть под заголовком

1. Лоадер полоска должны быть
2. Ну не может значит

2024-07-09 07:10 UTC, mfrolov89 commented on packages/components/src/NewDataGrid/Row/useLogic/useLogic.ts
> +      title: isDisabled && disabledReason,
Это сделано чтобы в рендере не было условий

if (isDisabled) return <Tooltip><Component /></Tooltip>;
return <Component />

Ошибок по типизации нет, в тултипе есть простой if на проверку title. Т.е когда мы пишем как я показал выше, мы дублируем проверку, заложенную в тултип

2024-07-09 07:17 UTC, mfrolov89 commented on packages/components/src/NewDataGrid/NewDataGrid.tsx
> +  onRetry: () => void;
Api аналогично DataList, будет странно что схожие компоненты, а названия пропсов для одного и того же различаются, какая-то общая стилистика и правила должны быть. Если применять тут другое название, то по хорошему нужно создавать задачу и на правку в DataList

2024-07-09 07:19 UTC, mfrolov89 commented on packages/components/src/NewDataGrid/NoData/styles.ts
> +  position: absolute;
Видимо в стили сюда не залез, посмотрел что используется div и закрыл

2024-07-09 07:23 UTC, mfrolov89 commented on packages/components/src/NewDataGrid/Body/styles.tsx
> +    $isEmpty ? `${ROW_HEIGHT * $minDisplayRows}px` : '100%'};
Говорили что апи должно максимально соотвествовать старому компоненту, поэтому не стал удалять этот момент. Для пользователей эта та же таблица по сути. Думаю им удобнее оперировать кол-вом строк при указании высоты, а не высчитывать в пикселях высоту и стилизовать этот компонент в месте использования

2024-07-09 09:51 UTC, mfrolov89 commented on packages/components/src/NewDataGrid/Body/utils/checkIsDisabled/checkIsDisabled.ts
> +export const checkIsDisabled = (
используется в Body

2024-07-09 09:59 UTC, AndTem commented on packages/components/src/NewDataGrid/Body/utils/checkIsDisabled/checkIsDisabled.ts
> +export const checkIsDisabled = (
Ожидал увидеть всю логику в useLogic, поэтому и не увидел

2024-07-09 11:59 UTC, mfrolov89 commented on packages/components/src/NewDataGrid/Body/Body.tsx
> +        isLoading={isLoading && isNoData}
Если есть данные в таблице, то лоадер не отображается, как раз покроет кейс, что при переходе по страницам нужно отображать линейный лоадер

2024-07-09 12:56 UTC, AndTem requested changes

2024-07-09 12:56 UTC, AndTem commented on packages/components/src/DataGrid/DataGrid.stories.tsx
> + * **Используйте NewDataGrid, который построен на css grid.**
Сделай NewDataGrid ссылкой

2024-07-09 12:56 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.test.tsx
> +  it('Лоадер отображается при isLoading=true', async () => {
Нужно уточнить что при первом отображении

2024-07-09 13:08 UTC, AndTem commented on packages/components/src/DataGrid/DataGrid.stories.tsx
> + * **Компонент устарел и больше не будет поддерживаться.**
```suggestion
 * **❗️❗️❗️ Компонент устарел и больше не будет поддерживаться.**
```

2024-07-10 05:58 UTC, AndTem commented on packages/components/src/DataGrid/DataGrid.stories.tsx
> + * **Используйте [NewDataGrid](https://main--61baeff6f06230003a88ef8a.chromatic.com/?path=/docs/components-newdatagrid--docs), который построен на css grid.**
Тут не должно быть домена.
Смотри как сделано в FormTextField

2024-07-10 06:27 UTC, AndTem approved these changes

2024-07-10 09:09 UTC, merged