doc(UIKIT-1480): Переформатирован storybook в новый формат
kaluga-astral/frontend pull request #1037
Opened 2024-07-10 13:22 UTC by Uvoi

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-07-11 08:37 UTC, Bblchock requested changes

2024-07-11 14:40 UTC, Bblchock approved these changes

2024-07-12 07:52 UTC, mfrolov89 requested changes

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/MenuGroup/MenuGroup.stories.tsx
> +export { AoIcon, ApIcon, EdoIcon, KedoIcon, AsIcon, OfdIcon, Ap2Icon };
Не должны экспортироваться и отображаться в сторе, так как не имеют к ней отношения

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/MenuItem/MenuItem.stories.tsx
Удали tooltipPlacement="left" в сторе с disabled

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/PageHeader/PageHeader.stories.tsx
> + * “Второй” заголовок на странице.<br>
```suggestion
 * Область, для размещения дополнительных действий<br>
```

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/PageHeader/PageHeader.stories.tsx
> -export const TooltipSecondaryAction = () => (
верни эту сторю

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/PageHeader/PageHeader.stories.tsx
>      <PageHeader title="Очень_очень_очень_очень_длинный_заголовок" />
Укажи нормальный заголовок, пример с длинным заголовком идет ниже

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/Paper/Paper.stories.tsx
> +          <Typography variant="ui" color="grey" colorIntensity="900">
color и colorIntensity не нужны

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/Paper/Paper.stories.tsx
> +        </MenuItem>
Поправь форматирование меню, пунктов быть не должно

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/Paper/Paper.stories.tsx
> +        Пример использования 2: Выпадающий список (Dropdown)
```suggestion
       Выпадающий список (Dropdown)
```

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/Paper/Paper.stories.tsx
> +        Пример использования 1: Хедер (Header)
```suggestion
        Header
```

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/Paper/Paper.stories.tsx
> +      {/* elevation={0} = нет тени */}
тут эти пояснения не нужны

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/Paper/Paper.stories.tsx
> + */
Добавь сюда текст с описанием где используется в вариантах 0 и 1 (который был в первоначальной сторе)

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/Profile/Profile.stories.tsx
>  export const Showcase = () => {
Разбей на 3 стори: Example, WithAvatar, WithAnnotation

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/SwipeableDrawer/SwipeableDrawer.stories.tsx
> +      <Typography variant="h2" style={{ color: 'red' }}>
Перенеси это пояснение в jsdoc, пример оформления можно посмотреть тут: https://main--61baeff6f06230003a88ef8a.chromatic.com/?path=/docs/components-datagrid--docs

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/Switch/Switch.stories.tsx
> +    <Switch checked />
это отдельная сторя Checked

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/Switch/Switch.stories.tsx
> +    <Switch disabled />
Эти 2 примера нужно вынести в сторю Disabled

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/TagBadge/TagBadge.stories.tsx
> +export const Default = () => <TagBadge color="primary" badgeContent="12" />;
Нужно расположить после Example

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/TagBadge/TagBadge.stories.tsx
> +export const Color = () => (
В этой сторе укажи все доступные цвета для дефолтного variant  и сделай отдельную сторю с variant

2024-07-12 07:52 UTC, mfrolov89 commented on packages/components/src/ToggleButtonGroup/ToggleButtonGroup.stories.tsx
> +      <ToggleButtonGroup onChange={handleChange1} value={value1}>
этот пример не нужен

2024-07-15 10:18 UTC, mfrolov89 commented on packages/components/src/PageHeader/PageHeader.stories.tsx
> +export const TooltipSecondaryAction = () => (
```suggestion
/**
 * Для отображения Tooltip на заблокированном элементе необходимо использовать prop ```disableReason``` и ```disabled```.<br>
 * Так же можно выводить Tooltip на не заблокированном элементе с помощью prop ```note```
 */
export const TooltipSecondaryAction = () => (
```

2024-07-15 11:28 UTC, mfrolov89 requested changes

2024-07-15 11:28 UTC, mfrolov89 commented on packages/components/src/Paper/Paper.stories.tsx
> +          <Typography variant="h6" color="grey" colorIntensity="700">
```suggestion
          <Typography variant="h6">
```

2024-07-15 11:35 UTC, mfrolov89 commented on packages/components/src/TagBadge/TagBadge.stories.tsx
> +
```suggestion
// TODO Доработать сторю в рамках https://track.astral.ru/soft/browse/UIKIT-1639
```

2024-07-15 11:36 UTC, mfrolov89 approved these changes

2024-07-16 07:44 UTC, merged