feat(UIKIT-1555,NewDataGridInfinite): Реализован новый компонент NewDataGridInfinite
kaluga-astral/frontend pull request #1039
Opened 2024-07-11 08:04 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-07-11 09:10 UTC, AndTem commented
В Infinite надо добавить такой же лоадер при первой загрузке, как и в DataGrid

2024-07-11 09:17 UTC, AndTem requested changes

2024-07-11 09:17 UTC, AndTem commented on packages/components/src/NewDataGridInfinite/NewDataGridInfinite.test.tsx
> +  it('Лоадер отображается при isLoading=true', () => {
Здесь надо уточнить какой именно лоадер и при каких условиях

2024-07-11 09:17 UTC, AndTem commented on packages/components/src/NewDataGridInfinite/NewDataGridInfinite.test.tsx
> +  it(`Сообщение "${END_OF_SCROLL_MESSAGE}" отображается при достижении конца списка`, () => {
Думаю ты хочешь проверить, что "дефолтное сообщение отображается". Не надо сюда его значение подпихивать

2024-07-11 09:17 UTC, AndTem commented on packages/components/src/NewDataGridInfinite/Error/Error.tsx
> +    <Typography align="center">{ERROR_MESSAGE}</Typography>
Сообщение об ошибко должно снаружи приходить. Здесь просто дефолтное значение

2024-07-11 09:17 UTC, AndTem commented on packages/components/src/NewDataGridInfinite/Error/styles.ts
> +export const Item = styled.li`
```suggestion
export const Wrapper = styled.li`
```

2024-07-11 09:17 UTC, AndTem commented on packages/components/src/NewDataGridInfinite/styles.ts
> +export const FooterRow = styled.div`
```suggestion
export const FooterRow = styled.footer`
```

2024-07-11 10:52 UTC, mfrolov89 commented on packages/components/src/NewDataGridInfinite/Error/Error.tsx
> +    <Typography align="center">{ERROR_MESSAGE}</Typography>
Не уверен что решение должно быть в лоб. Это ошибка при подгрузке данных при скроле, т.е по факту мы выводим просто заголовок, а не текст самой ошибки. Отображение текста ошибки нужно отдельно прорабатывать,  так как он может быть не обработан и там может быть огромное кол-во текста и где-то под ним кнопка "повторить запрос". Пользователь просто не увидит эту кнопку с большей вероятностью.

Это отображение полностью дублирует вариант из DataList, можно отдельно проработать этот вопрос и сразу поправить в рамках этих двух компонентов, чтобы их поведение и апи в этой части были одинаковы

2024-07-12 05:26 UTC, AndTem approved these changes

2024-07-12 08:28 UTC, merged