feat(UIKIT-1542, Badge): Добавлены варианты отображения contained и l…
kaluga-astral/frontend pull request #1042
Opened 2024-07-12 12:02 UTC by maksimmolofeev

…ight

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-07-15 09:24 UTC, mfrolov89 requested changes

2024-07-15 09:24 UTC, mfrolov89 commented on packages/components/src/Badge/Badge.stories.tsx
> +    <Grid spacing={10} columns={6}>
1. Поправь верстку, чтобы бейдж заходил на элемент, а не висел в стороне от него. Верстка гридами сломала это поведение

2. Предлагаю в примерах цвет кнопки задавать как у бейджа, но с противположным variant. Пример приложил

<img width="113" alt="Снимок экрана 2024-07-15 в 12 07 18" src="https://github.com/user-attachments/assets/0664cd55-82a8-46be-b225-1dd48c4884e8">

2024-07-15 09:24 UTC, mfrolov89 commented on packages/components/src/Badge/Badge.stories.tsx
> +        invisible={false}
пропс не нужен, должно быть дефолтным состоянием

2024-07-15 09:24 UTC, mfrolov89 commented on packages/components/src/Badge/styles.tsx
> +      getBgColor({ customColor, theme, variantColor })};
```suggestion
      getBgColor({ $customColor, theme, $variantColor })};
```

Пропсы, которые не должны попадать в dom, должны начинаться с $

2024-07-15 09:24 UTC, mfrolov89 commented on packages/components/src/Badge/styles.tsx
> +  variantColor,
```suggestion
  variantColor = 'default',
```

2024-07-15 09:24 UTC, mfrolov89 commented on packages/components/src/Badge/styles.tsx
> +    prop !== 'customColor' && prop !== 'withBorder' && prop !== 'variantColor',
перепиши на массив с includes

2024-07-15 09:44 UTC, maksimmolofeev commented on packages/components/src/Badge/styles.tsx
> +  variantColor,
variantColor = 'contained' | 'light',

2024-07-16 06:43 UTC, mfrolov89 commented on packages/components/src/Badge/styles.tsx
> +    !['customColor', 'withBorder', 'variantColor'].includes(prop),
```suggestion
    !['$customColor', '$withBorder', '$variantColor'].includes(prop),
```

2024-07-22 11:24 UTC, mfrolov89 approved these changes

2024-07-22 13:04 UTC, merged