@astral-ui | FEA | Autocomplete. Реализован Autocomplete
kaluga-astral/frontend pull request #105
Opened 2022-02-21 19:29 UTC by StanislavDa

2022-02-22 06:22 UTC, AndTem commented on packages/ui/src/Autocomplete/types.ts
> +  size?: 'medium' | 'small';
сделай через enum, чтобы обращаться в стилях тоже к нему

2022-02-22 06:22 UTC, AndTem commented on packages/ui/src/Autocomplete/Autocomplete.tsx
> +export const Autocomplete = ({
Компонент, также как и его Props должен быть generic, как в mui

2022-02-22 06:22 UTC, AndTem commented on packages/ui/src/Autocomplete/types.ts
> +  MuiAutocompleteProps<AutocompleteValueProps, boolean, false, false>,
Не должно быть забитого гвоздями AutocompleteValueProps, должен быть generic

2022-02-22 06:22 UTC, AndTem commented on packages/ui/src/Autocomplete/Autocomplete.tsx
> +      getOptionLabel={(option: AutocompleteValueProps) => option.title}
getOptionLabel должен быть пропсом так, как формат value может быть любой (какой прокинется в generic)

2022-02-22 06:22 UTC, AndTem commented on packages/ui/src/Autocomplete/types.ts
> +  error?: boolean;
Думаю, что эти пропсы можно взять через Pick из TextField

2022-02-22 08:31 UTC, AndTem commented
@StanislavDa забери изменения из main ветки, чтобы сбилдился storybook

2022-02-22 10:45 UTC, StanislavDa commented on packages/ui/src/Autocomplete/types.ts
> +  MuiAutocompleteProps<AutocompleteValueProps, boolean, false, false>,
Чет я туплю, имеется в виду `MuiAutocompleteProps<MuiAutocompleteValue<AutocompleteValueProps, boolean, false, false>, boolean, false, false>` ?

2022-02-28 05:32 UTC, AndTem requested changes

2022-02-28 05:32 UTC, AndTem commented on packages/ui/src/theme/components/MuiAutocomplete.ts
> +        paddingLeft: '4px !important',
spacing

2022-02-28 05:32 UTC, AndTem commented on packages/ui/src/Autocomplete/Autocomplete.tsx
> +  AutocompleteValueProps extends { title: string },
Не надо забивать гвоздями title, должны быть свобода формата.
Для рендеринга тэгов используй ту же функцию, которая используется для получения label для option

2022-02-28 06:14 UTC, AndTem commented on packages/ui/src/Autocomplete/Autocomplete.tsx
> +  placeholder = 'Выберите вариант',
это autocomplete, здесь должно быть скорее: "Введите, чтобы найти". Но лучше просто убрать дефолтное значение placeholder

2022-02-28 06:15 UTC, AndTem approved these changes

2022-02-28 06:22 UTC, merkelAlbert approved these changes

2022-02-28 06:22 UTC, merged