wip(UIKIT-1475,NewDataGrid): Добавлена возможность работать с древовидной структурой данных
kaluga-astral/frontend pull request #1054
Opened 2024-07-22 14:53 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-07-23 06:13 UTC, AndTem commented
При раскрытии дерева полоски не появляются для вложенных элементов:
<img width="221" alt="Снимок экрана 2024-07-23 в 09 13 19" src="https://github.com/user-attachments/assets/6e3ab929-68b5-4765-9f45-ce7080ba136a">

2024-07-23 06:51 UTC, AndTem requested changes

2024-07-23 06:51 UTC, AndTem commented on packages/components/src/NewDataGridInfinite/NewDataGridInfinite.tsx
> +import { checkIsDisabled } from '../NewDataGrid/Row/utils';
Нарушаешь закон деметры. Надо из индексного файла NewDataGrid экспортировать только то, что можно использовать вне компонента

2024-07-23 06:51 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.tsx
> +  isInitialExpanded?: boolean;
Может имеет смысл все пропсы для дерева положить в объект tree?
tree={{ isInitialExpanded,  expandedLevel ...}}

2024-07-23 06:51 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.tsx
> +  initialOpenedNestedChildrenCount?: number;
```suggestion
  initialVisibleChildrenCount?: number;
```

2024-07-23 06:51 UTC, AndTem commented on packages/components/src/NewDataGrid/types.ts
> +      children?: CellValue;
У тебя сейчас родитель и ребенок одной структуры кажется должны быть. Проверь, что на уровне типов все работает с различными данными

2024-07-23 06:51 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.tsx
Тесты нужны

2024-07-23 06:51 UTC, AndTem commented on packages/components/src/NewDataGrid/Row/Row.tsx
> +  const startAdornmentRender = () => {
https://kaluga-astral.github.io/style-guide/docs/rules/naming/functions#%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8-%D0%B8-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D1%8B-%D0%BD%D0%B0%D1%87%D0%B8%D0%BD%D0%B0%D1%82%D1%8C%D1%81%D1%8F-%D1%81-%D0%B3%D0%BB%D0%B0%D0%B3%D0%BE%D0%BB%D0%B0

2024-07-23 06:51 UTC, AndTem commented on packages/components/src/NewDataGrid/Row/styles.ts
> +    z-index: 2;
Из темы должен браться

2024-07-23 06:51 UTC, AndTem commented on packages/components/src/NewDataGrid/types.ts
> +export type CellValue =
Он ведь может быть и object

2024-07-23 06:51 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
> +    actions?: ReactNode | object;
Не понимаю что actions делают в data

2024-07-23 06:51 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
> +  type DataWithNestedType = {
Нужно сделать тип, который можно будет использовать для форматирования данных в нужную структуру

2024-07-23 06:51 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
> +          actions: {
Какая-то странная вложенность.
До этого видел просто options, а тут actions.options

2024-07-23 06:51 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
> +export const TreeWithCustomCell = () => {
Нужна story с демонстрацией рендера actions для вложенных строк

2024-07-23 06:51 UTC, AndTem commented on packages/components/src/NewDataGrid/Row/NestedChildren/NestedChildren.tsx
> +          .map(({ children, options, ...nestedRow }) => {
https://kaluga-astral.github.io/style-guide/docs/rules/react/logic#%D0%B7%D0%B0%D0%BF%D1%80%D0%B5%D1%89%D0%B5%D0%BD%D0%B0-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BA%D0%B0-%D0%B2-%D1%86%D0%B8%D0%BA%D0%BB%D0%B0%D1%85-%D0%B2%D0%BD%D1%83%D1%82%D1%80%D0%B8-jsx-%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%82%D0%BA%D0%B8

2024-07-23 06:51 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
> +          actions: {
Вообще не понял от куда в Data взялся actions, вроде не было такого раньше

2024-07-23 06:54 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
> +export const TreeWithCustomCell = () => {
Я искал как сделать actions для вложенной строки и не нашел. Оказалось, что это customCell

2024-07-29 08:34 UTC, AndTem commented
Баг: Кнопка "Показать все" не исчезает при одном элементе: https://61baeff6f06230003a88ef8a-xvbacshwey.chromatic.com/?path=/docs/components-newdatagrid--docs#tree

2024-07-29 08:37 UTC, AndTem commented
При сворачивании списка происходит подергиваение
https://github.com/user-attachments/assets/2a61a6ca-6135-4a72-9645-029ebab95bb7

2024-07-29 08:40 UTC, AndTem commented
DataGridInfinite: при loading и error не должна отображаться сортировка
<img width="1048" alt="Снимок экрана 2024-07-29 в 11 39 51" src="https://github.com/user-attachments/assets/2a9c1770-9c8c-4db5-a989-a35c1aa4ecc2">

+ вопрос: а должен ли вообще отображаться head?

2024-07-29 08:58 UTC, AndTem requested changes

2024-07-29 08:58 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.test.tsx
> +  it('Вложенные элементы не отображаются, если группа не раскрыта', () => {
Нужен тест на кнопку "Показать все".
Сейчас вот есть баг с этим саязанный

2024-07-29 08:58 UTC, AndTem commented on packages/components/src/NewDataGridInfinite/NewDataGridInfinite.stories.tsx
> +export const WithTreeLongList = () => {
Не хватает story с кастомными actions во вложенных строках (как в DataGrid)

2024-07-29 08:58 UTC, AndTem commented on packages/components/src/NewDataGrid/types.ts
> +export type CellValue = string | number | boolean | Date | undefined | object;
Может unknown? А если в данных будет null?

2024-07-29 08:58 UTC, AndTem commented
+ предыдущие комменты не исправлены

2024-07-29 09:51 UTC, mfrolov89 commented
> DataGridInfinite: при loading и error не должна отображаться сортировка <img alt="Снимок экрана 2024-07-29 в 11 39 51" width="1048" src="https://private-user-images.githubusercontent.com/23665108/352976516-2a9c1770-9c8c-4db5-a989-a35c1aa4ecc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDYyOTksIm5iZiI6MTcyMjI0NTk5OSwicGF0aCI6Ii8yMzY2NTEwOC8zNTI5NzY1MTYtMmE5YzE3NzAtOWM4Yy00ZGI1LWE5ODktYTM1YzFhYTRlY2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA5Mzk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNDM0OTRlZWQ1OTU4MjIxZTg1MTg1OTdlNjVjNWNiMDdiNzAwYWNhZGY4MDc5ZWI2NTUxYjYxYmRlMTFiOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hWJ4dbpMaCoHB5FwfEINQSQDQfufaUwxzFVhzroLuro">
> 
> * вопрос: а должен ли вообще отображаться head?

Сейчас визуалка полностью соответствует NewDataGrid, разное отображение, для практически одинаковых компонентов делать странно. По поводу того отображать или нет думаю стоит обсуждать отдельно, на макетах сейчас ерунда: для загрузки шапки нет, для ошибки есть, что странно. При этом лоадер там вообще не китовый...

По мне шапка хотя бы подсказывает что за данные грузятся и к чему относится ошибка, но это мое имхо.

2024-07-29 09:52 UTC, mfrolov89 commented on packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
> +  type DataWithNestedType = {
Исправлено

2024-07-29 09:52 UTC, mfrolov89 commented on packages/components/src/NewDataGrid/Row/NestedChildren/NestedChildren.tsx
> +          .map(({ children, options, ...nestedRow }) => {
Исправлено

2024-07-29 09:53 UTC, mfrolov89 commented on packages/components/src/NewDataGrid/types.ts
> +export type CellValue = string | number | boolean | Date | undefined | object;
Можно и поменять, этот тип уже существовал в таком виде, я его по сути и не трогал

2024-07-30 06:28 UTC, AndTem requested changes

2024-07-30 06:28 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
> +type DataRowType<TData extends Record<string, CellValue>> =
Пример супер запутанный с этими типами.
Надо чтобы можно было открыть story и понять как работать с этим. Сейчас открываешь и просто недоумеваешь

2024-07-30 09:25 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
> +  const fakeData = makeDataListWithTree(10);
Нужно чтобы в story была видна структура. Сейчас не видна и не понятно что внутри себя делает makeDataListWithTree.
Так для всех.
Также нужно, чтобы было видно использование типа для формирования данных

2024-07-30 09:34 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
> +  const fakeData = makeDataListWithTree(10);
Можно хоть комментом указать какой там формат

2024-07-30 09:42 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
> +  const fakeData = makeDataListWithTree(10);
Но лучше первый элемент описать руками, а остальное заспредить из фейка

2024-07-30 14:13 UTC, AndTem approved these changes

2024-07-31 06:41 UTC, merged