feat(UIKIT-1384, StepperWizard): Реализован компонент StepperWizard
kaluga-astral/frontend pull request #1056
Opened 2024-07-24 11:34 UTC by maksimmolofeev

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-07-29 09:30 UTC, mfrolov89 requested changes
1. Нужно добавить тесты
2. Забыл экспортировать из пакета

2024-07-29 09:30 UTC, mfrolov89 commented on packages/components/src/StepperWizard/StepperWizard.stories.tsx
> +    { label: 'Step 1' },
нужно добавить содежимое шагов

2024-07-29 09:30 UTC, mfrolov89 commented on packages/components/src/StepperWizard/StepperWizard.stories.tsx
> +    { label: 'Step 3', error: true },
```suggestion
    { label: 'Step 3', isError: true },
```

1. По новому гайду должны иметь префикс.
2. Отображение ошибки можно оформить отдельной сторей

2024-07-29 09:30 UTC, mfrolov89 commented on packages/components/src/StepperWizard/StepperWizard.stories.tsx
> +      <StepperWizard connector="arrow" activeStep={activeStep} steps={steps} />
Вариант с connector нужно оформить отдельной сторей

2024-07-29 09:30 UTC, mfrolov89 commented on packages/components/src/StepperWizard/types.ts
> +  label?: ReactNode;
label кажется должен быть обязательным

2024-07-29 09:30 UTC, mfrolov89 commented on packages/components/src/StepperWizard/types.ts
> +export type Steps = {
```suggestion
export type Step = {
```

в StepperWizardProps:
steps: Array<Step>;

И выносить тут в отдельный файл с типами кажется излишним

2024-07-29 09:30 UTC, mfrolov89 commented on packages/components/src/StepperWizard/StepperWizard.tsx
> +type StepperWizardProps = StepperProps & {
```suggestion
type StepperWizardProps = Omit<StepperProps, 'children'> & {
```

2024-07-29 09:30 UTC, mfrolov89 commented on packages/components/src/StepperWizard/StepperWizard.tsx
> +      {steps.map((step, index) => (
```suggestion
      {steps.map(({ label, isError }, index) => (
```

2024-07-29 09:31 UTC, mfrolov89 commented on packages/components/src/StepperWizard/StepperWizard.stories.tsx
> +import { Button, Grid } from '..';
```suggestion
import { Button } from '../Button';
import { Grid } from '../Grid';
```

2024-07-29 09:49 UTC, maksimmolofeev commented on packages/components/src/StepperWizard/types.ts
> +  label?: ReactNode;
Для StepLabel children не обязательный пропс

2024-07-29 09:57 UTC, maksimmolofeev commented on packages/components/src/StepperWizard/types.ts
> +export type Steps = {
Steps это тип для массива шагов, вынес его в отдельный файл с типами, для возможности использовать его при создании шагов

2024-07-29 14:30 UTC, mfrolov89 commented on packages/components/src/index.ts
> +export * from './StepperWizard';
используй явный экспорт, это защита что ничего лишнего не будет доступно из пакета

2024-07-29 14:33 UTC, mfrolov89 commented on packages/components/src/StepperWizard/types.ts
> +  label?: ReactNode;
Что там у StepLabel это отдельная история, представь что кто-то использует этот компонент и не укажет label, как это будет выглядеть? И типизацией мы даже не подскажем что не указано обязательное поле

2024-07-29 14:34 UTC, mfrolov89 commented on packages/components/src/StepperWizard/types.ts
> +export type StepInfo = {
просто Step занято? Тогда можно StepWizard назвать

2024-07-29 14:39 UTC, mfrolov89 commented on packages/components/src/StepperWizard/StepperWizard.test.tsx
> +  it('Шаги отображаются если переданы в steps', () => {
```suggestion
  it('Шаги отображаются, если переданы в steps', () => {
```

2024-07-29 14:39 UTC, mfrolov89 commented on packages/components/src/StepperWizard/StepperWizard.test.tsx
> +  it('Шаги отображаются если переданы в steps', () => {
В остальных местах перед 'если' тоже нужная запятая

2024-07-30 06:15 UTC, mfrolov89 commented on packages/components/src/index.ts
> +export { StepperWizard, type StepInfo } from './StepperWizard';
```suggestion
export { StepperWizard, type StepperWizardProps, type  StepWizard } from './StepperWizard';
```

2024-07-30 07:31 UTC, mfrolov89 commented on packages/components/src/StepperWizard/StepperWizard.stories.tsx
> +    { label: 'Step 1', stepContent: 'Описание для шага 1' },
Здесь у тебя сторя на orientation

2024-07-30 07:34 UTC, mfrolov89 commented on packages/components/src/StepperWizard/StepperWizard.stories.tsx
> +    { label: 'Step 1' },
Степпер, это компонент для переключения между сождержимым, с визуализацией текущего шага и информации об этом, поэтому stepContent в примерах должен быть.

2024-07-30 07:36 UTC, maksimmolofeev commented on packages/components/src/StepperWizard/StepperWizard.stories.tsx
> +    { label: 'Step 1' },
Уже было добавлено

2024-07-30 07:39 UTC, mfrolov89 commented on packages/components/src/StepperWizard/StepperWizard.stories.tsx
> +    { label: 'Step 1' },
Не вижу ни по коду, ни по сторибуку. У тебя добавлены они в Interaction

<img width="815" alt="Снимок экрана 2024-07-30 в 10 38 20" src="https://github.com/user-attachments/assets/f377b90b-ccd0-4353-ba17-0acfeacb7f91">

2024-07-30 07:40 UTC, maksimmolofeev commented on packages/components/src/StepperWizard/StepperWizard.stories.tsx
> +    { label: 'Step 1', stepContent: 'Описание для шага 1' },
А для stepContent сторя не нужна? Просто если использовать stepContent без 'orientation="vertical"', проиходит что-то не красивое

2024-07-30 07:40 UTC, maksimmolofeev commented on packages/components/src/StepperWizard/StepperWizard.stories.tsx
> +    { label: 'Step 1' },
Сорри, перепутал

2024-07-30 07:47 UTC, maksimmolofeev commented on packages/components/src/StepperWizard/StepperWizard.stories.tsx
> +    { label: 'Step 1', stepContent: 'Описание для шага 1' },
А сторя для stepContent? просто используя stepContent, без orientation="vertical", там происходит что-то не красивое

2024-07-30 09:30 UTC, mfrolov89 requested changes
У тебя сейчас верстка заточена под вертикальный вариант, для горизонтального содержимое должно быть вне шагов. Обсудил с Адреем api, пришли к мнению что нужно убрать поддержку отображения содержимого (stepContent)

2024-07-30 10:45 UTC, merged