feat(UIKIT-1601,Tree): Правка стилей для компонентов Tree
kaluga-astral/frontend pull request #1060
Opened 2024-07-28 11:52 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-07-28 11:58 UTC, mfrolov89 commented on packages/components/src/theme/mixins/list/list.ts
> +export const listContainer = () => css`
Слишком накладно писать одни и те же стили, считаю что миксины не помешают. Потом можно будет обсудить как их оформлять и где держать

2024-07-29 08:32 UTC, AndTem requested changes

2024-07-29 08:32 UTC, AndTem commented on packages/components/src/theme/mixins/list/list.ts
> +export const listContainer = () => css`
Думаю, им место в директории styles/mixins

2024-07-29 08:32 UTC, AndTem commented on packages/components/src/TreeLikeList/TreeLikeList.stories.tsx
> -    label: 'Наименование организации 1',
Надо вернуть данные, которые были

2024-07-29 08:32 UTC, AndTem commented on packages/components/src/Description/constants.ts
> +export const DESCRIPTION_ROOT_CLASSNAME = 'astral-ui_description_root';
```suggestion
export const DESCRIPTION_ROOT_CLASSNAME = 'astral-ui-descriptionRoot';
```

2024-07-29 09:04 UTC, AndTem approved these changes

2024-07-29 09:05 UTC, merged