bug(UIKIT-1650,FormDatePicker): Поправлен сброс значения, если первоначально оно было задано через defaultValues
kaluga-astral/frontend pull request #1065
Opened 2024-07-30 13:17 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-07-30 13:46 UTC, AndTem requested changes

2024-07-30 13:46 UTC, AndTem commented on packages/components/src/DatePicker/hooks/useMaskedValue/useMaskedValue.ts
> +      onChangeValue?.(null);
Это может сломать (и сломает) логику в приложениях.
Типизация также будет не актуальной в приложениях

2024-07-30 13:46 UTC, AndTem commented on packages/components/src/DatePicker/hooks/useMaskedValue/useMaskedValue.ts
> +      onChangeValue?.(null);
Может здесь нужно такое же решение, как в autocomplete? https://github.com/kaluga-astral/frontend/blob/main/packages/form/src/FormAutocomplete/FormAutocomplete.tsx#L72

2024-07-31 08:37 UTC, mfrolov89 commented on packages/components/src/DatePicker/hooks/useMaskedValue/useMaskedValue.ts
> +      onChangeValue?.(null);
Не вижу как можно использовать подход из autocomplete. Там какая история, в onChange поступает undefined, но в value, сразу же после этого мы получаем defaultValue.

В rhf явно говорят что в onChange не должно быть undefined.

<img width="965" alt="Снимок экрана 2024-07-31 в 11 34 55" src="https://github.com/user-attachments/assets/02ef8da5-a833-445a-a5fc-863cd89844b5">

Посмотрел почему нет проблем на примере несколькихз других компонентов:
FormTextField - после удаления устанавливает пустую строку
FormAutocomplete - устанавливает null

исходя их этого вряд-ли мы получим проблему, так как null для пустых полей уже существует в проектах

2024-07-31 08:44 UTC, AndTem commented on packages/components/src/DatePicker/hooks/useMaskedValue/useMaskedValue.ts
> +      onChangeValue?.(null);
Ок

2024-07-31 08:44 UTC, AndTem approved these changes

2024-08-02 11:09 UTC, merged