feat(UIKIT-1476,NewDataGrid): Добавлена опциональность выборки
kaluga-astral/frontend pull request #1068
Opened 2024-07-31 13:31 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-07-31 13:34 UTC, mfrolov89 reviewed
Чекбокс в шапке сейчас отображается всегда, даже если у всех полей первого уровня через опцию отключена возможность их выбора. По хорошему в этом случае чекбокс в шапке стоит скрывать, но у нас  еще могут быть заблокированные поля, у которых есть чекбокс. Пока нет понимания как учитывать их. Написал Землякову, чтобы обсудить этот вопрос.

2024-07-31 13:39 UTC, AndTem approved these changes

2024-07-31 13:45 UTC, AndTem requested changes

2024-07-31 13:45 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
> +export const TreeWithOptionIsNotSelectable = () => {
Не удачный пример. Сейчас чекбокс в хедеое просто не работает.
Это потому, что дерево кривое.
Сделай просто так, чтобы несколько пакетов были с чекбоксами

2024-08-02 04:36 UTC, AndTem approved these changes

2024-08-02 07:11 UTC, merged