feat(UIKIT-1608,Description): Реализована адаптация под мобильные устройства
kaluga-astral/frontend pull request #1071
Opened 2024-08-01 08:59 UTC by pan1caisreal

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-08-01 11:01 UTC, mfrolov89 requested changes

2024-08-02 06:22 UTC, mfrolov89 commented on packages/components/src/Description/useLogic/useLogic.ts
> +    leader: leader,
Обсуждали, что все пропсы, которые никак не модифицируются, должны передаваться напрямую, минуя useLogic

2024-08-02 06:26 UTC, mfrolov89 commented on packages/components/src/Description/styles.ts
> +      $direction === 'default' ? 'column' : $direction};
это лучше вынести в useLogic

2024-08-02 14:39 UTC, mfrolov89 commented on packages/components/src/Description/Value/styles.ts
> +  ${({ theme }) => theme.breakpoints.down('sm')} {
отдели пустой строкой

2024-08-02 14:40 UTC, mfrolov89 commented on packages/components/src/Description/Value/styles.ts
> +    text-align: ${({ $direction }) => $direction != 'row' && 'left'};
при определенных условиях у тебя false приходит в text-align

2024-08-04 21:41 UTC, mfrolov89 approved these changes

2024-08-05 05:11 UTC, AndTem requested changes

2024-08-05 05:11 UTC, AndTem commented on packages/components/src/Description/Description.stories.tsx
> + * Prop ```direction``` определяет перенос строк
Как будто речь про перенос строк при переполнении.
Надо еще написать как это работает для адаптива

2024-08-05 05:11 UTC, AndTem commented on packages/components/src/Description/Description.stories.tsx
> +        <StyledDescriptionValue>
С точки зрения пользователя доки будет не понятно что это за Styled и надо ли постоянно добавлять руками какие-то стили

2024-08-05 05:12 UTC, AndTem commented on packages/components/src/Description/Description.stories.tsx
> + * Prop ```direction``` определяет перенос строк
И дефолтное поведение описать

2024-08-05 07:57 UTC, AndTem approved these changes

2024-08-05 08:00 UTC, merged