feat(UIKIT-1607,Profile): Реализован новый функционал Profile
kaluga-astral/frontend pull request #1076
Opened 2024-08-05 10:44 UTC by pan1caisreal

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-08-05 13:00 UTC, AndTem commented on packages/components/src/Profile/Profile.stories.tsx
> +    <Box>
Стоит избегать использование компонентов из mui

2024-08-05 13:01 UTC, AndTem commented on packages/components/src/Profile/Profile.stories.tsx
> + * prop ```onExitClick``` функция, которая вызывается при выходе
Тут должно быть написано, что проброс добаляет кнопку выхода

2024-08-05 13:01 UTC, AndTem commented on packages/components/src/Profile/Profile.stories.tsx
> +export const RenderItem = () => {
```suggestion
export const RenderCustomItem = () => {
```

2024-08-05 13:02 UTC, AndTem commented on packages/components/src/Profile/Profile.stories.tsx
> +export const OnExitClick = () => {
Не увидел нигде фичи когда вместо аватара кнопка показывается.
Эта фича должна быть описана и реализована в DashboardLayout

2024-08-06 08:26 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +        {profile && !hasProfileMenu && isMobile && (
Если не прокинуть exitButton, то здесь все равно отрендерится кнопка

2024-08-06 08:27 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/useLogic/useLogic.ts
> +  const hasProfileMenu = Boolean(profile?.menu || profile?.menuList);
Логика неверна.
Если есть menu, то кнопки выхода быть не должно

2024-08-06 08:27 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +        {profile && !isMobile && (
На все эти кейсы надо тесты написать

2024-08-06 08:27 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +        {profile && !hasProfileMenu && isMobile && (
Все эти условия надо переместить в useLogic и назвать понятным названием

2024-08-06 08:29 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.stories.tsx
> +    <DashboardLayoutWrapper>
Этот же кейс надо добавить в DashboardLayout.stories.
Замени везде menu на menuList + сделай story "CustomMenu" - это использование menu

2024-08-06 08:29 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.stories.tsx
> +              <Box>
Уже оставлял коммент про использование box

2024-08-06 08:30 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.stories.tsx
> +export const WithoutProfileMenu = () => {
Такого название не должно быть в природе.
Мы сделали menuList и теперь говорим, что юзайте его. Menu prop только для кастома

2024-08-06 08:31 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.stories.tsx
> +export const WithoutProfileMenu = () => {
Можешь сделать отдельную story типа exit button

2024-08-06 08:31 UTC, AndTem commented on packages/components/src/Profile/Profile.tsx
> +export type MenuItemData = {
Ты этот тип экспортировать собираешься?
Тогда нужен префикс Profile

2024-08-06 08:32 UTC, AndTem commented on packages/components/src/Profile/Profile.tsx
> +   *  const renderItem: MenuItem['render'] = ({ title, icon }) => (
```suggestion
   *  const render: ProfileMenuItemData['render'] = ({ title, icon }) => (
```

2024-08-06 08:33 UTC, AndTem commented on packages/components/src/Profile/Profile.stories.tsx
> + * prop ```menuList``` принимает массив данных для отображения и заменяет prop ```menu```
Example надо изменить на актуальный menuList

2024-08-06 08:34 UTC, AndTem commented on packages/components/src/Profile/Profile.tsx
> +            PaperProps={{
up

2024-08-06 08:37 UTC, AndTem requested changes

2024-08-06 08:37 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.stories.tsx
> +    <DashboardLayoutWrapper>
Во всех сторях надо это сделать

2024-08-06 12:25 UTC, pan1caisreal commented on packages/components/src/Profile/Profile.tsx
> +            PaperProps={{
у menuList это было сделано, для Menu через css я не могу обратиться, там через props прокидывается

2024-08-07 07:39 UTC, AndTem requested changes

2024-08-07 07:39 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/useLogic/useLogic.ts
> +  const desktopProfileRender = Boolean(profile) && !isMobile;
Bollean переменные по другому именуются: https://kaluga-astral.github.io/style-guide/docs/rules/naming/vars#boolean-%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D1%8B-%D0%B8%D0%BC%D0%B5%D1%82%D1%8C-%D0%BF%D1%80%D0%B5%D1%84%D0%B8%D0%BA%D1%81-%D1%83%D0%BA%D0%B0%D0%B7%D1%8B%D0%B2%D0%B0%D1%8E%D1%89%D0%B8%D0%B9-%D0%BD%D0%B0-%D0%BF%D1%80%D0%B8%D0%BD%D0%B0%D0%B4%D0%BB%D0%B5%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%BA-boolean

2024-08-07 07:39 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/useLogic/useLogic.ts
> +  const desktopProfileRender = Boolean(profile) && !isMobile;
isShowProfileOnDescktop можно

2024-08-07 07:39 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +        {desktopProfileRender && (
desktopProfileRender и mobileProfileRender явно можно объеденить в одну переменную потому, что рендерят они одно и то же

2024-08-07 07:39 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.test.tsx
> +            logo() {
Да просто` <svg />` можно возвращать. Не нужна реальная иконка

2024-08-07 07:39 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.test.tsx
> +  it('Profile отображается', () => {
Надо написать тест, что на декстопе кнопка выхода не отображается

2024-08-07 07:39 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +            <Profile {...(profile as ProfileProps)} />
Не правильная типизация, если приходится делать приведение типов

2024-08-07 07:39 UTC, AndTem commented on packages/components/src/Profile/MenuList/MenuList.tsx
> +      <BottomDrawer onClose={onClose} open={open}>
Все, что вложенно внутрь BottomDrawer можно переиспользовать для мобилы и десктопа

2024-08-07 07:39 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +        {exitButtonRender && (
Сделать скрытие кнопки через css, чтобы не было у нас проблем с регидрацией в продуктах.
То же самое касается Menu

2024-08-07 07:39 UTC, AndTem commented on packages/components/src/Profile/Profile.test.tsx
> +  it('Кнопка exit отображается если передан exitButton', async () => {
Обратный кейс тоже бы проверить: кннопка не отображается, если не передан

2024-08-07 07:39 UTC, AndTem commented on packages/components/src/Profile/Profile.tsx
> +    if (!Menu && !menuList && !exitButton) {
Заверни в useEffect, чтобы не спамило при каждом перерендере

2024-08-07 07:39 UTC, AndTem commented on packages/components/src/DashboardLayout/DashboardLayout.stories.tsx
> +              <Grid>
А там нужна вообще обертка?

2024-08-07 07:50 UTC, AndTem commented
Название PR измени на такое, чтобы было понятно что конкретно было добавлено (про кнопку выхода)

2024-08-07 09:45 UTC, pan1caisreal commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +            <Profile {...(profile as ProfileProps)} />
profile же опциональный в dashboardLayout, можно добавить проверку на profile здесь

2024-08-07 09:54 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +            <Profile {...(profile as ProfileProps)} />
добавь

2024-08-07 12:16 UTC, AndTem requested changes

2024-08-07 12:16 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +        {profile && isShowProfile && (
Это тоже через css надо скрывать

2024-08-07 12:19 UTC, AndTem commented
Проблема с вертикальном центрированием кнопки: 
<img width="344" alt="Снимок экрана 2024-08-07 в 15 18 33" src="https://github.com/user-attachments/assets/f45a15ea-b6f9-475e-b4a4-723a65bd3380">

Также title надо на русский изменить. Это же для пользователей

2024-08-07 12:57 UTC, AndTem requested changes

2024-08-07 12:57 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/styles.tsx
> +      $isShowExitButton === false ? 'none' : 'flex'};
```suggestion
      !$isShowExitButton ? 'none' : 'flex'};
```

2024-08-07 12:57 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/styles.tsx
> +  $isShowProfile: boolean;
```suggestion
  $isShow: boolean;
```

2024-08-07 12:57 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/styles.tsx
> +  $isShowProfile: boolean;
Пропс ведь в контексте конкретного компонента работает, доп. префиксы излишни

2024-08-07 12:57 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/styles.tsx
> +  $isShowExitButton: boolean;
```suggestion
  $isShow: boolean;
```

2024-08-07 12:57 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.stories.tsx
> +              <Grid>
В DashboardLayout убрал обертки, а здесь нет.
Когда оставляют комменты в одной строке, надо проверить нет ли таких же проблем в других местах

2024-08-08 06:49 UTC, AndTem commented on packages/components/src/DashboardLayout/DashboardLayout.stories.tsx
> +const FAKE_MENU_LIST = [
Сделай так, чтобы этот массив был виден внутри каждой story. Потому что сейчас FAKE_MENU_LIST не говорит ни о чем человеку, который будет читать доку.
То есть надо просто сделать везде:
`menuList={[{ icon... }]}`
Извиняюсь за поздний коммент.

2024-08-08 07:08 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.stories.tsx
> +      menuList: [
Здесь ты прямо в компоненте определил массив, а ниже в отдельной константе. Все должно быть однородно

2024-08-08 07:28 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.stories.tsx
> +      menuList: [
Ничего не изменилось.
Надо чтобы во всех stories было одинаково: menuList: [{}]

2024-08-08 07:30 UTC, pan1caisreal commented on packages/components/src/DashboardLayout/Header/Header.stories.tsx
> +      menuList: [
Interection story объект я там не могу создавать константы, а menuList уже существует в других сторях

2024-08-08 07:33 UTC, AndTem approved these changes

2024-08-08 07:41 UTC, merged