bug(UIKIT-1647,NavMenu): Исправлена семантика
kaluga-astral/frontend pull request #1077
Opened 2024-08-05 12:39 UTC by pan1caisreal

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-08-05 13:08 UTC, AndTem requested changes

2024-08-05 13:08 UTC, AndTem commented on packages/components/src/ListItemButton/ListItemButton.tsx
> +      <>
Ты так разломаешь верстку в местах, где использовался ListItemButton без обертки.
Хорошее решение будет в данном случае сделать prop component и в нужных местах указать component="div"

2024-08-05 13:09 UTC, AndTem commented on packages/components/src/ListItemButton/ListItemButton.tsx
> +      <>
ListItemButton ведь экспортируется из пакета

2024-08-06 13:29 UTC, pan1caisreal commented on packages/components/src/ListItemButton/ListItemButton.tsx
> +      <>
Здесь prop компонент есть, исправил прокинув ключ в ListItemButton у navMenu

2024-08-06 13:30 UTC, pan1caisreal commented on packages/components/src/ListItemButton/ListItemButton.tsx
> +      <>
ItemButton имеет обертку li у себя

2024-08-06 13:35 UTC, AndTem requested changes

2024-08-06 13:35 UTC, AndTem commented on packages/components/src/NavMenu/Item/Item.tsx
> +    <>
А зачем фрагмент?

2024-08-07 12:12 UTC, AndTem approved these changes

2024-08-07 12:36 UTC, merged