feat(UIKIT-309,NewDataGrid): Добавлена обработка emptyCellValue
kaluga-astral/frontend pull request #1087
Opened 2024-08-09 12:26 UTC by pan1caisreal

# Чеклист

- [x] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для props экспортируемых компонентов
- [x] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2024-08-09 12:46 UTC, AndTem requested changes

2024-08-09 12:46 UTC, AndTem commented on packages/components/src/NewDataGrid/Cell/useLogic/useLogic.ts
> +    if (format && format(row) !== undefined) {
Кроме undefined есть еще null, пустая строка и NaN

2024-08-09 12:47 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.test.tsx
> +  it('EmptyCellValue отображается если нет данных', async () => {
Нужен еще кейс с format

2024-08-09 12:48 UTC, AndTem commented on packages/components/src/NewDataGrid/constants.ts
> +export const EMPTY_CELL_SYMBOL = '—';
Не понял зазем тут нужна константа эта

2024-08-09 13:39 UTC, AndTem requested changes

2024-08-09 13:57 UTC, AndTem requested changes

2024-08-09 13:57 UTC, AndTem commented on packages/components/src/NewDataGrid/Cell/useLogic/useLogic.ts
> +    if (field && row[field] !== undefined) {
Здесь вело тоже самое, что и в формат

2024-08-09 13:57 UTC, AndTem commented on packages/components/src/NewDataGrid/NewDataGrid.test.tsx
> +  it('EmptyCellValue отображается если нет данных', async () => {
Надо отдельно обработать все кейсы с null, 0 и тп.
Используй it.each

2024-08-12 09:45 UTC, mfrolov89 requested changes

2024-08-12 09:45 UTC, mfrolov89 commented on packages/components/src/NewDataGrid/NewDataGrid.test.tsx
> +    [undefined, '—'],
[undefined, null, '', NaN, '—']

2024-08-12 09:45 UTC, mfrolov89 commented on packages/components/src/NewDataGrid/NewDataGrid.test.tsx
> +      const emptyCell = screen.getByText(expectedCell);
можно указать фиксированное значение

2024-08-12 09:45 UTC, mfrolov89 commented on packages/components/src/NewDataGrid/faker.ts
> +type CommonDataType = {
Создает путаницу в типах, можно просто добавить опиональность полей в DataType

2024-08-12 10:58 UTC, pan1caisreal commented on packages/components/src/NewDataGrid/faker.ts
> +type CommonDataType = {
Придется для деревьев переписывать логику

2024-08-13 14:51 UTC, mfrolov89 commented on packages/components/src/NewDataGrid/NewDataGrid.test.tsx
> +          onRetry={() => {}}
пробрось фиксированный emptyCellValue, чтобы было понятно почему ты ищешь конкретный символ + тест будет не такой хрупкий: изменение символа по умолчанию и тест упадет

2024-08-13 14:51 UTC, mfrolov89 commented on packages/components/src/NewDataGrid/NewDataGrid.test.tsx
> +          rows={[{ cell: cell }]}
```suggestion
          rows={[{ cell }]}
```

2024-08-14 06:02 UTC, mfrolov89 commented on packages/components/src/NewDataGrid/NewDataGrid.test.tsx
> +      <NewDataGrid
здесь тоже нужен emptyCellValue

2024-08-14 07:14 UTC, mfrolov89 approved these changes

2024-08-14 07:29 UTC, merged