feat(UIKIT-1553,NewDateRangePicker): Реализован новый компонент NewDateRangePicker
kaluga-astral/frontend pull request #1093
Opened 2024-08-13 14:44 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-08-13 14:46 UTC, mfrolov89 commented on packages/form/src/FormNewDateRangePicker/FormNewDateRangePicker.stories.tsx
> +const validationSchema = object<FormValues>({
не нравится как отрабатывает такая схема валидации: если одно из полей пустое, то светит ошибку, но не отображает текст. Нужно будет еще поразбираться

2024-08-14 06:33 UTC, AndTem requested changes

2024-08-14 06:33 UTC, AndTem commented on packages/components/src/NewDateRangePicker/NewDateRangePicker.tsx
> +export const NewDateRangePicker = forwardRef<
Старый забыл пометить как deprecated

2024-08-14 06:33 UTC, AndTem commented on packages/components/src/NewDateRangePicker/NewDateRangePicker.tsx
> +} | null;
{} | null точно должен быть?
Это зависит от required в схеме, я бы убрал

2024-08-14 06:33 UTC, AndTem commented on packages/components/src/NewDateRangePicker/NewDateRangePicker.tsx
> +  'inputProps' | 'startAdornment'
label еще не хватает

2024-08-14 06:33 UTC, AndTem commented on packages/components/src/NewDateRangePicker/NewDateRangePicker.tsx
> +  from?: Date | null;
В пропсах компонента: start, end, а тут from, to. Может должно быть одинаково?

2024-08-14 06:33 UTC, AndTem commented on packages/form/src/FormNewDateRangePicker/FormNewDateRangePicker.test.tsx
> +    // TODO Разобраться со скоростью выполнения теста, в ci падает по таймауту в 3s, на локале выполняется примерно за 1.3s
Это из-за waitFor скорее всего. Можно попробовать заменить на act

2024-08-14 06:33 UTC, AndTem commented on packages/components/src/NewDateRangePicker/NewDateRangePicker.tsx
> +      {helperText && (
Поведение появления ошибки сейчас отличается от исходного. Должно быть заранее зарезервированное место под ошибку

2024-08-14 06:33 UTC, AndTem commented on packages/form/src/FormNewDateRangePicker/FormNewDateRangePicker.stories.tsx
> +const validationSchema = object<FormValues>({
Валидация не так должна быть реализована для этого поля. Ты сейчас отдельно валидируешь from и to, а надо вместе.
`dateField: required((value, ctx) => { if(value.from > value.to) return ctx.createError() })`

2024-08-14 06:33 UTC, AndTem commented on packages/form/src/FormNewDateRangePicker/FormNewDateRangePicker.stories.tsx
> +const validationSchema = object<FormValues>({
Можно будет отдельное правило валидации реализовать потом, которое покроет все стандартные кейсы наши

2024-08-14 12:23 UTC, mfrolov89 commented on packages/components/src/NewDateRangePicker/NewDateRangePicker.tsx
> +  'inputProps' | 'startAdornment'
может от inputProps отказаться вообще и поднять содержимое inputProps на уровень выше до DateItemProps?

2024-08-15 10:26 UTC, mfrolov89 commented on packages/form/src/FormNewDateRangePicker/FormNewDateRangePicker.test.tsx
> +    // TODO Разобраться со скоростью выполнения теста, в ci падает по таймауту в 3s, на локале выполняется примерно за 1.3s
Не уверен, есть похожая валидация в контролируемом компоненте, но там нет сабмита и waitFor, но в ci тест так же завершался ошибкой по таймауту, в следсвтие чего он увеличен

2024-08-15 13:22 UTC, AndTem commented
Валидация работает не правильно, кажется проблема в onChange
<img width="507" alt="Снимок экрана 2024-08-15 в 16 20 59" src="https://github.com/user-attachments/assets/f85ca05d-e101-4c62-8350-0df18c799630">

2024-08-15 13:22 UTC, AndTem commented
Popover криво открывается
<img width="684" alt="Снимок экрана 2024-08-15 в 16 22 12" src="https://github.com/user-attachments/assets/1d7fb412-fc63-4483-8bfe-ec5de176c33b">

2024-08-15 13:22 UTC, AndTem commented
Проведи приемочные тесты

2024-08-15 13:22 UTC, AndTem requested changes

2024-08-15 13:22 UTC, AndTem commented on packages/form/src/FormNewDateRangePicker/FormNewDateRangePicker.stories.tsx
> +  dateField: (value: FormValues['dateField'], ctx) => {
Надо через createRule делать, тогда с типизацией все будет ок

2024-08-15 13:22 UTC, AndTem commented on packages/form/src/FormNewDateRangePicker/FormNewDateRangePicker.stories.tsx
> +                label: 'Дата начала',
Ты label в корень вынес. 
А required думаю надо делать вообще в корне FormNewDateRangePicker, но это отдельная задача

2024-08-15 13:22 UTC, AndTem commented on packages/form/src/FormNewDateRangePicker/FormNewDateRangePicker.stories.tsx
> +  const handleSubmit = form.handleSubmit(
сейчас при сабмите бесконечный скролл

2024-08-15 13:22 UTC, AndTem commented on packages/form/src/FormNewDateRangePicker/FormNewDateRangePicker.stories.tsx
> +  const handleSubmit = form.handleSubmit(
И валмдация на required не отрабатывает

2024-08-15 13:33 UTC, mfrolov89 commented on packages/form/src/FormNewDateRangePicker/FormNewDateRangePicker.stories.tsx
> +                label: 'Дата начала',
я пока не стал трогать required, так как могуть быть ситуации, когда только одна дата обязательна

2024-08-15 13:34 UTC, AndTem commented on packages/form/src/FormNewDateRangePicker/FormNewDateRangePicker.stories.tsx
> +                label: 'Дата начала',
Но в корень item надо вынести required тогда

2024-08-16 05:54 UTC, mfrolov89 commented on packages/form/src/FormNewDateRangePicker/FormNewDateRangePicker.stories.tsx
> +                label: 'Дата начала',
<img width="212" alt="Снимок экрана 2024-08-16 в 08 52 02" src="https://github.com/user-attachments/assets/93ab387b-3b2c-4720-86fb-0967f3297d23">

если под item подразумевается startDateProps и endDateProps, то оно так и сделано

2024-08-16 05:58 UTC, AndTem commented on packages/form/src/FormNewDateRangePicker/FormNewDateRangePicker.stories.tsx
> +                label: 'Дата начала',
Но в story через inputProps

2024-08-16 06:00 UTC, mfrolov89 commented on packages/form/src/FormNewDateRangePicker/FormNewDateRangePicker.stories.tsx
> +                label: 'Дата начала',
это скрин из story, я там во всех примерах ушел от inputProps, а вот в тестах не правил

2024-08-16 06:02 UTC, mfrolov89 commented on packages/form/src/FormNewDateRangePicker/FormNewDateRangePicker.stories.tsx
> +                label: 'Дата начала',
А, все, в компоненте для форм не поправил

2024-08-19 05:33 UTC, AndTem approved these changes

2024-08-19 06:50 UTC, merged