feat(UIKIT-1590,TreeAutocomplete): Реализован компонент TreeAutocomplete
kaluga-astral/frontend pull request #1105
Opened 2024-08-22 09:19 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-08-22 09:23 UTC, mfrolov89 reviewed
<img width="597" alt="Снимок экрана 2024-08-22 в 12 20 22" src="https://github.com/user-attachments/assets/28f6c578-180f-41a8-9e76-561bb7700cec">

Пока это требование не реализовано, кажется что нужно переработать item, чтобы могли навигироваться при помощи клавиатуры

2024-08-22 10:24 UTC, AndTem commented
> Details

Просто focus() у элемента вызвать нельзя?

2024-08-22 10:27 UTC, AndTem commented
Состояние выбранного item не сбрасывается при отмене выбора

https://github.com/user-attachments/assets/891212e0-e37a-4733-be46-92a37b084aad

2024-08-22 10:30 UTC, AndTem commented
Баг arrow для tooltip
<img width="467" alt="image" src="https://github.com/user-attachments/assets/7d238ad6-41f2-495e-844a-40dc5aade914">

2024-08-22 10:35 UTC, AndTem commented
С клавиатуры сейчас вообще никак не попасть в модалку

2024-08-22 10:39 UTC, AndTem commented
С отступом ошибки что-то не так: 
<img width="272" alt="image" src="https://github.com/user-attachments/assets/039b4535-4aa5-4c3f-9b3c-312414bccf25">

2024-08-22 10:41 UTC, AndTem requested changes

2024-08-22 10:41 UTC, AndTem commented on packages/components/src/TreeAutocomplete/TreeAutocomplete.stories.tsx
> +      helperText="Обязательное"
```suggestion
      helperText="Заполните поле"
```

2024-08-22 10:41 UTC, AndTem commented on packages/components/src/TreeAutocomplete/TreeAutocomplete.stories.tsx
> +    label: 'Group 1',
Добавь более менее реальные данные

2024-08-22 10:41 UTC, AndTem commented on packages/components/src/TreeAutocomplete/TreeAutocomplete.tsx
> +  isLoadingError?: boolean;
Сделай по аналогии с Autocomplete и чтобы можно было текст прокинуть

2024-08-22 10:41 UTC, AndTem commented on packages/components/src/TreeAutocomplete/TreeAutocomplete.tsx
> +   * Предназначен для конфигурации всплывающего окна
```suggestion
   * Предназначен для конфигурации дерева в модалке
```

2024-08-22 10:41 UTC, AndTem commented on packages/components/src/TreeAutocomplete/OptionsModal/OptionsModal.tsx
> +        <SearchField fullWidth {...searchFieldProps} />
Поиск надо блокировать, если error или loading

2024-08-22 10:41 UTC, AndTem commented on packages/components/src/TreeAutocomplete/TreeAutocomplete.stories.tsx
> +export const Example = () => {
Надо добавить stories из TreeList компонента с конфигурацией дерева.
Либо сослаться хоть

2024-08-22 10:41 UTC, AndTem commented on packages/components/src/TreeAutocomplete/TreeAutocomplete.stories.tsx
> + * Например можно организовать поиск только по `label`
Только по lable и так дефольно реализовано. Надо показать как искать по note

2024-08-22 11:03 UTC, mfrolov89 commented
> Баг arrow для tooltip <img alt="image" width="467" src="https://private-user-images.githubusercontent.com/23665108/360393829-7d238ad6-41f2-495e-844a-40dc5aade914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjQ3NTUsIm5iZiI6MTcyNDMyNDQ1NSwicGF0aCI6Ii8yMzY2NTEwOC8zNjAzOTM4MjktN2QyMzhhZDYtNDFmMi00OTVlLTg0NGEtNDBkYzVhYWRlOTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDExMDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3OGZhYjU2ZTUxZTZiYWNlNjgxYzZmZDdmNzdiMTAxNTEwYjFmZGU2OGY0NDA2OGFjODc0NWYyNmQ0MGU0ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hvxaYmYozr5Obmj4hUGmzOjC9LemMGf0MKiMelARQpw">

Это тултип TreeList, обсуждали же что это не очень, но тогда решили оставить так. Из TreeAutocomplete я это не сконфигурирую

2024-08-23 07:39 UTC, mfrolov89 commented on packages/components/src/TreeAutocomplete/TreeAutocomplete.stories.tsx
> +      helperText="Обязательное"
Почему именно такой текст? Дефолтный текст валидации на такой кейс: "Обязательно"
Тут контролируемый компонент конечно, но кажется стоит писать именно согласованный вариант текста, чтоб не получилось что здесь кто-то увидит такой текст и начнет использовать его на продукте

2024-08-23 08:19 UTC, mfrolov89 commented on packages/components/src/TreeAutocomplete/TreeAutocomplete.stories.tsx
> + * Например можно организовать поиск только по `label`
Добавлю поиск по label и note по умолчанию, о чем договаривались ранее

2024-08-23 08:25 UTC, AndTem commented on packages/components/src/TreeAutocomplete/TreeAutocomplete.stories.tsx
> +      helperText="Обязательное"
Ага, подумал у нас в требовании едином Заполните поле.
Тогда Е на конце убрать надо

2024-08-23 09:22 UTC, mfrolov89 commented
> Состояние выбранного item не сбрасывается при отмене выбора
> 
>  2024-08-22.13.25.38.mov

Написал Землякову уточнить, потому что в моем понимании кнока отмены не равно кнопке сброса.

Пользователь выбрал некий пункт, далее он решил что ему ничего менять не нужно, поэтому нажимает кнопку 'отмена', так как она более очевидная, чем крестик

2024-08-26 09:34 UTC, mfrolov89 commented
> > Details
> 
> Просто focus() у элемента вызвать нельзя?

отказываемся от этого требования

2024-08-26 11:35 UTC, AndTem commented
Заблокированный элемент при клике выделяется (возможно баг самого дерева, который можно решить отдельно)
Запись экрана 2024-08-26 в 14.35.10

2024-08-26 11:38 UTC, AndTem commented
В форме сообщение об ошибке пропадает только после потери фокуса инпута

Uploading Запись экрана 2024-08-26 в 14.37.54.mov…

2024-08-26 14:38 UTC, mfrolov89 commented
> С клавиатуры сейчас вообще никак не попасть в модалку

исправлено

2024-08-26 14:39 UTC, mfrolov89 commented
> С отступом ошибки что-то не так: <img alt="image" width="272" src="https://private-user-images.githubusercontent.com/23665108/360396907-039b4535-4aa5-4c3f-9b3c-312414bccf25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODI4NjMsIm5iZiI6MTcyNDY4MjU2MywicGF0aCI6Ii8yMzY2NTEwOC8zNjAzOTY5MDctMDM5YjQ1MzUtNGFhNS00YzNmLTliM2MtMzEyNDE0YmNjZjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE0MjkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMTRiY2Q1ZDg5MDUyMTdhM2NhY2MyZGJhMzdjMzE3NTkxNGVkMTVlY2YzODg1NDU5ZjQ3ZjZhNTA0Y2NhMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.83Ni53ZlQvGHbEGIh2fLqad1y0ixuonFHl-IUF_L0F4">

исправлено

2024-08-26 14:45 UTC, pan1caisreal commented
![image](https://github.com/user-attachments/assets/04573d4f-4d4e-44e3-a03e-f15a53eddd4c)
Так и должно работать что при disabled Autocomplete от туда можно заданный элемент убрать?

2024-08-27 07:19 UTC, AndTem commented
> ![image](https://private-user-images.githubusercontent.com/105650840/361474071-04573d4f-4d4e-44e3-a03e-f15a53eddd4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDM0NzIsIm5iZiI6MTcyNDc0MzE3MiwicGF0aCI6Ii8xMDU2NTA4NDAvMzYxNDc0MDcxLTA0NTczZDRmLTRkNGUtNDRlMy1hMDNlLWYxNWE1M2VkZGQ0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwNzE5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2ZmNjFhZTg5MWE3YjFjYzEwOGJjN2RkOWVjMDJmZjJlYWFkNGQ2NGM5MDNjNWZlNTExMDI0MmVmZjkyYjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TJpsNhBfeQzc6keI7X3bNayW3mlbl4KPMUwVxbI5urs) Так и должно работать что при disabled Autocomplete от туда можно заданный элемент убрать?

Не должно быть

2024-08-29 08:49 UTC, AndTem approved these changes

2024-08-29 09:47 UTC, merged