feat(UIKIT-1714,ui): Добавлен новый компонент StaticDaysCalendar
kaluga-astral/frontend pull request #1112
Opened 2024-08-27 10:01 UTC by Ofigelov

- Отрефакторил утилиты дат
  - перенес общие-переиспользуемые в utils/date
  - удалил неиспользуемые
  - упростил результат для фабричных методов создающих грид основного диапазона
  - переименовал disabled и selected в isDisabled и isSelected для лучшего соответствия нашему стайл гайду
  - убрал флаг isRange в RangeDatePicker и в DaysPicker
- Перенес внутренний рендер DaysPicker в отдельный самостоятельный компонент, ответственный за рендер грида с датами
  - Добавил возможность создания собственного тултипа для каждого дня
  - Добавил возможность наполнения ячейки дня кастомными данными
  - Добавил возможность указывать набор выбранных диапазонов дат
  - Добавил мемоизацию рендера, теперь изменения, которые явно не влияют на отображение компонента, не будут влиять на его рендер.

# Чеклист

- [x] Написать тесты для реализованного функционала
- [x] Описать jsdoc для экспортируемых функций, компонентов
- [x] Описать jsdoc для props экспортируемых компонентов
- [x] Реализовать или обновить storybook для компонента
- [x] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-08-29 09:00 UTC, mfrolov89 requested changes
1. Необходимо поправить название pr, вместо ui указать название компонента
2. Забыл экспорт из пакета

2024-08-29 09:00 UTC, mfrolov89 commented on packages/components/src/StaticCalendar/StaticDaysCalendar/StaticDaysCalendar.tsx
> +    const id = useId();
useId используем из наших хуков

2024-08-29 09:00 UTC, mfrolov89 commented on packages/components/src/StaticCalendar/StaticDaysCalendar/StaticDaysCalendar.tsx
> +        baseDate: prev.baseDate,
просто передать 2 аргумента prev и next нельзя?

2024-08-29 09:00 UTC, mfrolov89 commented on packages/components/src/StaticCalendar/StaticDaysCalendar/StaticDaysCalendar.tsx
> +  const { dateA: memoizedSelectedDate, dateB: memoizedHoveredDate } = useMemo(
логику нужно перенести в useLogic

2024-08-29 09:00 UTC, mfrolov89 commented on packages/components/src/StaticCalendar/StaticCalendarGridButton/styles.ts
> +  &:hover {
не вижу смысла в такой записи, так как имеем еще один блок для ховера ниже

2024-08-29 09:00 UTC, mfrolov89 commented on packages/components/src/StaticCalendar/StaticDaysCalendar/MainButton/MainButton.tsx
> +      Boolean(onDayHover) ? () => onDayHover?.(props.date) : undefined
нужно вынести всю логику из рендера в useLogic

2024-08-29 09:00 UTC, mfrolov89 commented on packages/components/src/StaticCalendar/StaticDaysCalendar/MainButton/MainButton.tsx
> +    isHoliday={props.isHoliday}
стоит деструктурировать сразу все что потребуется (например disabled={isDisabled}), все остальное кажется можно без проблем прокинуть через спред-оператор

2024-08-29 09:00 UTC, mfrolov89 commented on packages/components/src/StaticCalendar/StaticDaysCalendar/MainButton/MainButton.tsx
> +export const MainButton = ({
может DayButton? По названию не понятно что это за кнопка и где должна использоваться

2024-08-29 09:00 UTC, mfrolov89 commented on packages/components/src/StaticCalendar/StaticCalendarGridButton/styles.ts
>  export type DateCalendarDayBtnWrapperProps = Omit<ButtonProps, 'variant'> & {
экспорт типа из styles это крайне странно, стоит оформить полноценным компонентом

2024-08-29 09:00 UTC, mfrolov89 commented on packages/components/src/StaticCalendar/StaticDaysCalendar/MainButton/MainButton.tsx
> +export const MainButton = ({
Имеем очень много кнопок с неочевидными названиями, какие есть мысли
1. MainButton удаляем, используемя напрямую StaticCalendarGridButton
2. StaticCalendarGridButton переименовываем в DayButton, или что в этом ключе, так как эта кнопка насколько понял прдназначена только для дат в календаре
3. Упрощаем структуру, выносим все содержимое из StaticDaysCalendar на уровень ниже
4. Название корневой папки синхронизируем с названием компонента

2024-08-29 09:00 UTC, mfrolov89 commented on packages/components/src/utils/date/constants.ts
> +export const DAYS_IN_WEEK = 7;
Нахождение тут этих констант вызывает сомнения, так как они доступны снаружи и в импорте мы ссылаем на utils, что не очень очевидно.

Возможно какие-то мысли будут у @AndTem

2024-08-29 09:02 UTC, Ofigelov commented on packages/components/src/StaticCalendar/StaticDaysCalendar/StaticDaysCalendar.stories.tsx
> + * Пере используется в DatePicker'ах. Так же подойдет для использования в самостоятельном календаре года
Хы, а мне во всех проверщиках орфографии говорит, что нужно раздельно писать

2024-08-29 09:05 UTC, Ofigelov commented on packages/components/src/DatePicker/types/pickerProps.ts
> -  isRange?: boolean;
А зачем он? Это пропс внутреннего компонента, наружу кита он не выходит, и во всех местах где он использовался, я убрал его.

2024-08-29 09:08 UTC, Ofigelov commented on packages/components/src/StaticCalendar/StaticDaysCalendar/StaticDaysCalendar.tsx
> +  const { dateA: memoizedSelectedDate, dateB: memoizedHoveredDate } = useMemo(
чтобы там был просто один useMemo?

2024-08-29 09:09 UTC, Ofigelov commented on packages/components/src/StaticCalendar/StaticCalendarGridButton/styles.ts
> +  &:hover {
Либо так, либо указание цвета текста в двух местах, потому что по умолчанию цвет текста меняется на ховер по кнопке, от которой отнаследован компонент.

Этот вариант мне показался компактней и проще в записи.

2024-08-29 09:11 UTC, Ofigelov commented on packages/components/src/StaticCalendar/StaticDaysCalendar/MainButton/MainButton.tsx
> +    isHoliday={props.isHoliday}
Да, но тогда придется снова собирать пропсы для передачи в `renderDayContent`. Разве это правильно?

2024-08-29 09:19 UTC, Ofigelov commented on packages/components/src/utils/date/constants.ts
> +export const DAYS_IN_WEEK = 7;
Оставлять их либо в StaticCalendar либо в DatePicker посчитал не верным, иначе компоненты будут зависеть друг от друга

2024-08-29 09:34 UTC, AndTem commented on packages/components/src/utils/date/constants.ts
> +export const DAYS_IN_WEEK = 7;
Ну создайте директорию constants в корне

2024-08-29 09:38 UTC, mfrolov89 commented on packages/components/src/StaticCalendar/StaticDaysCalendar/StaticDaysCalendar.stories.tsx
> + * Пере используется в DatePicker'ах. Так же подойдет для использования в самостоятельном календаре года
ужас, это приставка, а не предлог. Можно написать просто 'Используется в...'

2024-08-29 09:38 UTC, mfrolov89 commented on packages/components/src/DatePicker/types/pickerProps.ts
> -  isRange?: boolean;
если так, то согласен, не нужен

2024-08-29 09:42 UTC, Ofigelov commented on packages/components/src/StaticCalendar/StaticCalendarGridButton/styles.ts
>  export type DateCalendarDayBtnWrapperProps = Omit<ButtonProps, 'variant'> & {
А какая разница, откуда это берется внутри компонента? Сам компонент имеет свой index файл, и реэкспортит то, что мы можем использовать снаружи. Если мы сделаем отдельный файл, который будет совпадать с названием компонента, то его суть будет сводиться только к тому, чтобы реэкспортить из styles.
Получится цепочка: 'внешний потребитель'  -> 'реэкспорт в index.ts' -> 'реэкспорт в основном файл' -> 'экспорт из styles.ts'.
В этой цепочке обязанность основного файла только бюррократическая.

2024-08-29 10:51 UTC, mfrolov89 commented on packages/components/src/StaticCalendar/StaticDaysCalendar/MainButton/MainButton.tsx
> +    isHoliday={props.isHoliday}
мы сейчас пробуем немного измененный подход, на уровне объявления компонента дестуктуризацию не делаем, таr как useLogic должен получить все пропсы, а после уже все что нужно извлекаем. 

cont DayButton = (props) => {
   const {} = useLogic(props);

   const { isDisabled, isSelected, ... } = props;

   ...

2024-08-29 10:54 UTC, mfrolov89 commented on packages/components/src/StaticCalendar/StaticCalendarGridButton/styles.ts
>  export type DateCalendarDayBtnWrapperProps = Omit<ButtonProps, 'variant'> & {
файл styles предназначен для стилизации, как минимум можно в types вынести

2024-08-29 11:13 UTC, Ofigelov commented on packages/components/src/StaticCalendar/StaticCalendarGridButton/styles.ts
>  export type DateCalendarDayBtnWrapperProps = Omit<ButtonProps, 'variant'> & {
Оказалось, что этот тип вовсе нигде кроме как в этих стилях и не используется. Убрал экспорт.

2024-08-29 11:16 UTC, Ofigelov commented on packages/components/src/StaticCalendar/StaticDaysCalendar/StaticDaysCalendar.stories.tsx
> + * Для оптимальной работы требуется передавать не анонимную функцию
Вынес в отдельный хэндлер для наглядности

2024-08-29 11:20 UTC, Ofigelov commented on packages/components/src/StaticCalendar/StaticDaysCalendar/MainButton/MainButton.tsx
> +    isHoliday={props.isHoliday}
Давай в этот раз обойдемся без этого? Не понимаю в чем будет польза, только гемор ловить, от того, что нельзя использовать возможности языка

2024-08-30 07:37 UTC, mfrolov89 commented on packages/components/src/StaticCalendar/StaticCalendarGridButton/styles.ts
> +  &:hover {
Так наоборот это более объемная запись, сейчас она занимает 4 строчки, а может 2

2024-08-30 07:40 UTC, Ofigelov commented on packages/components/src/StaticCalendar/StaticCalendarGridButton/styles.ts
> +  &:hover {
сравни

твой вариант:
```
  color: ${(props) => getTextColor(props)};

  &:hover {
    color: ${(props) => getTextColor(props)};
  }
```
и мой вариант
```
  &,
  &:hover {
    color: ${(props) => getTextColor(props)};
  }
```

2024-08-30 08:07 UTC, mfrolov89 approved these changes

2024-08-30 08:14 UTC, merged