feat(UIKIT-1430, AutoSave): Реализован новый компонент
kaluga-astral/frontend pull request #1113
Opened 2024-08-27 11:44 UTC by pan1caisreal

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-08-29 09:46 UTC, mfrolov89 requested changes
нужны тесты

2024-08-29 09:46 UTC, mfrolov89 commented on packages/icons/generated-themed-icons/AutosaveLoaderFillMd.tsx
> +      fill="#1D3F66"
убери заливку цветом

2024-08-29 09:46 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.tsx
> +export type AutoSaveProps = {
```suggestion
export type AutoSaveIndicatorProps = {
```

2024-08-29 09:46 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.stories.tsx
> +export const Example = () => {
убери отступ до layout

<img width="1180" alt="Снимок экрана 2024-08-29 в 12 32 32" src="https://github.com/user-attachments/assets/1245cd09-27b9-45c3-8e70-4b027c84dc5f">

2024-08-29 09:46 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.tsx
> +import { useForwardedRef } from '../hooks';
сделай импорт перед компонентами, чтобы в перемешку не шли

2024-08-29 09:46 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.tsx
> +export const AutoSaveIndicator = forwardRef<HTMLDivElement, AutoSaveProps>(
а нужен ли тут вообще forwardRef?

2024-08-29 09:46 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.tsx
> +            <ErrorWrapper>
Оформи как отдельные компоненты: ErrorState, LoadingState и так далее.

2024-08-29 09:46 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.tsx
> +    const ref = useForwardedRef<HTMLDivElement>(forwardedRef);
думаю достаточно useRef, который стоит закинуть в useLogic

2024-08-29 09:46 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.tsx
> +    const { popoverProps, handleClose } = useLogic({ ref });
отдели пустой строкой

2024-09-02 08:43 UTC, mfrolov89 requested changes

2024-09-02 08:43 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/index.tsx
> +export * from './AutoSaveIndicator';
index.ts

2024-09-02 08:43 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.tsx
> +    const { popoverProps, handleClose } = useLogic({ ref });
up

2024-09-02 08:43 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/constants.ts
> +export const POPOVER_MESSAGE =
очень плохое название константы, содержимое вообще не понятно. Можно вообще от нее отказаться

2024-09-02 08:43 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/LoadingState/styles.ts
> +  0%, 100%{
```suggestion
  0%, 100% {
```

2024-09-02 08:43 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/LoadingState/styles.ts
> +  50%{
```suggestion
  50% {
```

2024-09-02 08:43 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/constants.ts
> +export const DEFAULT_STATE = 'Автосохранение включено';
Плохое название, в месте использования можно подумать что там именно название состояния, а не текст

2024-09-02 08:43 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/useLogic/useLogic.ts
> +    const popoverShow = localStorage.getItem('popoverShow');
вынеси название в константу и добавь префикс astralui-*

2024-09-02 08:43 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/useLogic/useLogic.ts
> +    const popoverShow = localStorage.getItem('popoverShow');
попробуй применить хук useLocalStorage

2024-09-02 08:43 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/useLogic/useLogic.ts
> +      anchorOrigin: {
никак не связано с логикой, определяй сразу в рендере

2024-09-02 08:43 UTC, mfrolov89 commented on packages/icons/generated-themed-icons/AutosaveErrorFillMd.tsx
> +    <path d="M7 20H17.5H18V19.9776C20.8032 19.725 23 17.369 23 14.5C23 11.9332 21.2417 9.77712 18.8639 9.17043C18.2503 6.21826 15.6342 4 12.5 4C9.78783 4 7.46364 5.6611 6.48927 8.02143C3.41461 8.2806
svg не сжимал?

2024-09-02 08:43 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.test.tsx
> +  ])('Состояния отображаются', (props, expectedState) => {
по названию будет непонятно к чему относится проверка

https://kaluga-astral.github.io/style-guide/docs/rules/tests/it-each

2024-09-02 08:51 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.test.tsx
> +  ])('Состояния отображаются', (props, expectedState) => {
вообще тут не тот случай когда стоит использовать each, это отдельные флаги, которые стоит так же отдельно тестировать. Each удобен когда функция или пропс может работать с разным типом данных и нужно проверить что со всеми ими он отработает корректно

2024-09-03 14:12 UTC, mfrolov89 requested changes
смотри ci

2024-09-03 14:12 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/constants.ts
> +export const IS_POPOVER_SHOW = 'astralui-popoverShow';
IS_POPOVER_SHOW - по названию булево значений + непонятно про какой поповер идет речь
astralui-popoverShow - увидев такой ключ в сторадже будет невозможно понять что еще за поповер


astralui-autosaveOnboard что-то в таком ключе

2024-09-03 14:12 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/useLogic/useLogic.ts
> +      open: open,
```suggestion
      open,
```

2024-09-03 14:12 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/useLogic/useLogic.ts
> +  const [storageIsPopoverShow, setStorageIsPopoverShow] = useLocalStorage(
storageOnBoardShow - контекст должен быть понятен

2024-09-03 14:12 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/ErrorState/ErrorState.tsx
> +          {ON_RETRY_MESSAGE}
это не сообщение, это текст кнопки

2024-09-03 14:12 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/ErrorState/styles.ts
> +  height: 16px;
может лучше вообще высоту отменить?

2024-09-03 14:12 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.stories.tsx
> +    <Grid spacing={3}>
все прилипает к краям сверху и снизу

2024-09-03 14:12 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.stories.tsx
> +        errorMsg="Изменения не сохранены"
errorMsg в каждом состоянии загрязнет сторю и делает ее недостверной

2024-09-03 14:12 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.stories.tsx
> +                <NewDataGrid<DataType>
1. таблица прилипла к краям
2. Непонятно какое она вообще имеет отношение к сторе, лучше показать всевдоформу с несколькими полям, при потере фокуса вызываем сохранение

2024-09-04 08:07 UTC, pan1caisreal commented on packages/components/src/AutoSaveIndicator/ErrorState/styles.ts
> +  height: 16px;
![image](https://github.com/user-attachments/assets/095e79c1-8e26-4c4f-b749-8e550acb21ef)
Если отменить высоту, то она очень высокая получается, и это плохо будет смотреться
Проп size=small 32px высота кнопки

2024-09-04 09:53 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/constants.ts
> +export const AUTOSAVE_POPOVER = 'astralui-autosaveOnboard';
```suggestion
export const AUTOSAVE_ONBOARD_KEY = 'astralui-autosaveOnboard';
```

2024-09-04 10:05 UTC, mfrolov89 commented on packages/components/src/AutoSaveIndicator/ErrorState/styles.ts
> +  height: 16px;
речь про unset

2024-09-04 12:48 UTC, mfrolov89 approved these changes

2024-09-04 13:20 UTC, merged