feat(UIKIT-1726,DatePicker): Адаптация под мобильные устройства
kaluga-astral/frontend pull request #1129
Opened 2024-09-09 12:11 UTC by pan1caisreal

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-09-10 07:26 UTC, mfrolov89 requested changes
1. Размер кнопок "<" и ">" не соответсвуют макетам
2. Размер окна при выборе месяца и года не должен меняться

2024-09-10 07:26 UTC, mfrolov89 commented on packages/components/src/DatePicker/styles.ts
> +  box-shadow: 0 -1px 10px 0 #072d571a;
1. Тень должна браться из темы
2. Нужна ли эта тень? На макетах есть 2 варианта, говорили что нужно уточнить

2024-09-10 07:26 UTC, mfrolov89 commented on packages/components/src/DatePicker/styles.ts
> +  box-shadow: 0 -1px 10px 0 #072d571a;
Название wrapper не очень подходит, так как подразумевешь сразу общую обертку, а это обертка только для кнопки подверждления

2024-09-10 07:26 UTC, mfrolov89 commented on packages/components/src/DatePicker/DatePicker.tsx
> +    const { isMobile } = useViewportType();
перенеси все в useLogic

2024-09-10 10:10 UTC, pan1caisreal commented on packages/components/src/DatePicker/styles.ts
> +  box-shadow: 0 -1px 10px 0 #072d571a;
1. Такой тени нет в теме
2. Дизайнеры сказали что тень нужна, добавили на макеты

2024-09-10 14:55 UTC, mfrolov89 requested changes
https://github.com/user-attachments/assets/ccfa8e9a-f4b1-4e0b-835d-4d006b124701

2024-09-10 14:55 UTC, mfrolov89 commented on packages/components/src/DatePicker/DateCalendar/styles.tsx
> +    / 48px 1fr 48px;
на десктопе кнопка 32px

2024-09-11 11:20 UTC, mfrolov89 requested changes
смотри ci

2024-09-11 11:20 UTC, mfrolov89 commented on packages/components/src/DatePicker/styles.ts
> +  box-shadow: 0 -1px 10px 0 ${({ theme }) => rgb(theme.palette.grey[900] 0.1)};
```suggestion
  box-shadow: 0 -1px 10px 0 ${({ theme }) => rgba(theme.palette.grey[900] 0.1)};
```

2024-09-12 06:47 UTC, mfrolov89 requested changes

2024-09-13 06:25 UTC, mfrolov89 commented on packages/components/src/DatePicker/useLogic/useLogic.ts
> +  const [selectDate, setSelectDate] = useState(value);
```suggestion
  const [selectedDate, setSelectedDate] = useState(value);
```

2024-09-20 08:41 UTC, mfrolov89 approved these changes

2024-09-20 10:13 UTC, merged