feat(UIKIT-1259,NotificationNext): Добавлен тип уведомлений progress
kaluga-astral/frontend pull request #1134
Opened 2024-09-12 09:49 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-09-12 09:50 UTC, mfrolov89 commented on packages/components/src/NotificationNext/NotificationNext.tsx
> +      update: (updateTitle, updateOptions) =>
ранее оговоренное название updateProgress показалсоь несколько излишним

2024-09-12 11:15 UTC, AndTem commented
Считаю, что не хватает быстрой анимации изменения высоты

2024-09-12 11:15 UTC, AndTem requested changes

2024-09-12 11:15 UTC, AndTem commented on packages/components/src/NotificationNext/NotificationNext.tsx
> +      update: (updateTitle, updateOptions) =>
```suggestion
      update: (title, options) =>
```

2024-09-12 11:15 UTC, AndTem commented on packages/components/src/NotificationNext/NotificationNext.tsx
> +      update: (updateTitle, updateOptions) =>
Название параметров - глаголы. А здесь должны быть существительные

2024-09-12 11:15 UTC, AndTem commented on packages/components/src/NotificationNext/NotificationNext.stories.tsx
> +    const progressNotify = notify.progress('Подписание документов 1 из 3', {
Кажется, что для удобства нужен метод create.
Чтобы заранее можно было проинициализровать и потом не работать с optional значениями

2024-09-12 11:15 UTC, AndTem commented on packages/components/src/NotificationNext/NotificationNext.stories.tsx
> +      containerId: 'progress-notify',
id нужен для story?
Можно как-то скрыть это в show code? Или коммент оставить
А то ощущение, что это обязательно делать

2024-09-12 11:15 UTC, AndTem commented on packages/components/src/NotificationNext/NotificationNext.stories.tsx
> +    toast.dismiss({ containerId: 'progress-notify' });
Мне кажется не хватает метода close. Он может пригодится в крайних сценариях

2024-09-12 11:17 UTC, AndTem commented on packages/components/src/NotificationNext/NotificationNext.stories.tsx
>  export const WithStack = () => {
Здесь забыл изменить старую реализацию на новую

2024-09-12 11:19 UTC, AndTem requested changes

2024-09-12 11:19 UTC, AndTem commented on packages/components/src/NotificationNext/NotificationNext.test.tsx
> +  afterEach(() => {
Кажется, этот блок должен быть внутри describe 'Progress notify'

2024-09-12 11:19 UTC, AndTem commented on packages/components/src/NotificationNext/NotificationNext.test.tsx
> +  describe('Progress notify', () => {
Нужен тест на закрытие уведомления: в progress нельзя заакрыть, в success и error можно

2024-09-13 06:45 UTC, AndTem requested changes

2024-09-13 06:45 UTC, AndTem commented on packages/components/src/NotificationNext/NotificationNext.stories.tsx
> +  const progressNotify = notify.initProgress({
При каждом перерендере будет создаваться новый объект. Оберни в useState, ref, useMemo

2024-09-13 06:45 UTC, AndTem commented on packages/components/src/NotificationNext/NotificationNext.stories.tsx
> +  const progressNotify = notify.initProgress({
Ну и сейчас не работает story

2024-09-13 06:45 UTC, AndTem commented on packages/components/src/NotificationNext/NotificationNext.stories.tsx
> +export const ProgressNotify = () => {
Сделай две колоник с кнопками, чтобы было понятно, что можно одновременно два уведомления отображать.
Также надо и тест на этот кейс написать

2024-09-13 07:34 UTC, mfrolov89 commented on packages/components/src/NotificationNext/NotificationNext.stories.tsx
> +  const progressNotify = notify.initProgress({
useMemo было, да куда-то сплыло(

2024-09-13 08:40 UTC, AndTem commented
> Считаю, что не хватает быстрой анимации изменения высоты

up

2024-09-13 09:10 UTC, mfrolov89 commented
> > Считаю, что не хватает быстрой анимации изменения высоты
> 
> up

Давай отдельной задачей потом сделаем. Не считаю что это важная часть функционала для этой задачи. Простейшее transtition height тут не сработает, у нас сейчас нет точек перехода, например hover или какого-то доп.класса (например открыто/скрыто) + нет заданных значений, у нас height: auto по сути. Как быстро сделать такую анимацию идей пока нет.

Что скажешь?

2024-09-13 09:14 UTC, AndTem commented
> > > Считаю, что не хватает быстрой анимации изменения высоты
> 
> > 
> 
> > up
> 
> 
> 
> Давай отдельной задачей потом сделаем. Не считаю что это важная часть функционала для этой задачи. Простейшее transtition height тут не сработает, у нас сейчас нет точек перехода, например hover или какого-то доп.класса (например открыто/скрыто) + нет заданных значений, у нас height: auto по сути. Как быстро сделать такую анимацию идей пока нет.
> 
> 
> 
> Что скажешь?

Ок. Но дизам на ревью отдать стоит

2024-09-13 11:27 UTC, AndTem approved these changes

2024-09-13 12:43 UTC, merged