feat(UIKIT-1721,HintIcon): Реализован новый компонент HintIcon
kaluga-astral/frontend pull request #1135
Opened 2024-09-12 13:19 UTC by pan1caisreal

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-09-12 15:52 UTC, mfrolov89 requested changes

2024-09-12 15:52 UTC, mfrolov89 commented on packages/components/src/HintIcon/useLogic/useLogic.ts
> +  const handleOpen = () => {
отдели пустой строкой

2024-09-12 15:52 UTC, mfrolov89 commented on packages/components/src/HintIcon/useLogic/useLogic.ts
> +    setOpen(false);
добавь тоже проверку на isMobile, setOpen нет нужды дергать

2024-09-12 15:52 UTC, mfrolov89 commented on packages/components/src/HintIcon/HintIcon.stories.tsx
> +export const OptionsVariant = () => {
```suggestion
export const IconOptionsVariant = () => {
```

2024-09-12 15:52 UTC, mfrolov89 commented on packages/components/src/HintIcon/HintIcon.stories.tsx
> +          iconOption={{ color: 'grey' }}
оставь с дефолтным цветом тут

2024-09-12 15:52 UTC, mfrolov89 commented on packages/components/src/HintIcon/HintIcon.test.tsx
> +    const icon = screen.getByLabelText('info').getElementsByTagName('svg')[0];
зачем такое усложнение, если у теб всего 1 svg?

2024-09-12 15:52 UTC, mfrolov89 commented on packages/components/src/HintIcon/Icon/styles.ts
> +export const InfoFill = styled(InfoFillMd, {
а если иконок будет еще больше?
Задавай цвет через общий контейнер

2024-09-12 15:52 UTC, mfrolov89 commented on packages/components/src/HintIcon/hooks/useIconColor/index.ts
> +export * from './useIconColor';
если хук нужен для компонента Icon, то он должен находится там. Так видна зависимость и что к чему относится

2024-09-12 15:52 UTC, mfrolov89 commented on packages/components/src/HintIcon/hooks/useIconColor/useIconColor.ts
> +    if (colorName) {
опиши через объект

2024-09-12 15:52 UTC, mfrolov89 commented on packages/components/src/HintIcon/hooks/useIconColor/useIconColor.ts
> +  color?: 'warning' | 'grey' | 'lightGrey';
```suggestion
  color?: IconColor;
```

2024-09-12 15:52 UTC, mfrolov89 commented on packages/components/src/HintIcon/hooks/useIconColor/useIconColor.ts
> +    if (colorName) {
с получением цвета через объект мемоизация не нужна, это простая операция

2024-09-12 15:52 UTC, mfrolov89 commented on packages/components/src/HintIcon/Icon/Icon.tsx
> +  const getIcon = () => {
иконку нужно получать из константы ICONS

2024-09-12 15:52 UTC, mfrolov89 commented on packages/components/src/HintIcon/Icon/Icon.tsx
> +  const iconColor = useIconColor({ color: iconOption?.color });
должен быть useLogic

2024-09-13 12:58 UTC, mfrolov89 commented on packages/components/src/HintIcon/HintIcon.test.tsx
> +    const icon = screen.getByLabelText('info').getElementsByTagName('svg')[0];
речь про getByLabelText

2024-09-13 13:03 UTC, mfrolov89 commented on packages/components/src/HintIcon/Icon/Icon.tsx
> +        {ICONS[variant][iconOptionVariant]}
вынеси в функцию, так как если ничего из объекта не получили, то нужно вернуть иконку в дефолтном варианте. Это необходимо чтобы ничего не сломалось, когда прокинут несуществующий вариант. Функцию можно закинуть в useLogic

2024-09-13 13:04 UTC, mfrolov89 commented on packages/components/src/HintIcon/Icon/useLogic/useLogic.ts
> +import { useIconColor } from '../hooks';
этот хук должн располагаться внутри папки useLogic

2024-09-13 13:28 UTC, pan1caisreal commented on packages/components/src/HintIcon/HintIcon.test.tsx
> +    const icon = screen.getByLabelText('info').getElementsByTagName('svg')[0];
![image](https://github.com/user-attachments/assets/917004ae-7d2d-40cd-94e4-72a7b7999609)
@mfrolov89

2024-09-16 06:17 UTC, mfrolov89 requested changes
Забыл экспорт в корневом index

2024-09-16 07:18 UTC, mfrolov89 approved these changes

2024-09-16 07:39 UTC, merged