feat(UIKIT-1743,AutoSaveIndicator): Добавлен store для индикатора автосохранения
kaluga-astral/frontend pull request #1136
Opened 2024-09-13 08:47 UTC by Cabagemage

# Чеклист

- [x] Написать тесты для реализованного функционала
- [x] Описать jsdoc для экспортируемых функций, компонентов
- [x] Описать jsdoc для props экспортируемых компонентов
- [x] Реализовать или обновить storybook для компонента
- [x] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-09-13 10:06 UTC, AndTem requested changes

2024-09-13 10:06 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/AutoSaveIndicatorStore/AutoSaveIndicatorStore.ts
> +export class AutoSaveIndicatorStore {
Тесты бы на этот стор написать, чтобы понять, что реактивность работает

2024-09-13 10:06 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/useInitAutoSaveIndicatorStore/useInitAutoSaveIndicatorStore.ts
> +export const useInitAutoSaveIndicatorStore = (
Давай по style guide, в директорию hooks

2024-09-13 10:06 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/useInitAutoSaveIndicatorStore/useInitAutoSaveIndicatorStore.ts
> +export const useInitAutoSaveIndicatorStore = (
js doc описание нужно с назначением

2024-09-13 10:06 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/AutoSaveIndicatorService.ts
> +export class AutoSaveIndicatorService implements IAutoSaveIndicatorService {
js doc нужен с описанием

2024-09-13 10:06 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/AutoSaveIndicatorStore/AutoSaveIndicatorStore.ts
> +export class AutoSaveIndicatorStore {
js doc нужен с описанием

2024-09-13 10:06 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/README.md
> +## Сервис AutoSaveIndicator
Надо написать о назначении и сослаться на компонент в storybook

2024-09-13 10:06 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/README.md
> +## Сервис AutoSaveIndicator
Добавь еще в storybook компонента ссылку на этот стор

2024-09-13 10:06 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/README.md
> +## Сервис AutoSaveIndicator
Идеально даже показать там пример использования

2024-09-13 10:06 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/README.md
> +**AutoSaveIndicatorService** - сама реализация сервиса. Является внутренним и его использование
Дока для пользователей пакета, такая инфа лишняя

2024-09-13 10:06 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/README.md
> +pages/somePage/header.tsx
modules/layout/features/MainLayout/Header

2024-09-13 10:06 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/README.md
> +class UIStore {
Отступы не соответсвуют нашим eslint

2024-09-13 10:06 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/AutoSaveIndicatorStore/AutoSaveIndicatorStore.ts
> +  public get hide() {
для каждого метода и геттера нужно jsdoc описать. Потому что с ним будут взаимодействовать разработчики

2024-09-13 10:06 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/README.md
> +## Сервис AutoSaveIndicator
Еще нужен список методов и свойств + их описание

2024-09-16 08:59 UTC, AndTem requested changes

2024-09-16 08:59 UTC, AndTem commented on packages/features/src/index.ts
> +} from './AutoSaveIndicatorService';
Сделай другую структуру:
AutoSaveIndicator
  services
  stores
  hooks

2024-09-16 08:59 UTC, AndTem commented on packages/features/README.md
> +**show** - Установки значения **isVisible** в true
```suggestion
`show` - Установки значения `isVisible`в true
```

2024-09-16 08:59 UTC, AndTem commented on packages/features/README.md
> +**show** - Установки значения **isVisible** в true
Будет как код выделено

2024-09-16 08:59 UTC, AndTem commented on packages/features/README.md
> +Необходимо создать инстанс AutoSaveIndicatorStore, затем вызвать хук useInitAutoSaveIndicatorStore на уровне скрина, где
Нужен кусок кода, где создается стор. И укажи путь: shared/stores/...

2024-09-16 08:59 UTC, AndTem commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.stories.tsx
> +const ObservableExample = observer(() => {
StoreIntergration

2024-09-16 08:59 UTC, AndTem commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.stories.tsx
> +const ObservableExample = observer(() => {
Нужно небольшое описание с ссылкой на стор

2024-09-16 08:59 UTC, AndTem commented on packages/components/src/AutoSaveIndicator/AutoSaveIndicator.stories.tsx
> + * Для декларативной работы с компонентом стоит использовать [AutoSaveIndicatorStore](https://github.com/kaluga-astral/frontend/tree/feat/UIKIT-1743/packages/features)
Замени ссылку на npm.
Мы же переедем скоро в gitlab

2024-09-16 08:59 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/AutoSaveIndicatorService.test.ts
> +  describe('Инициализация сервиса', () => {
Это же условия: При инициализации сервсиа

2024-09-16 08:59 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/AutoSaveIndicatorService.test.ts
> +    it('Состояние ошибки будет сброшено до изначального состояния при вызове метода', () => {
Приведи все текста кейсов в одно время.
Где будущее, где-то настоящее. Пусть везде будет настоящее

2024-09-16 08:59 UTC, AndTem commented on packages/features/src/AutoSaveIndicatorService/stores/AutoSaveIndicatorStore/AutoSaveIndicatorStore.ts
> +   * Метод для скрытия компонента
Слово "метод" - это шум.
Просто: скрывает компонент

2024-09-16 11:31 UTC, AndTem approved these changes

2024-09-16 11:49 UTC, mfrolov89 approved these changes

2024-09-16 11:52 UTC, merged