feat(UIKIT-1771,OverflowTypography): Добавлен prop visibleLastSymbolsCount
kaluga-astral/frontend pull request #1138
Opened 2024-09-16 08:22 UTC by pan1caisreal

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-09-16 11:29 UTC, mfrolov89 requested changes
Смотри ci

2024-09-16 11:29 UTC, mfrolov89 commented on packages/components/src/OverflowTypography/OverflowTypography.stories.tsx
> +    <div style={{ maxWidth: '200px' }}>
Не смотрел как поведет себя компонент, если задать rowsCount например 2?

2024-09-16 11:29 UTC, mfrolov89 commented on packages/components/src/OverflowTypography/OverflowTypography.tsx
> +    const canSlice = children && typeof children === 'string';
вынеси логику в useLogic

2024-09-17 08:54 UTC, pan1caisreal commented on packages/components/src/OverflowTypography/OverflowTypography.stories.tsx
> +    <div style={{ maxWidth: '200px' }}>
Добавил jsdoc в storie, rowsCount работать не будет, реализация его будет кривая на мой взгляд, если ее перенести на этот кейс из-за разделения компонента на 2 отдельных тэга span

2024-09-18 07:15 UTC, mfrolov89 commented on packages/components/src/OverflowTypography/OverflowTypography.stories.tsx
> + * Prop `visibleLastSymbolsCount` позволяет задавать число отображаемых символов после сокращения,
```suggestion
 * Prop `visibleLastSymbolsCount` позволяет задавать число отображаемых символов после сокращения.
```

2024-09-18 07:16 UTC, mfrolov89 commented on packages/components/src/OverflowTypography/OverflowTypography.stories.tsx
> + * при использовании `visibleLastSymbolsCount` не работает props `rowsCount`
```suggestion
 * При использовании `visibleLastSymbolsCount` не работает props `rowsCount`
```

Пропс не работает или работает не корректно? Если второе, то так и напиши, что поддеживается работа только для отображения в одну строку

2024-09-18 07:17 UTC, mfrolov89 commented on packages/components/src/OverflowTypography/OverflowTypography.stories.tsx
> +    <div style={{ maxWidth: '200px' }}>
стилизуй через styled. Инлайн стили не по код-стайлу и тут их тоже не стоит использовать, чтобы кто-то не подумал что так ок

2024-09-18 07:25 UTC, mfrolov89 commented on packages/components/src/OverflowTypography/OverflowTypography.tsx
> +    const { align = 'left' } = props;
почемы выше этот пропс не извлек?

2024-09-18 07:57 UTC, pan1caisreal commented on packages/components/src/OverflowTypography/OverflowTypography.stories.tsx
> + * при использовании `visibleLastSymbolsCount` не работает props `rowsCount`
Пропс сейчас не работает

2024-09-18 13:24 UTC, mfrolov89 commented on packages/components/src/OverflowTypography/OverflowTypography.stories.tsx
> +      <OverflowTypography align="right">
Зачем тут align="right"?

2024-09-19 07:03 UTC, mfrolov89 approved these changes
Было
<img width="1068" alt="Снимок экрана 2024-09-18 в 16 23 10" src="https://github.com/user-attachments/assets/ac338701-e149-4419-afeb-48b49950776f">

Стало

2024-09-19 08:20 UTC, merged