wip(@astral/ui, List): Сделан компонент List и дочерние и подготовлены стили для ссылок
kaluga-astral/frontend pull request #114
Opened 2022-02-28 09:10 UTC by olewka40

2022-02-28 11:40 UTC, AndTem commented
@olewka40 Необходимо убрать ripple для кнопок

2022-02-28 11:43 UTC, AndTem commented on packages/ui/src/List/List.stories.tsx
> +          <ListItem selected>
сделай интерактив, добавь useState, чтобы можно было нажимать на кнопки и получать отдачу

2022-02-28 11:44 UTC, AndTem commented on packages/ui/src/ListItemSecondaryAction/ListItemSecondaryAction.tsx
> +export const ListItemSecondaryAction = ({
лишний код, сделай просто экспорт из mui

2022-02-28 11:45 UTC, AndTem commented on packages/ui/src/ListSubheader/ListSubheader.tsx
> +export const ListSubheader = ({ children, ...props }: ListSubheaderProps) => {
лишний код, сделай просто экспорт

2022-03-01 07:14 UTC, AndTem commented on packages/ui/src/ListItemButton/ListItemButton.tsx
> +    <StyledListItemButton disableRipple {...props}>
у тебя здесь можно включить ripple. Убери из типа пропсов disableRipple и сделай так, чтобы нельзя было переопределить (то есть поставить определение пропса после {...props})

2022-03-01 07:18 UTC, AndTem requested changes
@olewka40 жду интерактив для stories

2022-03-01 14:53 UTC, AndTem commented
@olewka40 конфликты в lock файле. Реши в пользу main ветки

2022-03-01 14:55 UTC, AndTem commented on packages/ui/src/List/List.tsx
> +export const List = styled(MuiList)`
У нас для стилей создается отдельный файл styled. Здесь надо сделать также. В файле List.tsx просто сделай export { StyledList as List } from './styled'

2022-03-01 14:56 UTC, AndTem commented
@olewka40 название PR некорректное. Это точно не wip - это feat

2022-03-03 10:12 UTC, merkelAlbert commented on packages/ui/src/ListItemIcon/ListItemIcon.tsx
> +export const ListItemIcon = ({ children, ...props }: ListItemIconProps) => {
зачем children вытаскивать?

Можно же просто <StyledListItemIcon {...props} />

2022-03-03 11:22 UTC, AndTem approved these changes

2022-03-03 11:51 UTC, merkelAlbert requested changes
Во всех остальных тоже убери children, думал ты заметишь, прости что сразу не написал

2022-03-03 12:52 UTC, merkelAlbert approved these changes

2022-03-03 12:56 UTC, merged