feat(ui, DatePicker): Реализован компонент DatePicker
kaluga-astral/frontend pull request #148
Opened 2022-03-03 13:31 UTC by Laschenkov67

Реализовал компонент DatePicker с провайдером и styleOverrides

2022-03-03 13:38 UTC, AndTem requested changes

2022-03-03 13:38 UTC, AndTem commented on package.json
> +    "date-fns": "^2.28.0"
это должно быть в package.json для ui

2022-03-03 13:38 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.tsx
> +        //@ts-ignore
такого в коде быть не должно

2022-03-03 13:38 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.tsx
> +    const [value, setValue] = React.useState<Date | null>(new Date());
это для чего? у тебя value и onChange пропсами прокидывается

2022-03-03 13:38 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.tsx
> +export const DatePicker = React.forwardRef<HTMLDivElement, DatePickerProps>(
Из пропсов DatePickerProps надо убрать renderInputs и components потому, что ты сделал так, что их нельзя переопределить

2022-03-03 13:38 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.tsx
> +export const DatePicker = React.forwardRef<HTMLDivElement, DatePickerProps>(
Мы не используем namespaces. Делай просто import { forwardRef } from 'react'

2022-03-03 13:38 UTC, AndTem commented on packages/ui/src/DatePickersUtilsProvider/DatePickersUtilsProvider.tsx
> +export const DatePickersUtilsProvider = ({ children }: any) => (
почему utils?

2022-03-03 13:38 UTC, AndTem commented on packages/ui/src/DatePickersUtilsProvider/DatePickersUtilsProvider.tsx
> +export const DatePickersUtilsProvider = ({ children }: any) => (
добавь сразу props locale

2022-03-03 13:38 UTC, AndTem commented on packages/ui/src/theme/components/MuiPickersDay.ts
> +        fontSize: '14px',
fontSize должен браться из темы

2022-03-03 13:38 UTC, AndTem commented on packages/ui/src/theme/components/components.ts
> +const MuiPaper: Components<Theme>['MuiPaper'] = {
1. под каждый компонент создается свой файл
2. ты такими действиями сломал верстку других компонентов (paper используется не только в datepicker)

2022-03-03 13:40 UTC, AndTem commented on packages/ui/src/DatePickersUtilsProvider/DatePickersUtilsProvider.tsx
> +export const DatePickersUtilsProvider = ({ children }: any) => (
any - не используем

2022-03-03 13:41 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.stories.tsx
> +        renderInput={(params) => <TextField {...params} />}
у тебя renderInput определен уже внутри DatePicker

2022-03-03 13:59 UTC, AndTem commented
@Laschenkov67 
1. Кнопка при наведении не соответсвует дизайн системе
<img width="94" alt="image" src="https://user-images.githubusercontent.com/23665108/156578821-7b3fe0d2-30d8-450b-af69-f1fa5c366286.png">
2.Нижнее подчеркивание не устанавливается для выбранной даты
<img width="341" alt="image" src="https://user-images.githubusercontent.com/23665108/156578983-99984d4f-f3d8-4295-bdff-d25cf040c368.png">
3. При наведении на активную дату нижнее подчеркивание закругляется
<img width="63" alt="image" src="https://user-images.githubusercontent.com/23665108/156579119-4e58ee27-1a2c-4f54-a295-d7e33875bff0.png">
4. Некорректная тень у popup

2022-03-04 11:44 UTC, merkelAlbert commented on package.json
> +  "dependencies": {
test

2022-03-04 14:53 UTC, Laschenkov67 commented on packages/ui/src/DatePicker/DatePicker.tsx
> +        //@ts-ignore
Исправлено

2022-03-04 14:54 UTC, Laschenkov67 commented on packages/ui/src/DatePicker/DatePicker.tsx
> +    const [value, setValue] = React.useState<Date | null>(new Date());
Это нужно для установления текущей даты по умолчанию, немного исправил и убрал лишнее

2022-03-04 14:54 UTC, Laschenkov67 commented on packages/ui/src/DatePicker/DatePicker.tsx
> +export const DatePicker = React.forwardRef<HTMLDivElement, DatePickerProps>(
Исправлено

2022-03-04 14:54 UTC, Laschenkov67 commented on packages/ui/src/theme/components/MuiPickersDay.ts
> +        fontSize: '14px',
Исправлено

2022-03-04 14:58 UTC, Laschenkov67 commented on packages/ui/src/DatePickersUtilsProvider/DatePickersUtilsProvider.tsx
> +export const DatePickersUtilsProvider = ({ children }: any) => (
Вот здесь честно говоря не знаю какое название сделать, может быть LocalizationProvider так и оставить?

2022-03-05 07:22 UTC, AndTem commented on packages/ui/src/DatePickersUtilsProvider/DatePickersUtilsProvider.tsx
> +export const DatePickersUtilsProvider = ({ children }: any) => (
@Laschenkov67 согласен, LocalizationProvider

2022-03-05 09:09 UTC, Laschenkov67 commented on packages/ui/src/DatePickersUtilsProvider/DatePickersUtilsProvider.tsx
> +export const DatePickersUtilsProvider = ({ children }: any) => (
Исправлено

2022-03-15 08:33 UTC, merkelAlbert commented on packages/ui/src/DatePicker/DatePicker.tsx
> +    const [value] = useState<Date | null>(new Date());
Это для чего. Разве не из пропсов должно быть? И если есть value, то нужен onChange

2022-03-16 06:37 UTC, merkelAlbert commented on packages/ui/src/DatePicker/DatePicker.tsx
> +        value={new Date()}
нет. так у тебя value всегда текущей датой будет

{value = new Date(), ...props} так я предлагал

2022-03-16 06:39 UTC, merkelAlbert commented on packages/ui/src/LocalizationProvider/LocalizationProvider.tsx
> +}): JSX.Element => {
тип не нужен тут, он и так выведется

2022-03-16 07:29 UTC, Laschenkov67 commented on packages/ui/src/DatePicker/DatePicker.tsx
> +        value={new Date()}
Исправил

2022-03-16 07:29 UTC, Laschenkov67 commented on packages/ui/src/LocalizationProvider/LocalizationProvider.tsx
> +}): JSX.Element => {
Исправил

2022-03-21 05:14 UTC, AndTem commented
@Laschenkov67 тесты упали

2022-03-22 14:21 UTC, AndTem requested changes

2022-03-22 14:21 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.tsx
> +          style: {
Плохая практика стилизовать компонент через style. Сделай через styled и обращение через class

2022-03-22 14:21 UTC, AndTem commented on packages/ui/src/LocalizationProvider/LocalizationProvider.tsx
> +export const LocalizationProvider: FC<LocalizationProviderProps> = ({
из LocalizationProviderProps необходимо убрать dateAdapter так, как ты забил гвоздями здесь уже его

2022-03-22 14:21 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.stories.tsx
> +    <LocalizationProvider dateAdapter={AdapterDateFns}>
нет смысла прокидывать dateAdapter потому, что ты это делаешь внутри LocalizationProvider

2022-03-22 14:29 UTC, AndTem commented on packages/ui/src/DatePicker/types.ts
> +
Добвь тип DatePickerValue - какой тип устанавливается в value

2022-03-28 13:06 UTC, Laschenkov67 commented on packages/ui/src/LocalizationProvider/LocalizationProvider.tsx
> +export const LocalizationProvider: FC<LocalizationProviderProps> = ({
Исправил

2022-03-28 13:07 UTC, Laschenkov67 commented on packages/ui/src/DatePicker/types.ts
> +
Не понятно, какой тип и для чего добавить

2022-03-28 14:52 UTC, AndTem requested changes

2022-04-13 10:02 UTC, closed without merging