feat(@astral/ui, Dialog): Добавлены компоненты Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle
kaluga-astral/frontend pull request #154
Opened 2022-03-05 07:14 UTC by Nikita-Smirnov

2022-03-05 13:04 UTC, AndTem requested changes

2022-03-05 13:04 UTC, AndTem commented on packages/ui/src/theme/components/components.ts
> +const MuiDialogActions: Components<Theme>['MuiDialogActions'] = {
Необходимо сделать так, чтобы между элементами, которые прокидываются в этот компонент был отступ (используй grid)

2022-03-05 13:04 UTC, AndTem commented on packages/ui/src/Dialog/Dialog.tsx
> +export const Dialog = ({ children, ...props }: DialogProps) => {
еще нужен пропс disableBackdropClick

2022-03-10 12:19 UTC, merkelAlbert commented on packages/ui/src/Dialog/Dialog.tsx
> +      {title ? (
title && {}

2022-03-10 12:19 UTC, merkelAlbert commented on packages/ui/src/Dialog/Dialog.tsx
> +    if (disableBackdropClick && reason && reason == 'backdropClick') return;
зачем проверять reasonn? просто disableBackdropClick && reason == 'backdropClick'

2022-03-10 12:19 UTC, merkelAlbert commented on packages/ui/src/DialogActions/DialogActions.tsx
> +      {/*{children}*/}
?

2022-03-10 12:19 UTC, merkelAlbert commented on packages/ui/src/DialogActions/DialogActions.tsx
> +          {leftSideChildren}
Это 'больше не показывать на макетах'?

2022-03-10 12:19 UTC, merkelAlbert commented on packages/ui/src/DialogTitle/DialogTitle.tsx
> +      {showCloseButton ? (
&&

2022-03-10 12:21 UTC, Nikita-Smirnov commented on packages/ui/src/DialogActions/DialogActions.tsx
> +          {leftSideChildren}
да

2022-03-14 07:51 UTC, merkelAlbert commented on packages/ui/src/DialogActions/DialogActions.tsx
> +          {leftSideChildren}
Мне кажется это не нужно. во первых нейминг не очень. Во вторых, думаю, что юзеры должны сами это делать внутри DialogActions. Просто закинуть третьего ребенка и отпозиционировать его. 
Например что-то вроде такого.

`<DialogActions>
          <div style={{ marginRight: "auto" }}>
            <Button>dont show again</Button>
          </div>
          <Button autoFocus onClick={handleClose}>
            Disagree
          </Button>
          <Button onClick={handleClose} autoFocus>
            Agree
          </Button>
        </DialogActions>`
        
Нужно еще чье-то мнение.

2022-03-14 07:53 UTC, Nikita-Smirnov commented on packages/ui/src/DialogActions/DialogActions.tsx
> +          {leftSideChildren}
мне тоже так кажется, что не нужно: но Андрей комментарий  сделал https://github.com/kaluga-astral/frontend/pull/154#discussion_r820098130, по этому и добавил

2022-03-14 08:20 UTC, julderen commented on packages/ui/src/Dialog/Dialog.tsx
> +  const handleClose = (
если нет onClose, то нет смысла каждый раз вызывать данную функцию

2022-03-14 08:20 UTC, julderen commented on packages/ui/src/DialogActions/DialogActions.tsx
> +          {leftSideChildren}
Согласен с тем, что leftSideChildren не нужен. Думаю использование Grid как обертку для children достаточно

2022-03-14 08:22 UTC, Nikita-Smirnov commented on packages/ui/src/DialogActions/DialogActions.tsx
> +          {leftSideChildren}
ок, поправлю

2022-03-15 06:19 UTC, merkelAlbert commented on packages/ui/src/DialogTitle/DialogTitle.tsx
> +  showCloseButton,
зачем это? если передали onclose, то показывай крестик

2022-03-15 06:22 UTC, merkelAlbert commented on packages/ui/src/Dialog/Dialog.tsx
> +      if (onClose) {
выше же проверил. лучше сверху вместо && if сделай. наглядней намного

2022-03-15 06:26 UTC, merkelAlbert commented on packages/ui/src/Dialog/Dialog.tsx
> +      if (onClose) {
if не нужен. выше проверил уже

2022-03-15 06:36 UTC, julderen commented on packages/ui/src/DialogContentText/DialogContentText.tsx
> +import { DialogContentText } from '@mui/material';
export { DialogContentText } from '@mui/material';

2022-03-15 06:36 UTC, julderen commented on packages/ui/src/theme/components/MuiDialog.ts
> +        background: 'rgba(20, 42, 67, 0.54)',
мы должны использовать цвета только из темы

2022-03-15 06:36 UTC, julderen commented on packages/ui/src/theme/components/MuiDialogActions.ts
> +        '>div': {
отступ перед селектором

2022-03-15 07:43 UTC, merkelAlbert approved these changes

2022-03-15 08:48 UTC, julderen approved these changes

2022-03-16 05:25 UTC, merged