feat(ui,Placeholder): Реализован Placeholder
kaluga-astral/frontend pull request #166
Opened 2022-03-22 11:44 UTC by vinokurov-and

2022-03-22 14:06 UTC, AndTem requested changes

2022-03-22 14:06 UTC, AndTem commented on packages/ui/src/Placeholder/styled.ts
> +export const Container = styled.div`
Везде дожен быть префик Styled

2022-03-22 14:06 UTC, AndTem commented on packages/ui/src/Placeholder/styled.ts
> +export const FooterLayout = styled.div`
Семантически это не div, а footer

2022-03-22 14:06 UTC, AndTem commented on packages/ui/src/Placeholder/types.ts
> +  subtitle?: ReactNode;
string | ReactNode

2022-03-22 14:06 UTC, AndTem commented on packages/ui/src/Placeholder/styled.ts
> +  gap: ${({ theme }) => theme.spacing(3)};
gap для флексов плохо поддерживается. Используй компонет Grid

2022-03-22 15:11 UTC, vinokurov-and commented on packages/ui/src/Placeholder/constants.ts
> +export const IMG_SRC: string =
> это используется только для storybook, поэтому пусть в файле stroies и лежит

там слишком большой base64, может его в файле stories/constants тогда?

2022-03-22 15:15 UTC, AndTem commented on packages/ui/src/Placeholder/constants.ts
> +export const IMG_SRC: string =
Давай в рамках этой задачи заодно реализуем [эту](https://astraltrack.atlassian.net/browse/UIKIT-57). Тогда ты сможешь указать прямую ссылку на github

2022-03-23 13:14 UTC, AndTem requested changes

2022-03-23 13:14 UTC, AndTem commented on packages/ui/src/Placeholder/styled.ts
> +export const InnerContainer = styled.div`
префикс styled

2022-03-23 13:14 UTC, AndTem commented on packages/ui/src/Placeholder/styled.ts
> +  height: ${({ theme }) => theme.spacing(40)};
странно измерять высоту в отступах. Используй просто цифры

2022-03-23 13:14 UTC, AndTem commented on packages/ui/src/Placeholder/styled.ts
> +  width: ${({ theme }) => theme.spacing(96)};
странно измерять ширину в отступах. Используй просто цифры

2022-03-23 13:14 UTC, AndTem commented on packages/ui/src/Placeholder/styled.ts
> +  grid-gap: ${({ theme }) => theme.spacing(2)};
gap и template задается пропсами Grid

2022-03-23 13:14 UTC, AndTem commented on packages/ui/src/Placeholder/styled.ts
> +  grid-template-columns: 1fr 1fr;
сделай через repeat. Внутри может разное количество элементов

2022-03-23 13:33 UTC, AndTem commented on packages/ui/src/Placeholder/Placeholder.stories.tsx
> +import { Certificate } from '@astral/illustrations';
из-за этого падает билд. Необходимо создать пакет illustrations

2022-03-28 07:54 UTC, AndTem requested changes

2022-03-28 07:54 UTC, AndTem commented on packages/ui/src/Placeholder/Placeholder.stories.tsx
> +import NoCertificates from '../../../illustrations/src/NoCertificates.svg';
yarn workspaces по идеи должен спокойно разрулить эту проблему (публикация для storybook не нужна)

2022-03-28 07:54 UTC, AndTem commented on packages/ui/src/Placeholder/Placeholder.stories.tsx
> +            <span style={{ color: 'red' }}>разъясняющий</span> принципы работы
Змени span на Typography. В коде не должны встречаться голые тэги

2022-03-28 07:54 UTC, AndTem commented on packages/ui/src/Placeholder/styled.ts
> +    margin: ${({ theme }) => theme.spacing(1)};
ты так добавляешь лишние отступы сверху и по краям. А тебе нужны только справа

2022-03-28 07:54 UTC, AndTem commented on packages/illustrations/src/NoCertificates.svg
> +<svg width="324" height="162" viewBox="0 0 324 162" fill="none" xmlns="http://www.w3.org/2000/svg">
сделай название файла через kebab case

2022-03-28 07:54 UTC, AndTem commented on packages/illustrations/package.json
> +    "prebuild": "rimraf ./lib && commander copyCommonFiles && commander copyIllustrations",
Команды commander copyCommonFiles && commander copyIllustrations - не prebuild, а build

2022-03-28 07:54 UTC, AndTem commented on commander/tasks/copyIllustrations.js
> +    filter: ['**/*.svg'],
тут могут быть любые форматы изображений (png, svg, jpeg, webp...)

2022-03-28 07:54 UTC, AndTem commented on commander/tasks/copyIllustrations.js
> +const copyIllustrations = () => {
переименуй в copyImages

2022-03-28 14:53 UTC, AndTem requested changes

2022-03-28 14:53 UTC, AndTem commented on packages/ui/package.json
> +    "@astral/illustrations": "^0.10.0",
пакет должен быть в devDep

2022-03-28 15:04 UTC, AndTem approved these changes

2022-03-29 07:52 UTC, perevezencev approved these changes

2022-03-29 08:53 UTC, merged