UIKIT-15 Реализовал компонент Button в соответствии с дизайн системой
kaluga-astral/frontend pull request #17
Opened 2022-01-18 12:17 UTC by StanislavDa

2022-01-19 09:35 UTC, merkelAlbert requested changes

2022-01-19 09:35 UTC, merkelAlbert commented on packages/ui/src/Button/styled.ts
> +type ButtonState = 'default' | 'active' | 'focus' | 'hover';
можно вынести в енум по аналогии с Color,  Size...

2022-01-20 06:42 UTC, AndTem commented on packages/ui/src/Button/types.ts
> +export type ButtonColor = `${ButtonColors}`;
оставь комментарий, что здесь происходит

2022-01-20 06:43 UTC, AndTem commented on packages/ui/src/Button/styled.ts
> +      getBgColor({ ...props, buttonState: ButtonStates.HOVER })};
а без important никак?

2022-01-20 06:43 UTC, AndTem commented on packages/ui/src/Button/styled.ts
> +    return `${palette.grey['100']} !important`;
а без important никак?

2022-01-20 06:46 UTC, AndTem commented on packages/ui/src/Button/styled.ts
> +  const containedColor = BACKGROUND_COLOR_VARIANTS[buttonState].contained;
не вижу особого смысла в выделение этих значений, только усложнение. Просто в нужном месте обратись к теме palette.primary[800]

2022-01-20 06:46 UTC, AndTem commented on packages/ui/src/Button/styled.ts
> +    if (customColor === ERROR) return palette.red[containedColor];
здесь нужно использовать не red, green... а error, success, warning

2022-01-20 06:48 UTC, AndTem commented on packages/ui/src/Button/styled.ts
> +  if (customVariant === LIGHT) {
почему для light не primary не обрабатываются состояния?

2022-01-20 06:57 UTC, AndTem commented on packages/ui/src/Button/styled.ts
> +  if (customVariant === LINK) return 'transparent';
у Link тоже есть состояния

2022-01-20 06:59 UTC, AndTem commented on packages/ui/src/Button/styled.ts
> +}: StyledButtonThemeProps & { buttonState: ButtonState }) => {
очень много вложенных if. Может быть было бы лучше разделить на функции эту большую? getBgLink, getBgContained ...

2022-01-20 07:19 UTC, StanislavDa commented on packages/ui/src/Button/styled.ts
> +    return `${palette.grey['100']} !important`;
неа, при дизейбле все перетирается(

2022-01-20 10:17 UTC, StanislavDa commented on packages/ui/src/Button/styled.ts
> +  if (customVariant === LINK) return 'transparent';
у Link нет состояний для background цвета

2022-01-20 10:18 UTC, AndTem commented on packages/ui/src/Button/styled.ts
> +  if (customVariant === LINK) return 'transparent';
Понял, ок

2022-01-20 10:19 UTC, AndTem commented on packages/ui/src/Button/styled.ts
> +    return `${palette.grey['100']} !important`;
Попробуй более специфичное правильно использовать. Атрибут disabled подключи и глянь на css api компонента

2022-01-20 13:36 UTC, AndTem commented on packages/ui/src/Button/styled.ts
> +  const { LIGHT, CONTAINED, LINK, TEXT } = ButtonVariants;
у нас не принято делать реструктуризацию для enum

2022-01-20 13:55 UTC, AndTem approved these changes

2022-01-21 07:15 UTC, merkelAlbert approved these changes

2022-01-21 07:18 UTC, merged