feat(ui,MaskField): реализован компонент MaskField
kaluga-astral/frontend pull request #174
Opened 2022-03-30 14:08 UTC by merkelAlbert

2022-03-30 15:24 UTC, AndTem requested changes

2022-03-30 15:24 UTC, AndTem commented on packages/ui/src/MaskField/types.ts
> +type Optional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;
заюзай просто либу utility-types

2022-03-30 15:24 UTC, AndTem commented on packages/ui/src/MaskField/MaskField.stories.tsx
> +const Template: Story = () => {
Добавь стори с unmask пропсом

2022-03-30 15:24 UTC, AndTem commented on packages/ui/src/MaskField/types.ts
> +import type { IMaskInputProps } from 'react-imask/dist/mixin';
Добавь тип - MaskFieldValue. Будет использоваться при типизации форм

2022-03-30 15:27 UTC, merkelAlbert commented on packages/ui/src/MaskField/MaskField.stories.tsx
> +const Template: Story = () => {
Так сделал же без маски

2022-03-30 15:34 UTC, AndTem commented on packages/ui/src/MaskField/MaskField.stories.tsx
> +const Template: Story = () => {
В задаче есть требование на реализацию пропса unmask, если true, то в value устанавливается значение без маски. Я просто подумал, что оно уже в самом imask. Надо реализовать

2022-04-01 09:44 UTC, merkelAlbert commented on packages/ui/package.json
> +    "react-scripts": "^5.0.0"
![image](https://user-images.githubusercontent.com/31921243/161237442-817282e4-e5a4-4e66-98ef-5631657714a8.png)

2022-04-01 11:19 UTC, AndTem commented on packages/ui/package.json
> +    "react-scripts": "^5.0.0"
А тестов то нет)

2022-04-01 11:19 UTC, AndTem commented on packages/ui/package.json
> +    "react-scripts": "^5.0.0"
понял, оставь пока

2022-04-01 13:57 UTC, AndTem commented on packages/ui/package.json
> +    "utility-types": "^3.10.0"
если я правильно понял, то utility-types сейчас нигде не используется

2022-04-01 13:57 UTC, AndTem approved these changes

2022-04-01 13:58 UTC, AndTem commented
Отлично работает маска 👍

2022-04-04 08:07 UTC, perevezencev approved these changes

2022-04-04 08:08 UTC, merged