feat(ui,DataGrid): Реализована компонент DataGrid
kaluga-astral/frontend pull request #176
Opened 2022-04-05 07:52 UTC by StanislavDa

2022-04-07 09:29 UTC, merkelAlbert commented on packages/ui/src/DataGrid/DataGrid.tsx
> +  }, [rows, selectedRows]);
keyId

2022-04-07 09:29 UTC, merkelAlbert commented on packages/ui/src/DataGrid/DataGridBody/DataGridBody.tsx
> +  }, [rows]);
initialized

2022-04-07 09:29 UTC, merkelAlbert commented on packages/ui/src/DataGrid/DataGridCell/DataGridCell.tsx
> +  }, [field, format]);
row

2022-04-07 09:29 UTC, merkelAlbert commented on packages/ui/src/DataGrid/DataGridHead/DataGridHead.tsx
> +    [uncheckedRowsCount]
rowsCount

2022-04-07 09:29 UTC, merkelAlbert commented on packages/ui/src/DataGrid/DataGridHead/DataGridHead.tsx
> +    [uncheckedRowsCount]
rowsCount

2022-04-07 09:29 UTC, merkelAlbert commented on packages/ui/src/DataGrid/types.ts
> +export interface DataGridColumns<Column extends {}> {
interface должен быть?

2022-04-07 09:29 UTC, merkelAlbert commented on packages/ui/src/DataGrid/DataGridHead/DataGridHead.tsx
> +                  active={true}
просто active же

2022-04-07 09:29 UTC, merkelAlbert commented on packages/ui/src/DataGrid/DataGridBody/types.ts
> +  selectable: boolean;
?:

2022-04-07 14:17 UTC, AndTem requested changes

2022-04-07 14:17 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridBody/DataGridBody.tsx
> +      {rows.map((row) => {
не надо писать логику прямо в jsx разметке. Либо выноси в отдельный компонент, либо в функцию (типа renderRow)

2022-04-07 14:17 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridBody/DataGridBody.tsx
> +  const [initialized, setInitialized] = useState(false);
оставь комментарий - для чего это?

2022-04-07 14:17 UTC, AndTem commented on packages/ui/src/DataGrid/types.ts
> +  onSelectRow?: (props: Array<string>) => void;
Думаю, что лучше в парамтр прокидывать всю инфу из row, а не только id

2022-04-07 14:17 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridHead/DataGridHead.tsx
> +          const newSorting = [
оставь комментарии, что здесь происходит

2022-04-07 14:17 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridHead/DataGridHead.tsx
> +        {columns.map(({ field, label, sortable, align, renderCell }) => {
не пиши логику прямо в jsx разметке. Выделяй либо в отдельный компонент, либо в функцию

2022-04-07 14:17 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridCell/DataGridCell.tsx
> +    if (onClick) onClick(row);
не думаю, что нам нужен функционал, при котором нам надо обрабатывать нажатие на ячейку, а не строку или кнопку в ячейке. Убери onClick для cell

2022-04-07 14:17 UTC, AndTem commented on packages/ui/src/DataGrid/types.ts
> +  empty?: string | number;
не увидел обработку этого параметра

2022-04-07 14:17 UTC, AndTem commented on packages/ui/src/Pagination/Pagination.tsx
> +  rowsPerPage = 10,
о каких rows идет речь? Pagination не зависит от таблицы

2022-04-07 14:17 UTC, AndTem commented on packages/ui/src/Pagination/Pagination.tsx
> +  return (
Все, кроме MuiPagination не должно присутствовать в данном компоненте. 
Pagination не зависит от Table

2022-04-14 08:36 UTC, AndTem requested changes

2022-04-14 12:17 UTC, m-av97 commented on packages/ui/src/DataGrid/DataGrid.tsx
> +    [selectedRows]
onSelectRow

2022-04-14 12:17 UTC, m-av97 commented on packages/ui/src/DataGrid/DataGridBody/DataGridBody.tsx
> +  const renderCells = (row: T, rowId: string) => {
по какому принцыпу ты выбираешь useCallback или обычная функция? то же самое с useMemo.

2022-04-14 12:52 UTC, StanislavDa commented on packages/ui/src/DataGrid/DataGridBody/DataGridBody.tsx
> +  const renderCells = (row: T, rowId: string) => {
В основном, оборачиваю в useCallback/useMemo, если происходит какой-нибудь перебор массива для его последующего рендера или какая-либо обработка данных. тут в useCallback обернуть забыл

2022-04-14 12:55 UTC, AndTem requested changes

2022-04-14 13:13 UTC, StanislavDa commented on packages/ui/src/DataGrid/DataGridPagination/usePagination.tsx
> +  return (
Значит не так понял. Уточню, для DataGrid нужна кастомизированная пагинация - с отображением текущего диапазона записей `10 — 20 из 20 записей` + сами кнопки для перехода между страницами. Для этого я сделал обертку DataGridPagination, где рассчитывается диапазон + сама пагинация. Обертка прокидывалась в пропсы при необходимости. Какой смысл от хука тогда?)

2022-04-14 13:25 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridHead/DataGridHead.tsx
> +  const renderedColumns = useMemo(() => {
В отдельный компонент лучше вынести

2022-04-15 12:10 UTC, AndTem requested changes

2022-04-15 12:10 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridBody/DataGridBody.tsx
> +  // флаг для индикации первой отрисовки компонента
оставь комментарий - для чего этот флаг

2022-04-15 12:10 UTC, AndTem commented on packages/ui/src/DataGrid/DataGrid.tsx
> +  pagination,
замени pagination -> Footer

2022-04-15 12:10 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridPagination/DataGridPagination.tsx
> +export const DataGridPagination = ({
вынеси компонент на уровень выше

2022-04-18 10:47 UTC, AndTem requested changes

2022-04-18 10:47 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridHead/DataGridHeadColumns.tsx
> +    return columns.map(({ field, label, sortable, align, renderCell }) => {
странная конструкция компонента.
Сделай компонент DataGridHeadColumn, который будет отображать одну колонку.
А map можно спокойно поместить в основной компонент.

2022-04-18 10:47 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridHead/DataGridHeadColumns.tsx
> +export function DataGridHeadColumns<T>({
Также для каждого компонента должна быть своя директория

2022-04-18 12:18 UTC, AndTem requested changes

2022-04-18 12:18 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridHead/DataGridHead.tsx
> +      const sortParams = sorting.find(({ fieldId }) => field === fieldId);
все эти переменные очень хорошо будут чувствовать себя внутри DataGridHeadColumn

2022-04-18 12:18 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridBody/DataGridBody.tsx
> +  const [initialized, setInitialized] = useState(false);
теперь этот флаг не нужен потому, что если строки - пустой массив, то надо отобразить minDisplayRows

2022-04-19 13:00 UTC, AndTem commented on packages/ui/src/DataGrid/types.ts
> +  minDisplayRows?: number;
оставь коммент для используется этот пропс

2022-04-19 13:05 UTC, StanislavDa commented on packages/ui/src/DataGrid/types.ts
> +  minDisplayRows?: number;
оставил

2022-04-20 08:31 UTC, AndTem approved these changes

2022-04-20 08:35 UTC, m-av97 approved these changes

2022-04-20 08:35 UTC, merged