feat(ui,SideDialog): Реализован компонент SideDialog
kaluga-astral/frontend pull request #179
Opened 2022-04-07 09:13 UTC by olewka40

2022-04-07 09:34 UTC, perevezencev approved these changes

2022-04-07 13:51 UTC, AndTem requested changes

2022-04-07 13:51 UTC, AndTem commented on packages/ui/src/SideDialog/types.ts
> +  onClose?: (
а разве этого параметра нет в MuiDrawerProps?

2022-04-08 07:11 UTC, olewka40 commented on packages/ui/src/SideDialog/types.ts
> +  onClose?: (
не нашел

2022-04-08 07:14 UTC, AndTem commented on packages/ui/src/SideDialog/types.ts
> +  onClose?: (
а как ты тогда без реализации метода просто прокидываешь в MuiDrawer?

2022-04-08 07:16 UTC, olewka40 commented on packages/ui/src/SideDialog/types.ts
> +  onClose?: (
Ты про onClose?

2022-04-08 07:22 UTC, AndTem commented on packages/ui/src/SideDialog/types.ts
> +  onClose?: (
да

2022-04-11 09:15 UTC, perevezencev requested changes

2022-04-11 09:15 UTC, perevezencev commented on packages/ui/src/SideDialog/types.ts
> +  title?: string;
Как модалка будет выглядеть без title?

2022-04-11 09:15 UTC, perevezencev commented on packages/ui/src/SideDialog/types.ts
> +  onClose?: () => void;
Думаю это необходимо делать обязательным пропсом.

@AndTem что думаешь?

2022-04-11 09:17 UTC, AndTem commented on packages/ui/src/SideDialog/types.ts
> +  onClose?: () => void;
+
Также в типе MuiDrawerProps уже есть onClose - зачем его здесь переопределять?
https://mui.com/material-ui/api/drawer/
<img width="815" alt="image" src="https://user-images.githubusercontent.com/23665108/162706384-46c15791-1592-45db-86cd-51ba82fa9b60.png">

2022-04-11 09:19 UTC, olewka40 commented on packages/ui/src/SideDialog/types.ts
> +  onClose?: () => void;
Иначе TS  подсвечивает ошибку

2022-04-11 09:20 UTC, AndTem commented on packages/ui/src/SideDialog/types.ts
> +  onClose?: () => void;
Какую?

2022-04-11 09:22 UTC, olewka40 commented on packages/ui/src/SideDialog/types.ts
> +  onClose?: () => void;
![image](https://user-images.githubusercontent.com/35649223/162708520-59f128fc-07a0-4641-b05e-b1a72c0c70b2.png)

2022-04-11 09:24 UTC, olewka40 commented on packages/ui/src/SideDialog/types.ts
> +  onClose?: () => void;
а DialogTitle не только тут используется уже

2022-04-11 09:26 UTC, AndTem commented on packages/ui/src/SideDialog/types.ts
> +  onClose?: () => void;
Для onClose DialogTitle сделай отдельную функцию обертку, которая примирит форматы

2022-04-11 12:52 UTC, AndTem commented on packages/ui/src/SideDialog/SideDialog.stories.tsx
> +        <DialogContent>
Сделай для SideDialog свои отдельные компоненты: SideDialogContent, SideDialogContentText...

2022-04-11 12:54 UTC, AndTem commented on packages/ui/src/DialogTitle/types.ts
> +  onClose?: ModalProps['onClose'];
здесь интерфейс менятся не должен

2022-04-14 08:53 UTC, AndTem requested changes

2022-04-14 08:53 UTC, AndTem commented on packages/ui/src/SideDialogActions/SideDialogActions.tsx
> +}: DialogActionsProps) => {
У SideDialogActions должны быть свои пропсы, которые можно использовать.
Сделай SideDialogActionsProps

2022-04-14 08:53 UTC, AndTem commented on packages/ui/src/DialogTitle/DialogTitle.tsx
> +    (e) => onClose && onClose(e, 'escapeKeyDown'),
оставь комментарий почему используешь escapeKeyDown

2022-04-14 08:53 UTC, AndTem commented on packages/ui/src/SideDialogTitle/SideDialogTitle.tsx
> +export const SideDialogTitle = ({
А этот компонент чем-то отличается от DialogTitle? может просто можно реэкспортнуть с другим названием?

2022-04-14 09:54 UTC, olewka40 commented on packages/ui/src/SideDialogTitle/SideDialogTitle.tsx
> +export const SideDialogTitle = ({
там вообще ни один компонент не отличается)

2022-04-14 09:56 UTC, olewka40 commented on packages/ui/src/DialogTitle/DialogTitle.tsx
> +    (e) => onClose && onClose(e, 'escapeKeyDown'),
тут или в коде? 
Если тут, то в документашке написано что это опциональный тип, и можно стрингу любую туда закидывать, а по факту либо escapeKeyDown либо BackDropClick

2022-04-14 10:12 UTC, AndTem commented on packages/ui/src/DialogTitle/DialogTitle.tsx
> +    (e) => onClose && onClose(e, 'escapeKeyDown'),
В коде

2022-04-14 10:13 UTC, AndTem commented on packages/ui/src/SideDialogTitle/SideDialogTitle.tsx
> +export const SideDialogTitle = ({
Значит просто сделай реэкспорт с новым именем

2022-04-15 10:36 UTC, AndTem approved these changes

2022-04-18 06:39 UTC, perevezencev approved these changes

2022-04-18 10:41 UTC, merged