feat(ui,List): Реализован функционал сворачивания List
kaluga-astral/frontend pull request #181
Opened 2022-04-11 08:09 UTC by Nikita-Smirnov

2022-04-11 11:15 UTC, merkelAlbert commented on packages/ui/src/ListProvider/types.ts
> +  isOpen: ListContextType;
как то странно. isOpen = {open:boolean}

```<ListContext.Provider value={{ open: collapsed }}>```. зачем подменять всем известное апи?

ну или если хочется Provider:
```export const ListProvider = ListContext.Provider``` 
все типы красиво подтянуться

2022-04-11 11:36 UTC, Nikita-Smirnov commented on packages/ui/src/ListProvider/types.ts
> +  isOpen: ListContextType;
Поправил

2022-04-11 11:58 UTC, merkelAlbert approved these changes

2022-04-11 12:59 UTC, AndTem commented
Отсутсвует анимация закрытия

2022-04-12 10:25 UTC, Nikita-Smirnov commented
Добавил анимацию закрытия

2022-04-14 08:45 UTC, AndTem requested changes

2022-04-14 08:45 UTC, AndTem commented on packages/ui/src/List/List.tsx
> +  collapsedSize,
этот пропс должен быть определен внутри компонента и не переопределяться

2022-04-14 08:45 UTC, AndTem commented on packages/ui/src/ListItemText/ListItemText.tsx
> +  const listContext = useContext(ListContext);
сделай деструктуризацию

2022-04-15 07:09 UTC, Nikita-Smirnov commented on packages/ui/src/ListItemText/ListItemText.tsx
> +  const listContext = useContext(ListContext);
Поправил

2022-04-15 07:57 UTC, AndTem requested changes

2022-04-15 07:57 UTC, AndTem commented on packages/ui/src/List/List.tsx
> +  const open = collapsed === undefined || collapsed;
Boolean(colapsed)

2022-04-15 07:57 UTC, AndTem commented on packages/ui/src/List/List.tsx
> +  collapsedSize,
что. с этим?

2022-04-15 09:03 UTC, Nikita-Smirnov commented on packages/ui/src/List/List.tsx
> +  collapsedSize,
поправил collapsedSize

2022-04-15 09:05 UTC, AndTem approved these changes

2022-04-15 09:05 UTC, merged