feat(ui, DashboardLayout): Исправляет компоненты DashboardLayout, в частности Header, в соотвествии с дизайном
kaluga-astral/frontend pull request #195
Opened 2022-04-20 09:13 UTC by perevezencev

2022-04-21 14:55 UTC, AndTem requested changes

2022-04-21 14:55 UTC, AndTem commented on packages/ui/src/DashboardLayout/Header/Profile/Profile.tsx
> +export const Profile = forwardRef<HTMLDivElement, ProfileProps>(
не думаю, что это должно быть захардкожено в layout. profile может быть разный, с разным наполнением
Думаю, что в Layout можно сделать пропс - Profile и туда уже прокидывать, что хочешь.
А этот компонент абстрагировать

2022-04-21 14:55 UTC, AndTem commented on packages/ui/src/DashboardLayout/Header/Header.tsx
> +  const { nav, profile } = props;
виджет нужен не во всех продуктах, поэтому здесь и была такая логика

2022-04-21 14:55 UTC, AndTem commented on packages/ui/src/DashboardLayout/styled.tsx
> +    return `\n
через columns и rows без привязки к неймингу мне кажется был бы попроще

2022-04-21 14:55 UTC, AndTem commented on packages/ui/src/DashboardLayout/Header/Nav/Product/Product.tsx
> +      <Root ref={ref} variant="text">
логотип должен быть ссылкой + привязан к компоненту роутинга. Именно по этой причине так выглядела предыдущая реализация

2022-04-22 05:59 UTC, perevezencev commented on packages/ui/src/DashboardLayout/Header/Profile/Profile.tsx
> +export const Profile = forwardRef<HTMLDivElement, ProfileProps>(
Под "абстрагировать" имеешь в виду вынести на уровень `/packages/ui/Profile`?

2022-04-22 06:28 UTC, perevezencev commented on packages/ui/src/DashboardLayout/Header/Profile/Profile.tsx
> +export const Profile = forwardRef<HTMLDivElement, ProfileProps>(
Тут нужно определиться какой путь мы выбираем 
1) это все передавать через пропсы (как сейчас реализовано) 
2) более классический через children "собирать" компонент

2022-05-18 08:04 UTC, closed without merging