bug(theme): Добавлено абсолютное позиционирование для FormHelperText
kaluga-astral/frontend pull request #204
Opened 2022-04-21 15:30 UTC by vinokurov-and

2022-04-22 11:11 UTC, perevezencev commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        position: 'absolute',
А почему не через visibility тогда и падинг не нужен будет

2022-04-22 12:05 UTC, vinokurov-and commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        position: 'absolute',
> 

  и в helperText по умолчанию строку " "?

2022-04-22 12:05 UTC, vinokurov-and commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        position: 'absolute',
> А почему не через visibility тогда и падинг не нужен будет

и в helperText по умолчанию " "?

2022-04-22 13:15 UTC, AndTem requested changes

2022-04-22 13:15 UTC, AndTem commented on packages/ui/src/FormHelperText/styled.tsx
> +  font-size: 16px;
размеры шрифтов должны браться из темы

2022-04-22 13:15 UTC, AndTem commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        bottom: 0,
сделай так, чтобы при переполнении текст не на инпут лез, а вниз расширялся

2022-04-22 13:15 UTC, AndTem commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        position: 'absolute',
@perevezencev не понял задумки

2022-04-22 13:19 UTC, AndTem commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        position: 'absolute',
Тут скорее всего две строки будет, поэтому такое решение не прокатит

2022-04-22 13:21 UTC, perevezencev commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        position: 'absolute',
А какая разница, хоть 5 строк, но только они сразу должны быть в верстке.

2022-04-22 13:23 UTC, AndTem commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        position: 'absolute',
Но ведь тогда необходимо этот visibility как то устанавливать для текста (а для этого придется доп логику писать в проекте).
Final form выкидывает ошибки валидаци сразу при инициализации, а hook form например только после submit или onBlur (для hook form твой вариант будет работать без лишних действий)

2022-04-22 13:33 UTC, AndTem commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        position: 'absolute',
Понял.
Только visibility тут лишнее (это уже на уровне продукта надо решать показывать сообщение или нет).
@vinokurov-and можно просто установить высоту фиксированную для FormHelperText, а для MuiFormControl убрать лишний padding

2022-04-25 10:37 UTC, vinokurov-and commented on packages/ui/src/FormHelperText/styled.tsx
> +  font-size: 16px;
> размеры шрифтов должны браться из темы

pxToRem могу заюзать ведь?

дело в том, что под 16px подходит только h5, но h5 по смыслу как-то сюда не подходит

2022-04-25 11:22 UTC, AndTem commented on packages/ui/src/FormHelperText/styled.tsx
> +  font-size: 16px;
ничего не мешает тебе в стилях обращаться к typography.h5.fontSize. семантика не нарушается. Но тебе это здесь вообще точно нужно?

2022-04-25 11:25 UTC, vinokurov-and commented on packages/ui/src/FormHelperText/styled.tsx
> +  font-size: 16px;
> ничего не мешает тебе в стилях обращаться к typography.h5.fontSize. семантика не нарушается. Но тебе это здесь вообще точно нужно?

да, у иконки размер 24x24, а нужно 16px

в FormHelperText размер текста установлен в rem, соответственно зависимость от font-size html. Поэтому думаю и иконка должна быть в единицах rem, т.к. у текста и иконки прямая зависимость в размерах

2022-04-25 11:27 UTC, AndTem commented on packages/ui/src/FormHelperText/styled.tsx
> +  font-size: 16px;
а 1 em не прокатит?

2022-04-25 11:31 UTC, vinokurov-and commented on packages/ui/src/FormHelperText/styled.tsx
> +  font-size: 16px;
> а 1 em не прокатит?

если только 1.33....em

у картинки 16px (1.3333em) у текста 12px = 1em

2022-04-25 11:33 UTC, AndTem commented on packages/ui/src/FormHelperText/styled.tsx
> +  font-size: 16px;
понял, заюзай typography.h5.fontSize

2022-04-25 11:49 UTC, AndTem requested changes

2022-04-25 11:49 UTC, AndTem commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        minHeight: theme.typography.pxToRem(16),
почему в rem высота эта? Должна либо быть фиксированной, либо привязана к fontSize и lineHeight.

2022-04-25 11:49 UTC, AndTem commented on packages/ui/src/TextField/TextField.tsx
> +      return <Fragment />;
зачем это?

2022-04-25 11:51 UTC, vinokurov-and commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        minHeight: theme.typography.pxToRem(16),
> почему в rem высота эта? Должна либо быть фиксированной, либо привязана к fontSize и lineHeight.

llineHeight ниже в 16

2022-04-25 11:51 UTC, AndTem commented on packages/ui/src/TextField/TextField.stories.tsx
> +      <Stack gap={2} direction="column">
добавь кейс, когда текст ошибки появляется после onBlur

2022-04-25 11:52 UTC, vinokurov-and commented on packages/ui/src/TextField/TextField.tsx
> +      return <Fragment />;
Если в helpertText приходит undefined, то элемент helperText не рендерится. Соответственно не будет строки в 20px под текстовым полем

2022-04-25 11:53 UTC, vinokurov-and commented on packages/ui/src/TextField/TextField.tsx
> +      return <Fragment />;
> зачем это?

Если в helpertText приходит undefined, то элемент helperText не рендерится. Соответственно не будет строки в 20px под текстовым полем

2022-04-25 12:04 UTC, AndTem commented on packages/ui/src/TextField/TextField.tsx
> +      return <Fragment />;
Понял, ок

2022-04-25 12:05 UTC, vinokurov-and commented on packages/ui/src/TextField/TextField.tsx
> +      return <Fragment />;
> > зачем это?
> 
> Если в helpertText приходит undefined, то элемент helperText не рендерится. Соответственно не будет строки в 20px под текстовым полем, которое мы планируем отображать всегда. Можно сделать return < FormHelperText / >, но там есть кейс если нет children то return null; да и есть ли смысл возвращать < FormHelperText / > ради того чтобы вернуть пустой элемент?

lineHeight: theme.typography.pxToRem(16),

отсюда и ремы для height;
у нас подписи в ремах и зависят от font-size html, значит и высота должна быть реализована тем же способом

2022-04-25 12:06 UTC, vinokurov-and commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        minHeight: theme.typography.pxToRem(16),
> > почему в rem высота эта? Должна либо быть фиксированной, либо привязана к fontSize и lineHeight.
> 
> llineHeight ниже в 16

lineHeight: theme.typography.pxToRem(16),

отсюда и ремы для height;
у нас подписи в ремах и зависят от font-size html, значит и высота должна быть реализована тем же способом

2022-04-25 12:09 UTC, AndTem commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        minHeight: theme.typography.pxToRem(16),
А высота этого блока зависит от количества строк в helperText и его fontSize и lieHeight. Значит и здесь эта зависимость должна прослеживаться

2022-04-25 12:11 UTC, vinokurov-and commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        minHeight: theme.typography.pxToRem(16),
> А высота этого блока зависит от количества строк в helperText и его fontSize и lieHeight. Значит и здесь эта зависимость должна прослеживаться

но ведь пока не было постановки задачи в несколько строк. Делаем для одной строки. Сейчас если будет две строки то интерфейс просто сдвинется т.к. min-height

2022-04-25 12:12 UTC, vinokurov-and commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        minHeight: theme.typography.pxToRem(16),
> А высота этого блока зависит от количества строк в helperText и его fontSize и lieHeight. Значит и здесь эта зависимость должна прослеживаться

и как определить количество строк в helperText?)

2022-04-25 12:15 UTC, AndTem commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        minHeight: theme.typography.pxToRem(16),
Оставь сейчас просто typography.subtitle.fontSize (varinat текста установленного для helperText)

2022-04-25 12:40 UTC, vinokurov-and commented on packages/ui/src/theme/components/MuiFormHelperText.ts
> +        minHeight: theme.typography.pxToRem(16),
> Оставь сейчас просто typography.subtitle.fontSize (varinat текста установленного для helperText)

сделал под typography.small

2022-04-27 07:38 UTC, AndTem approved these changes

2022-04-27 07:44 UTC, perevezencev approved these changes

2022-04-27 07:47 UTC, merged