feat(ui, Product): UIKIT-195 | Реализует компонент Product
kaluga-astral/frontend pull request #211
Opened 2022-04-26 10:46 UTC by perevezencev

2022-04-26 11:06 UTC, AndTem requested changes

2022-04-26 11:06 UTC, AndTem commented on packages/ui/src/Product/Product.stories.tsx
> +          logo={() => (
лого лучше делать ссылкой через img. Чтобы его скачать можно было и для seo полезно (в теории)

2022-04-26 11:06 UTC, AndTem commented on packages/ui/src/Product/Product.stories.tsx
> +        <Product
Добавь кейс с Link

2022-04-26 11:06 UTC, AndTem commented on packages/ui/src/Product/index.ts
> +export * from './Product';
забыл сделать экспорт в главном индексном файле

2022-04-27 07:48 UTC, perevezencev commented on packages/ui/src/Product/Product.stories.tsx
> +        <Product
С роутером не стал делать, но смысл, надеюсь, понятен

2022-04-27 07:50 UTC, AndTem commented on packages/ui/src/Product/Product.stories.tsx
> +          logo={() => (
добавишь в story это? я вот не догодался)

2022-04-27 07:51 UTC, perevezencev commented on packages/ui/src/Product/Product.stories.tsx
> +          logo={() => (
окай

2022-04-27 11:24 UTC, m-av97 approved these changes

2022-04-27 11:46 UTC, AndTem approved these changes

2022-04-27 11:46 UTC, merged