feat(ui,Profile): UIKIT-206 | Реализует компонент Profile
kaluga-astral/frontend pull request #214
Opened 2022-04-27 12:52 UTC by perevezencev

2022-04-27 13:06 UTC, AndTem requested changes

2022-04-27 13:06 UTC, AndTem commented on packages/ui/src/Profile/types.tsx
> +  displayName: string;
добавь [js doc описание](https://astraltrack.atlassian.net/browse/UIKIT-183)

2022-04-27 13:06 UTC, AndTem commented on packages/ui/src/Profile/styled.tsx
> +export const DisplayName = styled.div`
не семантически, должен быть span

2022-04-27 13:06 UTC, AndTem commented on packages/ui/src/Profile/styled.tsx
> +export const DisplayName = styled.div`
Просто заюзай typography

2022-04-27 18:55 UTC, perevezencev commented on packages/ui/src/Profile/styled.tsx
> +export const DisplayName = styled.div`
В typography нет варианта с `font-size: 14px; line-height: 14px;` + этот элемент должен быть блочным (могу через `display: block;` сделать).

2022-04-27 19:20 UTC, m-av97 commented on packages/ui/src/Profile/styled.tsx
> +export const Root = styled(Button)`
А у тих компонентов разве не должно быть префикса Profile? ProfileRoot, ProfileAnnotation...

2022-04-27 19:49 UTC, perevezencev commented on packages/ui/src/Profile/styled.tsx
> +export const Root = styled(Button)`
В соотвествии с сегодняшними договоренностями, наверное, должны

2022-04-28 06:55 UTC, perevezencev commented on packages/ui/src/Profile/types.tsx
> +  displayName: string;
ok

2022-04-28 07:19 UTC, m-av97 approved these changes

2022-04-29 05:50 UTC, AndTem commented on packages/ui/src/Profile/styled.tsx
> +export const DisplayName = styled.div`
Да, давай так

2022-04-29 10:08 UTC, AndTem approved these changes

2022-04-29 10:08 UTC, merged