feat(ui,ActionCell): Добавлен коммент ActionCell
kaluga-astral/frontend pull request #215
Opened 2022-04-28 10:19 UTC by StanislavDa

2022-04-29 04:01 UTC, AndreyZlobin approved these changes

2022-04-29 04:04 UTC, AndreyZlobin commented
Думаю надо уточнить у дизайнера
![image](https://user-images.githubusercontent.com/51029733/165883717-eaa52668-8338-434b-ab4e-10c780578c23.png)

2022-05-25 13:56 UTC, StanislavDa commented on packages/ui/src/hooks/useMenu.ts
> +  useEffect(() => {
Без этого некорректно работает тултип, когда в него оборачивается DropdownButton - при наведении на кнопку тултип не появляется и вылезает только при клике на кнопку.

2022-05-25 14:13 UTC, AndTem requested changes

2022-05-25 14:13 UTC, AndTem commented on packages/ui/src/ActionCell/ActionCell.tsx
> +    return main.map(({ nested, icon, name, ...rest }) => {
По идеи, если уберешь rest, то ts будет должен понять, что это MultipleAction и приведение не потребутеся

2022-05-25 14:13 UTC, AndTem commented on packages/ui/src/ActionCell/ActionCell.tsx
> +    return main.map(({ nested, icon, name, ...rest }) => {
оставб map в рендере, а здесь оставь просто рендер action

2022-05-25 14:13 UTC, AndTem commented on packages/ui/src/ActionCell/ActionCell.tsx
> +                <MenuItem key={nestedActionName}>{nestedActionName}</MenuItem>
а здесь onClick разве не должно быть?

2022-05-25 14:13 UTC, AndTem commented on packages/ui/src/ActionCell/ActionCell.stories.tsx
> +    { icon: <EditOutlineMd />, name: 'Редактировать', onClick: () => {} },
Иконка для secondary не используется, можно убрать из api

2022-05-25 14:13 UTC, AndTem commented on packages/ui/src/ActionCell/ActionCell.tsx
> +  const renderAdditionalActions = useMemo(() => {
пусть будет тоже renderSecondary

2022-05-25 14:13 UTC, AndTem commented on packages/ui/src/ActionCell/ActionCell.tsx
> +  const renderMenuActions = useMemo(() => {
нет необходимости выносить это в отдельную функцию. выносим в отдельную только если там логика какая-то, помимо map

2022-05-25 14:15 UTC, AndTem commented
Добавь в storybook DataGrid тоже ActionCell

2022-05-25 14:23 UTC, AndTem commented on packages/ui/src/ActionCell/ActionCell.tsx
> +    return main.map(({ nested, icon, name, ...rest }) => {
https://www.typescriptlang.org/play?#code/C4TwDgpgBAggxsAlgewHZQLxQN6oIYC2EAXFAM7ABOiqA5gNxSoQUQAmpAZngDZkQBfegChQkKAFkArjyTwkaTDnxFSFanUbNWHKFSkRGeBClRk1VGrQDaAXSHDR4aDEqU8IeabJLX7kAA8XooAPpIyciZoAHwiwgAU1riEJFAA5GkANEwswOxcvPwCtlB4Pn4ewWYAlAB0BHhg8fHGCqjVmNE4wlBQiJxQLVGotdp5bB3YPb1QlBDAUpToraa1K2hk9Y3NZB0YXbvTAo69cwtLpcOjKSIC1UA

2022-05-25 14:26 UTC, StanislavDa commented on packages/ui/src/ActionCell/ActionCell.tsx
> +    return main.map(({ nested, icon, name, ...rest }) => {
не совсем понял, что имеется в виду

2022-05-26 06:58 UTC, merged