feat(ui,Notification): UIKIT-196 | Реализация системы нотификации
kaluga-astral/frontend pull request #216
Opened 2022-04-29 04:35 UTC by AndreyZlobin

2022-04-29 07:59 UTC, AndTem requested changes

2022-04-29 08:05 UTC, AndreyZlobin commented on packages/ui/src/Notification/components/NotificationTemplate/styled.ts
> +  & > svg {
Не открашиваются, я попробовал, а те цвета которые в variant не подходят

2022-04-29 09:47 UTC, StanislavDa commented on packages/ui/src/Notification/components/NotificationTemplate/styled.ts
> +  & > svg {
иконки не покрасились

в фигме
![image](https://user-images.githubusercontent.com/93906455/165922215-33977219-a576-47d8-8d67-d4fb189ce2a1.png)


в пре
![image](https://user-images.githubusercontent.com/93906455/165921745-a0e3f776-afa9-4fad-a5fe-21c60e9f06f2.png)

2022-04-29 10:13 UTC, StanislavDa approved these changes

2022-04-29 14:50 UTC, AndTem requested changes

2022-04-29 14:50 UTC, AndTem commented on packages/ui/src/Notification/components/NotificationTemplate/styled.ts
> +  & > svg {
здесь тоже через color окрашивается иконка

2022-04-29 15:36 UTC, AndreyZlobin commented on packages/ui/src/Notification/index.ts
> +export * from './components/NotificationContainer';
fix

2022-04-29 15:36 UTC, AndreyZlobin commented on packages/ui/src/Notification/types.ts
> +  title: string;
Сделал

2022-04-29 15:36 UTC, AndreyZlobin commented on packages/ui/src/Notification/components/NotificationTemplate/styled.ts
> +  & > svg {
Убрал, забыл убрать

2022-04-29 15:40 UTC, AndTem commented on packages/ui/src/Notification/Notification.tsx
> +export * from './components/NotificationContainer';
я имел в виду, что директорию components не создаем. Эуспорт через корнево индейс делаем

2022-04-29 15:41 UTC, AndTem commented on packages/ui/src/Notification/types.ts
> +   * @type {boolean}
достаточно добавить просто описание, типы излишние - тут ведь ts

2022-04-29 15:58 UTC, AndreyZlobin commented on packages/ui/src/Notification/types.ts
> +   * @type {boolean}
> достаточно добавить просто описание, типы излишние - тут ведь ts

Fix

2022-04-29 15:58 UTC, AndreyZlobin commented on packages/ui/src/Notification/Notification.tsx
> +export * from './components/NotificationContainer';
> я имел в виду, что директорию components не создаем. Эуспорт через корнево индейс делаем

Fix

2022-04-29 16:38 UTC, AndTem requested changes

2022-04-29 16:38 UTC, AndTem commented on packages/ui/src/NotificationTemplate/NotificationTemplate.tsx
> +export const NotificationTemplate: FC<NotificationTemplateProps> = ({
NotificationTemplate насколько я понял не живет вне Notification.
Вложи его вместе с NotificationContainer в Notification:
Notification/
  NotificationContainer
  NotificationTemplate
  index.ts

2022-04-29 16:38 UTC, AndTem commented on packages/ui/src/Notification/Notification.tsx
> +export const notify: Record<Variant, Notify> = {
Забыл все это заэкспортить из рутового index.ts

2022-05-08 13:51 UTC, m-av97 commented on packages/ui/src/Notification/constants/index.ts
> +export * from './notififationVariant';
Notififation

2022-05-08 13:51 UTC, m-av97 commented on packages/ui/src/Notification/Notification.tsx
> +interface NotificationOption extends Omit<NotificationProps, 'title'> {}
NotificationOptions

2022-05-08 14:23 UTC, AndreyZlobin commented on packages/ui/src/Notification/constants/index.ts
> +export * from './notififationVariant';
fix

2022-05-08 14:23 UTC, AndreyZlobin commented on packages/ui/src/Notification/Notification.tsx
> +interface NotificationOption extends Omit<NotificationProps, 'title'> {}
fix

2022-05-11 06:10 UTC, AndTem requested changes

2022-05-11 06:10 UTC, AndTem commented on packages/ui/src/Notification/index.ts
> +export * from './Notification';
Забыл сделать экспорт из корневого index

2022-05-11 06:25 UTC, AndTem approved these changes

2022-05-11 06:31 UTC, StanislavDa approved these changes

2022-05-11 06:32 UTC, merged