refactor(ui,DatePicker): переход на react-datepicker
kaluga-astral/frontend pull request #222
Opened 2022-05-05 09:58 UTC by lordniken

- в реализации присутствует костыль для интеграции MaskField (либо его оставляем, либо меняем api MaskField и в value кладем объект с target.value)
- helperText изменил высоту TextField из-за чего отступ календаря от филда стал больше.. можно его невелировать отрицательным значением margin, но проблема сохранится, если в helperText будет несколько строк
- комиты со стилизацией не прошли линтер (классы пикера не соответсвуют паттерну "^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$")

2022-05-05 10:03 UTC, AndTem commented
1. Если вводить значения руками в инпут, то после onblur происходит откат значения
2. Инпут не позволяет вводить в месяце первый символ >= 1. Данное поведение запутывает, обычно позволяют ввести любые цифры, а потом это валидируют. Здесь надо сделать также

2022-05-05 10:09 UTC, lordniken commented
> 1. Если вводить значения руками в инпут, то после onblur происходит откат значения

В истории указаны min/max date (+-90 дней от текущей даты), скорее всего ты не попал в интервал

2022-05-05 10:26 UTC, AndTem commented
> 

Эти ограничения должны работать при выборе даты в календаре, но при вводе значения в инпут (для инпута только валидация)

2022-05-05 10:27 UTC, AndTem commented
Сделай сразу правки по [style guide](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3518038027/Style+guide)

2022-05-23 10:10 UTC, perevezencev approved these changes

2022-05-23 10:23 UTC, AndTem requested changes

2022-05-23 10:23 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.stories.tsx
> +  useEffect(() => {
Лишнее

2022-05-23 10:23 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.tsx
> +import { IMask } from 'react-imask';
Тут не должно быть прямой зависимости от Imask. Также как и компонент, типы MaskField должно испортиться из нашего кита

2022-05-23 10:23 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.tsx
> +  const { placeholder = undefined, ...restInputProps } = inputProps;
Для чего делать дефолтное значение undefined?

2022-05-23 10:23 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.tsx
> +    const date = parse(e?.target.value, 'dd.MM.yyyy', new Date());
Строка с форматом должны быть вынесена в пропс и проставлена как дефолтный. В сам компонент этот же пропс и должен прикидываться

2022-05-23 10:23 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.tsx
> +            inputRef={(el: HTMLInputElement | null) => {
Оставь комментарий что здесь происходит

2022-05-23 10:23 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.tsx
> +  value: Date | null;
Почему не value?: Date?

2022-05-23 10:23 UTC, AndTem commented on packages/ui/src/DatePicker/DatePickerDay/DatePickerDay.tsx
> +  date?: Date | undefined;
| undefined лишнее

2022-05-23 10:23 UTC, AndTem commented on packages/ui/src/DatePicker/DatePickerHeader/DatePickerHeader.tsx
> +    () => format(date, 'LLLL yyy', { locale: ru }),
Для пикета должен быть Context с провайдером, из которого берётся locale

2022-05-23 10:23 UTC, AndTem commented on packages/ui/src/MaskField/types.ts
> +export type MaskFieldProps = Omit<
По style guide пропсы лежат в файле с компонентом

2022-05-23 10:23 UTC, AndTem commented on packages/ui/src/MaskField/types.ts
> +  autofix?: boolean | 'pad';
Добавь js doc описание для пропсов

2022-05-23 13:56 UTC, AndTem requested changes

2022-05-23 13:56 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.tsx
> +import { IMask, MaskField, MaskFieldProps } from '../MaskField';
Imask - указание на название библиотеки, с помощью которой реализован MaskField. Название не должно указывать на особенности реализации

2022-05-24 06:54 UTC, AndTem approved these changes

2022-05-24 07:13 UTC, merged