feat: Реализует компонент Header
kaluga-astral/frontend pull request #226
Opened 2022-05-11 17:46 UTC by perevezencev

2022-05-12 06:01 UTC, AndTem commented
Измени название ПР: feat(ui,DashboardLayout)

2022-05-12 06:11 UTC, AndTem requested changes

2022-05-12 06:11 UTC, AndTem commented on packages/ui/src/DashboardLayout/styled.tsx
> +export const Root = styled.div`
По style guide надо добавить префикс в название

2022-05-12 06:11 UTC, AndTem commented on packages/ui/src/DashboardLayout/DashboardLayout.stories.tsx
> +    nav: {
Мне кажется, что вложенность в виде nav лишняя

2022-05-12 06:11 UTC, AndTem commented on packages/ui/src/DashboardLayout/Header/HeaderNav/HeaderNav.tsx
> +        {Menu && <Menu />}
Это для чего?

2022-05-12 06:11 UTC, AndTem commented on packages/ui/src/DashboardLayout/Header/HeaderNav/HeaderNav.tsx
> +        {Switcher && <Switcher />}
Немного не подходящее название. Может ProductsWidget или ProductSwitcher?

2022-05-12 09:24 UTC, perevezencev commented on packages/ui/src/DashboardLayout/Header/HeaderNav/HeaderNav.tsx
> +        {Menu && <Menu />}
<img width="540" alt="Снимок экрана 2022-05-12 в 12 24 15" src="https://user-images.githubusercontent.com/5954104/168038345-a23bb589-2f49-4a2d-b601-c3f7f3d78035.png">
№2

2022-05-12 09:28 UTC, AndTem commented on packages/ui/src/DashboardLayout/Header/HeaderNav/HeaderNav.tsx
> +        {Menu && <Menu />}
А почему в типах связь с Menu? У нас разве есть горизонтальное Menu?

2022-05-12 09:36 UTC, AndTem commented on packages/ui/src/DashboardLayout/Header/HeaderNav/HeaderNav.tsx
> +        {Menu && <Menu />}
Мне кажется ты перепутал Menu и List

2022-05-12 09:38 UTC, perevezencev commented on packages/ui/src/DashboardLayout/Header/HeaderNav/HeaderNav.tsx
> +        {Menu && <Menu />}
Ну вообще я предполагаю что сюда будет передаваться компонент `<MenuList orientation="horizontal"`

2022-05-12 09:55 UTC, AndreyZlobin commented on packages/ui/src/DashboardLayout/Header/Header.tsx
> +    <HeaderRoot ref={ref}>
У Header не хватает action, думаю это children 
![image](https://user-images.githubusercontent.com/51029733/168038935-a4f86eab-b7e8-460d-9199-ea56472b6e75.png)
https://www.figma.com/file/xEfzD7H5uqkBtAN0uBNkSJ/Sirius-Design-System?node-id=2932%3A44150

2022-05-12 09:58 UTC, perevezencev commented on packages/ui/src/DashboardLayout/Header/Header.tsx
> +    <HeaderRoot ref={ref}>
Навигационное меню через проп menu можно передать, остальное через children или все через пропы @AndTem ?

2022-05-12 10:04 UTC, perevezencev commented on packages/ui/src/DashboardLayout/Header/HeaderNav/HeaderNav.tsx
> +        {Switcher && <Switcher />}
ProductSwitcher норм

2022-05-13 08:48 UTC, perevezencev commented on packages/ui/src/DashboardLayout/Header/HeaderNav/HeaderNav.tsx
> +        {Menu && <Menu />}
я пока вообще выпилю, в дальнейшем добавим

2022-05-13 09:51 UTC, AndTem approved these changes

2022-05-13 09:54 UTC, m-av97 approved these changes

2022-05-13 09:54 UTC, merged