chore(icons): иконкам success, warning, error, info добавлена возможность изменять цвет, так же иконкам соцсетей были даны соответствующие цвета
kaluga-astral/frontend pull request #229
Opened 2022-05-13 06:43 UTC by olewka40

2022-05-13 11:50 UTC, AndTem requested changes

2022-05-13 11:50 UTC, AndTem commented on packages/icons/index.stories.tsx
> +      <Grid key="fillmdcolored" container spacing={4} m={4}>
используй наш Grid

2022-05-13 11:50 UTC, AndTem commented on packages/icons/index.stories.tsx
> +          <h2 style={{ textAlign: 'center' }}>Fill md 24 colored</h2>
а нельзя отдельно показать логотипы?

2022-05-16 05:26 UTC, AndTem commented on packages/icons/index.stories.tsx
> +          <h2 style={{ textAlign: 'center' }}>CompanysLogos</h2>
Companies Logos - ошибка окончании

2022-05-16 09:29 UTC, AndTem approved these changes

2022-05-16 10:50 UTC, AndTem approved these changes

2022-05-16 10:57 UTC, AndreyZlobin approved these changes

2022-05-17 07:42 UTC, merged