UIKIT-174: feat(ui, DropdownButton): Реализован компонент DropdownButton
kaluga-astral/frontend pull request #237
Opened 2022-05-13 08:42 UTC by StanislavDa

2022-05-13 08:48 UTC, AndTem requested changes

2022-05-13 08:48 UTC, AndTem commented on packages/ui/src/DropdownButton/types.ts
> +export type DropdownButtonProps = Omit<ButtonProps, 'endIcon' | 'loading'> & {
По [style guide](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3527573602/Props#Type-props-%D0%B4%D0%BB%D1%8F-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0-%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD-%D0%BD%D0%B0%D1%85%D0%BE%D0%B4%D0%B8%D1%82%D1%81%D1%8F-%D0%B2-%D1%84%D0%B0%D0%B9%D0%BB%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0) пропсы внутри компонента

2022-05-13 08:48 UTC, AndTem commented on packages/ui/src/DropdownButton/DropdownButton.tsx
> +        variant="light"
variant не должен быть закардкожен

2022-05-13 08:48 UTC, AndTem commented on packages/ui/src/DropdownButton/DropdownButton.tsx
> +        pressed={open}
pressed -> selected

2022-05-13 08:48 UTC, AndTem commented on packages/ui/src/DropdownButton/DropdownButton.tsx
> +export const DropdownButton = forwardRef<
Необходим еще компонент IconDropdownButton - смотри описание задачи

2022-05-16 09:31 UTC, AndTem requested changes

2022-05-16 09:31 UTC, AndTem commented on packages/ui/src/DropdownButton/DropdownButton.tsx
> +  name: string;
добавь js doc описание

2022-05-17 07:40 UTC, AndTem approved these changes

2022-05-17 11:12 UTC, perevezencev commented on packages/ui/src/DropdownButton/DropdownButton.tsx
> +  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
Уже писал подобное в компоненте `Profile`. Думаю, что стоит вынести хэндлеры и стейт в отдельный хук. @AndTem что думаешь, нужна фича или оверхед?

2022-05-17 11:12 UTC, perevezencev commented on packages/ui/src/DropdownButton/DropdownButton.tsx
> +  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
Там немного по-другому, но суть такая же. 
<img width="582" alt="Снимок экрана 2022-05-17 в 14 05 40" src="https://user-images.githubusercontent.com/5954104/168797244-668af45f-d04b-431d-94bf-4fc474ff7dab.png">
Там я пытался уйти от вот такого `(event: MouseEvent<HTMLButtonElement>)`

2022-05-17 11:12 UTC, perevezencev commented on packages/ui/src/DropdownButton/styles.ts
> +
Почему не через переопределение темы?

2022-05-17 11:12 UTC, perevezencev commented on packages/ui/src/IconDropdownButton/IconDropdownButton.tsx
> +export type IconDropdownButtonProps = Omit<BaseButtonProps, 'loading'> & {
На сколько я помню в BaseButtonProps нет пропа `loading`

2022-05-17 11:12 UTC, perevezencev commented on packages/ui/src/IconDropdownButton/IconDropdownButton.tsx
> +  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
Еще один аргумент вынести в кастомные хук

2022-05-17 11:18 UTC, AndTem requested changes

2022-05-17 11:18 UTC, AndTem commented on packages/ui/src/DropdownButton/DropdownButton.tsx
> +      <DropdownButtonWrapper
Добавь ClickAwayListener

2022-05-17 11:18 UTC, AndTem commented on packages/ui/src/DropdownButton/DropdownButton.tsx
> +  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
Вынести типа useMenu?

2022-05-17 11:20 UTC, perevezencev commented on packages/ui/src/DropdownButton/DropdownButton.tsx
> +  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
Ага. Только надо бы еще над неймингом подумать. @m-av97 Как думаешь?

2022-05-17 11:21 UTC, AndTem commented on packages/ui/src/DropdownButton/styles.ts
> +
В отдельной задаче будет реализация selected состояния кнопки. Здесь пока просто прямая реализация

2022-05-18 07:56 UTC, StanislavDa commented on packages/ui/src/DropdownButton/DropdownButton.tsx
> +  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
вынес, если все норм, может сразу поправить и в компоненте Profile? Кста, хуки должны быть доступны потребителю?

2022-05-18 07:58 UTC, perevezencev approved these changes

2022-05-18 09:24 UTC, AndTem requested changes

2022-05-18 09:24 UTC, AndTem commented on packages/ui/src/hooks/useMenu.ts
> +export function useMenu() {
Опиши тип возвращаемого значения и добавь к нему js doc

2022-05-18 09:24 UTC, AndTem commented on packages/ui/src/index.ts
> +export * from './IconDropdownButton';
забыл экспорт хука сделать

2022-05-20 07:56 UTC, AndTem requested changes

2022-05-20 07:56 UTC, AndTem commented on packages/ui/src/hooks/useMenu.ts
> +type UseMenu = {
У тебя название как будто тип описывает хук. А на самом деле этот тип описывает возращаемое значение

2022-05-20 07:56 UTC, AndTem commented on packages/ui/src/IconDropdownButton/IconDropdownButton.tsx
> +    <Fragment>
можно просто <></>

2022-05-20 07:57 UTC, StanislavDa commented on packages/ui/src/IconDropdownButton/IconDropdownButton.tsx
> +    <Fragment>
мб единый стиль выбрать? просто где-то фрагменты, а где-то <></>

2022-05-20 08:01 UTC, StanislavDa commented on packages/ui/src/hooks/useMenu.ts
> +type UseMenu = {
UseMenuProps, UseMenuParams?)

2022-05-20 08:04 UTC, StanislavDa commented on packages/ui/src/IconDropdownButton/IconDropdownButton.tsx
> +    <Fragment>
А в итоге <></> или фрагменты? Если <></>, то сразу везде поменяю на них фрагменты?

2022-05-20 08:06 UTC, AndTem commented on packages/ui/src/IconDropdownButton/IconDropdownButton.tsx
> +    <Fragment>
По своему коду сделай <></>. Мы тех. советом обсудим добавление правила в style guide. Как добавим - создаим задачу на рефакторинг

2022-05-20 08:16 UTC, AndTem approved these changes

2022-05-20 08:42 UTC, perevezencev approved these changes

2022-05-20 09:22 UTC, merged