UIKIT-143: создан пакет @astral/form
kaluga-astral/frontend pull request #277
Opened 2022-05-17 10:45 UTC by AlexadraLitvinenko

2022-05-17 10:49 UTC, AndTem commented
Неверный заголовок PR, должно быть UIKIT-000: feat(form): message

2022-05-17 10:51 UTC, AndTem requested changes

2022-05-17 10:51 UTC, AndTem commented on commander/constants.js
> +  "@astral/ui",
Что то с eslint произошло. У нас одинарные ковычки

2022-05-17 10:51 UTC, AndTem commented on packages/form/README.md
> +В данном пакете находятся формы дизайн-системы Астрал.Софт.
Находятся обёртки компонентов формы для react hook form

2022-05-18 06:09 UTC, AndTem approved these changes

2022-05-18 06:20 UTC, AndreyZlobin approved these changes

2022-05-18 08:00 UTC, perevezencev approved these changes

2022-05-20 12:50 UTC, AndreyZlobin approved these changes

2022-05-20 13:05 UTC, merged