UIKIT-135: feat(ui,ContentState): Реализован компонент для управления состоянием
kaluga-astral/frontend pull request #278
Opened 2022-05-17 12:00 UTC by vinokurov-and

2022-05-17 12:07 UTC, AndTem commented on packages/ui/src/ContentState/ContentState.tsx
> +    return (
Для Placeholder img надо установить высоту и ширину, а то прыгает контент при загрузке

2022-05-19 10:47 UTC, AndTem requested changes

2022-05-19 10:47 UTC, AndTem commented on packages/ui/src/ContentState/ContentState.tsx
> +    const { title = 'Произошла ошибка', ...restCustomState } = customState;
Тут дефолтное значение для title лишнее

2022-05-19 10:58 UTC, AndTem approved these changes

2022-05-19 11:10 UTC, AndreyZlobin approved these changes

2022-05-19 11:27 UTC, m-av97 approved these changes

2022-05-20 13:05 UTC, merged