UIKIT-299: feat(ui,DataGrid): Добавлен generic для сортировки
kaluga-astral/frontend pull request #317
Opened 2022-06-10 10:22 UTC by cryzer12

Был добавлен generic для сортировки в DataGrid
Был изменен field columns на опциональный

2022-06-10 10:30 UTC, AndTem requested changes

2022-06-10 10:30 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridCell/DataGridCell.tsx
> +    return 'Нет данных';
Сделай дефис вместо текста и это надо добавить в пропс типа - emptyCellValue: ReactNode

2022-06-10 10:30 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridHeadColumn/types.ts
> +export type DataGridHeadColumnProps<
По [style guide](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3527573602/Props#Type-props-%D0%B4%D0%BB%D1%8F-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0-%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD-%D0%BD%D0%B0%D1%85%D0%BE%D0%B4%D0%B8%D1%82%D1%81%D1%8F-%D0%B2-%D1%84%D0%B0%D0%B9%D0%BB%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0) пропсы внутри компонента определяются. Надо везде сделать правки, где ты изменял код

2022-06-10 10:39 UTC, cryzer12 commented on packages/ui/src/DataGrid/DataGridHeadColumn/types.ts
> +export type DataGridHeadColumnProps<
да окей, так как все равно много где изменений было, можно и остальное поправить

2022-06-10 10:40 UTC, cryzer12 commented on packages/ui/src/DataGrid/DataGridCell/DataGridCell.tsx
> +    return 'Нет данных';
ReactNode или просто string?

2022-06-10 10:50 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridCell/DataGridCell.tsx
> +    return 'Нет данных';
ReactNode

2022-06-10 13:51 UTC, AndTem requested changes

2022-06-10 13:51 UTC, AndTem commented on packages/ui/src/DataGrid/types.ts
> +  emptyCellValue?: ReactNode;
этот пропс должен быть у самого DataGrid. Нет никакого смыысла указывать его для каждой колоник

2022-06-10 13:51 UTC, AndTem commented on packages/ui/src/DataGrid/types.ts
> +  emptyCellValue?: ReactNode;
Необходимо добавить js doc описание

2022-06-10 14:00 UTC, cryzer12 commented on packages/ui/src/DataGrid/types.ts
> +  emptyCellValue?: ReactNode;
логично

2022-06-10 14:22 UTC, AndTem requested changes

2022-06-14 11:47 UTC, AndreyZlobin commented on packages/ui/src/DataGrid/DataGrid.tsx
> +   * Массив данных для таблицы
@example
На всех кусках описания

2022-06-14 11:47 UTC, AndreyZlobin commented on packages/ui/src/DataGrid/DataGrid.tsx
> +   * Массив данных для таблицы
/**
   * @example 
   * Массив данных для таблицы

2022-06-14 11:47 UTC, AndreyZlobin commented on packages/ui/src/DataGrid/DataGridHead/DataGridHead.tsx
> +  SortField extends keyof Data = keyof Data,
А зачем тут? = keyof Data

2022-06-14 11:47 UTC, AndreyZlobin commented on packages/ui/src/DataGrid/types.ts
> +   * Флажок включающий сортировку колонки
Тут тоже аннотацию  example добавить  и во всех кейсах

2022-06-14 11:56 UTC, cryzer12 commented on packages/ui/src/DataGrid/DataGridHead/DataGridHead.tsx
> +  SortField extends keyof Data = keyof Data,
почему-то просит если есть дефолтные значения в первом параметро, то и во втором, ругается тс, хз почему

2022-06-15 05:00 UTC, AndreyZlobin approved these changes

2022-06-15 06:27 UTC, merged