bug(UIKIT-310,ui): Исправлена ошибка типизации для Tooltip и Circula…
kaluga-astral/frontend pull request #328
Opened 2022-06-23 11:42 UTC by vinokurov-and

…rProgress

2022-06-23 11:47 UTC, AndTem requested changes

2022-06-23 11:47 UTC, AndTem commented on packages/ui/src/Tooltip/Tooltip.tsx
>  import { TooltipProps } from './types';
По [style guide](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3527573602/Props) пропсы внутри компонента определяются.
Это делал не ты, но ты коснулся этого компонента, значит надо провести небольшой рефакторинг - перенести эти типы внутрь компонента (не забудь экспорт поправить)

2022-06-23 11:47 UTC, AndTem commented on packages/ui/src/CircularProgress/CircularProgress.tsx
>  import { CircularProgressProps } from './types';
По [style guide](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3527573602/Props) пропсы внутри компонента определяются.

2022-06-23 11:48 UTC, AndTem commented
Проверил в storybook? Запрещено использовать css и sx там для тултипа?

2022-06-23 12:33 UTC, vinokurov-and commented
> Проверил в storybook? Запрещено использовать css и sx там для тултипа?

на css не выдает ошибку.. 
![image](https://user-images.githubusercontent.com/48560509/175299343-1c1a617b-1be5-4bfd-90b3-3b4078cdb3b3.png)

2022-06-23 12:33 UTC, vinokurov-and commented
> Проверил в storybook? Запрещено использовать css и sx там для тултипа?

а не, всё ок 
![image](https://user-images.githubusercontent.com/48560509/175299466-3369d2d0-2f88-4c89-b88e-42492610d4a8.png)

2022-06-23 13:51 UTC, AndTem requested changes

2022-06-23 13:51 UTC, AndTem commented on packages/ui/src/CircularProgress/CircularProgress.tsx
> +export type CircularProgressProps = Omit<
WithoutEmotionSpecific должен применяться здесь

2022-06-24 05:52 UTC, AndTem requested changes

2022-06-24 05:52 UTC, AndTem commented on packages/ui/src/CircularProgress/declaration.d.ts
> +declare module '@mui/material/CircularProgress' {
Для того, чтобы это объявление попало в итоговый билд, необходимо, чтобы был ts файл. Сделай types.ts

2022-06-24 05:52 UTC, AndTem commented on packages/ui/src/CircularProgress/index.ts
> +export * from './declaration';
Из declaration ничего не экспортится

2022-06-27 13:11 UTC, vinokurov-and commented on packages/ui/src/CircularProgress/index.ts
> +export * from './declaration';
> Из declaration ничего не экспортится

даже types.ts убрать? declare подхватится?

2022-06-27 13:32 UTC, AndTem commented on packages/ui/src/CircularProgress/index.ts
> +export * from './declaration';
Да, вот пример: https://github.com/kaluga-astral/frontend/blob/main/packages/ui/src/Typography/types.ts

2022-06-27 13:32 UTC, AndTem approved these changes

2022-06-28 06:04 UTC, perevezencev approved these changes

2022-06-28 06:15 UTC, AndreyZlobin approved these changes

2022-06-28 10:30 UTC, AndTem commented on packages/ui/src/CircularProgress/types.ts
> +export {};
Давай перенесём, чтобы не было неоднозначностей.

@vinokurov-and закинь переопределением в сам компонент

2022-07-01 08:15 UTC, merged