feat(UIKIT-327,ui,OverflowTypography): Переиспользуемый компонент для…
kaluga-astral/frontend pull request #334
Opened 2022-07-18 07:39 UTC by Ofigelov

Вариация 'Typography' элемента, с автоматической проверкой на длину строки, и если длина больше настраиваемого значения 'overflowLimit', то тогда добавляется кастомизируемая обертка 'Tooltip'.

Так же важный параметр 'rowsCount', по умолчанию равен '1'. Означает число строк, после которого текст будет обрезаться, и добавляться многоточие.

Расчет максимальной ширины элемента производится по формуле `${ overflowLimit / rowsCount }ch`
Единица измерения 'ch' выбрана из того соображения, что нужно рассчитывать ширину по усредненной ширине символа, коей 'ch' приблизительно и является.

Собственно первый кейс для использования - в компоненте Autocomplete по умолчанию.

https://astraltrack.atlassian.net/browse/UIKIT-327

2022-07-19 07:43 UTC, AndTem requested changes

2022-07-19 07:43 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +export interface OverflowedProps {
Предпочитаем type интерфейсу

2022-07-19 07:43 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +const LazyTooltip = lazy(() =>
Из-за lazy придется дополнительно плясать со сборщиком, чтобы он обрабатывал внутри node_modules lazy

2022-07-19 07:43 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +  tooltipProps = {} as TooltipProps,
тут какой-то костыль. Не должно быть as

2022-07-19 07:43 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +      // @ts-ignore ругается на то что тайтл может быть перезаписан, но на то и расчет, что при необходимости его можно заменить.
Не используй @ts-ignore. Лучше тогда уж as any

2022-07-19 07:43 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +const LazyTooltip = lazy(() =>
Сделай без lazy. Не критично

2022-07-19 07:43 UTC, AndTem commented on packages/ui/src/OverflowTypography/styles.ts
> +  max-width: ${({ overflowLimit, rowsCount }) => overflowLimit / rowsCount}ch;
оставь здесь коммент что за расчеты

2022-07-19 07:43 UTC, AndTem commented on packages/ui/src/OverflowTypography/styles.ts
> +  display: -webkit-box;
Зачем -webkit-box? Если сделаешь просто flex, то префиксы emotion сам подставит

2022-07-19 07:43 UTC, AndTem commented on packages/ui/src/Autocomplete/Autocomplete.tsx
> +            rowsCount={DEFAULT_AUTOCOMPLETE_ELEMENT_ROWS_COUNT}
Для чего прокидывать эти пропсы если они и так по дефолту стоят в OverflowTypography?

2022-07-19 07:44 UTC, AndTem commented
-  В storybook для компонента нельзя изменить пропсы (не доступны контролы).
- В Autocomplete не работает OverflowTypography
<img width="319" alt="image" src="https://user-images.githubusercontent.com/23665108/179695266-2a3e96c2-b87c-473d-b24c-1a4ed1389cf0.png">

2022-07-19 08:16 UTC, AndTem commented on packages/ui/src/Autocomplete/Autocomplete.tsx
> +            rowsCount={DEFAULT_AUTOCOMPLETE_ELEMENT_ROWS_COUNT}
Понял

2022-07-19 08:25 UTC, Ofigelov commented
> * В storybook для компонента нельзя изменить пропсы (не доступны контролы).
> * В Autocomplete не работает OverflowTypography
> 
> <img alt="image" width="319" src="https://user-images.githubusercontent.com/23665108/179695266-2a3e96c2-b87c-473d-b24c-1a4ed1389cf0.png">



> 
У меня работает.

![image](https://user-images.githubusercontent.com/59384103/179703092-a64a5dc0-b9bb-4c0e-932d-955e3e474b82.png)

Вероятно проблема в том, что в твоем примере используется вариант с кастом рендерингом элементов, и в них текст надо отдельно заворчивать в OverflowTypography.

Я сделаю это для сторибука, но на проектах кастом рендеринги нужно будет отдельно обработать этим компонентом.

2022-07-19 08:35 UTC, perevezencev commented on packages/ui/src/OverflowTypography/styles.ts
> +  -webkit-box-orient: vertical;
Тоже лишнее

2022-07-19 08:35 UTC, perevezencev commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +  overflowLimit?: number;
Добавь комменты

2022-07-19 08:35 UTC, perevezencev commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +  const isLongerThanLimit =
Это все можно не делать если использовать ResizeObserver

https://github.com/kaluga-astral/astral-frontend/blob/c5939534266691982a4b2c494450379c1a37e3df/packages/ui/components/src/TextOverflowTooltip/TextOverflowTooltip.jsx#L34

2022-07-19 08:35 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/styles.ts
> +  display: -webkit-box;
нет тут именно `-webkit-box` должен быть. Именно данное сочетание цсс свойств дает возможность регулировать количество отображаемый строк перед обрезкой и добавлением многоточия. Я пробовал поменять `display: -webkit-box;` на `display: flex;` нужный эффект пропадает.

2022-07-19 08:37 UTC, perevezencev commented on packages/ui/src/OverflowTypography/styles.ts
> +  display: -webkit-box;
т.е. не в webkit оно не будет работать?

2022-07-19 08:38 UTC, perevezencev commented on packages/ui/src/OverflowTypography/styles.ts
> +  display: -webkit-box;
Тут скорее всего подойдет просто block

2022-07-19 08:42 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/styles.ts
> +  display: -webkit-box;
Нет, обычный блок тоже не работает.
Данное решение работает в хроме, мозиле и сафари. Я уже использовал его, QA пропустили без проблем.

2022-07-19 08:47 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/styles.ts
> +  -webkit-line-clamp: ${({ rowsCount }) => rowsCount};
у меня не добавляет 
![image](https://user-images.githubusercontent.com/59384103/179708514-66713162-35e6-4c93-afe4-7f9354943213.png)

2022-07-19 08:49 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/styles.ts
> +  -webkit-box-orient: vertical;
автоматически не добавляется 
![image](https://user-images.githubusercontent.com/59384103/179708889-ca8e97ba-9dd0-4327-b7ad-9cc0600c852c.png)

2022-07-19 08:53 UTC, perevezencev commented on packages/ui/src/OverflowTypography/styles.ts
> +  display: -webkit-box;
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp

интересно, но это не браузерный префикс

2022-07-19 08:54 UTC, perevezencev commented on packages/ui/src/OverflowTypography/styles.ts
> +  display: -webkit-box;
line-clamp тогда можно даже не определять, видимо, просто сразу -webkit-line-clamp

2022-07-19 08:56 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +      title={children}
Просто упростил использование, и добавил защиту от дурака, если передадут не текст, а куск хтмл, то отрендерится просто обрезаемый по колличеству строк хтмл текст, без обертки в виде Тултипа.

2022-07-19 09:07 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +  const isLongerThanLimit =
А я и не знал о его существовании =(

Но, приведенный пример основывается на JS расчетах, мой вариант опирается по сути только на цсс, он вполне кроссплатформенный, т.е. работает быстрее.

2022-07-19 10:25 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +export const OverflowTypography = ({
В общем я не стал оборачивать его форвард рефом, 2причниы:
1. нету в этом явной необходимости, [YAGNII ](https://ru.wikipedia.org/wiki/YAGNI)
2. при добавлении начинаются проблемы с типизацией на уровне использования

2022-07-19 10:27 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/styles.ts
> +  max-width: ${({ overflowLimit, rowsCount }) => overflowLimit / rowsCount}ch;
Почему то тут комменты не отображаются, хотя я по факту добавил их. Наверное потому что сама строка, по которой сделан коммент, не изменлась

2022-07-19 10:32 UTC, AndTem requested changes

2022-07-19 10:32 UTC, AndTem commented on packages/ui/src/Autocomplete/types.ts
>    Pick<TextFieldProps, 'error' | 'success' | 'helperText' | 'label'> & {
У нас по style guide пропсы определяются в файле компонента. Перенеси их туда

2022-07-19 10:32 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +  // опорная единица, по которой определяется max-width в ch по формуле ${overflowLimit / rowsCount},
Комменты должны быть в виде js doc. Смотри как сделано в других компонентах, например, DataGrid

2022-07-19 10:32 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +          {...{ ...props, overflowLimit, rowsCount, children }}
Немного странноватая конструкция. Первый spread можно убрать

2022-07-19 10:46 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +          {...{ ...props, overflowLimit, rowsCount, children }}
первый спред позволяет заменить повторяющиеся названия пропсов, т.е. вместо `<OverflowTypographyWrapper rowsCount={rowsCount} />` я использовал `<OverflowTypographyWrapper {...{rowsCount}} />`, но так как это элемент типографики, мы передаем в него оставшиеся потенциальные пропсы этой типографики: `<OverflowTypographyWrapper {...{...props, rowsCount}} />`.

2022-07-19 11:56 UTC, AndTem commented
Необходимо поправить ошибки линтеров

2022-07-19 11:57 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +          {...{ ...props, overflowLimit, rowsCount, children }}
<OverflowTypographyWrapper {...props}  rowsCount={rowsCount} /> выглядит понятнее

2022-07-19 11:59 UTC, AndTem requested changes

2022-07-19 11:59 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +   * @description опорная единица, по которой определяется max-width в ch по формуле ${overflowLimit / rowsCount}, и определяется необходимость монтирования Tooltip
Инфа о формуле здесь лишняя

2022-07-19 12:09 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +          {...{ ...props, overflowLimit, rowsCount, children }}
up

2022-07-20 06:15 UTC, AndTem approved these changes

2022-07-20 06:55 UTC, lordniken commented on .huskyrc
> -{
А зачем конфиг удалил?

2022-07-20 06:57 UTC, Ofigelov commented on .huskyrc
> -{
ой, эт не должно было сюда попасть, удалил для того чтобы коммит вобще сделать, а то не пропускает, сейчас верну

2022-07-20 06:59 UTC, lordniken commented on .huskyrc
> -{
можно через no-verify коммитить, не обязательно конфиг удалять)

2022-07-20 07:02 UTC, Ofigelov commented on .huskyrc
> -{
у меня в gui нету возможности, или я не знаю где вставить, постфикс этот

2022-07-20 07:49 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +export const OverflowTypography = ({
froeardRef необходим для того, чтобы у пользователей была возможность взять ref у Typography без необходимости вносить правки в ui-kit

2022-07-20 07:52 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +  const isLongerThanLimit =
@Ofigelov твое текущее решение не адаптивно. То есть если руками цифру указал не правильную, то работать будет неверно компонент. Паша предлагает автоматизированное решение, если есть такое же на css - предлагай

2022-07-20 09:18 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +export const OverflowTypography = ({
Добавил, как решили на груминге

2022-07-20 09:22 UTC, perevezencev commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +          <OverflowTypographyWrapper
Повторяющийся код начиная с 77 строки

2022-07-20 09:30 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +          <OverflowTypographyWrapper
Обновил

2022-07-20 10:29 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +  const isLongerThanLimit =
Во первых, [это ](https://github.com/kaluga-astral/astral-frontend/blob/c5939534266691982a4b2c494450379c1a37e3df/packages/ui/components/src/TextOverflowTooltip/TextOverflowTooltip.jsx#L34) решение не из коробки. Оно в старом репозитории, в старом стиле, без использования типографики, без тултипа. Не получится просто взять и использовать. А проблема существует у меня на проекте здесь и сейчас. 

Во вторых, я бы не хотел добавлять дополнительную логику с вычислениями в такой компонент как автокомплит, он сейчас очень перегружен разнообразными действиями, и в некоторых кейсах, с мултипл стейтом, валидацией, и когда в нем отрисовывается больше нескольких десятков опцией, при открытии, выборе, и закрытии наблюдаются проблемы с перфомансом, компонент тупо тормозит. А если предположить, что мы туда еще засунем такой компонентик с вычислениями для ширины, подпиской на обновления вьюпорта и пересчетом, и все это для десятков, а в обозримом будущем и для сотен+ элементов, то перфоманс этому точно не обрадуется.

Я вообще не очень хотел добавлять Тултип, и сделать это на нативном атрибуте title, но так как дизайн код и все такое, тут не отвертишься.

Решения которые используют CSS априори быстрее чем решения которые используют JS велосипед.

Так что мой вариант работает быстрее ровно на: отсутсвие подписок на изменения вьюпорта + отсутствие вычислений + отстуствие использование всех хуков.

`обязывает пользователя этого компонента передавать дополнительные пропсы`- тут все довольно гибко, можно передавать если не устраивают значения по умолчанию, и как правило в конкретных местах мы знаем что нам нужно, сколько строк, сколько символов и т.п., так что не вижу тут ничего криминального. Один раз установил для нужного компонента, и забыл.

По поводу адаптивности могу предложить добавить пропс isFullWidth, который будет выставлять ширину в 100%, и тогда компонентик будет тянуться на всю доступную ширину, как обычный `display: block`, но определение необходимости монтирования Тултипа все равно вычислять по длине строки, чтобы не городить велосипед. Подойдет для кейсов когда компонент оказался очень длинным, хотя как по мне надо такого избегать, и это уже проблема дизайна.

Если задумываться наперед, что у нас в когда нибудь появятся мобильные дизайны, брейкопинты и все такое, то можно будет добавить сюда использование этих брейкпоинтов, и сделать настройку пропсов по этим брейкпоинтам. Но это явно не сейчас.

2022-07-22 11:37 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +const resizeObserver = new ResizeObserver(debouncedResizeCb);
Я решил что лучше все таки иметь один инстанс ресайз обсервера для сотни компонентов, чем каждый из этих компонентов будет иметь свой обсервер. Экономия памяти и скорости исполнения.
Он один выполняет свою функцию вполне хорошо. Единственное, это передача ссылки на сетСтейт. Это я решил через мутация дом ноды. Т.е. каждая дом нода будет иметь ссылку на свой сетСтейт.

2022-07-22 11:37 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +        node.setOverflow = setOverflow;
да, как уже написал выше, это небольшая цена за оптимизацию компонента. Но так как тут все типизированно, все довольно прозрачно.

2022-07-22 11:39 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +    const ref =
но нам же реф может сверху прийти из фораврда, нам же надо будет его дальше передать в элемент типографики.

2022-07-22 11:40 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +          title={(typeof children === 'string' && children) || ''}
в children может прийти реакт компонент... или сюда его тоже можно...

2022-07-22 11:41 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +  rowsCount?: number;
да, я потестировал, работает корректно

2022-07-22 11:43 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +const resizeObserver = new ResizeObserver(debouncedResizeCb);
Ты уверен, что когда ты подписываешься на новую ноду, то старая не отписывается?
Мутация ноды - плохо. Можно просто замкнуть в компоненте и не делать костылей

2022-07-22 11:43 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +          title={(typeof children === 'string' && children) || ''}
Почему нет?

2022-07-22 11:45 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +        node.setOverflow = setOverflow;
Мутация ноды прозрачности не добавляет

2022-07-22 11:47 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +          title={(typeof children === 'string' && children) || ''}
незнаю, я почему то был уверен что только строку принимает. поменяю

2022-07-22 12:28 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +const resizeObserver = new ResizeObserver(debouncedResizeCb);
Боюсь, что из-за глобального инстанса у тебя при игнорировании вызовов могут быть проигнорированы нужные события.
Кейс: на странице в двух разных блоках с разной шириной находятся OverflowTypography. При изменении ширины экрана в первом блоке ширина изменялась 0.1s, во втором 0.3s. В итогу из-за debounce вызовы для первого блока могуть быть проигнорированы

2022-07-22 12:29 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +const resizeObserver = new ResizeObserver(debouncedResizeCb);
Сделай observer внутри компонента - если словим проблемы оптимизации - решим их

2022-07-25 04:08 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +const resizeObserver = new ResizeObserver(debouncedResizeCb);
Не, проблема в том что сущность дебаунса одна и та же, и ей не важно для какой ноды вызывается он, будет вызван только самый последний коллбэк. 
Я перенес дебаунс колбэк в тело реакт функции, т.е. обсервер будет вызывать для каждой ноды свой дебаунсСетОверфлоу.

2022-07-25 04:19 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +        node.setOverflow = setOverflow;
Я понимаю что без причины ноды лучше не мутировать, но, в текущей ситуации, нативный обсервер принимает всего лишь один аргумент в виде ноды, и прокинуть к ней свой колбэк можно только мутировав эту ноду.

Я вынес всю эту логику в кастомный хук, там эта мутация происходит, используется, и наружу прокидывается как обычный хтмл элемент. В процессе использования есть дефенсив код на проверку наличия мутации.

Так что все изолировано, и наружу ничем лишним не светит.

2022-07-25 11:17 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +const resizeObserver = new ResizeObserver(debouncedResizeCb);
ResizeObserver  у тебя не привязан к конкретному компоненту, поэтому описанная мною проблема не решается увеличением количества debounce обработчиков

2022-07-25 12:45 UTC, AndTem commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +const resizeObserver = new ResizeObserver(debouncedResizeCb);
В нашем случае, если мы хотим оптимизировать создание инстансовresize observer, resize observer должен быть инициализирован для каждого отдельного контейнера, в котором находятся наши OverflowTypography. В таком случае можно будет придумать какой нибудь OverflowContainer (с контекстом), НО сейчас эта оптимизация преждевременна

2022-07-26 03:57 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +const resizeObserver = new ResizeObserver(debouncedResizeCb);
Обновил, сделал как ты сказал.

2022-07-26 06:00 UTC, AndTem requested changes

2022-07-26 06:00 UTC, AndTem commented on packages/ui/src/OverflowTypography/hooks/useOverflowed/useOverflowed.ts
> +    return;
Return здесь не обязательный

2022-07-26 06:00 UTC, AndTem commented on packages/ui/src/OverflowTypography/hooks/useOverflowed/useOverflowed.ts
> +  useLayoutEffect(() => {
Почему layoutEffect?

2022-07-26 06:09 UTC, perevezencev commented on packages/ui/src/OverflowTypography/hooks/useOverflowed/useOverflowed.ts
> +  useLayoutEffect(() => {
Скорее всего потому что внутри идет обращение к `ref`, но дальше идет проверка `ref?.current`

2022-07-26 06:09 UTC, perevezencev commented on packages/ui/src/OverflowTypography/styles.ts
> +  display: -webkit-box;
Мы же это убираем?

2022-07-26 06:10 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/hooks/useOverflowed/useOverflowed.ts
> +  useLayoutEffect(() => {
потому что он срабатывает после всех изменений в dom дереве, т.е. буквально после монтирования компонента на страницу, и т.к. мы по сути зависим от методов дом дерева, с получением размеров, нам надо либо делать задержку через requestAnimationFrame или setTimeout чтобы корректно поулчить все размеры, либо же просто воспользоваться лэйаут эффектом.

2022-07-26 06:11 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/hooks/useOverflowed/useOverflowed.ts
> +    return;
без него линтеры ругаются

2022-07-26 06:12 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/styles.ts
> +  display: -webkit-box;
нет, без этого не будет возможности обрезать в 2 строки.

2022-07-26 06:13 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/hooks/useOverflowed/useOverflowed.ts
> +  useLayoutEffect(() => {
>  но дальше идет проверка

без этой проверки линтеры ругаются

2022-07-26 06:19 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/OverflowTypography.tsx
> +        <Tooltip title={children || ''} disableInteractive {...tooltipProps}>
Обновил

2022-07-26 06:38 UTC, AndTem commented on packages/ui/src/OverflowTypography/styles.ts
> +  display: -webkit-box;
Сделай еще fallback, если -webkit не работает в браузере

2022-07-26 06:38 UTC, AndTem approved these changes

2022-07-26 06:51 UTC, Ofigelov commented on packages/ui/src/OverflowTypography/styles.ts
> +  display: -webkit-box;
![image](https://user-images.githubusercontent.com/59384103/180940370-8010bd5e-a48f-495b-8274-4b1b387e479c.png)
![image](https://user-images.githubusercontent.com/59384103/180940569-870c2e49-ece7-4790-a1a9-2c8f3252f1bd.png)
![image](https://user-images.githubusercontent.com/59384103/180940657-d86e4ad3-fad8-43d2-bfe7-d1a48bffb0d1.png)

не думаю что это требуется, везде где это работает, требуется -webkit префикс

2022-07-26 08:18 UTC, perevezencev approved these changes

2022-07-26 08:18 UTC, perevezencev commented on packages/ui/src/OverflowTypography/hooks/useOverflowed/useOverflowed.ts
> +  const debouncedSetOverflow = useCallback(
@AndTem предлагаю не отображать никаких суффиксов в таких местах

2022-07-26 08:41 UTC, AndTem commented on packages/ui/src/OverflowTypography/hooks/useOverflowed/useOverflowed.ts
> +  const debouncedSetOverflow = useCallback(
@perevezencev ты про префикс? А как тут без него?

2022-07-26 08:44 UTC, perevezencev commented on packages/ui/src/OverflowTypography/hooks/useOverflowed/useOverflowed.ts
> +  const debouncedSetOverflow = useCallback(
просто `setOverflow` без `debounce` (throttle, memoized etc.)

2022-07-26 08:48 UTC, AndTem commented on packages/ui/src/OverflowTypography/hooks/useOverflowed/useOverflowed.ts
> +  const debouncedSetOverflow = useCallback(
@AndTem а setOverflow из useState как в таком случае тогда обзывать?

2022-07-26 08:51 UTC, perevezencev commented on packages/ui/src/OverflowTypography/hooks/useOverflowed/useOverflowed.ts
> +  const debouncedSetOverflow = useCallback(
Резонно. А вообще в этом случае я бы сделал так:
```
const handleResize = useCallback(
```

2022-07-26 08:52 UTC, AndTem commented on packages/ui/src/OverflowTypography/hooks/useOverflowed/useOverflowed.ts
> +  const debouncedSetOverflow = useCallback(
@Ofigelov переименуешь?

2022-07-26 13:08 UTC, merged