bug(UIKIT-329,ui,Collapse): Восстановлена анимация состояний
kaluga-astral/frontend pull request #335
Opened 2022-07-19 07:24 UTC by Sergeypro91

2022-07-19 07:28 UTC, AndTem requested changes

2022-07-19 07:28 UTC, AndTem commented on packages/ui/src/Collapse/styled.ts
> +export const StyledCollapse = styled(Collapse)`
Название файла не по [style guide](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3527770446/Styled+components)

2022-07-19 07:28 UTC, AndTem commented on packages/ui/src/List/styled.ts
>      text-decoration: none;
Название файла не по [style guide](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3527770446/Styled+components)

2022-07-19 07:46 UTC, AndTem commented on packages/ui/src/List/styled.ts
>      text-decoration: none;
Не вижу изменений

2022-07-19 07:51 UTC, AndTem commented on packages/ui/src/List/List.tsx
> -        <Collapse
Почему убрал это от сюда? И COLLAPSED_SIZE тоже удалил для чего?

2022-07-19 08:11 UTC, AndTem commented on packages/ui/src/Collapse/Collapse.stories.tsx
> +      <Collapse in={open} timeout={150} orientation="vertical">
Может быть стоит добавить timeout={150} как дефолтный пропс, если он у нас везде руками указывается все равно?

2022-07-19 08:12 UTC, AndTem approved these changes

2022-07-19 08:15 UTC, perevezencev commented on packages/ui/src/List/List.tsx
> +      <ListProvider value={{ open }}>{children}</ListProvider>
А нужен ли сейчас ListProvider?

2022-07-19 09:23 UTC, Sergeypro91 commented on packages/ui/src/Collapse/Collapse.stories.tsx
> +      <Collapse in={open} timeout={150} orientation="vertical">
Базовый "transition-duration" = 300ms, если не указать на прямую. Проставление на 150 выполнил таким, каким его установил предыдущий разработчик. Вопрос к тому, необходимо ли изменить базовый "transition-duration" на 150ms?

2022-07-19 10:25 UTC, AndTem commented on packages/ui/src/Collapse/Collapse.stories.tsx
> +      <Collapse in={open} timeout={150} orientation="vertical">
Не надо. Пусть будет дефолтный от mui. Эти удали тогда

2022-07-19 10:26 UTC, Sergeypro91 commented on packages/ui/src/List/List.tsx
> +      <ListProvider value={{ open }}>{children}</ListProvider>
В текущей реализации необходимости в данном компоненте нет. Проверил использование "ListProvider", как я понял его добавили для реализации скрытия пунктов листа в горизонтальном формате, в связи с этим возник overhead логики. Удалил "ListProvider" и почистил места применения его самого и его контекста.

2022-07-19 11:54 UTC, perevezencev approved these changes

2022-07-20 06:16 UTC, AndTem approved these changes

2022-07-20 06:17 UTC, merged