UIKIT-133: feat(ui,Sidebar): Реализует компонент Sidebar
kaluga-astral/frontend pull request #337
Opened 2022-07-20 08:42 UTC by perevezencev

2022-07-21 13:29 UTC, AndTem requested changes

2022-07-21 13:29 UTC, AndTem commented on packages/ui/src/Tooltip/Tooltip.tsx
> +        placement={placement} {...restProps}>{children}</StyledTooltip>
eslint у тебя не отработал

2022-07-21 13:29 UTC, AndTem commented on packages/ui/src/hooks/useLocalStorage.ts
> +export { useLocalStorage } from 'react-use';
По style guide каждый хук в отдельной директории

2022-07-21 13:29 UTC, AndTem commented on packages/ui/src/theme/components/MuiButton.ts
> +        gap: theme.spacing(1),
gap для флексов пока еще не очень хорошо поддердивается

2022-07-21 13:29 UTC, AndTem commented on packages/ui/src/IconButton/IconButton.tsx
> +import { StyledIconButton } from './styled';
По style guide styles

2022-07-21 13:29 UTC, AndTem commented
У тебя с merge какие-то проблемы. Запроси ревью, когда решишь

2022-07-26 08:19 UTC, perevezencev commented on packages/ui/src/theme/components/MuiButton.ts
> +        gap: theme.spacing(1),
По caniuse вроде нормальная поддержка.
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/5954104/180958714-12ed6901-c640-44b4-8638-d42d153c5e23.png">

2022-07-26 08:19 UTC, perevezencev commented on packages/ui/src/theme/components/MuiButton.ts
> +        gap: theme.spacing(1),
Наверное, нужно установить некий порог

2022-08-01 05:53 UTC, perevezencev commented on packages/ui/src/IconButton/IconButton.tsx
> +import { StyledIconButton } from './styled';
Пофикшено

2022-08-01 05:53 UTC, perevezencev commented on packages/ui/src/hooks/useLocalStorage.ts
> +export { useLocalStorage } from 'react-use';
Пофикшено

2022-08-01 05:53 UTC, perevezencev commented on packages/ui/src/Tooltip/Tooltip.tsx
> +        placement={placement} {...restProps}>{children}</StyledTooltip>
Пофикшено

2022-08-01 13:08 UTC, AndTem requested changes

2022-08-01 13:08 UTC, AndTem commented on packages/ui/src/NavMenu/NavMenuItemButton/NavMenuItemButton.tsx
> +  opened?: boolean;
opened не используется

2022-08-01 13:08 UTC, AndTem commented on packages/ui/src/NavMenu/NavMenuItemButton/NavMenuItemButton.tsx
> +  opened?: boolean;
То есть не прокидывается нигде

2022-08-01 13:08 UTC, AndTem commented on packages/ui/src/NavMenu/NavMenu.tsx
> +export const NavMenu = forwardRef<HTMLUListElement, NavMenuProps>(
Не хватает дефолтного story

2022-08-01 13:08 UTC, AndTem commented on packages/ui/src/DashboardLayout/Header/styled.tsx
> +  padding: ${({ theme }) => theme.spacing(2, 3)};
styles файл
https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3527770446/Styled+components

2022-08-01 13:08 UTC, AndTem commented on packages/ui/src/DashboardLayout/styled.tsx
> +      [main-start]    "sidebar main" 1fr  [main-end] / auto 1fr
styles файл

2022-08-01 13:08 UTC, AndTem commented on packages/ui/src/DashboardLayout/Sidebar/styles.ts
> +  min-width: ${({ collapsedIn }) => {
для "чистоты" функцию лучше вынести

2022-08-01 13:08 UTC, AndTem commented on packages/ui/src/DashboardLayout/Sidebar/styles.ts
> +  min-width: ${({ collapsedIn }) => {
или сделать через тернарник

2022-08-01 13:08 UTC, AndTem commented on packages/ui/src/DashboardLayout/Sidebar/Sidebar.tsx
> +export type SidebarProps = {
не хватает jsdoc (используется потребителем компонент)

2022-08-01 13:08 UTC, AndTem commented on packages/ui/src/DashboardLayout/Sidebar/Sidebar.tsx
> +    const [collapsedIn, setCollapsedIn] = useState(savedCollapsedIn ?? true);
useToggle из react-use подойдет

2022-08-01 13:08 UTC, AndTem commented on packages/ui/src/DashboardLayout/Sidebar/SidebarToggler/styled.ts
> +export const SidebarTogglerRoot = styled(SidebarTogglerButton)`
styles файл

2022-08-01 13:08 UTC, AndTem commented on packages/ui/src/DashboardLayout/Sidebar/SidebarToggler/SidebarToggler.tsx
> +  onChange: () => void;
onToggle кажется более подходит

2022-08-01 13:08 UTC, AndTem commented on packages/ui/src/DashboardLayout/Sidebar/SidebarToggler/SidebarToggleButton/styled.ts
> +  gap: 0;
styles файл

2022-08-01 16:59 UTC, perevezencev commented on packages/ui/src/NavMenu/NavMenuItemButton/NavMenuItemButton.tsx
> +  opened?: boolean;
<img width="790" alt="image" src="https://user-images.githubusercontent.com/5954104/182202988-8d14d538-b6d8-438c-9ec0-a99201a3a242.png">
Используется

2022-08-01 17:00 UTC, perevezencev commented on packages/ui/src/NavMenu/NavMenu.tsx
> +export const NavMenu = forwardRef<HTMLUListElement, NavMenuProps>(
Не понял, что за story?

2022-08-01 17:02 UTC, perevezencev commented on packages/ui/src/NavMenu/NavMenuItem.tsx
> +import {
Вроде договаривались, что выносим в отельную директорию, если компонент сложный (т.е. у него есть свои стили/хуки/константы etc)?!

2022-08-01 17:17 UTC, perevezencev commented on packages/ui/src/ListItem/styled.ts
> +    background: #f4f4fb;
Этого цвета нет в теме. Там стоит комментарий на этот счет.

2022-08-01 17:29 UTC, perevezencev commented on packages/ui/src/DashboardLayout/Sidebar/Sidebar.tsx
> +export type SidebarProps = {
Пофикшено

2022-08-02 07:36 UTC, perevezencev commented on packages/ui/src/DashboardLayout/Header/styled.tsx
> +  padding: ${({ theme }) => theme.spacing(2, 3)};
Пофикшено

2022-08-02 07:36 UTC, perevezencev commented on packages/ui/src/DashboardLayout/styled.tsx
> +      [main-start]    "sidebar main" 1fr  [main-end] / auto 1fr
Пофикшено

2022-08-02 07:36 UTC, perevezencev commented on packages/ui/src/DashboardLayout/Sidebar/styles.ts
> +  min-width: ${({ collapsedIn }) => {
Пофикшено

2022-08-02 07:36 UTC, perevezencev commented on packages/ui/src/DashboardLayout/Sidebar/Sidebar.tsx
> +    const [collapsedIn, setCollapsedIn] = useState(savedCollapsedIn ?? true);
Пофикшено

2022-08-02 07:37 UTC, perevezencev commented on packages/ui/src/DashboardLayout/Sidebar/SidebarToggler/SidebarToggler.tsx
> +  onChange: () => void;
Пофикшено

2022-08-02 07:37 UTC, perevezencev commented on packages/ui/src/DashboardLayout/Sidebar/SidebarToggler/SidebarToggleButton/styled.ts
> +  gap: 0;
Пофикшено

2022-08-02 07:37 UTC, perevezencev commented on packages/ui/src/ListProvider/types.ts
> +export type ListContextType = {
Пофикшено

2022-08-02 07:37 UTC, perevezencev commented on packages/ui/src/ListItemText/styled.ts
> +export const StyledListItemText = styled(ListItemText)<StyledListItemTextProps>`
Пофикшено

2022-08-02 07:37 UTC, perevezencev commented on packages/ui/src/List/styled.ts
> +export const StyledList = styled(MuiList)<ListProps>`
Пофикшено

2022-08-02 07:37 UTC, perevezencev commented on packages/ui/src/List/List.tsx
> +const COLLAPSED_SIZE = 60;
Пофикшено

2022-08-02 09:57 UTC, AndTem commented on packages/ui/src/NavMenu/NavMenuItem.tsx
> +import {
Нет, у нас под каждый компонент, утилу, хук отдельная дирекция не зависимо от содержимого

2022-08-03 10:44 UTC, AndTem commented on packages/ui/src/NavMenu/NavMenu.tsx
> +export const NavMenu = forwardRef<HTMLUListElement, NavMenuProps>(
Storybook

2022-08-03 11:56 UTC, perevezencev commented on packages/ui/src/NavMenu/NavMenuItem.tsx
> +import {
Пофикшено

2022-08-03 11:56 UTC, perevezencev commented on packages/ui/src/NavMenu/NavMenu.tsx
> +export const NavMenu = forwardRef<HTMLUListElement, NavMenuProps>(
Пофикшено

2022-08-03 12:37 UTC, AndTem approved these changes

2022-08-03 12:43 UTC, m-av97 approved these changes
Ф

2022-08-05 07:30 UTC, AndTem commented
В Sidebar у разворачивая nav и items разный тайминг. Из-за этого текст "доезжает" уже после полного открытия nav

2022-08-05 07:32 UTC, perevezencev commented
Сhromatic: https://www.chromatic.com/pullrequest?appId=61baeff6f06230003a88ef8a&number=337

Storybook: https://61baeff6f06230003a88ef8a-tkkfwuwnwe.chromatic.com/?path=/story/components-dashboardlayout--edo

StorybookFS: https://61baeff6f06230003a88ef8a-tkkfwuwnwe.chromatic.com/iframe.html?args=&id=components-dashboardlayout--edo&viewMode=story

2022-08-10 14:56 UTC, Astral-design approved these changes

2022-08-10 15:12 UTC, AndTem commented
> В Sidebar у разворачивая nav и items разный тайминг. Из-за этого текст "доезжает" уже после полного открытия nav

@perevezencev up

2022-08-16 06:34 UTC, perevezencev commented
Пофиксил

2022-08-16 07:03 UTC, merged