feat(UIKIT-350,ui,BackdropStack): Реализация абстрактного компонента BackdropStack
kaluga-astral/frontend pull request #354
Opened 2022-08-15 07:07 UTC by Ofigelov

Решил в название не добавлять `Manager`, показалось что слишком многословно получается.

2022-08-15 07:28 UTC, AndTem commented
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/23665108/184593862-a1aee578-403a-46c4-9622-ac513d42b481.png">
Storybook не отображает внутренности внешнего компонента. Помести внутренности DialogExample прямо в рендер story

2022-08-16 06:15 UTC, perevezencev commented on packages/ui/src/BackdropStack/BackdropStack.stories.tsx
> +const AutoCompleteExample = ({ index }: IndexedProps) => {
Autocomplete

2022-08-16 06:15 UTC, perevezencev commented on packages/ui/src/BackdropStack/BackdropStack.stories.tsx
> +type IOption = {
Option

2022-08-16 06:15 UTC, perevezencev commented on packages/ui/src/BackdropStack/BackdropStack.stories.tsx
> +  const { handleClose, handleOpen } = useBackdropStackToggle(
Мб просто `useBackdropStack`?

2022-08-16 06:15 UTC, perevezencev commented on packages/ui/src/BackdropStack/BackdropStack.stories.tsx
> +          <SelectExample index={0} />
Для чего тут нужны index?

2022-08-16 06:15 UTC, perevezencev commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +export const BackdropStackContext = createContext<StackOptions>({
Если пользователь этого хука не обернет все в BackdropStackProvider то будут вызваны эти методы, что может спровоцировать странные ошибки.
Предлагаю тут либо завести некий класс c с конкретной реализациий этих методов
```
class BackdropStackManager {
   push() { ... }
   pop() { ... }
   clean() { ... }
   remove() { ... }
}
```
и передавать его "по ссылке"
либо же передать в defaultValue = null и хэндлить это в `BackdropStackProvider` и там же выдавать пользователю ошибку.

2022-08-16 06:15 UTC, perevezencev commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  const stack = useRef<string[]>([]);
useMemo

2022-08-16 06:15 UTC, perevezencev commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  const nextIdToClose = useRef<string | null>(null);
Если выберешь путь с BackdropStackManager то это все можно будет инкапсулировать внутри класса. Это позволит удобно написать юниты

2022-08-16 06:15 UTC, perevezencev commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +    setTimeout(() => {
Зачем тут setTimeout?

2022-08-16 07:01 UTC, Astral-design commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +    setTimeout(() => {
Реализация закрытия  компонента select/ autocomplete и тд внутри модального окна не соответствует логике задачи
текущая реализация: при открытии autocomplete и клике вне модального окна закрывается модальное окно.
требуемая реализация: при открытии autocomplete и клике вне модального окна закрывается select, при повторном клике вне модального окна закрывается модальное окно.

2022-08-16 08:31 UTC, Ofigelov commented on packages/ui/src/BackdropStack/BackdropStack.stories.tsx
> +  const { handleClose, handleOpen } = useBackdropStackToggle(
Мне кажется без Toggle постфикса будет сложновато понять какой функционал нам предоставляется.

2022-08-16 08:32 UTC, Ofigelov commented on packages/ui/src/BackdropStack/BackdropStack.stories.tsx
> +          <SelectExample index={0} />
для создания уникального айдишника, который будет попадать в BackdropStack

2022-08-16 08:34 UTC, Ofigelov commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +export const BackdropStackContext = createContext<StackOptions>({
сейчас же на заглушке стоять пустые функции, и если не будет провайдера, то тогда будет работать как будто никакого BackdropStack нету

2022-08-16 08:37 UTC, Ofigelov commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  const stack = useRef<string[]>([]);
useMemo не гарантирует что значение не изменится, следовательно в крайних кейсах это может вызвать проблемы
https://ru.reactjs.org/docs/hooks-reference.html#usememo
![image](https://user-images.githubusercontent.com/59384103/184835761-f96e6613-bcc8-46b8-a671-065446d35560.png)

2022-08-16 08:43 UTC, Ofigelov commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +    setTimeout(() => {
> Зачем тут setTimeout?

это в некотором роде дебаунс на минималках, клик снаружи всплывает, и синхронно вызывается удаление из стека, и так как порядок соблюден, код успешно исполняется, и мы получаем тоже самое поведение, которое надо избежать.

я пробовал использовать дебаунс лодаша, но его проблема в том, что исполняется последняя вызванная функция, т.е. с последними запрошенными аргументами, остальные игнорируются. А надо чтобы исполнялась именно первая, а остальные вызовы игнорировались бы.

2022-08-16 08:59 UTC, Ofigelov commented on packages/ui/src/BackdropStack/hooks/useBackdropStackModalToggle/useBackdropStackModalToggle.ts
> +      reason === 'escapeKeyDown' || (reason === 'backdropClick' && pop(id));
Вынес значения в union type, потому что этот метод будет скармливаться диалогу от mui, и там с енамом могут быть проблемы в типах.

2022-08-18 06:13 UTC, Ofigelov commented
Перед тем как создать ишую в `mui`, я решил дополнительно по исследовать как работает диалог и автокомплит под капотом. Обнаружил, что автокомплит закрывается по эвенту `blur` а не `ClickAwayListener`, а еще клик по бэкдропу модалки под капотом работает просто по нативному реактовому `onClick`. 

Т.е. наш первоначальный вывод о `mousedown` и `mouseup` эвентах не верен.

[Поисследовав](https://learn.javascript.ru/mouse-events-basics#poryadok-sobytiy) и поэксперементировав с эвентами клика, блюра, я пришел к выводу, что последовательность вызовов эвентов выглядит так:

1. mousedown
2. blur
3. mouseup
4. click

эдакий `цикл клика`

т.е. `blur` всегда будет вызываться после `mousedown`, опираясь на это, я обновил логику поведения метода `pop`.

`mousedown` будет генерировать свой уникальный id, означающий весь `цикл клика`.

при первом срабатывании `pop` запоминаем текущий `id` цикла клика.
при последующем вызове проверяем причину вызова, если это backdropClick и текущий `id` `цикла клика` не изменился, то игнорируем.

2022-08-18 12:27 UTC, Astral-design approved these changes

2022-09-01 12:07 UTC, StanislavDa approved these changes

2022-09-07 07:17 UTC, AndTem requested changes

2022-09-07 07:17 UTC, AndTem commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +class BackdropStackManager {
1. У тебя BackdropStackManager не компонент, поэтому файл должен быть не .tsx
2. В клиентском коде у тебя используется не этот класс, а хук, поэтому BackdropStackManager скорее внутри хука, а не наоборот

2022-09-07 07:17 UTC, AndTem commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  | string;
У тебя сейчас reason может быть любой строкой. Так и задумано?

2022-09-07 07:17 UTC, AndTem commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +export type Reasons =
Reason - в единственном числе

2022-09-07 07:17 UTC, AndTem commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +type PopFunc = (id: PopId, reason?: Reasons) => boolean;
Нет смысла выносить тип для функции, она ведь не переисользуется

2022-09-07 07:17 UTC, AndTem commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  private previousPopInfo: PopTuple = ['', ''];
С ходу задумка не понятно. Необходим комментарий

2022-09-07 07:17 UTC, AndTem commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  private currentPointerId: PointerId = '';
Почему не string | null?

2022-09-07 07:17 UTC, AndTem commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  constructor() {
Внутри класса не должно быть завязок на браузер.
В таком варианте у тебя при использовании SSR будет ошибка.
Все взаимодействие с браузером должно быть вынесено в хук

2022-09-07 07:17 UTC, AndTem commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  private checkOnBackdropAndBlurCombination = (reason?: Reasons): boolean => {
checkOn - достаточно просто check

2022-09-07 07:25 UTC, Ofigelov commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  | string;
незнаю где взять отсальные причины закрытия, и не уверен нужно ли.

2022-09-07 07:27 UTC, AndTem commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  | string;
Не нужно, поэтому убери string

2022-09-07 07:29 UTC, Ofigelov commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  private currentPointerId: PointerId = '';
чтобы не делать лишних проверок на соответствие типов, а пустая строка по falsy норм отбивается

2022-09-07 07:32 UTC, AndTem commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  private currentPointerId: PointerId = '';
Все инварианты должны быть предусмотрены на уровне типизации.
У тебя здесь неявность появляется, как будто  currentPointerId есть всегда, но это не так

2022-09-07 07:43 UTC, Ofigelov commented on packages/ui/src/BackdropStack/hooks/useBackdropStackToggle/useBackdropStackToggle.ts
> +  const [isOpened, setOpened] = useState(false);
мне кажется не надо давать в хуке подменять поведение хука, тогда в нем(в хуке) смысла нету, да и логика хука сломается, если нужно что то поменять в бизнес логике, то тогда надо реализовывать отдельный кастомный хук с бизнес логикой, используя там инстанс класса `BackdropStackManager`.

2022-09-07 07:44 UTC, Ofigelov commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +class BackdropStackManager {
1. поправлю
2. думаю стоит оставить инстанс класса тут, чтобы можно было реализовать бизнес логику

2022-09-07 07:57 UTC, Ofigelov commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  constructor() {
а если просто добавить `?` в `document.addEventListener`, т.е. `document?.addEventListener`?

2022-09-07 08:01 UTC, AndTem commented on packages/ui/src/BackdropStack/hooks/useBackdropStackToggle/useBackdropStackToggle.ts
> +  const [isOpened, setOpened] = useState(false);
Понял твою задумку.
Теперь понятно почему toggle в названии.
Добавь описание к хуку, что он хранит стейт и управлять им не умеет

2022-09-07 08:39 UTC, Ofigelov commented on packages/ui/src/BackdropStack/hooks/useBackdropStackToggle/useBackdropStackToggle.ts
> +  const [isOpened, setOpened] = useState(false);
сделано

2022-09-07 08:52 UTC, AndTem commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  constructor() {
Судя по всему без привязки к pointer этот сервис бесполезен.
Сделай лучше функцию init, которая будет содержать тоже самое, что и constructor сейчас.
А в хуке init будет вызываться в useEffect.

P.S. надо добавить еще коммент зачем тебе привязка к pointer

2022-09-07 09:02 UTC, Ofigelov commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  constructor() {
а где он должен быть полезен кроме как в браузере? при ssr ломаться не будет, гидратация пройдет успешно.
а что нам даст перенесение инициализации в хук?

2022-09-07 09:04 UTC, Ofigelov commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +class BackdropStackManager {
зачем две директории? это же по сути один компонент

2022-09-09 07:51 UTC, AndTem commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +class BackdropStackManager {
У нас в корне лежат react компоненты, а это не компонент.
Хук должен быть в hooks, а Manager в services

2022-09-09 07:52 UTC, AndTem commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +  constructor() {
Ок, оставляем в constructor

2022-09-12 07:11 UTC, AndTem commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +class BackdropStackManager {
Up

2022-09-12 17:46 UTC, Ofigelov commented on packages/ui/src/BackdropStack/BackdropStack.tsx
> +class BackdropStackManager {
сделано

2022-09-13 06:43 UTC, AndTem approved these changes

2022-09-13 11:00 UTC, closed without merging