feat(UIKIT-307,ui,Typography): Добавлен пропс color
kaluga-astral/frontend pull request #356
Opened 2022-08-18 12:16 UTC by StanislavDa

2022-08-18 12:22 UTC, m-av97 commented on packages/ui/src/Typography/Typography.tsx
> +    return (color && TypographyColors[color]) || color;
Можно же просто TypographyColors[color] ?? color

2022-08-18 12:25 UTC, StanislavDa commented on packages/ui/src/Typography/Typography.tsx
> +    return (color && TypographyColors[color]) || color;
тс ругается, т.к color может быть undefined
`TS2538: Type 'undefined' cannot be used as an index type.`

2022-08-18 12:30 UTC, Astral-design approved these changes

2022-08-18 13:47 UTC, m-av97 commented on packages/ui/src/Typography/Typography.tsx
> +    return (color && TypographyColors[color]) || color;
Ааа, все

2022-08-18 13:49 UTC, m-av97 approved these changes

2022-08-18 13:54 UTC, perevezencev approved these changes

2022-08-18 13:54 UTC, AndTem requested changes

2022-08-18 13:55 UTC, AndTem commented on packages/ui/src/Typography/constants.ts
> +export enum TypographyColors {
[правило](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3665920106#%D0%92%D1%81%D0%B5%2C-%D1%81%D0%B2%D1%8F%D0%B7%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%BC-%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D0%B8%2C-%D0%BD%D0%B0%D1%85%D0%BE%D0%B4%D1%8F%D1%82%D1%81%D1%8F-%D0%B2-%D0%B4%D0%B8%D1%80%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%B8-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0.)

2022-08-19 10:47 UTC, AndTem requested changes

2022-08-19 10:47 UTC, AndTem commented on packages/ui/src/Typography/Typography.stories.tsx
> +      <Typography color="success" variant="h1" paragraph>
Не хватает ещё демонстрации textSecondary

2022-08-19 10:47 UTC, AndTem commented on packages/ui/src/Typography/types.ts
> +  color?: TypographyColor | ((theme: Theme) => string) | string;
| string быть не должно. Это убивает типизацию

2022-08-19 11:12 UTC, AndTem approved these changes

2022-08-19 11:14 UTC, merged