doc(UIKIT-255,ui): Реализован storybook в соответствии с дизайном для Button
kaluga-astral/frontend pull request #361
Opened 2022-08-29 10:17 UTC by StanislavDa

2022-08-29 10:24 UTC, AndTem commented
Необходимо при демонстрации кейсов учитывать адаптив (на маленьких экранах не переносятся кнопки)

2022-08-29 10:25 UTC, AndTem requested changes

2022-08-29 10:25 UTC, AndTem commented on packages/ui/src/Button/Button.stories.tsx
> +    <div style={{ padding: '32px 0', background: '#FAFBFC' }}>
Вынеси компонент для демонстрации кейсов, чтобы его можно было переиспользовать (с title и description)

2022-08-29 10:26 UTC, StanislavDa commented on packages/ui/src/Button/Button.stories.tsx
> +    <div style={{ padding: '32px 0', background: '#FAFBFC' }}>
внутри .stories.tsx или куда-то выше?

2022-08-29 10:28 UTC, AndTem commented on packages/ui/src/Button/Button.stories.tsx
> +    <div style={{ padding: '32px 0', background: '#FAFBFC' }}>
Выше, чтобы в других местах тоже можно было переиспользовать. Можешь создать директорию docs и там это определить (наружу только не экспортам эти компоненты)

2022-08-29 10:30 UTC, StanislavDa commented on packages/ui/src/Button/Button.stories.tsx
> +    <div style={{ padding: '32px 0', background: '#FAFBFC' }}>
> Можешь создать директорию docs и там это определить (наружу из пакета только не экспортам эти компоненты)

Если typedoc подрубим, он будет генерить приколы в docs, не будет потом проблем?)

2022-08-29 10:39 UTC, AndTem commented on packages/ui/src/Button/Button.stories.tsx
> +    <div style={{ padding: '32px 0', background: '#FAFBFC' }}>
Если экспортить из пакета не будем ничего связанного с docs, то и проблем не будет

2022-08-29 11:53 UTC, AndTem commented on packages/ui/src/docs/StorybookExampleTemplate.tsx
> +import { ReactNode, useMemo } from 'react';
Не забываем про style guide. Под каждый компонент своя директория.
И не хватает индексного файла для docs

2022-08-29 11:55 UTC, AndTem requested changes

2022-08-29 11:55 UTC, AndTem commented on packages/ui/src/docs/StorybookExampleTemplate.tsx
> +  subtitle = [],
Не description?

2022-08-29 11:55 UTC, AndTem commented on packages/ui/src/docs/StorybookExampleTemplate.tsx
> +        <Grid container spacing={4} {...gridProps}>
Думаю, что лишнее, можно при в самих stories юзать то, что нужно сейчас

2022-08-29 12:47 UTC, AndTem commented on packages/ui/src/Button/Button.stories.tsx
> +      description={[
descriptionLшst кажется. А нужен там массив вообще?

2022-08-29 13:03 UTC, StanislavDa commented on packages/ui/src/Button/Button.stories.tsx
> +      description={[
Есть моменты, где несколько абзацев идет перед демкой компонента

2022-08-29 13:07 UTC, AndTem approved these changes

2022-08-31 10:42 UTC, Astral-design commented
- Добавить обводку для фона под кнопками: Толщина 1px, цвет Gray300(#DDE2E8)
- Добавить пример использования
- Поправить шрифт кнопок. Должно быть font-weight: 500;
- Поправить цвет красного бейджа на кнопке Status/Error 800 (#F24646)
- Проверить ширину контента. Лучше сделать уже, не удобно читать такие длинные строки текста
- Всё тоже относится и к кнопкам с иконкой

2022-09-01 15:10 UTC, AndTem commented on packages/ui/src/Button/Button.stories.tsx
> +      <br />
Почему бы просто для StorybookExampleTemplate не добавить отступы?

2022-09-01 15:11 UTC, AndTem requested changes

2022-09-01 15:11 UTC, AndTem commented on packages/ui/src/Button/Button.stories.tsx
> +    <div style={{ width: matches ? '100%' : '70%' }}>
Этот компонент можно вынести тоже для переиспользования.
<ExampleTemplate>
<ExampleTemplate.Case>
</ExampleTemplate.Case>
</ExampleTemplate>

А ExampleTemplate решает какая ширина у него и добавляет через грид отсутпы между кейсами

2022-09-19 07:15 UTC, AndTem approved these changes

2022-09-19 07:22 UTC, merged