feat(UIKIT-185,ui,DataGrid): Изменен внешний вид компонента сортировки. Поправлены шрифты
kaluga-astral/frontend pull request #379
Opened 2022-09-02 11:53 UTC by StanislavDa

2022-09-02 11:57 UTC, AndTem commented
Шрифты в отдельный ПРИВЕТ необходимо вынести

2022-09-02 11:59 UTC, AndTem requested changes

2022-09-02 11:59 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridHeadColumn/styled.tsx
> +import { TableCellProps } from '@mui/material';
Несоответствие [style guide](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3527114889/React+components#%D0%92%D1%81%D0%B5-%D1%81%D1%82%D0%B8%D0%BB%D0%B8-%D0%B4%D0%BB%D1%8F-react-components-%D0%B2%D1%8B%D0%BD%D0%BE%D1%81%D1%8F%D1%82%D1%81%D1%8F-%D0%B2-%D0%BE%D1%82%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D1%84%D0%B0%D0%B9%D0%BB-styles,-%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B9-%D0%BD%D0%B0%D1%85%D0%BE%D0%B4%D0%B8%D1%82%D1%81%D1%8F-%D1%80%D1%8F%D0%B4%D0%BE%D0%BC-%D1%81-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%BC-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0)

2022-09-02 12:41 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridHeadColumn/styles.ts
> +  .MuiSvgIcon-root {
хрупкая верстка получается.
Лучше на svg подвязаться или придумать другой способ стилизации иконки

2022-09-02 12:56 UTC, m-av97 approved these changes

2022-09-02 13:49 UTC, AndTem commented
Сортировка должна работать всегда только для одного столбца, при этом другие должны сбрасываться

2022-09-05 10:06 UTC, StanislavDa commented
> Сортировка должна работать всегда только для одного столбца, при этом другие должны сбрасываться

Разве не будет таких кейсов, где нужна сортировка сразу по нескольким столбцам?

2022-09-05 10:12 UTC, AndTem commented
> > Сортировка должна работать всегда только для одного столбца, при этом другие должны сбрасываться
> 
> 
> 
> Разве не будет таких кейсов, где нужна сортировка сразу по нескольким столбцам?

Это как?

2022-09-05 10:17 UTC, StanislavDa commented
> Это как?
Как сейчас реализовано - отсортировал сразу по 2 столбцам
![image](https://user-images.githubusercontent.com/93906455/188426382-3aecca38-38fb-4ef4-a110-4fc40fe55807.png)

2022-09-05 10:19 UTC, AndTem commented
> > Это как?
> 
> Как сейчас реализовано - отсортировал сразу по 2 столбцам
> 
> ![image](https://user-images.githubusercontent.com/93906455/188426382-3aecca38-38fb-4ef4-a110-4fc40fe55807.png)
> 
> 
> 
> 
> 
> 

Ну как это одновременно отсортировать и по дате и ещё по одному параметру?

2022-09-05 10:21 UTC, StanislavDa commented
> Ну как это одновременно отсортировать и по дате и ещё по одному параметру?

Ну на ао5 при запросах можно передавать custoFilter, в котором можно указать как и по каким столбцам нужна сортировка, к примеру. Хз, если такое поведение точно не нужно, то выпилю)

2022-09-05 10:34 UTC, AndTem commented
> > Ну как это одновременно отсортировать и по дате и ещё по одному параметру?
> 
> 
> 
> Ну на ао5 при запросах можно передавать customFilter, в котором можно указать как и по каким столбцам нужно сортировать, к примеру. Хз, если такое поведение точно не нужно, то выпилю)
> 
> 
> 
> 

Такой кейс должен решаться с помощью других ui элементов. Это не стандартное поведение, которое вызовет у пользователя непонимание

2022-09-05 10:36 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridHeadColumn/styles.ts
> +  .MuiSvgIcon-root {
Up

2022-09-06 05:30 UTC, AndTem requested changes

2022-09-06 05:30 UTC, AndTem commented on packages/ui/src/DataGrid/DataGrid.tsx
>     * Массив сортируемых колонок
Теперь не массив

2022-09-06 05:30 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridHead/DataGridHead.tsx
> +      } else if (isCurrentField && sorting.sort === SortStates.DESC) {
В данном случае нет смысла использовать else if. Достаточно просто if потому, что в предыдущем условии делается return

2022-09-06 08:49 UTC, AndTem approved these changes

2022-09-06 08:53 UTC, merged