feat(UIKIT-407,ui,SwipeableDrawer): Создание компонента SwipeableDrawer
kaluga-astral/frontend pull request #387
Opened 2022-09-07 10:58 UTC by Sergeypro91

Создан новый компонент SwipeableDrawer.

2022-09-07 12:08 UTC, AndTem requested changes

2022-09-07 12:08 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/SwipeableDrawer.tsx
> +} from './styled';
styles - смотри [style guide](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3527114889/React+components#%D0%92%D1%81%D0%B5-%D1%81%D1%82%D0%B8%D0%BB%D0%B8-%D0%B4%D0%BB%D1%8F-react-components-%D0%B2%D1%8B%D0%BD%D0%BE%D1%81%D1%8F%D1%82%D1%81%D1%8F-%D0%B2-%D0%BE%D1%82%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D1%84%D0%B0%D0%B9%D0%BB-styles,-%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B9-%D0%BD%D0%B0%D1%85%D0%BE%D0%B4%D0%B8%D1%82%D1%81%D1%8F-%D1%80%D1%8F%D0%B4%D0%BE%D0%BC-%D1%81-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%BC-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0)

2022-09-07 12:08 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/SwipeableDrawer.tsx
> +  StyleTypography,
[Название компонентов не соответсвует ](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3527114889/React+components#%D0%94%D0%BB%D1%8F-styled-components-%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD-%D0%BF%D1%80%D0%B8%D1%81%D1%83%D1%82%D1%81%D1%82%D0%B2%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BF%D1%80%D0%B5%D1%84%D0%B8%D0%BA%D1%81---%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%80%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%BE%D0%B3%D0%BE-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0)style guide

2022-09-07 12:08 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/SwipeableDrawer.tsx
> +import { SwipeableDrawerProps } from './types';
Смотри [style guide](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3527114889/React+components#Type-props-%D0%B4%D0%BB%D1%8F-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0-%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD-%D0%BD%D0%B0%D1%85%D0%BE%D0%B4%D0%B8%D1%82%D1%81%D1%8F-%D0%B2-%D1%84%D0%B0%D0%B9%D0%BB%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0)

2022-09-07 12:08 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/SwipeableDrawer.tsx
> +      <Global
Что мешает обернуть styled MuiSwipeableDrawer?

2022-09-07 12:08 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/types.ts
> +export interface SwipeableDrawerExtend {
используем type

2022-09-07 12:08 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/types.ts
> +  drawerBleedingTitle: string;
Для всех пропсов должен быть jsdoc

2022-09-07 12:08 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/SwipeableDrawer.tsx
> +  drawerBleedingIcon,
Почему нет дефолтной иконки?

2022-09-07 12:08 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/styled.ts
> +    boxShadow: '0 -1px 16px rgb(7 45 87 / 15%)',
Тени должны браться из темы

2022-09-07 12:08 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/styled.ts
> +    padding: '24px 24px 12px',
Все отступы через spacing

2022-09-07 12:08 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/styled.ts
> +export const StyledDrawerHeader = styled(Box)<{ drawerBleeding: number }>(
Мы используем string template и tagged functions

2022-09-07 12:08 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/styled.ts
> +const isDisplayed = (children: ReactNode) => (children ? 'none' : 'block');
isDisplayed по названию должен возвращать boolean, а у тебя нет

2022-09-07 12:08 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/styled.ts
> +  zIndex: 1,
Почему 1, а не 33?
Все zIndex должны отталкиваться от zIndex, существующих в теме.
Пример: theme.dialog.zIndex + 1

2022-09-08 07:01 UTC, AndTem requested changes

2022-09-08 07:01 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/styles.ts
> +export const SwipeableDrawerHeader = styled(Box)<SwipeableDrawerHeaderProps>`
Не забываем про семантику.
Этот компонент должен быть header

2022-09-08 07:01 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/styles.ts
> +  `calc(100vh - ${drawerBleedingHeight}px * 2)`;
Не понятные вычисления. Нужен коммент

2022-09-08 07:01 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/styles.ts
> +const getMaxHeight = ({
Название мало о чем говорит. Конкретизируй

2022-09-08 08:05 UTC, AndTem commented
У тебя в storybook шторка всегда присутствует на экране сжатая и ее можно вытащить.
А на проекте эта шторка будет открывать только по нажатию на кнопку, а в закрытом виде отсутствовать

2022-09-08 08:23 UTC, Sergeypro91 commented
> У тебя в storybook шторка всегда присутствует на экране сжатая и ее можно вытащить. А на проекте эта шторка будет открывать только по нажатию на кнопку, а в закрытом виде отсутствовать

За функционал скрытия / отображения шапки в выключенном состоянии  "Drawer" отвечает параметр ModalProps={{ keepMounted: false }}.

2022-09-08 08:25 UTC, AndTem commented
> > У тебя в storybook шторка всегда присутствует на экране сжатая и ее можно вытащить. А на проекте эта шторка будет открывать только по нажатию на кнопку, а в закрытом виде отсутствовать
> 
> За функционал скрытия / отображения шапки в выключенном состоянии "Drawer" отвечает параметр ModalProps={{ keepMounted: false }}.

Значит надо его продемонстировать в storybook

2022-09-08 08:25 UTC, AndTem approved these changes

2022-09-08 09:12 UTC, AndTem commented
Можно сливать в текущем варианте, но заводить сразу баг:
При закрытии дергается анимация (сначала уменьшается до 60px, а потом отбельной анимацией полностью скрывается)

2022-09-08 09:22 UTC, AndTem approved these changes

2022-09-08 09:27 UTC, Ofigelov commented on packages/ui/src/SwipeableDrawer/styles.ts
> +  text-overflow: ellipsis;
у [mui компонента](https://mui.com/material-ui/api/typography/#props) `Typography` есть пропс `nowrap`, если его передать, то он генерирует стили для ограничения ширины с добавлением многоточия.

Может стоит тогда тут немного упростить?

2022-09-08 11:42 UTC, AndTem requested changes

2022-09-08 11:42 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/styles.ts
> +  return !ModalProps?.keepMounted && !open
оставь коммент, что тут происходит и зачем

2022-09-08 11:42 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/styles.ts
> +const determineHowSwipeableDrawerTransform = ({
getUnmountTransform не подходит?)

2022-09-08 11:48 UTC, Ofigelov approved these changes

2022-09-08 11:49 UTC, AndTem commented on packages/ui/src/SwipeableDrawer/styles.ts
> +  return !ModalProps?.keepMounted && !open
up

2022-09-08 13:33 UTC, merged