feat(UIKIT-399): Реализован компонент Fab и storybook под него
kaluga-astral/frontend pull request #388
Opened 2022-09-07 12:45 UTC by olewka40

2022-09-07 12:49 UTC, AndTem requested changes

2022-09-07 12:49 UTC, AndTem commented on packages/ui/src/Fab/styled.ts
> +const getBgColor = ({
Нет необходимости делать такую сложную логику с enum. Достаточно просто завязываться на :hover и тп

2022-09-07 12:49 UTC, AndTem commented on packages/ui/src/Fab/constants.ts
> +  SQUARE = 'square',
Зачем? У есть fab, а вариантов нет для него

2022-09-07 12:49 UTC, AndTem commented on packages/ui/src/Fab/styled.ts
> +export const StyledFab = styled(Fab, {
Читай [style guide](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3527114889/React+components#Styled-components)

2022-09-07 12:49 UTC, AndTem commented on packages/ui/src/Fab/types.ts
> +import { FabProps as MuiFabProps } from '@mui/material';
Читай [style guide](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3527114889/React+components#Props)

2022-09-07 12:52 UTC, AndTem commented on packages/ui/src/Fab/index.ts
> +export * from './Fab';
Не хватает импорта из пакета

2022-09-07 12:56 UTC, AndTem commented on packages/ui/src/Fab/Fab.tsx
> +  return <StyledFab {...props} ref={ref} />;
Сделай squer вариант дефолтным

2022-09-07 12:59 UTC, AndTem commented on packages/ui/src/Fab/Fab.tsx
> +export default Fab;
[style guide](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3559522553/Import+export#%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D1%8E%D1%82%D1%81%D1%8F-%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D1%8D%D0%BA%D1%81%D0%BF%D0%BE%D1%80%D1%82%D1%8B)

2022-09-07 13:25 UTC, olewka40 commented on packages/ui/src/Fab/styled.ts
> +const getBgColor = ({
цвета в макете одни , а по дефолту другие, в таком случае как определять нужный цвет? если ты про FabStates

2022-09-07 13:31 UTC, AndTem commented on packages/ui/src/Fab/styled.ts
> +const getBgColor = ({
:active {
    color: ${(theme) => theme.palette.primary.main};
    background: ${(theme)=> theme.palette.primary.main};
  }

2022-09-07 14:04 UTC, olewka40 commented on packages/ui/src/Fab/index.ts
> +export * from './Fab';
в style guid же так же 
![image](https://user-images.githubusercontent.com/35649223/188898545-c561ba7e-5312-4962-b9c6-a88d825b3105.png)

2022-09-07 14:14 UTC, AndTem commented on packages/ui/src/Fab/index.ts
> +export * from './Fab';
Ты из пакета ui не экспортируешь Fab

2022-09-08 08:14 UTC, AndTem requested changes

2022-09-08 08:14 UTC, AndTem commented on packages/ui/src/Fab/styles.ts
> +    if (fabState === FabStates.DEFAULT) {
colors[FabStates.DEFAULT] и никаких if не нужно

2022-09-08 08:14 UTC, AndTem commented on packages/ui/src/Fab/styles.ts
> +  const backGroundColors = {
background

2022-09-08 08:14 UTC, AndTem commented on packages/ui/src/Fab/styles.ts
> +  return '';
Почему пустая строка?
Должен быть дефолтный цвет

2022-09-08 08:14 UTC, AndTem commented on packages/ui/src/Fab/styles.ts
> +  return '';
Почему пустая строка? Должна быть прозрачность

2022-09-08 08:14 UTC, AndTem commented on packages/ui/src/Fab/enums.ts
> +export enum FabVariants {
сделай через union, а то у тебя где то union, а где то enum

2022-09-08 08:14 UTC, AndTem commented on packages/ui/src/Fab/styles.ts
> +  if (props.size === FabSizes.LARGE) {
Зачем дублировать с нижним return?

2022-09-08 08:14 UTC, AndTem commented on packages/ui/src/Fab/Fab.stories.tsx
> +      <Typography variant="h3">Square Type</Typography>
Повнимательнее.
У тебя несоответствие между title и реальностью

2022-09-08 11:20 UTC, olewka40 commented
Добавил еще размер small , предполагаю что он будет 42 пикселя, тк large и medium 62 и 52

2022-09-08 11:36 UTC, AndTem requested changes

2022-09-08 11:36 UTC, AndTem commented on packages/ui/src/Fab/styles.ts
> +  return props.size && sizes[props.size];
у тебя сейчас getSize может вернуть undefined.
sizes[props.size || 'large']

2022-09-08 11:36 UTC, AndTem commented on packages/ui/src/Fab/styles.ts
> +  if (!color) {
Не понял, а почему !color?

2022-09-08 11:38 UTC, olewka40 commented on packages/ui/src/Fab/styles.ts
> +  if (!color) {
потому что изначально, дефолтные значения цвета и бэкграунда другие, и их нужно переопределять,

2022-09-08 11:39 UTC, olewka40 commented on packages/ui/src/Fab/styles.ts
> +  if (!color) {
![image](https://user-images.githubusercontent.com/35649223/189112875-388c12be-ba79-41f4-b0e4-3c87edf3ec74.png)
вот то как должно быть

2022-09-08 11:39 UTC, olewka40 commented on packages/ui/src/Fab/styles.ts
> +  if (!color) {
![image](https://user-images.githubusercontent.com/35649223/189112966-56fc592c-33d4-4e7e-be2e-d8ad4f29bf97.png)
а вот это если не переопределять дефолтные значения

2022-09-08 11:43 UTC, AndTem commented on packages/ui/src/Fab/styles.ts
> +  if (!color) {
А что мешает сделать для color дефолтное значение в props? И тогда не будет такой логики непонятной

2022-09-08 13:38 UTC, AndTem requested changes

2022-09-08 13:38 UTC, AndTem commented on packages/ui/src/Fab/enums.ts
> +  DEFAULT = 'default',
Читай про enum в [style guide](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3571220793/Typescript#%D0%9A%D0%BB%D1%8E%D1%87%D0%B8-%D0%B4%D0%BB%D1%8F-enum-%D0%BE%D0%BF%D0%B8%D1%81%D1%8B%D0%B2%D0%B0%D1%8E%D1%82%D1%81%D1%8F-%D0%B2-PascalCase)

2022-09-08 13:38 UTC, AndTem commented on packages/ui/src/Fab/Fab.tsx
> +    color = 'default',
У нас для обычных кнопок дефолтный цвет - primary.
Давай здесь сделаем также

2022-09-08 14:21 UTC, AndTem approved these changes

2022-09-09 07:47 UTC, AndreyZlobin approved these changes

2022-09-09 07:57 UTC, merged