feat(UIKIT-421): Адаптирован Button под мобильную версию в соответствии с дизайном
kaluga-astral/frontend pull request #391
Opened 2022-09-13 06:39 UTC by olewka40

2022-09-13 06:47 UTC, AndTem requested changes

2022-09-13 06:47 UTC, AndTem commented on packages/ui/src/ButtonBase/styles.ts
> +export const getBreakPoint = ({
Зачем это выделять в отдельную функцию?

2022-09-13 06:47 UTC, AndTem commented on packages/ui/src/ButtonBase/styles.ts
> +  @media screen and (min-width: ${getBreakPoint}) {
Для media query используются функции из темы - https://mui.com/material-ui/customization/breakpoints/#css-media-queries

2022-09-13 06:47 UTC, AndTem commented on packages/ui/src/Button/styles.ts
> +    font-size: 16px;
Все размеры шрифта должны браться их темы

2022-09-13 06:54 UTC, AndTem commented on packages/ui/src/Button/Button.stories.tsx
> +export const MobileButtonShowcase: Story = () => (
А зачем этот отдельный showcase? Все же через media query

2022-09-13 06:56 UTC, olewka40 commented on packages/ui/src/ButtonBase/styles.ts
> +export const getBreakPoint = ({
линтер не даёт закоммитить если делать выражение внутри медиазапроса

2022-09-13 07:00 UTC, olewka40 commented on packages/ui/src/Button/Button.stories.tsx
> +export const MobileButtonShowcase: Story = () => (
для того чтобы красиво было  + кнопки с With Icon оборачиваются в отдельный блок чтобы текст не вылезал за пределы кнопки

2022-09-13 07:53 UTC, olewka40 commented on packages/ui/src/ButtonBase/styles.ts
> +export const getBreakPoint = ({
учитывая комментарии ниже, вопрос снят и проблема решена

2022-09-13 08:32 UTC, AndTem commented on packages/ui/src/Button/Button.stories.tsx
> +export const MobileButtonShowcase: Story = () => (
У нас есть параллельный ПР, где будет красивый storybook, поэтому это лишнее

2022-09-13 14:45 UTC, AndTem approved these changes

2022-09-14 06:45 UTC, Ofigelov commented
хроматик показывает что иконки стали меньше, разве так и должно быть?

https://www.chromatic.com/pullrequest?activeElementId=comparison-test-key-61f8e4cbba513b709bd7f5c2-1200&appId=61baeff6f06230003a88ef8a&number=391&view=changes

2022-09-14 06:47 UTC, AndreyZlobin approved these changes

2022-09-14 06:48 UTC, Ofigelov commented on packages/ui/src/Button/styles.ts
> +export const StyledLoadingButton = styled(LoadingButton, {
по нашему[ стайл гайду](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3527770446/Styled+components#%D0%94%D0%BB%D1%8F-styled-components-%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD-%D0%BF%D1%80%D0%B8%D1%81%D1%83%D1%82%D1%81%D1%82%D0%B2%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BF%D1%80%D0%B5%D1%84%D0%B8%D0%BA%D1%81---%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%80%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%BE%D0%B3%D0%BE-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0), в styles не должно быть имен содержащих `Styled`

2022-09-14 06:50 UTC, olewka40 commented on packages/ui/src/Button/styles.ts
> +export const StyledLoadingButton = styled(LoadingButton, {
@Ofigelov а как ты тогда стилизуешь компоненты?) ButtonLoadingButton так себе смотрится(

2022-09-14 06:51 UTC, olewka40 commented
> хроматик показывает что иконки стали меньше, разве так и должно быть?
> 
> https://www.chromatic.com/pullrequest?activeElementId=comparison-test-key-61f8e4cbba513b709bd7f5c2-1200&appId=61baeff6f06230003a88ef8a&number=391&view=changes

там всё по макетам)

2022-09-14 06:55 UTC, Ofigelov commented
> > хроматик показывает что иконки стали меньше, разве так и должно быть?
> > https://www.chromatic.com/pullrequest?activeElementId=comparison-test-key-61f8e4cbba513b709bd7f5c2-1200&appId=61baeff6f06230003a88ef8a&number=391&view=changes
> 
> там всё по макетам)

иконка 8px на кнопке в 40px?

![image](https://user-images.githubusercontent.com/59384103/190082408-8262d228-a663-4476-808a-df649d7c725a.png)

2022-09-14 06:59 UTC, olewka40 commented
> > > хроматик показывает что иконки стали меньше, разве так и должно быть?
> > > https://www.chromatic.com/pullrequest?activeElementId=comparison-test-key-61f8e4cbba513b709bd7f5c2-1200&appId=61baeff6f06230003a88ef8a&number=391&view=changes
> > 
> > 
> > там всё по макетам)
> 
> иконка 8px на кнопке в 40px?
> 
> ![image](https://user-images.githubusercontent.com/59384103/190082408-8262d228-a663-4476-808a-df649d7c725a.png)

сейчас перепроверю

2022-09-14 08:37 UTC, Ofigelov commented on packages/ui/src/Button/styles.ts
> +export const StyledLoadingButton = styled(LoadingButton, {
`ButtonLoadingWrapper`

2022-09-14 08:51 UTC, AndTem approved these changes

2022-09-14 09:04 UTC, Ofigelov approved these changes

2022-09-14 09:06 UTC, AndreyZlobin approved these changes

2022-09-14 09:07 UTC, merged