chore: Добавлена возможность настройки конфига команды build через аргументы
kaluga-astral/frontend pull request #394
Opened 2022-09-13 12:35 UTC by vinokurov-and

При использовании VS Code в историях компонентов отображаются ошибка 
![image](https://user-images.githubusercontent.com/48560509/189902339-1ad2cef4-d631-4417-a2c9-70fad849232f.png)

Было решено создать отдельный конфиг для сборки проекта

2022-09-13 12:55 UTC, vinokurov-and commented
Папка src добавлена из-за ошибки при сборке

![image](https://user-images.githubusercontent.com/48560509/189906576-ca5c5cd1-ad9e-4c7e-8374-88b1a9fc85c3.png)

2022-09-13 12:58 UTC, vinokurov-and commented
почему падает сборка? На локали всё ок

2022-09-13 14:48 UTC, AndTem requested changes

2022-09-13 14:48 UTC, AndTem commented on commander/constants.js
> +const DEFAULT_CONFIG_PATH = './tsconfig.json';
TSCONFIG

2022-09-13 14:48 UTC, AndTem commented on commander/main.js
> +      build({ config: args.config });
Считаю, что параметризация не нужна.
Просто делаем tsconfig.build везде и все

2022-09-13 14:48 UTC, AndTem commented on packages/ui/package.json
> +    "lint:types": "npm --prefix ../icons run svgr && tsc --noEmit -p ./tsconfig.build.json",
Здесь нужен просто tsconfig.json потому, что мы storybook тоже хотим линтить

2022-09-13 14:53 UTC, AndTem commented on packages/ui/package.json
> +    "lint:types": "npm --prefix ../icons run svgr && tsc --noEmit -p ./tsconfig.build.json",
тест комментария

2022-09-14 08:35 UTC, vinokurov-and commented on commander/main.js
> +      build({ config: args.config });
> Считаю, что параметризация не нужна. Просто делаем tsconfig.build везде и все

но ведь не везде он нужен, зачем плодить лишние конфигурации? для icons там даже различий в конфиге не будет

2022-09-14 12:42 UTC, AndTem commented on commander/main.js
> +      build({ config: args.config });
Для единообразия. Заходишь в репу и видишь, что везде одинаково

2022-09-15 09:29 UTC, vinokurov-and commented
@AndTem некоторые ошибки я добавил в игнор. Либо решать сейчас, либо отдельно?

2022-09-15 10:32 UTC, AndTem requested changes

2022-09-15 10:32 UTC, AndTem commented on packages/ui/src/ContentState/ContentState.stories.tsx
>  import NoCertificates from '@astral/illustrations/src/no-certificates.svg';
В корень ui пакета надо добавить global.d.ts:
declare *.svg { export default string }

2022-09-15 10:33 UTC, AndTem commented
> @AndTem некоторые ошибки я добавил в игнор. Либо решать сейчас, либо отдельно?

Оставлять так, все равно будем под макеты переделывать storybook. Только декларацию для .svg добавь (коммент оставил)

2022-09-15 13:11 UTC, lordniken approved these changes

2022-09-15 13:11 UTC, merged