feat(UIKIT-234,ui,ProductWidget): Добавлен компонент ProductWidget
kaluga-astral/frontend pull request #400
Opened 2022-09-14 12:22 UTC by StanislavDa

2022-09-14 12:32 UTC, AndTem requested changes

2022-09-14 12:32 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidgetContent/ProductWidgetContent.tsx
> +      {!loading && (
У тебя loading может быть false, если ошибка произойдет

2022-09-14 12:32 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidgetContent/ProductWidgetContent.tsx
> +    <ContentWrapper container spacing={1} component="ul">
можно заюзать ContentState

2022-09-14 12:32 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidgetContent/ProductWidgetContent.tsx
> +      <ProductWidgetItem key={product.name} {...product} />
Для списка должен быть ul и li

2022-09-14 12:32 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidgetContent/ProductWidgetContent.tsx
> +  const productsList = useMemo(() => {
Для чего это мемоизировать?

2022-09-14 12:32 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidget.tsx
> +  const [error, setError] = useState('');
Тебе же строка не нужна в error. делай boolean

2022-09-14 12:32 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidget.tsx
> +  const [anchorEl, setAnchorEl] = useState<HTMLButtonElement | null>(null);
useMenu наше не подойдет?

2022-09-14 12:32 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidget.tsx
> +        setError('error');
Здесь как раз пригодился бы captureExeption из ConfigContext

2022-09-14 12:32 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidgetItem/ProductWidgetItem.tsx
> +      <ProductLink href={url}>
А здесь не подходит MenuItem?

2022-09-14 12:32 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidgetItem/ProductWidgetItem.tsx
> +        <Logo src={logoUrl} alt="" color={color} />
Айяяй. Для alt всегда что-то должно быть

2022-09-14 12:34 UTC, StanislavDa commented on packages/ui/src/ProductWidget/ProductWidget.tsx
> +  const [anchorEl, setAnchorEl] = useState<HTMLButtonElement | null>(null);
забыл про этот хук)

2022-09-14 12:34 UTC, StanislavDa commented on packages/ui/src/ProductWidget/ProductWidgetItem/ProductWidgetItem.tsx
> +      <ProductLink href={url}>
а есть смысл тянуть его?

2022-09-14 12:35 UTC, StanislavDa commented on packages/ui/src/ProductWidget/ProductWidgetItem/ProductWidgetItem.tsx
> +        <Logo src={logoUrl} alt="" color={color} />
если картинка не загрузилась, то, например, с name в alt виджет очень коряво смотрится(

2022-09-14 12:36 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidgetItem/ProductWidgetItem.tsx
> +      <ProductLink href={url}>
Почему нет? Переиспользование верстки.
Тут вообще можно полностью Menu юзать кажется

2022-09-14 12:37 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidgetItem/ProductWidgetItem.tsx
> +        <Logo src={logoUrl} alt="" color={color} />
alt не просто так придуман, он нужен для доступности.
Если будет проблема с отображением незагруженных картинок - решим

2022-09-14 12:40 UTC, StanislavDa commented on packages/ui/src/ProductWidget/ProductWidgetItem/ProductWidgetItem.tsx
> +        <Logo src={logoUrl} alt="" color={color} />
некрасиво же)
<img width="346" alt="image" src="https://user-images.githubusercontent.com/93906455/190156226-96739928-67ca-4c9a-bfc1-31b48b78a4ec.png">

2022-09-14 12:44 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidgetItem/ProductWidgetItem.tsx
> +        <Logo src={logoUrl} alt="" color={color} />
Это крайний кейс

2022-09-14 12:45 UTC, AndTem commented
Отсутсвует storybook для компонента по макетам:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/23665108/190157205-bd470976-46b4-49b2-ac9e-6b3cb7280d20.png">

2022-09-19 10:34 UTC, AndTem requested changes

2022-09-19 10:34 UTC, AndTem commented on packages/ui/src/DashboardLayout/Header/Header.tsx
> +import React, { forwardRef } from 'react';
Зачем делать импорт реакта?

2022-09-19 10:34 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidgetContent/ProductWidgetContent.tsx
> +  products: Array<{
У тебя уже определён этот тип, но здесь он почему то руками заново определяется

2022-09-19 10:34 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidgetContent/ProductWidgetContent.tsx
> +        // TODO: imgSrc обязательный параметр, а в title не засунуть текст с иконкой(
Создай задачу в jira и здесь ссылку на неё оставь

2022-09-19 10:34 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidgetContent/ProductWidgetContent.tsx
> +  const productsList = products.map((product) => (
Это можно спокойно делать в jsx без выноса в константу

2022-09-19 10:34 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidget.stories.tsx
> +        <ProductWidget getProducts={handleGetProducts} />
Давай весь этот компонент переименуем в ProductSwitcher. Более понятное название

2022-09-19 10:35 UTC, AndTem requested changes

2022-09-19 10:35 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidget.tsx
> +      } catch (e) {
Не хватает пробросать ошибки в captureException

2022-09-19 10:39 UTC, StanislavDa commented on packages/ui/src/DashboardLayout/Header/Header.tsx
> +import React, { forwardRef } from 'react';
ide подчеркивает, мб выключить это можно как-то?
![image](https://user-images.githubusercontent.com/93906455/191000135-6296321f-e305-48d6-9bab-16d56cc5321d.png)

2022-09-19 10:40 UTC, StanislavDa commented on packages/ui/src/ProductWidget/ProductWidgetContent/ProductWidgetContent.tsx
> +  products: Array<{
мб вынести тип WidgetProduct в types.ts?

2022-09-19 10:47 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidgetContent/ProductWidgetContent.tsx
> +  products: Array<{
Можно

2022-09-19 10:48 UTC, AndTem commented on packages/ui/src/DashboardLayout/Header/Header.tsx
> +import React, { forwardRef } from 'react';
Пиши в чат

2022-09-19 10:50 UTC, StanislavDa commented on packages/ui/src/ProductWidget/ProductWidget.tsx
> +      } catch (e) {
мб как-то доработать captureException? в try-catch error - unknown, а captureException сейчас требует данные с определенными типами

2022-09-19 10:52 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidget.tsx
> +      } catch (e) {
Он должен принимать объект error. Конечно надо доработать

2022-09-19 10:56 UTC, StanislavDa commented on packages/ui/src/ProductWidget/ProductWidget.tsx
> +      } catch (e) {
Получается, в ConfigProvider:
`captureException: (error: Error) => void`
В рамках этой задачи можно или в отдельном пре?

2022-09-19 10:57 UTC, StanislavDa commented on packages/ui/src/ProductWidget/ProductWidget.tsx
> +      } catch (e) {
Но тогда в try-catch все равно придется что-то придумывать. error из try-catch же unknown

2022-09-19 11:02 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidget.tsx
> +      } catch (e) {
В отдельном PR.
Просто скопируй интерфейс из sentry

2022-09-19 11:41 UTC, StanislavDa commented on packages/ui/src/ProductWidget/ProductWidget.tsx
> +      } catch (e) {
![image](https://user-images.githubusercontent.com/93906455/191009276-0c9db3a2-1a38-43d3-bba8-fbb3ed8e1f93.png)
у нас нельзя использовать any, а CaptureContext тип из Sentry

2022-09-19 11:45 UTC, AndTem commented on packages/ui/src/ProductWidget/ProductWidget.tsx
> +      } catch (e) {
Сделай eslint-disable и все

2022-09-20 09:25 UTC, AndTem requested changes

2022-09-20 09:25 UTC, AndTem commented on packages/ui/src/ProductSwitcher/ProductSwitcher.tsx
> +        captureException?.(error);
Он же в контексте всегда есть

2022-09-20 09:26 UTC, StanislavDa commented on packages/ui/src/ProductSwitcher/ProductSwitcher.tsx
> +        captureException?.(error);
он же необязательным стал недавно

2022-09-20 09:28 UTC, AndTem commented on packages/ui/src/ProductSwitcher/ProductSwitcher.tsx
> +        captureException?.(error);
Пропс необязательный, но в контексте ведь дефолтная функция всегда есть и проверять ее повсюду в коде не надо

2022-09-20 09:39 UTC, StanislavDa commented on packages/ui/src/ProductSwitcher/ProductSwitcher.tsx
> +        captureException?.(error);
тогда надо типизацию снова поправить в configProvider:
- у `configContextProps` все параметры сделать `required`
- у `configProviderProps` параметры сделать `Partial<ContextProps>`
- в `ConfigContext.Provider` `value={{ captureException: props.captureException || ((error) => console.error(error))}}`, чтобы useEffect выводил предупреждение, когда captureException не прокинут.
Снова в отдельном пр-е делать?)

2022-09-20 09:44 UTC, AndTem commented on packages/ui/src/ProductSwitcher/ProductSwitcher.tsx
> +        captureException?.(error);
Да можешь сразу здесь. Чтобы не было окна между релизами

2022-09-20 10:13 UTC, AndTem approved these changes

2022-09-20 12:09 UTC, lordniken approved these changes

2022-09-21 18:48 UTC, Astral-design commented
готово

2022-09-21 18:50 UTC, Astral-design approved these changes

2022-09-21 18:50 UTC, merged