feat(UIKIT-217,ui,DataGrid): Реализовано состояние NoData
kaluga-astral/frontend pull request #404
Opened 2022-09-15 14:32 UTC by Sergeypro91

2022-09-15 15:04 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> +import NoData from '@astral/illustrations/src/no-data.svg';
Делай инлайн svg

2022-09-16 05:29 UTC, AndTem requested changes

2022-09-16 05:29 UTC, AndTem commented on packages/ui/src/DataGrid/DataGrid.stories.tsx
> +  const renderDataGridPlaceholder = (isLoading: boolean) => {
DataGridNoData должен быть инкапсулирован в DataGrid.
Это же очень не удобно

2022-09-16 05:29 UTC, AndTem commented on packages/ui/src/DataGrid/DataGrid.stories.tsx
> +    return isDataPresent ? (
Это условие должно быть внутри DataGrid.
Тебе самому было бы удобно в каждом месте прописывать эти условия?

2022-09-16 05:29 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> +      <StyledDataGridNoData>
Почему везде префикс нормальный, а тут styled

2022-09-16 05:29 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> +const renderBaseNoDataIcon = () => (
Это по факту компонент:
С большой буквы должен быть
Render лишнее

2022-09-16 05:29 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> +  <svg viewBox="0 0 124 124" fill="none" xmlns="http://www.w3.org/2000/svg">
Минифицируй эту svg перед вставкой

2022-09-16 05:31 UTC, AndTem requested changes

2022-09-16 05:31 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> + * @description Рендер иконки отсутствия данных по умолчанию
Не обязательно для каждой функции, которую пишешь делать описание.
Обязательно только для пропсов компонента, который экспортиться из пакета

2022-09-16 05:40 UTC, AndTem requested changes

2022-09-16 05:40 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> +   * @example <DataGridNoData  imgSrc={NoData} />
В example одно, в типах другое. Повнимательней

2022-09-16 05:40 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridNoData/styles.ts
> +export const StyledDataGridNoData = styled.div`
По семантике здесь подходит figure. Не забываем про семантичность

2022-09-16 05:41 UTC, Sergeypro91 commented on packages/ui/src/DataGrid/DataGrid.stories.tsx
> +  const renderDataGridPlaceholder = (isLoading: boolean) => {
Была идея дать возможность пробросить кастомный placeholder или заменить иконку в базовом используя всего одно доп поле пропсов.

2022-09-16 05:44 UTC, AndTem commented on packages/ui/src/DataGrid/DataGrid.stories.tsx
> +  const renderDataGridPlaceholder = (isLoading: boolean) => {
Что мешает сохранить пропс NoDataPlaceholder, но сделать так, чтобы было дефолтное значение

2022-09-16 05:47 UTC, Sergeypro91 commented on packages/ui/src/DataGrid/DataGrid.stories.tsx
> +  const renderDataGridPlaceholder = (isLoading: boolean) => {
В таком случае понадобится два пропса, отдельно для кастомной иконки и кастомного плейсхолдера.

2022-09-16 05:50 UTC, AndTem commented on packages/ui/src/DataGrid/DataGrid.stories.tsx
> +  const renderDataGridPlaceholder = (isLoading: boolean) => {
Зачем?
Оставляешь prop NoDataPlaceholder и делаешь для него дефолтное значение.
Если надо что то изменить, делаешь так, как у тебя сейчас в примере

2022-09-16 06:01 UTC, Sergeypro91 commented on packages/ui/src/DataGrid/DataGrid.stories.tsx
> +  const renderDataGridPlaceholder = (isLoading: boolean) => {
Быть может тогда и для Footer предусмотреть подобную логику ?

2022-09-16 06:10 UTC, AndTem commented on packages/ui/src/DataGrid/DataGrid.stories.tsx
> +  const renderDataGridPlaceholder = (isLoading: boolean) => {
Для футера не нужно дефолтное значение.
Нам может понадобиться таблица без пагинации

2022-09-16 06:13 UTC, Sergeypro91 commented on packages/ui/src/DataGrid/DataGrid.stories.tsx
> +  const renderDataGridPlaceholder = (isLoading: boolean) => {
Мы можем передать туда также null. По хорошему пагинацию нужно переписать, как минимум из-за того что логика самой пагинации не инкапсулирована в компоненте пагинации, и из-за того что сейчас пагинация в принципе ожидает полного перечня данных, а потом уже делает выборку. Не учитывается факт серверной пагинации (что, как правило, мы и делаем в таблицах).

2022-09-16 06:16 UTC, AndTem commented on packages/ui/src/DataGrid/DataGrid.stories.tsx
> +  const renderDataGridPlaceholder = (isLoading: boolean) => {
У нас пагинация может быть разной.
Например, infinite scroll. Поэтому и сделано так, как сейчас.
Также не забывай про braking changes

2022-09-16 06:18 UTC, AndTem commented on packages/ui/src/DataGrid/DataGrid.stories.tsx
> +  const renderDataGridPlaceholder = (isLoading: boolean) => {
Если есть идеи по пагинации - делай задачу в shared и будем обсуждать

2022-09-16 06:35 UTC, Sergeypro91 commented on packages/ui/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> +  <svg viewBox="0 0 124 124" fill="none" xmlns="http://www.w3.org/2000/svg">
Что имеется ввиду под минификацией?

2022-09-16 06:37 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> +  <svg viewBox="0 0 124 124" fill="none" xmlns="http://www.w3.org/2000/svg">
svgo

2022-09-16 06:45 UTC, Sergeypro91 commented on packages/ui/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> +  <svg viewBox="0 0 124 124" fill="none" xmlns="http://www.w3.org/2000/svg">
SVG уже был минифицирован.

2022-09-16 08:04 UTC, AndTem requested changes

2022-09-16 08:04 UTC, AndTem commented on packages/ui/src/DataGrid/DataGrid.tsx
> +   * @example <DataGrid  noDataIcon={NoData} />
у тебя нет пропса noDataIcon для DataGrid

2022-09-16 08:04 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> +  return !loading ? (
Нарушение принципа единственной ответсвенности.
У тебя DataGridNoData просто отображает NoData, а решение когда его нудно отображать должно приниматься выше

2022-09-16 08:04 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> +        <DataGridNoDataTitle variant="h4">{title}</DataGridNoDataTitle>
если юзаешь figure, то должен быть figcaption

2022-09-16 08:17 UTC, Sergeypro91 commented on packages/ui/src/DataGrid/DataGrid.tsx
> +   * @example <DataGrid  noDataIcon={NoData} />
[Sergeypro91](https://github.com/Sergeypro91) [2 hours ago](https://github.com/kaluga-astral/frontend/pull/404#discussion_r972634392) • 
В таком случае понадобится три пропса, отдельно для кастомной иконки, кастомного тайтла и кастомного плейсхолдера.

Member
@[AndTem](https://github.com/AndTem) AndTem [2 hours ago](https://github.com/kaluga-astral/frontend/pull/404#discussion_r972636265)
Зачем?
Оставляешь prop NoDataPlaceholder и делаешь для него дефолтное значение.
Если надо что то изменить, делаешь так, как у тебя сейчас в примере

Вот тут я немного не понял. Так как в итоге, всё же предусмотреть пропс для кастомной иконки, кастомного тайтла?

2022-09-16 08:18 UTC, AndTem commented on packages/ui/src/DataGrid/DataGrid.tsx
> +   * @example <DataGrid  noDataIcon={NoData} />
Код написан верно, а jsdoc некорректный у тебя

2022-09-16 09:39 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> +          <DataGridNoDataTitle variant="h4">{title}</DataGridNoDataTitle>
Лишняя обертка ни к чему. Используй пропс component="figcaption"

2022-09-16 09:40 UTC, AndTem commented on packages/ui/src/DataGrid/DataGrid.tsx
> +  NoDataPlaceholder?: ReactNode;
[style guide](https://astraltrack.atlassian.net/wiki/spaces/FG/pages/3527114889/React+components#%D0%92%D1%81%D0%B5-props-%D1%81-%D0%BC%D0%B0%D0%BB%D0%B5%D0%BD%D1%8C%D0%BA%D0%BE%D0%B9-%D0%B1%D1%83%D0%BA%D0%B2%D1%8B)
Только для футера не меняй, а то упадет компонент в проде

2022-09-16 10:25 UTC, AndTem commented on packages/ui/src/DataGrid/DataGridNoData/styles.ts
> +export const DataGridNoDataFigcaption = styled.figcaption`
У Typography есть пропс: component.
Тебе просто надо было сделать <Typography component="figcaption" />

2022-09-16 10:55 UTC, AndTem approved these changes

2022-09-16 11:24 UTC, AndreyZlobin approved these changes

2022-09-16 11:31 UTC, AndreyZlobin approved these changes

2022-09-16 11:31 UTC, merged