feat(UIKIT-260,ui,ContentState): Реализованы ErrorBoundary и ConfigProvider
kaluga-astral/frontend pull request #405
Opened 2022-09-16 12:06 UTC by StanislavDa

DatePickerProvider заменен ConfigProvider-ом

2022-09-16 12:50 UTC, AndTem requested changes

2022-09-16 12:50 UTC, AndTem commented on packages/ui/src/ContentState/ContentState.tsx
> +  if (isError && customState) {
Зачем ломаешь существующую логику?

2022-09-16 12:50 UTC, AndTem commented on packages/ui/src/ErrorBoundary/ErrorBoundary.tsx
> +        <Grid alignItems="center" justifyContent="center">
Используй Placeholder для отображения ошибки

2022-09-16 12:50 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.stories.tsx
> +    <ConfigProvider captureException={() => {}}>
Кажется, здесь это ни к чему

2022-09-16 12:50 UTC, AndTem commented on packages/ui/src/Placeholder/styles.ts
> +  margin: auto auto ${({ theme }) => theme.spacing(8)};
Это для чего?
Если надо - делай отдельный PR

2022-09-16 12:53 UTC, StanislavDa commented on packages/ui/src/ErrorBoundary/ErrorBoundary.tsx
> +        <Grid alignItems="center" justifyContent="center">
у Placeholder imgSrc обязателен, а в images нет подходящего изображения. И нужно ли оно?

2022-09-16 12:54 UTC, StanislavDa commented on packages/ui/src/ContentState/ContentState.tsx
> +  if (isError && customState) {
Мне показалось, что isCustom лишний флаг, т.к. в сторибуке в него прокидывался флаг isError. 2 флага с одинаковой логикой?

2022-09-16 12:54 UTC, StanislavDa commented on packages/ui/src/Placeholder/styles.ts
> +  margin: auto auto ${({ theme }) => theme.spacing(8)};
webstorm предложил так сократить, не стал сопротивляться)

2022-09-16 12:54 UTC, AndTem commented on packages/ui/src/ErrorBoundary/ErrorBoundary.tsx
> +        <Grid alignItems="center" justifyContent="center">
Понял. Вообще нужен конечно, но пока изображения нет оставим так. Как дизайнеры сделают - отрефакторим

2022-09-16 13:47 UTC, AndTem commented on packages/ui/src/ContentState/ContentState.tsx
> +  if (isError && customState) {
isCustom - для отображения третьего состояния

2022-09-16 13:47 UTC, AndTem commented on packages/ui/src/Placeholder/styles.ts
> +  margin: auto auto ${({ theme }) => theme.spacing(8)};
А, понял

2022-09-16 15:10 UTC, AndTem approved these changes

2022-09-16 15:10 UTC, AndTem commented on packages/ui/src/ConfigProvider/ConfigProvider.tsx
> +export type ConfigContextProps = {
Js doc должен быть здесь

2022-09-19 08:38 UTC, vinokurov-and approved these changes

2022-09-19 08:53 UTC, merged