feat(UIKIT-419,ui,DatePicker): Новая реализация компонента DatePicker
kaluga-astral/frontend pull request #418
Opened 2022-09-28 11:04 UTC by Ofigelov

https://astraltrack.atlassian.net/browse/UIKIT-419

полностью новый компонент DatePicker, без зависимостей от `react-date-picker` и `date-fns`
Я постарался сохранить типы от предыдущего, за исключением типов от `react-date-picker`.

Решение пока что только базовое, без RangePicker и без TimePicker вариаций, но на его базе будет легче сделать нео

2022-09-29 06:27 UTC, AndTem commented
Bug: если открыть пикер и нажать на поповер, то он не закроется с первого раза по нажатию вне поповера

2022-09-29 11:07 UTC, lordniken commented on packages/ui/src/DatePicker/common/components/DateCalendar/components/DateCalendarChevronBtn/styles.ts
> +  width: ${({ theme }) => theme.spacing(8)};
зачем указывать размеры через `spacing`?

2022-09-29 11:08 UTC, Ofigelov commented on packages/ui/src/DatePicker/common/components/DateCalendar/components/DateCalendarChevronBtn/styles.ts
> +  width: ${({ theme }) => theme.spacing(8)};
а как по другому?

2022-09-29 11:12 UTC, Ofigelov commented
> 1. Цвет выбранного дня (если он выбран в предыдщуем/следующем месяце) не верный
ок, поправлю

> 2. Hover для выбранно дня, наверное, лучше убрать (тут лучше с дизайнерами решить).

> 3. При вводе даты с клавиатуры (если у нас указаны min/max ограничения) введеная дата заменяется на минимальную/максимальную. Вроде бы мы решили так не делать, чтобы не подменять данные за пользователя.

Если не ограничивать, то тогда придется обрабатывать кейсы, что пользователю показывается календарь с заблокированными элементами.

Я бы лучше добавил какое нибудь оповещение пользователю, что мы не даем ему просто ввести дату которая вне разрешенных пределов.

> 4. Лучше ручками указать высоту popover, чтобы от месяца к месяцу высота календаря не прыгала.

если захардкодить высоту, то тогда в календарике будут пустоты, а дизайнеры такого не любят, уж лучше пусть высота скачет.

> 5. Нужно поправить header каленадря в соответствии с [дизайном](https://www.figma.com/file/3ghN4WjSgkKx5rETR64jqh/Sirius-Design-System-(%D0%90%D0%9A%D0%A2%D0%A3%D0%90%D0%9B%D0%AC%D0%9D%D0%9E)?node-id=735%3A12817)

Нужно больше конретики, что не так? Заглавная буква месяца?

2022-09-29 11:18 UTC, lordniken commented
> > 1. Цвет выбранного дня (если он выбран в предыдщуем/следующем месяце) не верный
> 
> ок, поправлю
> 
> > 2. Hover для выбранно дня, наверное, лучше убрать (тут лучше с дизайнерами решить).
> 
> Дизайнеры, придите
> 
> > 3. При вводе даты с клавиатуры (если у нас указаны min/max ограничения) введеная дата заменяется на минимальную/максимальную. Вроде бы мы решили так не делать, чтобы не подменять данные за пользователя.
> 
> Если не ограничивать, то тогда придется обрабатывать кейсы, что пользователю показывается календарь с заблокированными элементами.
> 
> Я бы лучше добавил какое нибудь оповещение пользователю, что мы не даем ему просто ввести дату которая вне разрешенных пределов.
> 
> > 4. Лучше ручками указать высоту popover, чтобы от месяца к месяцу высота календаря не прыгала.
> 
> если захардкодить высоту, то тогда в календарике будут пустоты, а дизайнеры такого не любят, уж лучше пусть высота скачет.
> 
> > 5. Нужно поправить header каленадря в соответствии с [дизайном](https://www.figma.com/file/3ghN4WjSgkKx5rETR64jqh/Sirius-Design-System-(%D0%90%D0%9A%D0%A2%D0%A3%D0%90%D0%9B%D0%AC%D0%9D%D0%9E)?node-id=735%3A12817)
> 
> Нужно больше конретики, что не так? Заглавная буква месяца?

3. Тут как раз должная быть валидационная ошибка формы, но если мы перезатираем введеную дату - ошибки не будет, т.к. дата изменится на валидную.
4. В старой реализации и в MUI высота статичная, вроде бы никому это не мешало и при переключении месяцев высота не прыгала. Лучше уточнить у дизайнера.
5. Судя по макету заглавная буква и без `г` в конце.

2022-09-29 11:27 UTC, lordniken commented on packages/ui/package.json
> +    "@mui/base": "5.0.0-alpha.85",
зачем `^` убрал? у нас на этот счет [баг был](https://astraltrack.atlassian.net/browse/UIKIT-231)

2022-09-29 11:30 UTC, Ofigelov commented on packages/ui/package.json
> +    "@mui/base": "5.0.0-alpha.85",
потому что с крышкой у меня webstorm не фунциклирует, и @AndTem сказал убрать крышечку

2022-09-29 11:31 UTC, Ofigelov commented on packages/ui/package.json
> +    "@mui/base": "5.0.0-alpha.85",
а погоди, эту mui, тогда незнаю, вроде сам руками не убирал

2022-09-29 13:19 UTC, Ofigelov commented on packages/ui/src/DatePicker/common/components/DateCalendar/components/DateCalendarChevronBtn/styles.ts
> +  width: ${({ theme }) => theme.spacing(8)};
заменил все похожие места

2022-09-29 13:20 UTC, Ofigelov commented on packages/ui/package.json
> +    "@mui/base": "5.0.0-alpha.85",
вернул крышечки

2022-09-29 13:50 UTC, Ofigelov commented
@lordniken ховер поправил, добавил логики чтобы позволять пользователю вводить любые цифры в маске, останется валидацией выводить сообщения, что пользователь не прав

@Astral-design несколько вопросов

- буква `г` в после номера годоа, можем ли оставить?
- ховер на выбранной дате, кажется что он должен вести себя как то иначе, но совсем без ховера нельзя, т.к. это все еще кликабельный элемент
- что делать с меняющейся высотой календаря при переключении месяца? 
варианты решений что приходят мне в голову:
  - оставить как есть, пускай меняется
  - зафиксировать высоту, но тогда будут появляться пустоты
  - всегда рендерить сетку в 6 * 7, но тогда будут кейсы, что дни следующих месяцев могут заполнять по 2 строчки снизу

2022-09-29 14:37 UTC, lordniken commented on packages/ui/src/DatePicker/common/components/DateCalendar/components/DateCalendarGridBtn/styles.ts
> +    bottom: 4px;
для `top`/`bottom`/`left`/`right` указывается отступ через `spacing`

2022-09-29 14:40 UTC, lordniken commented on packages/ui/src/DatePicker/common/components/DateCalendar/components/DateCalendarGridBtn/styles.ts
> +  color: ${({ theme, isCurrent, isOutOfAvailableRange, selected }) =>
я бы предложил вынести расчет в отдельную функцию

2022-09-29 14:41 UTC, lordniken commented on packages/ui/src/DatePicker/common/components/DateCalendar/components/DateCalendarBtn/DateCalendarBtn.tsx
> +    <Tooltip title={title || ''} disableInteractive>
default value тут не подходит?

2022-09-29 15:10 UTC, Astral-design commented
1. Нужно сделать так чтобы размеры календаря и тд были фиксированными и не скакали, как реализовано в ДС,
2. Если пользователь вводит дату которая не попадает в допустимый диапозон, то нужно конечно дать явно понять пользователю почему эта дата не проставляется. На дизайне сейчас это не заложено, но теперь планируесть доработать сценарий.
3. Да в хедере месеца на дизайне с заглавной буквы

2022-09-30 04:59 UTC, Ofigelov commented on packages/ui/src/DatePicker/common/components/DateCalendar/components/DateCalendarBtn/DateCalendarBtn.tsx
> +    <Tooltip title={title || ''} disableInteractive>
Немогу найти нигде в спецификации как применяется defaultValue для тултипа

Но основной прикол тут в том, что пропс `title` для mui Tooltip принимает только строку, и если эта строка пустая, то тогда не рендерит тултип.

2022-09-30 05:01 UTC, Ofigelov commented on packages/ui/src/DatePicker/common/components/DateCalendar/components/DateCalendarGridBtn/styles.ts
> +    bottom: 4px;
а почему? чем пиксели позиционирования отличаются от пикселей для размеров?
я так понял что `theme.spacing` для отступов, а отступы это паддинги и маргины

2022-09-30 05:29 UTC, Ofigelov commented on packages/ui/src/DatePicker/common/components/DateCalendar/components/DateCalendarGridBtn/styles.ts
> +  color: ${({ theme, isCurrent, isOutOfAvailableRange, selected }) =>
не соглашусь, несколько причин:
- сложность исполнения, придется заводить отдельный хелпер, типизировать, соедния типы темы и компонента, при передаче свойств придется использовать приведение типов, а результат всего лишь значение одного цсс свойства;
- получившийся хелпер не удастся где то переиспользовать, т.к. поведение слишком специфично;
- читаемость не улучшится, а наоборот ухудшится, т.к. ничего служного тут не происходит, а ухудшится из за того, что для понимания придется ходить по хелперам, разбираться что куда и как передается;

2022-09-30 05:34 UTC, AndTem commented on packages/ui/src/DatePicker/common/components/DateCalendar/components/DateCalendarGridBtn/styles.ts
> +    bottom: 4px;
Потому, что spacing используется для: margin, padding, bottom, top, left, right.
Эту информацию в будущем занесу в contributing.md

2022-09-30 05:46 UTC, Ofigelov commented on packages/ui/src/DatePicker/common/components/DateCalendar/components/DateCalendarGridBtn/styles.ts
> +    bottom: 4px;
готово

2022-09-30 06:04 UTC, Ofigelov commented
> 1. Нужно сделать так чтобы размеры календаря и тд были фиксированными и не скакали, как реализовано в ДС,

готово

> 2. Если пользователь вводит дату которая не попадает в допустимый диапозон, то нужно конечно дать явно понять пользователю почему эта дата не проставляется. На дизайне сейчас это не заложено, но теперь планируесть доработать сценарий.

Это будет реализовано в рамках валидации форм, этот компонент не отвечается за валидацию, его задачи:
 - дать пользователю возможность ввести/выбрать дату,
 - не сломаться
 - соответсвовать дизайну

> 3. Да в хедере месеца на дизайне с заглавной буквы

Правки внесени, резултат [перепроверить можно тут](https://61baeff6f06230003a88ef8a-vgtebtzykr.chromatic.com/iframe.html?id=components-datepickers-defaultdatepicker--showcase&viewMode=story)

2022-09-30 06:22 UTC, lordniken commented on packages/ui/src/DatePicker/common/components/DateCalendar/components/DateCalendarBtn/DateCalendarBtn.tsx
> +    <Tooltip title={title || ''} disableInteractive>
я про `title = ''` в деструктуризации выше

2022-09-30 06:25 UTC, lordniken commented on packages/ui/src/DatePicker/common/components/DateCalendar/components/DateCalendarGridBtn/styles.ts
> +  color: ${({ theme, isCurrent, isOutOfAvailableRange, selected }) =>
ИМХО [такой](https://github.com/kaluga-astral/frontend/blob/main/packages/ui/src/Badge/styled.tsx) подход читается проще и результат предсказуемый. Тут не про переиспользование, а скорее инкапсуляцию логики вычисления.

2022-09-30 06:44 UTC, Ofigelov commented on packages/ui/src/DatePicker/common/components/DateCalendar/components/DateCalendarBtn/DateCalendarBtn.tsx
> +    <Tooltip title={title || ''} disableInteractive>
а, понятно, изменил

2022-09-30 06:45 UTC, Ofigelov commented on packages/ui/src/DatePicker/common/components/DateCalendar/components/DateCalendarGridBtn/styles.ts
> +  color: ${({ theme, isCurrent, isOutOfAvailableRange, selected }) =>
Готово. 
Но ИМХО, мне не нравится такой подход, уж очень он не рациональный. 
9 строк вполне себе читаемого кода, раздул в 42.

2022-09-30 08:35 UTC, Astral-design approved these changes

2022-10-03 07:35 UTC, lordniken approved these changes

2022-10-03 10:31 UTC, AndTem commented
Actual:
Если ввожу невалидную дату в инпут, а потом делаю onBlur, то value просто откатывается.
Expected:
Value в инпуте всегда актуальное - если пользователь ввел невалидную дату, то ему должна в форме подсветиться валидация. Никаких откатов значений

2022-10-03 10:55 UTC, Ofigelov commented
> Actual: Если ввожу невалидную дату в инпут, а потом делаю onBlur, то value просто откатывается. Expected: Value в инпуте всегда актуальное - если пользователь ввел невалидную дату, то ему должна в форме подсветиться валидация. Никаких откатов значений

А где ты это воспроизводишь? на последнем хроматике вроде таких проблем нету

2022-10-05 04:15 UTC, Ofigelov commented
> > Actual: Если ввожу невалидную дату в инпут, а потом делаю onBlur, то value просто откатывается. Expected: Value в инпуте всегда актуальное - если пользователь ввел невалидную дату, то ему должна в форме подсветиться валидация. Никаких откатов значений
> 
> А где ты это воспроизводишь? на последнем хроматике вроде таких проблем нету

Пофикшено

2022-10-05 05:09 UTC, StanislavDa approved these changes

2022-10-05 11:24 UTC, AndTem requested changes

2022-10-05 11:24 UTC, AndTem commented on packages/ui/src/DatePicker/common/components/YearPicker/hooks/useYearsGrid/useYearsGrid.ts
> +  for (let i = 0 - YEAR_OFFSET; i < YEARS_IN_GRID - YEAR_OFFSET; i++) {
мемоизация нужна

2022-10-05 11:24 UTC, AndTem commented on packages/ui/src/DatePicker/common/components/YearPicker/hooks/useYearsGrid/useYearsGrid.ts
> +  for (let i = 0 - YEAR_OFFSET; i < YEARS_IN_GRID - YEAR_OFFSET; i++) {
Нужны комментарии в коде

2022-10-05 11:24 UTC, AndTem commented on packages/ui/src/DatePicker/common/constants/monthsInYear.ts
> +export const MONTHS_IN_YEAR = 12;
Достаточно будет просто файла constants.ts для всех констант

2022-10-05 11:24 UTC, AndTem commented on packages/ui/src/DatePicker/common/types/addHelper.ts
> +export type AddHelper = (date: Date, count: number) => Date;
Не уверен, что для этого нужен отдельный тип.
Если хочешь создавать однотипные хелперы - делай фабрику, но думаю что это не к чему.
Все эти функции не прикреплены к пикеры

2022-10-05 11:24 UTC, AndTem commented on packages/ui/src/DatePicker/common/utils/buildIsoDateString/buildIsoDateString.ts
> +  `${zeroPad(year, 4)}-${zeroPad(month, 2)}-${zeroPad(day, 2)}T${zeroPad(
Вынлядит нечитаемо, выноси в константы

2022-10-05 11:24 UTC, AndTem commented on packages/ui/src/DatePicker/common/utils/buildIsoDateString/buildIsoDateString.ts
> + * @description хелпер генерирующий строковую дату в формате ISO
Мы используем термин utils, а не helpers

2022-10-05 11:24 UTC, AndTem commented on packages/ui/src/DatePicker/common/utils/buildIsoDateString/buildIsoDateString.ts
> + * @description опции для генерации даты без смещения по часовому поясу пользователя
Для типов описание jsdoc выглядит иначе, посмотри

2022-10-05 11:24 UTC, AndTem commented on packages/ui/src/DatePicker/common/utils/buildIsoDateString/buildIsoDateString.ts
> +export const buildIsoDateString = ({
А Date.toISOString() не подходит?

2022-10-05 11:24 UTC, AndTem commented on packages/ui/src/DatePicker/common/utils/getBaseDateInRange/useBaseDateInRange.ts
> +export const useBaseDateInRange = ({
это хук, а не утила

2022-10-05 11:24 UTC, AndTem commented on packages/ui/src/DatePicker/common/utils/isDate/isDate.ts
> +export const isDate = (value: unknown): value is Date =>
Ну уверен, что стоит это писать самому. Проще взять из либы

2022-10-05 12:02 UTC, Ofigelov commented on packages/ui/src/DatePicker/common/utils/buildIsoDateString/buildIsoDateString.ts
> +export const buildIsoDateString = ({
нет, потому что стандартный метод преобразует дату в строку, при этом есть неприятный сайд эффект с тем что получаем дату зависимую от часового пояса пользовтеля, а тут создается сразу строковая дата в формате iso.

2022-10-05 12:05 UTC, Ofigelov commented on packages/ui/src/DatePicker/common/utils/addDays/addDays.ts
> +export const addDays: AddHelper = (date, count) =>
Нельзя отказаться от date-fns не заменив методы работы с датой. 
Поэтому как бы да, появился набор утилит необходимый для работы. И они вот они, работают, свои задачи выполняют. Давай тесты для дата пикера сделаем отдельной задачей.

2022-10-05 12:12 UTC, Ofigelov commented on packages/ui/src/DatePicker/common/components/MonthPicker/hooks/buildMonthsGrid/useMonthsGrid.ts
> +  const grid: GridItem<MonthItem>[] = [];
мемоизация будет на компоненте сверху, а при каждом перемещении по календарю это все равно будет рассчитываться заново. Так что мемоизация тут только раздует код.

2022-10-05 12:13 UTC, Ofigelov commented on packages/ui/src/DatePicker/common/components/MonthPicker/hooks/buildMonthsGrid/useMonthsGrid.ts
> +export const useMonthsGrid: GridBuilder<MonthItem> = ({
типы далеко, чтобы унифицировать схожие методы для работы с разными лэйаутами дни
/месяцы/года.

2022-10-05 12:32 UTC, Ofigelov commented on packages/ui/src/DatePicker/common/hooks/useToggle/useToggle.ts
> +import { useState } from 'react';
`useToggle из react-use` не умеет в коллбэки

2022-10-05 12:45 UTC, Ofigelov commented on packages/ui/src/DatePicker/common/utils/isDate/isDate.ts
> +export const isDate = (value: unknown): value is Date =>
я считаю что лучше иметь, потому что логика простая, и без зависимостей.

2022-10-05 12:59 UTC, AndTem commented on packages/ui/src/DatePicker/common/utils/isDate/isDate.ts
> +export const isDate = (value: unknown): value is Date =>
В таком случае необходимо делать отдельный пакет для работы с датами.
Обсудим это на встрече

2022-10-06 06:26 UTC, AndTem commented on packages/ui/src/DatePicker/common/utils/isDateOutOfRange/isDateOutOfRange.ts
> +    return (hasMinDate && +date < +minDate) || (hasMaxDate && +date > +maxDate);
Используем только явные преобразования типов (Number())

2022-10-06 06:49 UTC, AndTem commented on packages/ui/src/DatePicker/common/hooks/useToggle/useToggle.ts
> +export const useToggle = ({
Использовать более абстрактные названия

2022-10-06 06:58 UTC, AndTem commented on packages/ui/src/ConfigProvider/ConfigProvider.tsx
> +  locale: 'ru',
Заменить на lang. Сделать union для lang

2022-10-06 07:07 UTC, AndTem commented on packages/ui/src/DatePicker/common/utils/addDays/addDays.ts
> +export const addDays: AddHelper = (date, count) =>
Заменяем на date-fns

2022-10-06 07:16 UTC, AndTem commented on packages/ui/src/DatePicker/common/utils/buildIsoDateString/buildIsoDateString.ts
> +  `${zeroPad(year, 4)}-${zeroPad(month, 2)}-${zeroPad(day, 2)}T${zeroPad(
zeroPad является String.prototype.padStart()

2022-10-11 05:34 UTC, AndTem requested changes

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/utils/areDatesSame/areDatesSame.ts
> +) => (isDate(a) && isDate(b) && +a === +b) || a === b;
Используем явное преобразование типов.
Замени везде + на Number()

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/utils/addDays/addDays.ts
> +export const addDays = (date: Date, count: number) =>
Общались с тобой на тему: заменить такие утилы на date-fns

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/utils/areDatesSame/areDatesSame.ts
> + * @description утилита для сверки одинаковости дат, или их отсутствия
Нет такого слова "одинаковости"

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/utils/buildIsoDate/buildIsoDate.ts
> + * @description рендер даты не зависящей от часового пояса пользователя
Это утила, тут никакого рендера нет

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/utils/buildIsoDate/buildIsoDateString.ts
> +  return `${YYYY}-${MM}-${DD}T${HH}:${mm}:${ss}.000Z`;
Я не уверен, что всегда необходимо все, что идет после T.
В том же DatePicker тебе нужна только дата, без часового пояса и времени

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/utils/isDate/isDate.ts
> +export const isDate = (value: unknown): value is Date =>
заменить на date-fns

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/utils/addDays/addDays.ts
> +export const addDays = (date: Date, count: number) =>
Все утилы для дат необходимо положить в директорию date и работать через index файл

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/utils/maskDate/maskToDate/maskToDate.ts
> + * @description утилита конвертации строковой даты созданной по маске обратно в Date
Используй format и parse из date-fns и будет намного меньше проблем

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/hooks/useForwardedRef/useForwardedRef.ts
> +export const useForwardedRef = <T>(forwardedRef: ForwardedRef<T>) => {
Не хвататет описания

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/hooks/useEscapeClickEffect/useEscapeClickEffect.ts
> +export const useEscapeClickEffect = ({
Не хватает описания

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/hooks/useEscapeClickEffect/useEscapeClickEffect.ts
> +type UseEscapeClickEffectProps = {
не хвататет описания пропсов

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.tsx
> +import { areDatesSame } from '../utils/areDatesSame';
Все импорты для утил должны разруливать через индексный файл

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.tsx
> +import { DateMask } from '../utils/maskDate/maskDate';
У тебя сейчас типы внутри utils ментально зависят от DatePicker (посредством DateMask), такого быть не должно

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.tsx
> +          onNativeChange={(e) => checkValue(e.target.value)}
Все обработчики описываем константой

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/DatePicker/components/DatePickerClickAwayListener/DatePickerClickAwayListener.tsx
> +export const DatePickerClickAwayListener = ({
Не используем по style guide components директорию

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/DatePicker/components/DayPicker/hooks/useDaysGrid/useDaysGrid.ts
> +      grid.push({
сложная большая логика в этом хуке.
Нужны либо комментарии везде, либо выносить по отдельным функциям логику для облегчения понимания

2022-10-11 05:34 UTC, AndTem commented on packages/ui/src/DatePicker/components/DayPicker/hooks/useDaysGrid/useDaysGrid.ts
> +          +date >= +selectedDate &&
Уже писал несколько раз - используем явное преобразование типов

2022-10-11 05:40 UTC, Ofigelov commented on packages/ui/src/DatePicker/components/DatePickerClickAwayListener/DatePickerClickAwayListener.tsx
> +export const DatePickerClickAwayListener = ({
а куда их девать то тогда? Выносить на один уровень со всеми компонентами кита?

2022-10-11 05:41 UTC, AndTem commented on packages/ui/src/DatePicker/components/DatePickerClickAwayListener/DatePickerClickAwayListener.tsx
> +export const DatePickerClickAwayListener = ({
DatePicker/DatePickerAwayListener

2022-10-11 05:41 UTC, Ofigelov commented on packages/ui/src/DatePicker/DatePicker.tsx
> +          onNativeChange={(e) => checkValue(e.target.value)}
тут же одна простая строчка без переноса, зачем заниматься раздувательством кода если функция супер простая, и используется только в одном месте?

2022-10-11 05:44 UTC, AndTem commented on packages/ui/src/DatePicker/DatePicker.tsx
> +          onNativeChange={(e) => checkValue(e.target.value)}
Единообразие.

2022-10-11 05:44 UTC, Ofigelov commented on packages/ui/src/utils/buildIsoDate/buildIsoDateString.ts
> +  return `${YYYY}-${MM}-${DD}T${HH}:${mm}:${ss}.000Z`;
я в нескольких местах использую часы и минуты

2022-10-11 05:51 UTC, Ofigelov commented on packages/ui/src/utils/addDays/addDays.ts
> +export const addDays = (date: Date, count: number) =>
запутался немного, вроде решили что пока оставить, просто вынести в отдельную папку.
Хорошо, заменю.

2022-10-11 08:08 UTC, Ofigelov commented on packages/ui/src/utils/maskDate/maskToDate/maskToDate.ts
> + * @description утилита конвертации строковой даты созданной по маске обратно в Date
может ненадо? это топ 5 самых тяжелых утилит date-fns.
![image](https://user-images.githubusercontent.com/59384103/195034406-133b389f-25b4-40f8-b3f7-99177f67560b.png)

2022-10-11 08:10 UTC, AndTem commented on packages/ui/src/utils/maskDate/maskToDate/maskToDate.ts
> + * @description утилита конвертации строковой даты созданной по маске обратно в Date
Не просто так они тяжелые. Со временем эти функции также вырастут как в date-fns

2022-10-11 08:14 UTC, Ofigelov commented on packages/ui/src/utils/maskDate/maskToDate/maskToDate.ts
> + * @description утилита конвертации строковой даты созданной по маске обратно в Date
мне кажется что по концепции YAGNE нам не стоит их тянуть.

2022-10-11 08:34 UTC, Ofigelov commented on packages/ui/src/DatePicker/DatePicker.tsx
> +import { DateMask } from '../utils/maskDate/maskDate';
Чет не очень понял тут про ментальную зависимость.

Сейчас есть два метода для конвертации: из даты в масковую строку, и строковой маски в дату. Они зависят от DateMask. Они не могут не зависеть от DateMask, потому что он им нужен для корректной работы. А ДатаПикер в свою очередь пропсом принимает этот DateMask, и передает конвертаторам, чтобы те работали бы от него одного.

2022-10-11 13:31 UTC, AndTem requested changes

2022-10-11 13:31 UTC, AndTem commented on packages/ui/src/utils/date/isDate/isDate.ts
> +import { isDate as fnsIsDate } from 'date-fns';
date-fns больше не в зависимостях

2022-10-11 13:31 UTC, AndTem commented on packages/ui/src/utils/date/maskDate/maskToDate/maskToDate.ts
> +export const maskToDate = (date: string): Date => dayjs(date).toDate();
Лучше сохранить исходное название formatDate, parseDate

2022-10-11 13:31 UTC, AndTem commented on packages/ui/src/DatePicker/DateCalendar/DateCalendarChevronBtn/DateCalendarNextBtn.tsx
> +export const DateCalendarNextBtn = forwardRef<
По style guide каждый компонент в отдельной директории

2022-10-11 13:31 UTC, AndTem commented on packages/ui/src/DatePicker/MinMaxDateContext/MinMaxDateContext.tsx
> +export const MinMaxDateContext = createContext<MinMaxDate>({
Не хвататет комментария для чего предназначен этот контекст

2022-10-12 09:21 UTC, AndTem approved these changes

2022-10-12 09:49 UTC, merged