feat(UIKIT-418,validations): Расширен список правил валидации
kaluga-astral/frontend pull request #422
Opened 2022-09-30 10:36 UTC by StanislavDa

Добавлены следующие правила валидации:

- ```isINNUL```
- ```isINNIP```
- ```isOGRNIP```
- ```isOGRNUL```
- ```isMinLength```
- ```isMaxLength```
- ```isMaxValue```
- ```isMinValue```
- ```isMaybeNumber```
- ```isDate```
- ```isSNILS```

2022-09-30 10:39 UTC, AndTem commented on packages/validations/src/isINNUL/isINNUL.ts
> +  (message: string = IS_INNUL_DEFAULT_MESSAGE) =>
Надо добавить параметр exludeValues (название примерное).
Кейс: есть ИНН, которые невалидны по всем правилам, но в оф. документ он записан и для гос. органа является валидным

2022-09-30 10:40 UTC, StanislavDa commented on packages/validations/src/isINNUL/isINNUL.ts
> +  (message: string = IS_INNUL_DEFAULT_MESSAGE) =>
для инн ИП тоже?

2022-09-30 10:44 UTC, AndTem commented on packages/validations/src/isINNUL/isINNUL.ts
> +  (message: string = IS_INNUL_DEFAULT_MESSAGE) =>
@StanislavDa да

2022-09-30 13:38 UTC, AndTem requested changes

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isDate/isDate.ts
> +        if (Boolean(date.getTime())) {
isNanN(date.getTime()) кажется надежнее

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isDate/isDate.ts
> +      if (value instanceof Date) {
Отсутсвует проверка на 'Invalid Date'

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isDate/isDate.test.ts
> +describe('isDate', () => {
отсутсвует проверка на костомный message. Касается всех правил

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isINNIP/isINNIP.ts
> +            ) %
нечитаемый код

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isINNIP/isINNIP.ts
> +                [7, 2, 4, 10, 3, 5, 9, 4, 6, 8][index] * Number(symbol) + sum,
в константе должен быть массив

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isINNIP/isINNIP.ts
> +        if (arrSymbols.some((symbol) => isNaN(Number(symbol)))) {
Не понятно зачем boolean сравнивать на больше с другим булеан

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isINNIP/isINNIP.test.ts
> +  it.each<unknown>([
тест кейсы из старой репы здесь есть?
Должны быть, чтобы не поломать систему

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isINNIP/isINNIP.ts
> + * @param {string} [value] проверяемое значение
это бесполезное описание

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isDate/isDate.ts
> +      if (value === '') {
зачем везде на пустую строку проверять?
if(!value) не достаточно?

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isMaxLength/isMaxLength.ts
> +  (max: number, message: string = getDefaultMessage(max)) =>
У тебя сейчас используется в функции два разных сообщения. Если они действительно нужны, то должны быть возможность заменить их обе

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isMaxLength/isMaxLength.ts
> +      if (max <= 0) {
Это должно быть при первом вызове, а не когда сюда уже value приходить

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isMaxLength/isMaxLength.ts
> +      if (isEmpty(value)) {
Если в самое начало поставить, то и часть проверок уйдет

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isMaxLength/isMaxLength.test.ts
> +  it.each<unknown>([
почему разделено на два одинаковых it?

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isMaxValue/isMaxValue.ts
> +  (max: number, message: string = `Должно быть меньше чем ${max}`) =>
Текста сохранил из старой репы?

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isMaxValue/isMaxValue.ts
> +        !/\s/g.test(value) &&
регулярка должны быть в константе и нудны комментарии

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isMaxValue/isMaxValue.test.ts
> +  it.each<unknown>([1, Infinity, 0.34, '0.34'])('Valid for: %s', (value) => {
не понятно зачем отдельный it такой же

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isMaybeNumber/isMaybeNumber.ts
> +        typeof value === 'string' &&
а просто isNaN(String(value)) не достаточно?

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isMaybeNumber/isMaybeNumber.test.ts
> +  it.each<unknown>([-1, '-44', '-0.12'])('Valid for: %s', (value) => {
Необходимо проверить 2e3 значение

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isMinValue/isMinValue.ts
> +        throw new Error('Значение параметра `min` должно быть >= 0');
Почему? Отрицательные числа тоже надо обрабатывать

2022-09-30 13:38 UTC, AndTem commented on packages/validations/src/isOGRNIP/isOGRNIP.test.ts
> +  it.each<unknown>([
Маску добавь во все invalid правила как тест кейс. Чтобы было понятно, что маска не прокатывает

2022-10-03 05:43 UTC, StanislavDa commented on packages/validations/src/isDate/isDate.ts
> +      if (value === '') {
Не достаточно, иначе всякие 0, false, NaN будут проходить проверку

2022-10-03 05:47 UTC, StanislavDa commented on packages/validations/src/isMaybeNumber/isMaybeNumber.ts
> +        typeof value === 'string' &&
Не достаточно. isNaN ожидает number + логично, что все кроме number и string не может быть числом. isNaN(Number(false)) пройдет проверку

2022-10-03 05:48 UTC, StanislavDa commented on packages/validations/src/isMaxValue/isMaxValue.ts
> +  (max: number, message: string = `Должно быть меньше чем ${max}`) =>
частично

2022-10-03 05:49 UTC, AndTem commented on packages/validations/src/isDate/isDate.ts
> +      if (value === '') {
Думаю, что если ты повсеместно делаешь такую проверку, то ее надо вынести либо в отдельную функцию, либо в фабрику

2022-10-03 05:50 UTC, StanislavDa commented on packages/validations/src/isMaxLength/isMaxLength.test.ts
> +  it.each<unknown>([
проверяются 2 разных сообщения

2022-10-03 05:52 UTC, AndTem commented on packages/validations/src/isMaxLength/isMaxLength.test.ts
> +  it.each<unknown>([
it должны быть с разными названиями, иначе это один и тот же it

2022-10-03 05:52 UTC, AndTem commented on packages/validations/src/isMaxValue/isMaxValue.ts
> +  (max: number, message: string = `Должно быть меньше чем ${max}`) =>
Должна быть полная идентичность.
Эти сообщения были согласованы с дизайнерами

2022-10-04 12:48 UTC, AndTem requested changes

2022-10-04 12:48 UTC, AndTem commented on packages/validations/src/compose/compose.ts
> +  (value: unknown) =>
Возвращаемое значение необходимо указать явно

2022-10-04 12:48 UTC, AndTem commented on packages/validations/src/composeAllSettled/composeAllSettled.ts
> +  (value: unknown) => {
Возвращаемое значение необходимо указать явно

2022-10-04 12:48 UTC, AndTem commented on packages/validations/src/createRule/createRule.ts
> +export function createRule(creator: any) {
добавь коммент почему any используется

2022-10-04 12:48 UTC, AndTem commented on packages/validations/src/isINNIP/isINNIP.ts
> + * @param {string} [value] проверяемое значение
up

2022-10-04 12:48 UTC, AndTem commented on packages/validations/src/types.ts
> +export type Message = {
Для каждого правила будет свой набор сообщений, поэтому думаю не стоит это абстрагировать

2022-10-04 12:48 UTC, AndTem commented on packages/validations/src/isMinValue/isMinValue.ts
> +      } = { min: 0 },
Здесь params должен быть required

2022-10-04 12:48 UTC, AndTem commented on packages/validations/src/isMinValue/isMinValue.ts
> +        value !== ''
Это проверяется выше

2022-10-04 12:58 UTC, AndTem commented on packages/validations/src/isMinValue/isMinValue.ts
> +        typeof value === 'string' &&
А не подойдет ли здесь isMaybeNumber правило?

2022-10-04 12:59 UTC, StanislavDa commented on packages/validations/src/isMinValue/isMinValue.ts
> +        typeof value === 'string' &&
хотел заменить, но забыл

2022-10-04 13:12 UTC, StanislavDa commented on packages/validations/src/types.ts
> +export type Message = {
внутри каждого правила валидации писать?

2022-10-05 08:20 UTC, AndTem requested changes

2022-10-05 08:20 UTC, AndTem commented on packages/validations/src/isSNILS/isSNILS.ts
> +          (calculatedCheckSum % DEFAULT_CHECKED_SUM[2] ===
Вынеси хоть в константу проверку то, нечитаемо сейчас

2022-10-05 08:20 UTC, AndTem commented on packages/validations/src/utils/isEmptyString.ts
> +export const isEmptyString = (value: unknown) => {
Описание jsdoc добавь для чего это используется в правилах

2022-10-05 08:20 UTC, AndTem commented on packages/validations/src/isINNUL/isINNUL.ts
> + * @param {string} [value] проверяемое значение
Уже писал, что нет никакой необходимости писать об этом здесь. Причем описание некорректное потому, что первый вызов функции не принимает value. Ну и не string ведь оно.
Просто убери это везде

2022-10-05 08:20 UTC, AndTem commented on packages/validations/src/isMaxLength/isMaxLength.ts
> +    max: number;
jsdoс для параметров должен быть для этого типа описан, а не для функции

2022-10-05 08:21 UTC, AndTem commented on packages/validations/src/compose/compose.ts
> +  (value: unknown): undefined | ValidationResult =>
ValidationReusult и так ведь undefined | string.
Ни к чему здесь union

2022-10-05 09:54 UTC, AndTem approved these changes

2022-10-05 09:54 UTC, AndTem commented on packages/validations/src/isMaxValue/isMaxValue.ts
> +      } = { max: 0 },
Дефолтное значение не нужно, у тебя ведь параметр required

2022-10-05 11:58 UTC, AndTem approved these changes

2022-10-06 12:45 UTC, merged