feat(UIKIT-142,form,FormMaskField): Реализован адаптер для MaskField
kaluga-astral/frontend pull request #424
Opened 2022-10-06 09:41 UTC by StanislavDa

2022-10-07 13:49 UTC, lordniken approved these changes

2022-10-10 06:54 UTC, perevezencev approved these changes

2022-10-10 09:13 UTC, AndTem requested changes

2022-10-10 09:13 UTC, AndTem commented on packages/form/src/FormMaskField/FormMaskField.tsx
> + * @description Тестовый инпут с маской для формы
Почему тестовый?

2022-10-10 09:14 UTC, StanislavDa commented on packages/form/src/FormMaskField/FormMaskField.tsx
> + * @description Тестовый инпут с маской для формы
копипаста из formTextField. там тоже поправлю

2022-10-10 09:20 UTC, AndTem approved these changes

2022-10-10 09:20 UTC, merged