feat(UIKIT-496,ui,ActionCell): Добавлен пропс position для тултипа
kaluga-astral/frontend pull request #447
Opened 2022-11-02 08:13 UTC by StanislavDa

2022-11-02 08:15 UTC, AndTem requested changes

2022-11-02 08:17 UTC, StanislavDa commented on packages/ui/src/ActionCell/ActionCell.tsx
> +  placement?: TooltipProps['placement'];
мб тогда все пропсы тултипа прокидывать в TooltipProps например?

2022-11-02 08:19 UTC, AndTem commented on packages/ui/src/ActionCell/ActionCell.tsx
> +  placement?: TooltipProps['placement'];
Для каждой отдельной кнопки?

2022-11-02 08:24 UTC, StanislavDa commented on packages/ui/src/ActionCell/ActionCell.tsx
> +  placement?: TooltipProps['placement'];
сразу для всех

2022-11-02 08:40 UTC, StanislavDa commented on packages/ui/src/ActionCell/ActionCell.tsx
> +  placement?: TooltipProps['placement'];
переименовал в общем

2022-11-02 10:15 UTC, AndTem approved these changes

2022-11-03 07:22 UTC, m-av97 approved these changes

2022-11-03 07:23 UTC, merged