feat(UIKIT-513,ui,ConfirmDialog): Добавлен компонент ConfirmDialog
kaluga-astral/frontend pull request #467
Opened 2022-11-15 10:05 UTC by StanislavDa

2022-11-15 10:07 UTC, AndTem requested changes

2022-11-15 10:07 UTC, AndTem commented on packages/ui/src/ConfirmDialog/ConfirmDialog.tsx
> +  description: string;
Optional лучше сделать

2022-11-15 10:07 UTC, AndTem commented on packages/ui/src/ConfirmDialog/ConfirmDialog.tsx
> +  title: string;
ReactNode лучше спала сделать и description тоже

2022-11-15 10:07 UTC, AndTem commented on packages/ui/src/ConfirmDialog/ConfirmDialog.stories.tsx
> +  const [open, setOpen] = React.useState(false);
Бери useToggle из наших хуков

2022-11-15 10:08 UTC, AndTem requested changes

2022-11-15 10:08 UTC, AndTem commented on packages/ui/src/ConfirmDialog/ConfirmDialog.tsx
> +    confirm: ButtonProps & { text: string };
Тут тоже не хватает описания в jsdoc

2022-11-15 10:11 UTC, AndTem requested changes

2022-11-15 10:11 UTC, AndTem commented on packages/ui/src/ConfirmDialog/ConfirmDialog.tsx
> +type ConfirmDialogProps = {
Думаю надо еще добавить отдельно onClose. Потому кнопка отмены может не только закрывать модалку

2022-11-15 10:12 UTC, StanislavDa commented on packages/ui/src/ConfirmDialog/ConfirmDialog.tsx
> +type ConfirmDialogProps = {
Ага, тоже про это думал

2022-11-15 10:22 UTC, StanislavDa commented on packages/ui/src/ConfirmDialog/ConfirmDialog.tsx
> +  description: string;
Сейчас диалог с коротким title выглядит так. Это из-за position:absolute у кнопки закрытия диалога. Поправлю в этом пр-е?
![image](https://user-images.githubusercontent.com/93906455/201895278-974a46ab-43ac-4c93-ad3b-a773b2a89acd.png)

2022-11-15 10:25 UTC, StanislavDa commented on packages/ui/src/ConfirmDialog/ConfirmDialog.tsx
> +  title: string;
Dialog в title ожидает string. там тоже поправить?

2022-11-15 10:26 UTC, AndTem commented on packages/ui/src/ConfirmDialog/ConfirmDialog.tsx
> +  description: string;
Правь

2022-11-15 10:27 UTC, AndTem commented on packages/ui/src/ConfirmDialog/ConfirmDialog.tsx
> +  title: string;
Если там тоже string, то пусть будет так

2022-11-15 10:48 UTC, AndTem requested changes

2022-11-15 10:48 UTC, AndTem commented on packages/ui/src/ConfirmDialog/ConfirmDialog.tsx
> +    <Dialog title={title} open={open} onClose={actions.cancel.onClick}>
onClose={onClose}

2022-11-15 10:48 UTC, AndTem commented on packages/ui/src/ConfirmDialog/ConfirmDialog.stories.tsx
> +  const [isActive, handleActive, handleInactive] = useToggle();
handleOpen, handleClose

2022-11-15 10:54 UTC, AndTem approved these changes

2022-11-16 09:48 UTC, perevezencev approved these changes

2022-11-16 09:59 UTC, m-av97 commented on packages/ui/src/ConfirmDialog/ConfirmDialog.tsx
> +    cancel: ButtonProps & { text: string };
Это разве не должно быть nullable? Например диалог с инофрмацией для ознакомления и там одна кнопка ОК

2022-11-30 08:15 UTC, AndTem commented
@StanislavDa напоминаю о не закрытом PR

2022-12-09 07:38 UTC, m-av97 approved these changes

2022-12-09 07:39 UTC, merged