ButtonBase. Рефакторинг стилизации, минорные правки сторибука.
kaluga-astral/frontend pull request #47
Opened 2022-02-09 11:25 UTC by StanislavDa

UIKIT-83 Исправил стили active ButtonBase
UIKIT-78 Отрефакторил стилизацию ButtonBase 
UIKIT-76 поправил импорт в теме сторибука 
UIKIT-84 поправил оформление сторибука

2022-02-09 16:39 UTC, AndTem requested changes

2022-02-09 16:39 UTC, AndTem commented on packages/ui/src/Button/styled.ts
> +  &:focus-visible {
Плохая поддержка псевдокласса. В сафари только в этом году появился по флагом. Используй обычный focus

2022-02-11 07:51 UTC, AndTem commented on packages/ui/src/ButtonBase/styled.ts
> +    outline: 2px solid ${({ theme }) => theme.palette.primary['400']};
добавь transition для outline

2022-02-11 10:09 UTC, julderen approved these changes

2022-02-11 11:47 UTC, merged