feat(UIKIT-187,ui,PageLayout): Добавлен компонент PageLayout
kaluga-astral/frontend pull request #474
Opened 2022-11-21 06:21 UTC by lordniken

2022-11-21 08:54 UTC, perevezencev commented on packages/ui/package.json
> +    "@astral/icons": "*",
Зачем там? Потенциально может поломать что то, если версия иконок будет > 1

2022-11-21 08:54 UTC, perevezencev commented on packages/ui/src/Breadcrumbs/index.ts
> +export { Breadcrumbs } from '@mui/material';
`export { Breadcrumbs, type BreadcrumbsProps } from '@mui/material';
`

2022-11-21 08:54 UTC, perevezencev commented on packages/ui/src/PageContent/PageContent.tsx
> +  hasDefaultPadding?: boolean;
Обычно используется `disablePadding`

2022-11-21 08:54 UTC, perevezencev commented on packages/ui/src/PageHeader/ButtonGroups/ButtonGroups.tsx
> +export const ButtonGroups = (props: ButtonGroupsProps) => {
`ButtonGroup`

2022-11-21 08:54 UTC, perevezencev commented on packages/ui/src/PageHeader/PageHeader.stories.tsx
> +            mainButtons: [
мб просто main и secondary

2022-11-21 08:59 UTC, AndTem commented on packages/ui/package.json
> +    "@astral/icons": "*",
@perevezencev это для локалки. При публикации подставляется конкретная версия паекта

2022-11-21 13:17 UTC, perevezencev commented on packages/ui/package.json
> +    "@astral/icons": "*",
ок

2022-11-21 13:19 UTC, perevezencev commented on packages/ui/src/PageHeader/ButtonGroup/styles.ts
> +export const ButtonGroupsWrapper = styled.div`
`ButtonGroup`

2022-11-21 13:20 UTC, perevezencev commented on packages/ui/src/PageHeader/PageHeader.tsx
> +  breadCrumbs?: ReactNode[];
это одно слово, `breadсrumbs`

2022-11-21 13:20 UTC, perevezencev commented on packages/ui/src/PageHeader/PageHeader.tsx
> +  subHeader?: ReactNode;
subheader

2022-11-21 13:23 UTC, perevezencev commented on packages/ui/src/PageHeader/PageHeader.tsx
> +  backButton?: Pick<BaseButtonProps, 'component' | 'onClick'>;
```
backButton?: PageHeaderBackButtonProps
```

2022-11-22 05:12 UTC, AndTem requested changes

2022-11-22 05:12 UTC, AndTem commented on packages/ui/src/index.ts
> +export * from './PageAside';
Два раза одно и тоже экспортируется

2022-11-22 06:43 UTC, AndTem approved these changes

2022-11-22 10:59 UTC, Astral-design approved these changes

2022-11-22 10:59 UTC, merged