feat(UIKIT-551,ui,AwayClickListener): реализован абстрактный компонент AwayClickListener
kaluga-astral/frontend pull request #497
Opened 2022-12-07 08:49 UTC by Ofigelov

2022-12-08 04:03 UTC, Ofigelov commented
мне кажется это костыль, посмотрите лучше вот [этот мой пулик](https://github.com/kaluga-astral/frontend/pull/497), в нем эта проблема решается сама по себе

2022-12-08 06:07 UTC, AndTem requested changes

2022-12-08 06:07 UTC, AndTem commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +export const AwayClickListener = ({
Нужен тест

2022-12-08 06:07 UTC, AndTem commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return <div ref={ref}>{children}</div>;
Ты сохранил API mui? в противном случае в продуктах будут проблемы (сразу вижу, что не хватает classname)

2022-12-08 06:07 UTC, AndTem commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +export type AwayClickListenerProps = Omit<UseAwayClickListenerOptions, 'ref'>;
PropsWithChildren должен быть здесь

2022-12-08 06:07 UTC, AndTem commented on packages/ui/src/types.ts
>  export type Reason =
1. Надо изменить название (типа CloseReason)
2. Нужен jsdoc описание
3. Не уверен, что есть смысл запихивать всевозможные reason в один тип. Может нужно для каждого компонента свой определять?

2022-12-08 06:07 UTC, AndTem commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +export const useAwayClickEffect = ({
Нужен тест

2022-12-08 06:07 UTC, AndTem commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +    const onClick = (e: PointerEvent) => {
Обычно обработчики вне useEffect определяются

2022-12-08 06:07 UTC, AndTem commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +        onAwayClick?.(e, 'awayClick');
У тебя onAwayClick required, значит ? лишнее

2022-12-08 06:07 UTC, AndTem commented on packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
> +      (previousReason === 'blur' || previousReason === 'awayClick') &&
Кажется, что появляется связность между backdropManager и useAway. Тебе так не кажется? Нет идей улучшения?

2022-12-08 06:11 UTC, AndTem commented on packages/ui/src/AwayClickListener/AwayClickListener.stories.tsx
> +      <MotivationPart />
Используй для описания сторей наши готовые компоненты, как в [Button](https://github.com/kaluga-astral/frontend/blob/main/packages/ui/src/Button/Button.stories.tsx)

2022-12-08 06:13 UTC, Ofigelov commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return <div ref={ref}>{children}</div>;
рест же нельзя прокидывать, вот я и вовсе его убрал

2022-12-08 06:15 UTC, AndTem commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return <div ref={ref}>{children}</div>;
Из-за того, что нельзя пронизывать рест ты решил просто сделать braking changes? Необходимо сохранить апи Mui

2022-12-08 06:17 UTC, Ofigelov commented on packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
> +      (previousReason === 'blur' || previousReason === 'awayClick') &&
ну а как их еще то связать, они должны какие то общие штуки использовать, если напрямую нельзя, косвенно нельзя, то как можно то?

2022-12-08 06:17 UTC, AndTem commented on packages/ui/src/types.ts
>  export type Reason =
Мысль понятна. Ок

2022-12-08 06:19 UTC, AndTem requested changes

2022-12-08 06:19 UTC, AndTem commented on packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
> +      (previousReason === 'blur' || previousReason === 'awayClick') &&
Я бы поместил все нужные эвенты в массив и здесь через includes проверял. Так будет расширяемо и понятнее

2022-12-08 06:23 UTC, Ofigelov commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return <div ref={ref}>{children}</div>;
Почему breakingChanges? компонент же новый, нигде в проекте еще не используется

2022-12-08 06:29 UTC, AndTem commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return <div ref={ref}>{children}</div>;
У тебя может и нет, а у других да

2022-12-08 06:30 UTC, Ofigelov commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +    const onClick = (e: PointerEvent) => {
ага, только вот дом нода, необходимая для проверки на вхождения `e.target`, инкаспулирована в этом хуке, и если для подписки это не проблема прокидывать ее вторым аргументом в стрелочной функции, то для отписки потребуется создавать инкапсулированную ссылку, с передачей туда всех нужных параметров, в итоге по сути вся функция все равно окажется внутри хука.

2022-12-08 06:32 UTC, AndTem commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return <div ref={ref}>{children}</div>;
Так, ты его назвал даже по другому, не как в mui.
Тогда ок.
Но добавить classname нужно

2022-12-08 06:36 UTC, AndTem commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +    const onClick = (e: PointerEvent) => {
Не понял про инкапсулированные ссылки. Тебе достаточно const node = ref?.current вынести на верхний уровень и все будет ок

2022-12-08 06:44 UTC, Ofigelov commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +    const onClick = (e: PointerEvent) => {
```
const onClick = (
  e: PointerEvent,
  node: HTMLElement,
  preventBubbling: boolean,
  onAwayClick: (e: PointerEvent, reason: Reason) => void,
) => {
  if (!node.contains(e.target as HTMLElement)) {
    if (preventBubbling) {
      e.stopPropagation();
      e.stopImmediatePropagation();
    }

    onAwayClick(e, 'awayClick');
  }
};

export const useAwayClickEffect = ({
  ref,
  onAwayClick,
  preventBubbling,
  isActive,
}: UseAwayClickListenerOptions) => {
  useEffect(() => {
    const node = ref?.current;

    if (!isActive || !node) {
      return;
    }

    const _onClick = (e: PointerEvent) =>
      onClick(e, node, preventBubbling, onAwayClick);

    window.addEventListener('pointerdown', _onClick);

    return () => {
      window.removeEventListener('pointerdown', _onClick);
    };
  }, [isActive, ref]);
};
```

вот, такой код получится, и я имею в виду, что нам все равно нужен будет внутренний приватный onClick, чтобы потом отписаться, и я не вижу в этом профита

2022-12-08 07:11 UTC, AndTem commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +    const onClick = (e: PointerEvent) => {
Мое предложение - сделать onClick внутри useAwayClickEffect, но не внутри useEffect

2022-12-08 07:18 UTC, Ofigelov commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +    const onClick = (e: PointerEvent) => {
это же еще потребуется доп обертка `useCallback`, зачем это переусложнение? какой профит?

2022-12-08 07:27 UTC, AndTem commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +    const onClick = (e: PointerEvent) => {
Единообразие хуков.
У нас обработчики пишутся вне useEffect

2022-12-08 07:32 UTC, Ofigelov commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +    const onClick = (e: PointerEvent) => {
в ките 3 `addEventListener` 
1 BackdropStackManager - вне хук стиля
2 useEscapeClickEffect - внутри эффекта
3 useAwayClickEffect - текущий компонент

вот и единообразие.

2022-12-08 07:34 UTC, AndTem commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +    const onClick = (e: PointerEvent) => {
Считаю, что за то время, которое ты тратишь на споры, можно было бы сделать правки по PR и слить его.
Критика относительно уже написанного кода сейчас не уместна

2022-12-08 07:41 UTC, Ofigelov commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +    const onClick = (e: PointerEvent) => {
Аргумент "у нас так принято" не позволит научиться. Я хочу услышать аргументированное объяснение, чем мой код плох, в чем его изъяны.
Перероверил стайл гайд, там про это ничего не сказано.

2022-12-08 08:20 UTC, Ofigelov commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +export const AwayClickListener = ({
добавил

2022-12-08 08:21 UTC, Ofigelov commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return <div ref={ref}>{children}</div>;
добавил

2022-12-08 08:21 UTC, Ofigelov commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +export type AwayClickListenerProps = Omit<UseAwayClickListenerOptions, 'ref'>;
поправил

2022-12-08 08:21 UTC, Ofigelov commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +export const useAwayClickEffect = ({
добавил

2022-12-08 08:21 UTC, Ofigelov commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +        onAwayClick?.(e, 'awayClick');
поправил

2022-12-08 08:21 UTC, Ofigelov commented on packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
> +      (previousReason === 'blur' || previousReason === 'awayClick') &&
поправил

2022-12-08 08:27 UTC, Ofigelov commented on packages/ui/src/types.ts
>  export type Reason =
поправил

2022-12-08 08:29 UTC, AndTem requested changes

2022-12-08 08:29 UTC, AndTem commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.test.ts
> +describe('useEscapeClickEffect', () => {
useEscapeClickEffect -> useAwayClickEffect

2022-12-08 08:29 UTC, AndTem commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.test.ts
> +    document.body.appendChild(div);
Лучше сделать через react component, чтобы сразу было видно как это и должно выглядеть в коде

2022-12-08 08:29 UTC, AndTem commented on packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
> +const backdropConflictsReasons = new Set<CloseEventReason | undefined>([
undefined кажется лишним

2022-12-08 08:29 UTC, AndTem commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +    const onClick = (e: PointerEvent) => {
Значит вынесем это на обсуждение по style guide. Сделай сейчас отдельным onClick (и useCallback будет не нужен потому, что ты этот onClick ни в какие компоненты не пробрасываешь)

2022-12-08 08:38 UTC, Ofigelov commented on packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
> +const backdropConflictsReasons = new Set<CloseEventReason | undefined>([
`undefined` здесь нужен, потому что не все компоненты могут пробрасывать причину закрытия

2022-12-08 08:41 UTC, AndTem commented on packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
> +const backdropConflictsReasons = new Set<CloseEventReason | undefined>([
Но сам Set ведь у тебя не может быть undefined. Или метод has ошибку выдает, если не указать undefined?

2022-12-08 08:42 UTC, vinokurov-and commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +    const onClick = (e: PointerEvent) => {
там вроде проблема будет если useCallback не заюзать

тогда ссылка будет меняться при каждом отображении и при размонтировании в removeAddEventListener попадет другая ссылка onClick

2022-12-08 08:43 UTC, Ofigelov commented on packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
> +const backdropConflictsReasons = new Set<CloseEventReason | undefined>([
ошибка типизации, ага

2022-12-08 08:48 UTC, AndTem commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +    const onClick = (e: PointerEvent) => {
@Ofigelov я понял проблему с ссылками. Оставляй как есть 👍

2022-12-08 08:48 UTC, Ofigelov commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.test.ts
> +    document.body.appendChild(div);
тесты проверяют функционал, а для того чтобы смотреть как это должно работать есть сторибук.

тест же валидный, кейсы валидные, проверки проходят. Зачем еще сложнее это все делать?

2022-12-08 08:50 UTC, Ofigelov commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.ts
> +    const onClick = (e: PointerEvent) => {
ух, не зря я сопротивлялся >_<

2022-12-08 08:51 UTC, AndTem commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.test.ts
> +    document.body.appendChild(div);
Тесты кроме проверок еще и демонстрируют варианты использования.
Но здесь у тебя же хук тестируется, твой вариант проще

2022-12-08 08:54 UTC, Ofigelov commented on packages/ui/src/hooks/useAwayClickEffect/useAwayClickEffect.test.ts
> +describe('useEscapeClickEffect', () => {
готово

2022-12-08 08:57 UTC, AndTem approved these changes

2022-12-08 09:37 UTC, m-av97 commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +export const AwayClickListener = ({
Может как в муи ClickAwayListener??

2022-12-08 09:37 UTC, m-av97 commented on packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
> +const backdropConflictsReasons = new Set<CloseEventReason | undefined>([
вообще не понятно что это. Нужно либо поеменять нейм, либо коменты оставить

2022-12-08 09:37 UTC, m-av97 commented on packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
> +type PopTuple = [CloseEventReason | undefined, PointerId];
вообще не понятно что это. Нужно либо поеменять нейм, либо коменты оставить. Что такое PointerId?

2022-12-08 09:37 UTC, m-av97 commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return (
Зачем это все обернуто в див еще и с класснеймами? Тут по сути только чилдрен должны возвращаться. Рефку же можно из евента вытщаить в хендлере.

2022-12-08 10:15 UTC, Ofigelov commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return (
обертка нужна, чтобы отслеживать клики внутри этой обертки

например компонент дата пикер, поппер датапикера не должен закрываться, если пользователь выделяет что то внутри инпута, а так как инпут не является дочерним элементом поппера, то взаимодействия с инпутом будут приводить к закрытию поппера.

если нужно какое то другое действие, где нужно отслеживать именно клик вне конкретного рефа,
 то для этого предназначен хук `useAwayClickListener`

2022-12-08 10:16 UTC, Ofigelov commented on packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
> +type PopTuple = [CloseEventReason | undefined, PointerId];
это логика стороннего компонента, не думаю что стоит рефакторить его в рамках текущих изменений

2022-12-08 10:26 UTC, Ofigelov commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +export const AwayClickListener = ({
в правилах английского языка первое слово описывает второе, [compound nouns](https://dictionary.cambridge.org/grammar/british-grammar/nouns-compound-nouns)

- `Big Ban` - большой бэн, 
- `dish wahser` - мойка посуды
- `sea water` - морская вода

и именно из этой логики - `Away Click Listener` - слушатель клика снаружи

так же, наш компонент немного отличается по api, и чтобы не было пересечений я считаю что лучше оставить мой вариант

2022-12-08 11:46 UTC, m-av97 commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +export const AwayClickListener = ({
Только click away это то же самое, что set up, turn on/off, go on. Это фразовые глаголы и они так и пишутся. Ты же не говоришь offTurn, upSet

2022-12-08 11:47 UTC, m-av97 commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +export const AwayClickListener = ({
А по твоей ссылке комбинируются 2 существительных. Тут же глагол + предлог

2022-12-08 11:48 UTC, m-av97 commented on packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
> +type PopTuple = [CloseEventReason | undefined, PointerId];
Хотя бы коммент тогда)

2022-12-08 11:53 UTC, Ofigelov commented on packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
> +const backdropConflictsReasons = new Set<CloseEventReason | undefined>([
покрыл весь BackdropStackManager jsdoc комментами

2022-12-08 11:53 UTC, Ofigelov commented on packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
> +type PopTuple = [CloseEventReason | undefined, PointerId];
покрыл весь BackdropStackManager jsdoc комментами

2022-12-08 12:13 UTC, m-av97 commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return (
Да неее.... не должно такого быть же( если допустим я на li хочу эту тему,то у меня в ul появится div и сломает семантику. 

https://github.com/ooade/react-click-away-listener/blob/main/src/index.tsx 

вот еще пример. Как я понял это можно решить через ownerDocument. 
@AndTem что думаешь по поводу обертки?

2022-12-08 12:32 UTC, Ofigelov commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +export const AwayClickListener = ({
`click away` говорится в повелительном наклонении, как призыв к действию, `давай кликай снаружи`

в данном контексте, клик это существительное, away как прилагательное `наружний`, как раз подходит под [compound nouns](https://dictionary.cambridge.org/grammar/british-grammar/nouns-compound-nouns), и в итоге получается `awayClickListener` слушатель клика снаружи

2022-12-08 13:01 UTC, Ofigelov commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return (
если надо на `li` навесить, используем хук с передачей туда рефа, и радуемся жизни

2022-12-08 13:10 UTC, AndTem commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return (
Считаю, что брать ref от children в таком компоненте было бы круто. Это удобно.
При том, что наши команды работают с mui, который именно так себя и ведет.
В плане реализации это практически ничего не стоит. Альберт прикрепил ссылку на подробную реализацию

2022-12-08 13:14 UTC, AndTem commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +export const AwayClickListener = ({
Я не специалист в английском языке, но думаю, что интернациональная команда знала как правильно называть компонент.
И все таки вернусь к моему первому комментарию в этом PR: давай сделаем название и api идентичное (близкое) тому, что есть в mui, с добавлением наших специфических пропсов (оставить onClickAway от mui только, это не проблема).
Профит от этого следующий: команды привыкли работать с mui и им будет проще переходить на новый ui-kit в уже написанных проектах. При этом мы ничего не теряем

2022-12-08 16:13 UTC, Ofigelov commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return (
Реф на чилдрена будет работать, только если в  качестве чилдрена передали одиночный компонет, самым верхним элементом которого является дом нода, т.е. если разработчик передаст туда `React.Fragment`, то реф на такой элемент мы взять не сможем.
И поэтому еще раз, если не нужен див, следует использовать хук, и передавать туда реф на ноду, которую надо отслеживать.

2022-12-08 17:00 UTC, m-av97 commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return (
https://www.npmjs.com/package/react-click-away-listener

Смотри примеры

2022-12-08 19:03 UTC, Ofigelov commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return (
посмотрел, реф на фрагмент там не работает, как и ожидалось.
сделал с использованием cloneElement и методом хелпером https://codesandbox.io/s/nervous-dew-lif2y3?file=/src/App.tsx

2022-12-09 05:21 UTC, AndTem commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return (
Никакой проблемы в том, что с фрагментом это не работает нет.
Будет работать только с теми компоненты, от которых ref можно получить. В Mui так и работает, так и ожидают пользователи нашего пакета

2022-12-09 06:04 UTC, Ofigelov commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +export const AwayClickListener = ({
Переименовал

2022-12-09 06:05 UTC, Ofigelov commented on packages/ui/src/AwayClickListener/AwayClickListener.tsx
> +  return (
Убрал див, забираем реф от чилдрена, типизацией позволяем  чилдреном использовать только JSX.Element

2022-12-09 06:08 UTC, m-av97 commented on packages/ui/src/ClickAwayListener/ClickAwayListener.stories.tsx
> +      <Typography variant="h3">AwayClickListener</Typography>
ClickAway

2022-12-09 06:08 UTC, AndTem requested changes

2022-12-09 06:08 UTC, AndTem commented on packages/ui/src/ClickAwayListener/ClickAwayListener.tsx
> +export type AwayClickListenerProps = Omit<
Забыл переименовать пропсы

2022-12-09 06:08 UTC, AndTem commented on packages/ui/src/ClickAwayListener/ClickAwayListener.tsx
> +  onAwayClick,
onClickAway для совместимости

2022-12-09 06:08 UTC, AndTem commented on packages/ui/src/ClickAwayListener/ClickAwayListener.test.tsx
> +describe('AwayClickListener', () => {
Забыл переименовать

2022-12-09 06:08 UTC, AndTem commented on packages/ui/src/ClickAwayListener/ClickAwayListener.stories.tsx
> +  title: 'Components/AwayClickListener',
Забыл переименовать

2022-12-09 06:08 UTC, AndTem commented on packages/ui/src/hooks/useClickAwayEffect/useClickAwayEffect.ts
> +export type UseAwayClickListenerOptions = {
Забыл переименовать. Посмотри, где еще

2022-12-09 06:08 UTC, m-av97 commented on packages/ui/src/ClickAwayListener/ClickAwayListener.test.tsx
> +describe('AwayClickListener', () => {
ClickAway

2022-12-09 06:09 UTC, m-av97 commented on packages/ui/src/ClickAwayListener/ClickAwayListener.test.tsx
> +      <ClickAwayListener onAwayClick={onAwayClick} isActive={true}>
onClickAway

2022-12-09 06:09 UTC, m-av97 commented on packages/ui/src/ClickAwayListener/ClickAwayListener.tsx
> +export type AwayClickListenerProps = Omit<
ClickAway

2022-12-09 06:09 UTC, AndTem commented
CI  с ts и eslint упал

2022-12-09 06:09 UTC, m-av97 commented on packages/ui/src/ClickAwayListener/ClickAwayListener.tsx
> +import { UseAwayClickListenerOptions, useClickAwayEffect } from '../hooks';
ClickAway

2022-12-09 06:10 UTC, m-av97 commented on packages/ui/src/hooks/useClickAwayEffect/useClickAwayEffect.ts
> +export type UseAwayClickListenerOptions = {
ClickAway

2022-12-09 06:10 UTC, m-av97 commented on packages/ui/src/hooks/useClickAwayEffect/useClickAwayEffect.ts
> +  onAwayClick: (e: PointerEvent, reason: CloseEventReason) => void;
ClickAway

2022-12-09 06:10 UTC, m-av97 commented on packages/ui/src/types.ts
> +  | 'awayClick'
ClickAway

2022-12-09 06:18 UTC, Ofigelov commented on packages/ui/src/types.ts
> +  | 'awayClick'
Готово. Небуду везде писать одно и то же

2022-12-09 06:23 UTC, m-av97 approved these changes

2022-12-09 06:24 UTC, AndTem approved these changes

2022-12-09 06:24 UTC, merged