Добавлена тема, шрифты, компонент Typography.
kaluga-astral/frontend pull request #5
Opened 2021-11-11 07:55 UTC by StanislavDa

2021-11-12 07:14 UTC, AndTem commented on packages/ui/theme/components.ts
> +    MuiCssBaseline: {
Лучше для каждого компонента отдельную константу создавать

2021-11-12 07:14 UTC, AndTem commented on packages/ui/theme/components.ts
> +            font-family: 'Ubuntu';
Добавь font-display: swap;

2021-11-12 07:15 UTC, AndTem commented on packages/ui/theme/components.ts
> +              color: '#1874FF',
цвет должен из палитры браться

2021-11-12 07:16 UTC, AndTem commented on packages/ui/theme/components.ts
> +            src: url(${UbuntuLight}) format('truetype');
почему только в ttf формате? Почему нет woff2? Это же не вариативные шрифты насколько я понимаю?

2021-11-12 07:17 UTC, AndTem commented on packages/ui/declarations/typography.d.ts
> +declare module '@mui/material/styles' {
для чего это? в mui ошибки типизации или ты так переопределяешь глобально типы?

2021-11-12 07:18 UTC, AndTem commented on packages/ui/src/Typography/Typography.tsx
> +  value: string
Самым лучшим решением будет сохранять апи mui

2021-11-12 07:19 UTC, AndTem commented on packages/ui/src/Typography/__test__/Typography.test.tsx
> +describe('Typography', () => {
для чего такой бесполезный тест?

2021-11-12 07:19 UTC, AndTem commented on packages/ui/tsconfig.json
> +    "./**/*.ts",
"./**/*.tsx" тоже должен быть

2021-11-12 07:20 UTC, AndTem commented on packages/ui/theme/baseTheme.ts
> +export default createTheme({
тема должны уметь расширяться

2021-11-12 07:21 UTC, AndTem commented on packages/ui/theme/baseTheme.ts
> +export default createTheme({
необходимо также экспортить тип темы из theme

2021-11-12 07:22 UTC, AndTem commented on packages/ui/src/Typography/Typography.tsx
> +interface ITypography extends TypographyProps {
TypographyProps

2021-11-12 07:22 UTC, AndTem commented on packages/ui/src/Typography/Typography.tsx
> +interface ITypography extends TypographyProps {
Этот тип должен экспортиться для того, чтобы клиенты могли его использовать

2021-11-12 07:24 UTC, AndTem commented on packages/ui/theme/typography.ts
> +    h1: {
В зависимости от девайса должны быть разные размеры шрифта. Все размеры должны быть в rem

2021-11-12 07:24 UTC, AndTem commented on packages/ui/theme/typography.ts
> +      fontWeight: 500
fontWeight должен браться из темы - medium, bold...

2021-11-12 07:29 UTC, StanislavDa commented on packages/ui/declarations/typography.d.ts
> +declare module '@mui/material/styles' {
переопределил глобально типы

2021-11-12 07:29 UTC, AndTem commented on packages/ui/src/Typography/Typography.tsx
> +  value: string
То есть не использовать value, а children

2021-11-12 07:34 UTC, AndTem commented on packages/ui/theme/typography.ts
> +export default<TypographyOptions> {
многие компоненты mui внутри себя используют body1, он должен быть определен

2021-11-12 07:35 UTC, AndTem commented on packages/ui/theme/typography.ts
> +    small: {
Какова причина использования кастомных названий, вместо тех, что есть в mui?

2021-11-12 07:39 UTC, AndTem commented on packages/ui/declarations/typography.d.ts
> +declare module '@mui/material/styles' {
ты "сломал" типы mui. Такие типы соответсвуют только кастомному компоненту, который ты написал

2021-11-12 07:44 UTC, AndTem commented on packages/ui/theme/typography.ts
> +export default<TypographyOptions> {
htmlFontSize тоже должен быть определен для того, чтобы rem правильно расчитывался

2021-11-12 07:47 UTC, sultanovfv commented on packages/ui/theme/components.ts
> +              color: '#1874FF',
Переделается в рамках истории Colors, поэтому сейчас можно пропустить

2021-11-12 07:53 UTC, AndTem commented on packages/ui/theme/components.ts
> +              color: '#1874FF',
оставь тогда TODO

2021-11-12 08:01 UTC, sultanovfv commented
H1 - 
H1 - 
H1 - 
H1 - 
H1 - 
H1 -

2021-11-12 09:08 UTC, perevezencev commented on packages/ui/theme/baseTheme.ts
> +import typography from './typography'
Давайте делать все экспорты/импорты по имени

2021-11-12 09:44 UTC, perevezencev requested changes

2021-11-12 09:44 UTC, perevezencev commented on packages/ui/theme/typography.ts
> +      fontSize: '35px',
В дизайне действительно где то используется h1 размером в 35 пикселей?

2021-11-15 13:45 UTC, StanislavDa commented on packages/ui/theme/typography.ts
> +      fontSize: '35px',
В сетке он есть, будет ли где-то использоваться пока не известно

2021-11-16 11:18 UTC, AndTem commented on packages/ui/src/theme/baseTheme.ts
> +  return responsiveFontSizes(createMuiTheme(merge({}, themeOptions, options)))
для чего был добавлен responsiveFontSizes?

2021-11-16 11:20 UTC, AndTem commented on packages/ui/src/Typography/Typography.tsx
> +export const Typography = ({ variant, children, ...args }: TypographyProps) => {
...args обычно ...props называется

2021-11-16 11:22 UTC, AndTem commented on packages/ui/src/theme/baseTheme.ts
> +export const createTheme = (options?: ThemeOptions) => {
в директории не хватает индексного файла

2021-11-16 11:22 UTC, AndTem commented on packages/ui/src/index.ts
> +export * from './Typography'
здесь должна экспортиться тема

2021-11-16 11:23 UTC, AndTem commented on packages/ui/src/theme/typography.ts
> +  htmlFontSize: number | undefined = 14
странноватая конструкция. Параметр должен быть required

2021-11-16 11:25 UTC, StanislavDa commented on packages/ui/src/theme/baseTheme.ts
> +  return responsiveFontSizes(createMuiTheme(merge({}, themeOptions, options)))
To automate this setup, you can use the responsiveFontSizes() helper to make Typography font sizes in the theme responsive.
https://mui.com/customization/typography/#responsive-font-sizes

2021-11-16 11:25 UTC, StanislavDa commented on packages/ui/src/theme/typography.ts
> +  htmlFontSize: number | undefined = 14
в теме htmlFontSize идет как необязательный параметр и может быть undefined

2021-11-16 11:29 UTC, AndTem commented on packages/ui/src/theme/typography.ts
> +  htmlFontSize: number | undefined = 14
понятно, тогда вынеси htmlFontSize в отдельную константу, чтобы была синхронизация. А то у тебя магическое число 14 появилось

2021-11-16 11:30 UTC, AndTem commented on packages/ui/src/theme/typography.ts
> +  htmlFontSize: number | undefined = 14
и кстати вместо htmlFontSize: number | undefined можно указывать htmlFontSize?: number

2021-11-16 11:33 UTC, perevezencev requested changes

2021-11-16 11:33 UTC, perevezencev commented on packages/ui/src/Typography/Typography.tsx
> +export const Typography = ({ variant, children, ...args }: TypographyProps) => {
или ...restProps

2021-11-16 11:33 UTC, perevezencev commented on packages/ui/src/theme/typography.ts
> +const pxToRem = (
а эту утилу нельзя импортную откуда то из @mui/material/styles

2021-11-16 11:33 UTC, perevezencev commented on packages/ui/src/theme/typography.ts
> +  htmlFontSize: number | undefined = 14
htmlFontSize?:

2021-11-16 11:54 UTC, StanislavDa commented on packages/ui/src/theme/typography.ts
> +const pxToRem = (
неа, не вытаскивается

2021-11-17 07:11 UTC, AndTem approved these changes

2021-11-17 07:15 UTC, perevezencev approved these changes

2021-11-23 11:45 UTC, merged