bug(UIKIT-487,form,hooks): Убраны атрибуты RHF из DOM элементов формы
kaluga-astral/frontend pull request #500
Opened 2022-12-08 23:50 UTC by vinokurov-and

…тов формы

2022-12-09 05:19 UTC, AndTem requested changes

2022-12-09 05:19 UTC, AndTem commented on packages/form/src/hooks/useInputProps/useInputProps.tsx
> +export const useInputProps = <FieldProps extends FieldValues>(
Может стоит объединить useErrorProps и useInputProps в один хук?
Будет проще использовать

2022-12-09 09:11 UTC, vinokurov-and commented on packages/form/src/hooks/useInputProps/useInputProps.tsx
> +export const useInputProps = <FieldProps extends FieldValues>(
думаю да, но тогда мб и хук переименовать? но как, или так оставить?

2022-12-09 09:13 UTC, AndTem commented on packages/form/src/hooks/useInputProps/useInputProps.tsx
> +export const useInputProps = <FieldProps extends FieldValues>(
useFieldProps думаю вполне ок

2022-12-14 11:33 UTC, AndTem commented
@vinokurov-and напоминаю о висящем PR

2022-12-14 19:35 UTC, vinokurov-and commented on packages/form/src/hooks/useInputProps/useInputProps.tsx
> +export const useInputProps = <FieldProps extends FieldValues>(
Объединил useFieldErrorProps и useInputProps в один хук и назвал всё таки useFieldProps (при этом оставил два других), потому что:

- useFieldProps называется по аналогии с useFiedlErrorProps (без Form)
- useFieldErrorProps нужен к частных случаях типо FormDatePicker, там необходимо отдельно прокинуть ошибку в inputProps

2022-12-16 12:14 UTC, AndTem requested changes

2022-12-16 12:20 UTC, vinokurov-and commented on packages/form/src/hooks/useFieldProps/useFieldProps.ts
> +export const useFieldProps = <FieldProps extends FieldValues>(
> назовани сразу useFormFieldProps

тогда надо и в useFieldErrorProps менять название

2022-12-16 12:52 UTC, AndTem commented on packages/form/src/hooks/useFieldProps/useFieldProps.ts
> +export const useFieldProps = <FieldProps extends FieldValues>(
Да, и для inputProps.
Это связано с тем, что все будет экспортиться из единого пакета во второй версии

2022-12-16 12:57 UTC, vinokurov-and commented on packages/form/src/hooks/useFieldProps/useFieldProps.ts
> +export const useFieldProps = <FieldProps extends FieldValues>(
Ок

2022-12-16 13:13 UTC, AndTem commented on packages/form/src/hooks/useFieldProps/useFieldProps.ts
> +export const useFieldProps = <FieldProps extends FieldValues>(
Может сюда и ref добавить? Для rhf всегда ref нужен

2022-12-19 22:46 UTC, vinokurov-and commented on packages/form/src/hooks/useFieldProps/useFieldProps.ts
> +export const useFieldProps = <FieldProps extends FieldValues>(
> Может сюда и ref добавить? Для rhf всегда ref нужен

имеешь ввиду фильтровать сторонний ref здесь, чтобы не перезаписать ref от rhf?

2022-12-20 04:48 UTC, AndTem commented on packages/form/src/hooks/useFieldProps/useFieldProps.ts
> +export const useFieldProps = <FieldProps extends FieldValues>(
Имею в виду инкапсулировать useRef в этот хук

2023-01-09 13:07 UTC, vinokurov-and commented on packages/form/src/hooks/useFieldProps/useFieldProps.ts
> +export const useFieldProps = <FieldProps extends FieldValues>(
> Имею в виду инкапсулировать useRef в этот хук

я не понимаю зачем тут useRef?

2023-01-10 06:13 UTC, AndTem commented on packages/form/src/hooks/useFieldProps/useFieldProps.ts
> +export const useFieldProps = <FieldProps extends FieldValues>(
Для того, чтобы весь дублируемый код находился в одном хуке.
Это не только облегчит создание новый компонентов, но и исключит человеческий фактор (забыл ref)

2023-01-11 09:01 UTC, vinokurov-and commented on packages/form/src/hooks/useFieldProps/useFieldProps.ts
> +export const useFieldProps = <FieldProps extends FieldValues>(
> Для того, чтобы весь дублируемый код находился в одном хуке. Это не только облегчит создание новый компонентов, но и исключит человеческий фактор (забыл ref)

ты про это? 
![image](https://user-images.githubusercontent.com/48560509/211763013-56a25638-8b1a-4bb6-9d23-e904b30de2a6.png)

2023-01-11 09:08 UTC, AndTem commented on packages/form/src/hooks/useFieldProps/useFieldProps.ts
> +export const useFieldProps = <FieldProps extends FieldValues>(
@vinokurov-and да, мы же можем его инкапсулировать в useFormFieldProps ?

2023-01-11 09:09 UTC, vinokurov-and commented on packages/form/src/hooks/useFieldProps/useFieldProps.ts
> +export const useFieldProps = <FieldProps extends FieldValues>(
> @vinokurov-and да, мы же можем его инкапсулировать в useFormFieldProps ?

теперь понял, думаю, что да, попробую

2023-01-11 13:31 UTC, Sergeypro91 approved these changes

2023-02-21 14:40 UTC, vinokurov-and commented on packages/components/src/NavMenu/NavMenuItem/NavMenuItemButton/styles.ts
> +    }) ;
не знаю откуда это, убрать не могу, пишет "lint-staged prevented an empty git commit"

2023-02-21 14:45 UTC, AndTem approved these changes

2023-02-21 15:27 UTC, merged