feat(UIKIT-493,validations,isEmail): Добавлен валидатор email
kaluga-astral/frontend pull request #507
Opened 2022-12-16 02:52 UTC by aesarantsev

2022-12-16 06:08 UTC, AndTem requested changes

2022-12-16 06:08 UTC, AndTem commented on packages/validations/src/isEmail/isEmail.ts
> +export const DEFAULT_ERROR_MESSAGE = 'Некорректный E-mail';
Текста взяты из старого репозитория?

2022-12-16 06:09 UTC, aesarantsev commented on packages/validations/src/isEmail/isEmail.ts
> +export const DEFAULT_ERROR_MESSAGE = 'Некорректный E-mail';
Да, и регулярка тоже

2022-12-16 06:09 UTC, AndTem approved these changes

2022-12-16 06:18 UTC, m-av97 commented on packages/validations/src/isEmail/isEmail.test.ts
> +  it('Valid default invalid length message', () => {
Validate

2022-12-16 06:18 UTC, m-av97 commented on packages/validations/src/isEmail/isEmail.test.ts
> +  it('Valid custom message', () => {
Validate

2022-12-16 06:18 UTC, m-av97 commented on packages/validations/src/isEmail/isEmail.test.ts
> +  it('Valid custom invalid length message', () => {
Validate

2022-12-21 07:13 UTC, perevezencev approved these changes

2022-12-21 07:13 UTC, perevezencev commented
Апрувнул, но фиксации коменты Альберта, плз

2022-12-21 09:10 UTC, AndTem approved these changes

2022-12-22 07:46 UTC, merged