feat(UIKIT-93,ui,RangeDatePicker): новый компонент DateRangePicker
kaluga-astral/frontend pull request #522
Opened 2022-12-30 08:49 UTC by Ofigelov

2023-01-11 13:23 UTC, Sergeypro91 commented on packages/components/src/DateRangePicker/DateRangePicker.tsx
> +const DEFAULT_SPACING = 2;
Уточню для себя на будущее. Как Ты считаешь, со скольки констант стоит выносить их в отдельный файл ?

2023-01-11 14:09 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/DateCalendarGridBtn.tsx
> +    className={`${className} ${isInSelectedRange ? IS_IN_RANGE_CLASS : ''} ${
тут решил сделать с использованием классов, потому что нашел достаточно простой способ выкрутиться, чтобы добавить правильные скругления кнопкам по дизайну.
Вариант сделать это через чистый css-in-js выглядел бы слишком усложненным. Там прям было бы совсем сложно к пониманию, что происходит. А эффект не такой уж и важный.

2023-01-11 14:23 UTC, Sergeypro91 approved these changes

2023-01-12 09:25 UTC, vinokurov-and commented on packages/components/src/DatePicker/DatePickerPopper/DatePickerPopper.tsx
>    Omit<WithoutEmotionSpecific<PopperProps>, 'children'>
видимо в Omit надо добавить еще и 'disablePortal' и другие пропсы, которые находятся внизу под спредом props

2023-01-12 09:25 UTC, vinokurov-and commented on packages/components/src/DatePicker/DatePickerPopper/DatePickerPopper.tsx
> +import { Fade, PopperProps } from '@mui/material';
Может Popper стоит добавить как компонент в ui? Иногда он нужен и в проекте, когда нужно сделать что-то кастомное, плюс тут используется

2023-01-12 09:25 UTC, vinokurov-and commented on packages/components/src/DatePicker/DatePickerPopper/DatePickerPopper.tsx
> +import { Fade, PopperProps } from '@mui/material';
Fade есть у нас в ките, можно не из материала

2023-01-12 09:25 UTC, vinokurov-and commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtnLarge/styles.ts
> +    width: calc(100% - 32px);
что такое 32px

2023-01-12 10:19 UTC, Ofigelov commented on packages/components/src/DatePicker/DatePickerPopper/DatePickerPopper.tsx
> +import { Fade, PopperProps } from '@mui/material';
Можно, но это звучит как задача не относящаяся к текущему компоненту

2023-01-12 10:26 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtnLarge/styles.ts
> +    width: calc(100% - 32px);
ты хочешь сказать что надо использовать `theme.spacing`? 
или намекаешь на магическое число в стилях?

в первом случае: вроде договаривались для ширин и высот использовать пиксели

во втором: это же стили, тут магические числа на каждом шагу, давать всем числам в стилях описание странно, по всюду будет примерно одно и тоже, что то вроде "SIZE_BY_DESIGN", имхо, это будет оверхед

2023-01-13 07:43 UTC, vinokurov-and commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtnLarge/styles.ts
> +    width: calc(100% - 32px);
Я так понял это нижняя полоса в месяце и годе. По дизайну там вообще эта полоска размером с надпись, она не фиксированная

2023-01-13 07:43 UTC, vinokurov-and commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtnLarge/styles.ts
> +    width: calc(100% - 32px);
а если отвечать на твой вопрос, то я имел ввиду, что это за величина и почему 32, а не 24 например, судя по твоему ответу - это величина по дизайну, но по дизайну там не 32 (там динамический размер в зависимости от надписи).

2023-01-13 07:43 UTC, vinokurov-and commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtnLarge/styles.ts
> +    width: calc(100% - 32px);
хотя, тут конечно куда посмотреть... наверно, тут нужно выяснять у дизайнеров, что и как

![image](https://user-images.githubusercontent.com/48560509/212264469-62a6ba9c-e13a-4e56-85cf-463bc51aadae.png)

2023-01-13 07:43 UTC, vinokurov-and commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtnLarge/styles.ts
> +    width: calc(100% - 32px);
@Astral-design

2023-01-13 08:05 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtnLarge/styles.ts
> +    width: calc(100% - 32px);
я сделал так, чтобы полоска была бы с боковым отступом в 16px `left: 16px` и ширина полоски в 100% минус два раза по 16px, т.е. `wodth: calc(100% - 32px)`

2023-01-13 08:13 UTC, vinokurov-and commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtnLarge/styles.ts
> +    width: calc(100% - 32px);
Даша подправила макеты, теперь понятно, что слева и справа отступы везде фиксированные. Всё ок
![image](https://user-images.githubusercontent.com/48560509/212270788-bb3b83c9-7035-4794-badb-970c5d76fcb9.png)

2023-01-13 08:19 UTC, vinokurov-and commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtnLarge/styles.ts
> +    width: calc(100% - 32px);
> я сделал так, чтобы полоска была бы с боковым отступом в 16px `left: 16px` и ширина полоски в 100% минус два раза по 16px, т.е. `wodth: calc(100% - 32px)`

оставь, пожалуйста, комментарий там, что по дизайну с каждой стороны по 16px, чтобы в случае каких-либо правок не гадать и не искать в дизайне, что это за величина магическая

2023-01-13 08:36 UTC, perevezencev requested changes

2023-01-13 08:36 UTC, perevezencev commented on packages/components/src/DashboardLayout/Sidebar/styles.ts
> +    }) ;
👀

2023-01-13 08:36 UTC, perevezencev commented on packages/components/src/DatePicker/DateCalendar/DateCalendarBody/styles.ts
> +import { ELEMENTS_COUNT_IN_ROW_IN_LARGE_GRID } from '../../constants/counts';
Почему это в константе?

2023-01-13 08:36 UTC, perevezencev commented on packages/components/src/DatePicker/DateCalendar/DateCalendarBtnTooltip/DateCalendarBtnTooltip.tsx
> +}: DateCalendarBtnTooltipProps) =>
```
if (isActive) {
  return (
    <Tooltip title={title} disableInteractive>
       {children}
    </Tooltip>
  )
}

return children
```

2023-01-13 08:36 UTC, perevezencev commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/DateCalendarGridBtn.tsx
> +   * @description количество элементов в строке, требуется для стилизации
```требуется для стилизации``` это не обязательно для документации

2023-01-13 08:36 UTC, perevezencev commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/DateCalendarGridBtn.tsx
> +  isInSelectedRange?: boolean;
Чем отличаются isInSelectedRange от isOutOfAvailableRange?

2023-01-13 08:36 UTC, perevezencev commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/DateCalendarGridBtn.tsx
> +  isCurrent: boolean;
Если локальная то мб лучше `isLocalTime`

2023-01-13 08:36 UTC, perevezencev commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/DateCalendarGridBtn.tsx
> +    className={`${className} ${isInSelectedRange ? IS_IN_RANGE_CLASS : ''} ${
Тут не могу не согласиться с Сережей. По нашему гайдлайну мы используем styled. И я уверен что это будет выглядеть намного проще чем сейчас. 

PS 
для className в таком случае мы используем classnames or clsx

2023-01-13 08:36 UTC, perevezencev commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtnLarge/DateCalendarGridBtnLarge.tsx
> +export const DateCalendarGridBtnLarge = DateCalendarGridBtnLargeWrapper;
Для чего это нужно?

2023-01-13 08:36 UTC, perevezencev commented on packages/components/src/DatePicker/DateCalendar/DateCalendarBtnTooltip/DateCalendarBtnTooltip.tsx
> +export const DateCalendarBtnTooltip = ({
DateCalendarButtonTooltip

2023-01-13 08:36 UTC, perevezencev commented on packages/components/src/DatePicker/hooks/useMaskedValueAndSelectedBaseDate/useMaskedValueAndSelectedBaseDate.ts
> +  onDatePick: () => void;
Чем от `onChange` отличается?

2023-01-13 08:36 UTC, perevezencev commented on packages/components/src/DatePicker/hooks/useMaskedValueAndSelectedBaseDate/useMaskedValueAndSelectedBaseDate.ts
> +    onChangeMaskedDate(date);
onMaskedDateChange

2023-01-13 08:36 UTC, perevezencev commented on packages/components/src/DatePicker/hooks/useMaskedValueAndSelectedBaseDate/useMaskedValueAndSelectedBaseDate.ts
> +    onChangeMaskedValue(e.target.value);
`onMaskedValueChange`

2023-01-13 08:36 UTC, perevezencev commented on packages/components/src/DatePicker/hooks/useMaskedValueAndSelectedBaseDate/useMaskedValueAndSelectedBaseDate.ts
> +      onNativeChange: handleChangeMaskInput,
handleMaskedInputChange

2023-01-13 08:36 UTC, perevezencev commented on packages/components/src/utils/date/isDateOutOfRange/isDateOutOfRange.ts
> +  !((dateA >= date && date >= dateB) || (dateB >= date && date >= dateA));
`import { isWithinInterval } from 'date-fns'`

2023-01-13 08:36 UTC, perevezencev commented on packages/components/src/hooks/useInputPopperHooks/useInputPopperHooks.ts
> +export const useInputPopperHooks = ({
Зачем Hooks в конце?

2023-01-13 08:41 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarBody/styles.ts
> +import { ELEMENTS_COUNT_IN_ROW_IN_LARGE_GRID } from '../../constants/counts';
потому что это переиспользуется и в js и в css

2023-05-03 09:21 UTC, Ofigelov commented on packages/components/src/hooks/useInputPopperHooks/useInputPopperHooks.ts
> +export const useInputPopperHooks = ({
Потому что это хук объединяющий другие хуки.

2023-05-03 09:29 UTC, Ofigelov commented on packages/components/src/DatePicker/hooks/useMaskedValueAndSelectedBaseDate/useMaskedValueAndSelectedBaseDate.ts
> +  onDatePick: () => void;
отличие в том, что изменение значения инпута, не равно выбору даты в пикере. При выборе даты в пикере, нам надо закрывать поппер. А при измененеии даты в инпуте с клавиатуры, поппер не должен закрываться.

2023-05-03 09:34 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtnLarge/DateCalendarGridBtnLarge.tsx
> +export const DateCalendarGridBtnLarge = DateCalendarGridBtnLargeWrapper;
Просто реэкспорт из стилей, т.к. кнопка самодостаточная после того как ей добавили стили, ей не требуется доп логика, получается что это просто подготовка, чтобы ее можно было бы переиспользовать в других местах.
Не уверен как в таком случае должно выгладеть.

2023-05-03 09:37 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/DateCalendarGridBtn.tsx
> +  isInSelectedRange?: boolean;
Отличается предназначением. 
isInSelectedRange - дата в выбранном диапазоне.
isOutOfAvailableRange - дата вне диапазона, доступного к выбору, т.е. дата меньше чем minDate или больше чем maxDate

2023-05-03 09:42 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/DateCalendarGridBtn.tsx
> +  isInSelectedRange?: boolean;
![image](https://user-images.githubusercontent.com/59384103/235883063-819a8eb9-921d-4839-9f62-abeccb99544c.png)

2023-05-03 09:59 UTC, Ofigelov commented on packages/components/src/utils/date/isDateOutOfRange/isDateOutOfRange.ts
> +  !((dateA >= date && date >= dateB) || (dateB >= date && date >= dateA));
1. мы отказываемся от `date-fns`
2. я уже написал то что нужно в точности, и даже тесты для этого добавил. Считаю что не стоит заменять этот хелпер на что то стороннее, потому что на него опирается довольно много логики в данных компонентах, и при замене можно словить проблем.

2023-05-03 10:04 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/DateCalendarGridBtn.tsx
> +  /**
Тут не оч понял, что нужно сделать

2023-05-03 10:22 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/DateCalendarGridBtn.tsx
> +    className={`${className} ${isInSelectedRange ? IS_IN_RANGE_CLASS : ''} ${
Да, по гайдлайну это не камильфо. Но я не вижу как это сделать по простому через styled.
classnames/clsx нет в проекте.

2023-05-04 05:28 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/DateCalendarGridBtn.tsx
> +    className={`${className} ${isInSelectedRange ? IS_IN_RANGE_CLASS : ''} ${
посидел, еще подумал, вроде нашел вариант как сделать

2023-05-05 14:05 UTC, AndTem requested changes

2023-05-05 14:05 UTC, AndTem commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/styles.ts
> +  --radius-left: ${(props) => getLeftBorderRadius(props)};
Не понимаю зачем тут css vars, если ты функцию getLeftBorderRadius(props) можешь подставить просто вместо var(--radius-left)

2023-05-05 14:05 UTC, AndTem commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/styles.ts
> +  &:nth-of-type(${({ lengthInRow }) => lengthInRow}n + 1) {
нужен комментарий. Сложная верстка

2023-05-05 14:05 UTC, AndTem commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/styles.ts
> +  if (
Нужен коммент, очень сложная логика

2023-05-05 14:05 UTC, AndTem commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtnLarge/styles.ts
> +    width: calc(100% - 32px);
Если это отступ, то используй spacing

2023-05-05 14:05 UTC, AndTem commented on packages/components/src/DateRangePicker/DateRangePicker.tsx
> +  itemA?: DateItemProps;
startDateProps, endDateProps?

2023-05-05 14:05 UTC, AndTem commented on packages/components/src/DateRangePicker/DateRangePicker.tsx
> +      monthOffset: 1,
Что это значит? Почему 1?

2023-05-05 14:05 UTC, AndTem commented on packages/components/src/DateRangePicker/DateRangePicker.tsx
> +            maxDate={isDate(itemB.value) ? addDays(itemB.value, -1) : maxDate}
Вынеси эту логику в функцию и оставь коммент, Не понятно что здесь происходит

2023-05-05 14:13 UTC, AndTem commented
Нет автофокуса на второй инпут, когда выбрана начальная дата

2023-05-05 14:58 UTC, Ofigelov commented on packages/components/src/DateRangePicker/DateRangePicker.tsx
> +      monthOffset: 1,
я посчитал, что второй пикер должен отличаться от первого на 1 месяц. Требований к этому не выдвигалось, поэтому сделал так, как понял сам.

2023-05-05 15:02 UTC, Ofigelov commented
> Нет автофокуса на второй инпут, после выбора начальной даты

нужен автофокус именно на второй *инпут* после того как пользователь в первом *пикере* выбрал дату? Ты уверен что именно такое поведение ожидается?

2023-05-05 15:03 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarButtonTooltip/DateCalendarButtonTooltip.tsx
> +  if (isActive) {
завернуть компонент в мемо?

2023-05-05 15:20 UTC, AndTem commented
> > Нет автофокуса на второй инпут, после выбора начальной даты
> 
> 
> 
> нужен автофокус именно на второй *инпут* после того как пользователь в первом *пикере* выбрал дату? Ты уверен что именно такое поведение ожидается?

Да, разве это необычно?

2023-05-05 15:21 UTC, AndTem commented on packages/components/src/DatePicker/DateCalendar/DateCalendarButtonTooltip/DateCalendarButtonTooltip.tsx
> +  if (isActive) {
Это не поможет, из дерева компонент все равно будет вырываться.
Либо снаружи решение какое-то, либо key

2023-05-05 16:26 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/styles.ts
> +  --radius-left: ${(props) => getLeftBorderRadius(props)};
у нас 4 угла, два левых, два правых. В цсс нет свойства, которое бы указывало бы отдельно на левые углы, и отдельно на правые. В данной ситуации нужно именно так.
Если убираем цсс переменные, то получается что у нас будет в два раза чаще будут вызываться утилиты геренации.
вот для сравнения, как это будет выглядеть без цсс переменных
```
border-radius: ${(props) => getLeftBorderRadius(props)}
    ${(props) => getRightBorderRadius(props)}
    ${(props) => getRightBorderRadius(props)}
    ${(props) => getLeftBorderRadius(props)};

  &:nth-of-type(${({ lengthInRow }) => lengthInRow}n + 1) {
    border-bottom-left-radius: ${({ theme, isInSelectedRange }) =>
      isInSelectedRange ? theme.shape.small : ''};
    border-top-left-radius: ${({ theme, isInSelectedRange }) =>
      isInSelectedRange ? theme.shape.small : ''};
  }

  &:nth-of-type(${({ lengthInRow }) => lengthInRow}n) {
    border-bottom-right-radius: ${({ theme, isInSelectedRange }) =>
      isInSelectedRange ? theme.shape.small : ''};
    border-top-right-radius: ${({ theme, isInSelectedRange }) =>
      isInSelectedRange ? theme.shape.small : ''};
  }
```
Ты считаешь что это выглядит и читается лучше?

2023-05-05 16:38 UTC, Ofigelov commented
> > > Нет автофокуса на второй инпут, после выбора начальной даты
> > 
> > 
> > нужен автофокус именно на второй _инпут_ после того как пользователь в первом _пикере_ выбрал дату? Ты уверен что именно такое поведение ожидается?
> 
> Да, разве это необычно?

Я бы как пользователь вообще бы не ожидал такого поведения. Если я мышкой выбираю первый день, то и второй тоже выберу мышкой, авто фокус на втором инпуте мне вообще не пригодится. 
А если я с клавиатуры табом дотыкал до выбора дня в пикере, то после выбора первой даты я бы ожидал что фокус окажется во втором пикере, автофокус на инпуте мне не очень кстати придется. Тем более, что по дом дереву поппер с пикерами находится после обоих инпутов, и это значит, если мы закинем автофокус на второй инпут, мне, как пользователю, придется вновь табом протыкать весь первый пикер, чтобы попасть на второй, а там под 40кнопок. Это долго, я буду на нервах от того что мне уже пришлось кучу раз табом тыкать, а после такого автофокуса мне придется повторить этот подвиг. 
Вообще вся история с доступносью в дата пикере, это наверное отдельная задача. Надо бы какую то продуманную юзер стори, в которой будут описаны все требования того, как это должно работать, и уже тогда это можно брать на реализацию.

2023-05-06 05:57 UTC, Ofigelov commented on packages/components/src/hooks/useFocusAwayEffect/useFocusAwayEffect.ts
> +    if (!isActive || !node) {
может не произойти в каком случае?

2023-05-06 06:05 UTC, Ofigelov commented on packages/components/src/utils/date/isDateOutOfRange/isDateOutOfRange.ts
> +  dateA,
не соглашусь, потому что утилита предполагает сравнение дат в обе стороны, т.е. дата B может быть меньше даты А.
т.е. в таком случае дата А не является стартовой.

2023-07-06 08:41 UTC, Ofigelov commented on packages/components/src/hooks/useInputPopperHooks/useInputPopperHooks.ts
> +export const useInputPopperHooks = ({
почему? под капотом же используется именно `Popper` от `mui`

2023-07-06 08:44 UTC, Ofigelov commented on packages/components/src/DatePicker/MinMaxDateContext/MinMaxDateContext.tsx
> +export const DEFAULT_MIN_DATE = buildIsoDate({ year: 1900 });
надо, потому что контекст появляется позже, чем начинают использовать minDate и maxDate

2023-07-06 08:45 UTC, Ofigelov commented on packages/components/src/DatePicker/DatePicker.tsx
> +      minDate = DEFAULT_MIN_DATE,
Контекст появляется позже, чем начинают использоваться minDate и maxDate

2023-07-06 09:32 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarButtonTooltip/DateCalendarButtonTooltip.tsx
> +  if (isActive) {
поисследовал немного, и у меня сейчас не происходит анмаунта.
https://i.imgur.com/9XGCJIm.gif

2023-07-06 14:27 UTC, AndTem commented on packages/components/src/hooks/useInputPopperHooks/useInputPopperHooks.ts
> +export const useInputPopperHooks = ({
Потому что popper - это название либы, а popover - название ui элемента

2023-07-06 14:37 UTC, AndTem requested changes

2023-07-06 14:37 UTC, AndTem commented on packages/components/src/utils/date/isDateOutOfRange/isDateOutOfRange.ts
> +  dateA,
хм, понятно

2023-07-06 14:37 UTC, AndTem commented on packages/components/src/DatePicker/DateCalendar/DateCalendarButtonTooltip/DateCalendarButtonTooltip.tsx
> +  if (isActive) {
А isActive то меняется на гифке?

2023-07-06 14:37 UTC, AndTem commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/styles.ts
> +  --radius-left: ${(props) => getLeftBorderRadius(props)};
Убедил

2023-07-07 03:34 UTC, Ofigelov commented on packages/components/src/DatePicker/MinMaxDateContext/MinMaxDateContext.tsx
> +export const DEFAULT_MIN_DATE = buildIsoDate({ year: 1900 });
тоже не выйдет, т.к. контекст больше нужен для самих пикеров, нежели для всего компонента в целом. А у DateRangePicker аж два пикера, и у каждого свой контекст.

2023-07-07 03:40 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarButtonTooltip/DateCalendarButtonTooltip.tsx
> +  if (isActive) {
Нет, меняется только контент. Но я не вижу проблемы в том, что происходит перерендер для части кнопок, ведь так и задумано. Тултип, со всеми его обертками и доп вычислениями не требуется для disabled элемента.

2023-07-07 04:13 UTC, Ofigelov commented on packages/components/src/hooks/useFocusAwayEffect/useFocusAwayEffect.ts
> +    if (!isActive || !node) {
Когда isActive === false, я и не ожидаю что должно пойти выполнение эффекта до самого конца, потому что лишний eventListener и не нужен. Прикол же в том, что unmount часть эффекта вызывается каждый раз при изменении чего либо в его подписках. И именно поэтому, при изменении isActive из true в false, у нас сначала удалится eventListener, и только потом будет вызвано тело эффекта, в котором выполнение остановится, и новый эвент листенер не будет добавлен, и, следовательно, не требуется дополнительный unmount.
я создал пример в [codesandbox](https://codesandbox.io/s/xenodochial-borg-rzvd4s?file=/src/App.tsx), там в консоли явно видно, что колличество добавленных eventListener'ов равно колличеству удаленных.

2023-07-07 04:27 UTC, Ofigelov commented on packages/components/src/hooks/useInputPopperHooks/useInputPopperHooks.ts
> +export const useInputPopperHooks = ({
По [документации](https://mui.com/material-ui/react-popover/) `mui`, ключевое отличие `Popover` от `Popper` в том, что `Popover`, по сути своей - миниатюрное модальное окно, блокирующее всё что находится под ним, т.е. пользователь не может взаимодействовать с элементами интерфейса вне открывшегося элемента, и даже с текстовым инпутом, которое было инициатором появления `Popover`. 
`Popper` же позволяет более гибко настраивать его поведение, когда ему закрываться, и не блокирует элементы находящиеся снаружи.

2023-07-07 06:14 UTC, AndTem commented on packages/components/src/hooks/useInputPopperHooks/useInputPopperHooks.ts
> +export const useInputPopperHooks = ({
Предназначение одно и то же у них. По документации также.
Просто popover инкапсулирует готовый ui, а popper предоставляет только функционал без paper внутри

2023-07-07 06:15 UTC, AndTem commented on packages/components/src/hooks/useFocusAwayEffect/useFocusAwayEffect.ts
> +    if (!isActive || !node) {
Понял, не заметил, что после if идет подписка

2023-07-07 06:16 UTC, AndTem commented on packages/components/src/DatePicker/MinMaxDateContext/MinMaxDateContext.tsx
> +export const DEFAULT_MIN_DATE = buildIsoDate({ year: 1900 });
а почему нельзя в configContext это хранить?

2023-07-07 06:18 UTC, AndTem commented on packages/components/src/DatePicker/DateCalendar/DateCalendarButtonTooltip/DateCalendarButtonTooltip.tsx
> +  if (isActive) {
В чем смысл тогда твоей гифки и примера?
Изменение обертки при измении props - это минус производительность.
Если в данном случае не критично, то ок, но проблема все равно есть

2023-07-07 06:28 UTC, Ofigelov commented on packages/components/src/DatePicker/MinMaxDateContext/MinMaxDateContext.tsx
> +export const DEFAULT_MIN_DATE = buildIsoDate({ year: 1900 });
Потому что если хранить их в configContext тогда придется усложнять систему, чтобы кастомизировать отдельно взятый ДатаПикер.
И какой в этом особо смысл?
Все равно внутри пикеров это будет забираться из контекста самих пикеров, а не из конфиг контекста. По сути, мы не решим проблему единой точки входа, кмк, только увеличим зацепление.
Эти константы являются конечной точкой правды. А входные пропсы ДатаПикеров позволяют кастомизировать необходимые значения.

2023-07-07 06:33 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarButtonTooltip/DateCalendarButtonTooltip.tsx
> +  if (isActive) {
В твоем замечании, четко сказано, ` при перерендере происходит анмаунт`. Моя гифка, доказывает, что это не так.
По теме производительности - Разве существует другой способ заворачивать компонент в разные врапперы в зависимости от условий?

2023-07-07 06:51 UTC, AndTem commented on packages/components/src/DatePicker/DateCalendar/DateCalendarButtonTooltip/DateCalendarButtonTooltip.tsx
> +  if (isActive) {
Есть. Можно либо сделать так, чтобы tooltip был всегда, просто выключался, либо добавить доп. обертку с key

2023-07-07 07:21 UTC, AndTem commented on packages/components/src/DatePicker/DateCalendar/DateCalendarButtonTooltip/DateCalendarButtonTooltip.tsx
> +  if (isActive) {
Почитай два комментария выше.
"Если в данном случае не критично, то ок, но проблема все равно есть"
А tooltip у нас и так прокачан, есть prop withoutContainer

2023-07-07 07:37 UTC, Ofigelov commented on packages/components/src/hooks/useInputPopperHooks/useInputPopperHooks.ts
> +export const useInputPopperHooks = ({
т.е. нас устроит, что название компонента не сходится с тем, что у нас под капотом используется, и философия немного не сходится?

2023-07-07 07:40 UTC, AndTem commented on packages/components/src/hooks/useInputPopperHooks/useInputPopperHooks.ts
> +export const useInputPopperHooks = ({
Не вижу где не сходится философия. Я уже не раз писал, что название не должно указывать на реализацию.
Внешний пользователь не должен зависеть от mui конецептуально, а этот хук ведь из пакета экмпортируется

2023-07-07 07:46 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarButtonTooltip/DateCalendarButtonTooltip.tsx
> +  if (isActive) {
Если ок, то тогда резолвим коммент?

2023-07-07 10:58 UTC, AndTem requested changes

2023-07-07 10:58 UTC, AndTem commented on packages/components/src/hooks/useInputPopper/useInputPopper.ts
> +    _?: SyntheticEvent<Element, Event> | Event,
```suggestion
    event?: SyntheticEvent<Element, Event> | Event,
```

2023-07-07 11:06 UTC, Ofigelov commented on packages/components/src/hooks/useInputPopperHooks/useInputPopperHooks.ts
> +export const useInputPopperHooks = ({
переименовал

2023-07-07 11:11 UTC, AndTem commented on packages/components/src/hooks/useInputPopover/useInputPopover.ts
>    const [isOpenPopper, openPopper, closePopper] = useToggle({
Тут забыл заменить popper на popover

2023-07-07 11:34 UTC, AndTem approved these changes

2023-07-07 13:48 UTC, merged