feat(UIKIT-602,ui,SidebarButton): Реализован компонент SidebarButton
kaluga-astral/frontend pull request #526
Opened 2023-01-11 10:32 UTC by StanislavDa

2023-01-11 10:35 UTC, AndTem requested changes

2023-01-11 10:37 UTC, StanislavDa commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +  sidebarButton?: ReactElement;
ts ругается на ReactNode при cloneElement. А cloneElement нужен, шоб пропс прокинуть

2023-01-11 10:45 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +  sidebarButton?: ReactElement;
Используй контекст, зачем cloneElement

2023-01-11 10:46 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +  sidebarButton?: ReactElement;
header={<div><SidebarButton>создать</SidebarButton></div>}

2023-01-11 12:13 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +  sidebarButton?: ReactElement;
Я тебе наврал.
Там же не контекст используется а useLocalStorage.
https://github.com/kaluga-astral/frontend/blob/faba8cb5928b05ba5476f15d91c08d02e38463fd/packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx#L30

Необходимо просто вынести переиспользуемый хук useSidebar

2023-01-11 12:19 UTC, StanislavDa commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +  sidebarButton?: ReactElement;
он и так переиспользуемый, сейчас вопрос в том, как в кнопке получить ключ '@astral/ui::Sidebar::collapsedIn', который прокидывается в Sidebar

2023-01-11 12:25 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +  sidebarButton?: ReactElement;
Понял. Вот так через context можно раздать:
https://codesandbox.io/s/react-context-forked-9dhsio?file=/src/index.js

Просто внутри Sidebar делаешь Context.Provider, а Button сможет забирать этот контекст

2023-01-11 12:46 UTC, AndTem requested changes

2023-01-11 12:46 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +   * Кнопка главного действия в сайдбаре
description неверный и не хватает example

2023-01-11 12:46 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/SidebarButton/styles.ts
> +      !collapsedIn ? theme.spacing(2) : theme.spacing(0)} !important;
вместо important можешь попробовать && { margin-right: }

2023-01-11 12:46 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/SidebarProvider/SidebarProider.tsx
> +  collapsedIn: false,
может лучше isOpen?

2023-01-11 12:46 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/SidebarProvider/SidebarProider.tsx
> +  collapsedIn = true,
лишняя логика дефолтного значения

2023-01-11 12:47 UTC, AndTem commented
Запроси ревью у дизайнеров

2023-01-11 12:52 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/SidebarProvider/SidebarProider.tsx
> +  collapsedIn: false,
Context ведь только в одгом месте используется сейчас. Я именно про контекст

2023-01-11 13:13 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +   * Кнопка главного действия в сайдбаре
Ничего не изменилось

2023-01-12 06:05 UTC, AndTem approved these changes

2023-01-12 08:46 UTC, m-av97 commented on packages/components/src/DashboardLayout/Sidebar/SidebarButton/SidebarButton.tsx
> +        <Button ref={ref} isOpen={isOpen} {...props}>
SidebarButton

2023-01-12 08:46 UTC, m-av97 commented on packages/components/src/DashboardLayout/Sidebar/SidebarButton/styles.ts
> +export const Button = styled(UIKitButton)<ButtonProps>`
SidebarButton

2023-01-12 08:46 UTC, m-av97 commented on packages/components/src/DashboardLayout/Sidebar/SidebarProvider/SidebarProider.tsx
> +import { ReactNode, createContext } from 'react';
опечатка в названии файла

2023-01-12 08:49 UTC, StanislavDa commented on packages/components/src/DashboardLayout/Sidebar/SidebarButton/SidebarButton.tsx
> +        <Button ref={ref} isOpen={isOpen} {...props}>
Компонент SidebarButton называется, конфликт неймингов будет(

2023-01-12 09:22 UTC, m-av97 approved these changes

2023-01-12 09:23 UTC, merged