feat(UIKIT-603,ui,ErrorBoundary): Добавлен экспорт ErrorBoundary
kaluga-astral/frontend pull request #529
Opened 2023-01-12 14:37 UTC by StanislavDa

В ErrorBoundary теперь не нужно передавать captureException - он берется из контекста

2023-01-12 14:46 UTC, AndTem requested changes

2023-01-12 14:46 UTC, AndTem commented on packages/components/src/ErrorBoundary/ErrorBoundary.tsx
>  class ErrorBoundary extends React.Component<Props, State> {
Не хватает описания в jsdoc

2023-01-12 14:46 UTC, AndTem commented on packages/components/src/ErrorBoundary/ErrorBoundary.tsx
> +  context!: React.ContextType<typeof ConfigContext>;
configContext

2023-01-12 14:46 UTC, AndTem commented on packages/components/src/ErrorBoundary/ErrorBoundary.tsx
> +    const context = this.context;
можно же просто this.configContext.captureException, или дестркутуризацию. Ни к чему просто так ссылку копировать

2023-01-12 14:54 UTC, StanislavDa commented on packages/components/src/ErrorBoundary/ErrorBoundary.tsx
> +  context!: React.ContextType<typeof ConfigContext>;
Если context переименовать, там будет пусто. Возможно из-за этого

![image](https://user-images.githubusercontent.com/93906455/212099018-4c9af340-9c38-475b-a45e-f3a2e756ec77.png)

2023-01-13 05:28 UTC, AndTem requested changes

2023-01-13 05:28 UTC, AndTem commented on packages/components/src/ErrorBoundary/ErrorBoundary.tsx
> + * Компонент, который перехватывает ошибки в оберутых в него компонентах.
Добавь что он из не просто перехватывает, а отправляет ошибку в captureException

2023-01-13 05:29 UTC, AndTem approved these changes

2023-01-13 05:59 UTC, m-av97 approved these changes

2023-01-13 07:01 UTC, AndTem approved these changes

2023-01-13 07:01 UTC, merged