feat(UIKIT-622,ui,FlowButton): Добавлен компонент FlowButton
kaluga-astral/frontend pull request #536
Opened 2023-02-03 08:14 UTC by olewka40

2023-02-03 08:18 UTC, olewka40 commented
Принял решение сделать такие пропы, чилдрен это основной текст, чтобы не было расхождения с обычной кнопкой по апи , и smallText для маленького текста сверху. 
Не title потому что в моём понимании Title должен быть больше 
Не subTitle потому что он в моём понимании должен быть снизу

2023-02-03 08:39 UTC, AndTem requested changes

2023-02-03 08:39 UTC, AndTem commented on packages/components/src/FlowButton/FlowButton.test.tsx
> +import { describe, expect, it } from 'vitest';
Используем global

2023-02-03 08:39 UTC, AndTem commented on packages/components/src/FlowButton/FlowButton.tsx
> +          <Typography marginTop={1} variant="h6" color="white">
Не используем sx.
Отступ через styled.
Подобные конструкции размазывают стилизацию по рендеру и styles

2023-02-03 08:39 UTC, AndTem commented on packages/components/src/FlowButton/FlowButton.tsx
> +          <Typography marginTop={1} variant="h6" color="white">
Color из темы должен браться. Сейчас ты захардкодил

2023-02-03 08:39 UTC, AndTem commented on packages/components/src/FlowButton/styles.ts
> +  width: 300px;
Может min width?

2023-02-03 08:39 UTC, AndTem commented on packages/components/src/FlowButton/styles.ts
> +  display: flex;
Если сделаешь гридом, то и отступ не надо будет указывать.
И лишний контейнер кстати тоже не нужен тогда

2023-02-03 08:39 UTC, AndTem commented on packages/components/src/FlowButton/types.ts
> +  smallText: string;
Не хватает jsdoc

2023-02-03 08:39 UTC, AndTem commented on packages/components/src/FlowButton/types.ts
> +  smallText: string;
Не стоит по именовании на внешний вид подвязываться. Лучше на семантику.
Здесь targetText может подойти

2023-02-03 08:41 UTC, AndTem requested changes

2023-02-03 08:41 UTC, AndTem commented on packages/components/src/FlowButton/FlowButton.test.tsx
> +  it('Prop:loading: отображается лоадер', () => {
А в кнопке вообще loading состояние реализовано?

2023-02-06 06:29 UTC, olewka40 commented on packages/components/src/FlowButton/FlowButton.test.tsx
> +  it('Prop:loading: отображается лоадер', () => {
Нет

2023-02-06 06:36 UTC, AndTem commented on packages/components/src/FlowButton/FlowButton.test.tsx
> +  it('Prop:loading: отображается лоадер', () => {
Значит тест не актуален

2023-02-07 10:05 UTC, AndTem requested changes

2023-02-07 10:05 UTC, AndTem commented on packages/components/src/FlowButton/FlowButton.test.tsx
> +  it('Prop:loading: блокирует кнопку', () => {
Нет пропса loading

2023-02-07 10:05 UTC, AndTem commented on packages/components/src/FlowButton/FlowButton.tsx
> +import { FlowButtonProps } from './types';
По style guide пропав в файле компонента описываются

2023-02-07 10:05 UTC, AndTem commented on packages/components/src/FlowButton/FlowButton.tsx
> +        <Grid container justifyContent="flex-start" justifyItems="flex-start">
Flex-start, при этом используешь grid

2023-02-07 10:05 UTC, AndTem commented on packages/components/src/FlowButton/styles.ts
> +  display: flex;
Не используемый компонент

2023-02-07 10:05 UTC, AndTem commented on packages/components/src/FlowButton/styles.ts
> +  width: 300px;
Up

2023-02-07 10:05 UTC, AndTem commented on packages/components/src/FlowButton/types.ts
> +export type FlowButtonProps = ButtonProps & {
Убери лишние пропав из этой кнопки. size, loading, variant...
И в storybook args тоже лишние есть

2023-02-07 10:08 UTC, AndTem commented
Тесты упали

2023-02-08 09:19 UTC, AndTem approved these changes

2023-02-08 09:25 UTC, m-av97 approved these changes

2023-02-08 09:26 UTC, merged