feat(UIKIT-651,ui,Tag): Добавлен тип text для тега
kaluga-astral/frontend pull request #544
Opened 2023-02-13 10:12 UTC by aesarantsev

Реализовано две задачи:
feat(UIKIT-651,ui,Tag): Добавлен тип text для тега
feat(UIKIT-439,ui,Tag): Добавлен пропс размера для тега

size по умолчанию сделан small для обратной совместимости

2023-02-13 10:40 UTC, AndTem commented
В название пр добавь информацию про size, чтобы в changelog было видно

2023-02-13 10:43 UTC, AndTem requested changes

2023-02-13 10:43 UTC, AndTem commented on packages/components/src/Tag/enums.ts
> +export enum TagSizes {
Через union удобнее будет

2023-02-13 10:43 UTC, AndTem commented on packages/components/src/Tag/constants.ts
> +export const HEIGHTS = {
Не обязательно выносить в отдельный файл это. Можно написать в styles

2023-02-13 12:31 UTC, lordniken commented on packages/components/src/Tag/styles.ts
> +      return theme.spacing(1.5, 2);
Договаривались использовать только целые числа в `spacing`. Если в макете отступ не кратен 4, тогда его значение нужно уточнить у дизайнера

2023-02-14 05:23 UTC, aesarantsev commented on packages/components/src/Tag/styles.ts
> +      return theme.spacing(1.5, 2);
Убрал тут паддинги сверху и снизу, они были не нужны

2023-02-14 05:24 UTC, aesarantsev commented on packages/components/src/Tag/enums.ts
> +export enum TagSizes {
Имеешь ввиду сделать тип TagSize через union? 
enum TagSizes нам нужен, он используется и для типа и в логике установки стилей

2023-02-14 06:58 UTC, AndTem commented on packages/components/src/Tag/enums.ts
> +export enum TagSizes {
Для типа он используется костыльно, преобразуясь в итоге в union.
в логике тоже можно спокойно без enum прожить (size === 'small')

2023-02-14 07:20 UTC, aesarantsev commented on packages/components/src/Tag/enums.ts
> +export enum TagSizes {
Поправил

2023-02-14 07:22 UTC, AndTem commented on packages/components/src/Tag/styles.ts
> +const HEIGHTS: { [size in TagSize]: string } = {
Эту конструкцию можно заменить на Record<TagSize, string>

2023-02-14 07:22 UTC, AndTem approved these changes

2023-02-14 07:27 UTC, aesarantsev commented on packages/components/src/Tag/styles.ts
> +const HEIGHTS: { [size in TagSize]: string } = {
Готово

2023-02-14 07:27 UTC, lordniken approved these changes

2023-02-14 07:52 UTC, Astral-design approved these changes

2023-02-14 07:52 UTC, merged