feat(UIKIT-397,ui,Tag): Добавлен Badge для тега
kaluga-astral/frontend pull request #545
Opened 2023-02-14 08:05 UTC by aesarantsev

2023-02-14 08:12 UTC, AndTem requested changes

2023-02-14 08:12 UTC, AndTem commented on packages/components/src/Tag/styles.ts
> +    return 'white';
цвет из темы должен браться

2023-02-14 08:12 UTC, AndTem commented on packages/components/src/Tag/styles.ts
> +  const colors: { [tagColor in TagColor]: BadgeColor } = {
Recors<TagColor, BadgeColor>

2023-02-14 08:12 UTC, AndTem commented on packages/components/src/Tag/Tag.tsx
> +  badge?: string;
Думаю, что лучше сделать так:

<Tag label="" endAddon={<TagBadge />}  startAddon={<TagBadge />} />

Получим гибкость, возможность расширения и tree shaking

2023-02-14 08:12 UTC, AndTem commented on packages/components/src/Tag/Tag.tsx
> +      getBadgeColor({
Это должно быть внутри styled

2023-02-14 08:12 UTC, AndTem commented on packages/components/src/Tag/Tag.tsx
> +        {label}{' '}
Вместо пробела левый отступ надо делать для endAddon

2023-02-14 08:12 UTC, AndTem commented on packages/components/src/Badge/Badge.tsx
> +  withBorder?: boolean;
jsdoc

2023-02-14 08:13 UTC, AndTem commented on packages/components/src/Tag/Tag.tsx
> +  badge?: string;
То есть завести отдельный компонент TagBadge

2023-02-15 05:32 UTC, aesarantsev commented on packages/components/src/Tag/styles.ts
> +    return 'white';
Это не цвет. Это пропс для определения цвета, передаваемый в компонент

2023-02-15 06:20 UTC, AndTem requested changes

2023-02-15 06:20 UTC, AndTem commented on packages/components/src/TagBadge/styles.ts
> +}) => {
Нужен тип возвращаемого значения

2023-02-15 06:20 UTC, AndTem commented on packages/components/src/TagBadge/styles.ts
> +export const getCheckableTagBadgeBgColor = ({
Эта утаила не относится к styles. Выноси в Utils

2023-02-15 06:20 UTC, AndTem commented on packages/components/src/TagBadge/styles.ts
> +export const getCheckableTagBadgeBgColor = ({
И не хватает jsdoc описания для функции

2023-02-15 06:20 UTC, AndTem commented on packages/components/src/TagBadge/TagBadge.tsx
> +export const TagBadge = ({
Нужно jsdoc описание компонента

2023-02-15 06:20 UTC, AndTem commented on packages/components/src/TagBadge/TagBadge.stories.tsx
> +    <TagBadge color="primary" badgeContent={'12'} />
Он не должен существовать без Tag. Поэтому тут должно быть взаимодействие с Tag

2023-02-15 06:20 UTC, AndTem commented on packages/components/src/CheckableTag/CheckableTag.tsx
> +        <></>
Можно просто null

2023-02-15 06:20 UTC, AndTem commented on packages/components/src/CheckableTag/types.ts
> +export type CheckableTagAddonProps = {
Props описываются в файле компонента

2023-02-15 06:21 UTC, AndTem commented on packages/components/src/CheckableTag/CheckableTag.tsx
> +  startAddon?: CheckableTagAddon;
Добавь @example блок для jsdoc

2023-02-15 07:39 UTC, AndTem requested changes

2023-02-15 07:39 UTC, AndTem commented on packages/components/src/TagBadge/utils/getCheckableTagBadgeBgColor/getCheckableTagBadgeBgColor.ts
> + * @param {Object} disabled - Состояние disabled тега.
Параметры описывать не обязательно

2023-02-15 07:40 UTC, AndTem approved these changes

2023-02-15 07:46 UTC, m-av97 commented on packages/components/src/CheckableTag/CheckableTag.tsx
> +    const startAddonWithCheckable = (props: TagAddonProps) =>
Странное имя. Как будто еще слова не хватает в конце. Мб что-то типо checkableStartAddon

2023-02-15 08:18 UTC, m-av97 approved these changes

2023-02-15 08:42 UTC, Astral-design approved these changes

2023-02-15 08:44 UTC, merged