bug(UIKIT-656,ui,DataGridPagination): Исправлено кол-во записей на последней странице
kaluga-astral/frontend pull request #547
Opened 2023-02-15 12:57 UTC by StanislavDa

2023-02-15 13:00 UTC, AndTem requested changes

2023-02-15 13:00 UTC, AndTem commented on packages/components/src/DataGridPagination/DataGridPagination.tsx
> +  const rangeEnd = useMemo(() => {
Считаю, что нужно вынести в отдельную функцию и добавить комментов (не понятные расчеты).
Также нужен тест для компонента для на этот кейс

2023-02-15 13:12 UTC, StanislavDa commented on packages/components/src/DataGridPagination/DataGridPagination.tsx
> +   * Мксимальное количество записей на страницу
а этой штукой пользоваться можно? если да, то сообщение коммита дефолтное оставлять?)

2023-02-15 13:14 UTC, AndTem commented on packages/components/src/DataGridPagination/DataGridPagination.tsx
> +   * Мксимальное количество записей на страницу
Да, просто тыкай на кнопку

2023-02-15 13:19 UTC, StanislavDa commented on packages/components/src/DataGridPagination/DataGridPagination.tsx
> +  const rangeEnd = useMemo(() => {
чет смотрю и не вижу смысла в отдельную функцию что-то выносить, просто логика размажется =\

2023-02-15 14:30 UTC, AndTem commented on packages/components/src/DataGridPagination/DataGridPagination.test.tsx
> +  it('page=4, totalCount=31', () => {
Смотри [style guide](https://track.astral.ru/soft/wiki/pages/viewpage.action?pageId=3772645403#id-%D0%A2%D0%B5%D1%81%D1%82%D1%8B-%D0%9D%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D1%82%D0%B5%D1%81%D1%82-%D0%BA%D0%B5%D0%B9%D1%81%D0%B0%D0%BF%D1%80%D0%B8%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8props%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D0%BE%D0%B1%D1%8B%D1%82%D1%8C%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%BE%D0%BF%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D0%BE%D0%BC%D1%83%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D1%83)

2023-02-15 14:35 UTC, StanislavDa commented on packages/components/src/DataGridPagination/DataGridPagination.test.tsx
> +  it('page=4, totalCount=31', () => {
Там кейса с 2 пропсами нет( 
Так шоле: 'Props:page=3, Props:totalCount=26: Текст пагинации "21 — 24 из 24 записей"'
Или так: 'Props:totalCount=26: Текст пагинации "21 — 24 из 24 записей"'

2023-02-15 14:39 UTC, AndTem commented on packages/components/src/DataGridPagination/DataGridPagination.test.tsx
> +  it('page=4, totalCount=31', () => {
Props:page=5:count=2: отображается правильный каунтер

Еще можно через each сделать и не придется дублировать тест кейсы

2023-02-15 14:56 UTC, AndTem approved these changes

2023-02-16 06:48 UTC, lordniken approved these changes

2023-02-16 06:49 UTC, merged