feat(UIKIT-669,form,FormTextField): Добавлена возможность убрать пробелы
kaluga-astral/frontend pull request #553
Opened 2023-02-21 13:48 UTC by StanislavDa

2023-02-21 13:53 UTC, AndTem requested changes

2023-02-21 13:53 UTC, AndTem commented on packages/form/src/FormTextField/FormTextField.tsx
> +  trimmed?: boolean;
jsdoc

2023-02-21 13:53 UTC, AndTem commented on packages/form/src/FormTextField/FormTextField.tsx
> +  const { trimmed = true } = props;
лишний props в input попадет

2023-02-21 13:53 UTC, AndTem commented on packages/form/src/FormTextField/FormTextField.tsx
> +    field.onBlur();
event дальше должен протокнуться

2023-02-21 13:57 UTC, AndTem commented on packages/form/src/FormTextField/FormTextField.tsx
> +    field.onBlur();
Значит надо из пропсов забрать onBlur и вызвать его

2023-02-21 13:59 UTC, StanislavDa commented on packages/form/src/FormTextField/FormTextField.tsx
> +    field.onBlur();
типа 2 раза? и field.onBlur() и props.onBlur() ?

2023-02-21 14:00 UTC, AndTem commented on packages/form/src/FormTextField/FormTextField.tsx
> +    field.onBlur();
Да. Без этого ты не сможешь на onBlur подписаться из проекта

2023-02-21 14:03 UTC, StanislavDa commented on packages/form/src/FormTextField/FormTextField.tsx
> +    field.onBlur();
а есть разница в каком порядке их вызывать?

2023-02-21 14:04 UTC, AndTem commented on packages/form/src/FormTextField/FormTextField.tsx
> +    field.onBlur();
Нет

2023-02-21 14:08 UTC, AndTem requested changes

2023-02-21 14:14 UTC, StanislavDa commented on packages/form/src/FormTextField/FormTextField.tsx
> +  trimmed?: boolean;
не увидел, поправил

2023-02-21 14:37 UTC, AndTem commented on packages/form/src/FormTextField/FormTextField.tsx
> +  trimmed?: boolean;
Напиши, что это происходит на onblur

2023-02-21 14:39 UTC, StanislavDa commented on packages/form/src/FormTextField/FormTextField.tsx
> +  trimmed?: boolean;
готово

2023-02-21 14:45 UTC, AndTem approved these changes

2023-02-22 06:30 UTC, AndTem commented
Что-то с merge не то произошло

2023-02-22 06:31 UTC, StanislavDa commented
> Что-то с merge не то произошло

Конфликты были в текстфилде, вручную порешал

2023-02-22 06:55 UTC, vinokurov-and approved these changes
###

2023-02-22 06:55 UTC, merged