bug(UIKIT-682,FormTextField): Не пробрасывается ref
kaluga-astral/frontend pull request #567
Opened 2023-03-21 06:12 UTC by sk-iv

- исправлен inputProps.ref
В компонентах Autocomplete, DatePicker inputProps.ref пробрасывался корректно

2023-03-21 06:14 UTC, vinokurov-and approved these changes

2023-03-21 06:17 UTC, AndTem requested changes

2023-03-21 06:17 UTC, AndTem commented on packages/form/src/hooks/useFormFieldProps/useFormFieldProps.ts
> +  return { ...inputProps, ...field, ...errorProps, inputProps: { ref } };
Теперь получение ref сломалось для Autocomplete и DatePicker.
Надо для Autocomplete и DatePicker сделать проборос пропса ref={inputRef} и написать такой же тест, как и для TextField.
Проброс пропса необходим для обратной совместимости

2023-03-21 06:25 UTC, vinokurov-and commented on packages/form/src/hooks/useFormFieldProps/useFormFieldProps.ts
> +  return { ...inputProps, ...field, ...errorProps, inputProps: { ref } };
может быть ещё ситуация, что кому то понадобится прокинуть inputProps снаружи FormField компонента какого-нибудь

нужно видимо ещё что-то такое: return { ...inputProps, ...field, ...errorProps, inputProps: { ...inputProps.inputProps ,ref}}

или мы исключаем прокидывание inputProps в FormField ?

2023-03-21 06:27 UTC, AndTem commented on packages/form/src/hooks/useFormFieldProps/useFormFieldProps.ts
> +  return { ...inputProps, ...field, ...errorProps, inputProps: { ref } };
Не заметил, что здесь inputProps.
@sk-iv а почему не inputRef?

2023-03-22 06:48 UTC, sk-iv commented on packages/form/src/hooks/useFormFieldProps/useFormFieldProps.ts
> +  return { ...inputProps, ...field, ...errorProps, inputProps: { ref } };
исправила на inputRef

2023-03-22 06:55 UTC, sk-iv commented on packages/components/src/Autocomplete/Autocomplete.tsx
> +export const Autocomplete = forwardRef(AutocompleteInner) as <
пробросила корневой ref, тк в консоли была ошибка:
![image](https://user-images.githubusercontent.com/16607988/226825021-b13f04e7-4f1f-4a08-b9d5-2406ca9bc3fb.png)

2023-03-22 07:03 UTC, AndTem commented on packages/form/src/FormDatePicker/FormDatePicker.test.tsx
> +      const input = screen.getByRole('textbox', { name: /date/i });
вместо waitFor можно заюзать findBy (он работает с retry и timeout)

2023-03-22 07:03 UTC, AndTem approved these changes

2023-03-22 08:01 UTC, vinokurov-and approved these changes

2023-03-22 08:36 UTC, AndTem approved these changes

2023-03-22 08:58 UTC, merged