feat(UIKIT-672, features, cryptoPro): сервисы и компоненты для работы с КриптоПро
kaluga-astral/frontend pull request #569
Opened 2023-03-30 13:27 UTC by AlexadraLitvinenko

2023-03-31 12:10 UTC, AndTem requested changes

2023-03-31 12:10 UTC, AndTem commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/CertificatesRenderOptions/CertificatesRenderOptions.tsx
> +export const CertificatesRenderOptions =
```suggestion
export const CertificatesOptions =
```

2023-03-31 12:10 UTC, AndTem commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/CryptoProCertAutocomplete.stories.tsx
> +      <CryptoProCertAutocomplete
control должен принимать

2023-03-31 12:10 UTC, AndTem commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/CryptoProCertAutocomplete.tsx
> +export const CryptoProCertAutocomplete = <
По хорошему должен быть реализован autocomplete без формы, а потом уже отдельно коннектить к форме

2023-03-31 12:10 UTC, AndTem commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/CertificatesRenderOptions/transformCertificates/transformCertificates.ts
> +    type: certificate.subject.innLe
Вложенный тернарник - злло

2023-03-31 12:10 UTC, AndTem commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/CryptoProCertAutocomplete.tsx
> +export const CryptoProCertAutocomplete = <
В идеале иметь тест на этот компонент

2023-03-31 12:10 UTC, AndTem commented on packages/features/src/cryproPro/stores/CryptoProStore/CryptoProStore.ts
> +export class CryptoProStore {
Не хватает jsdoc описания для класса

2023-03-31 12:10 UTC, AndTem commented on packages/features/src/cryproPro/stores/CryptoProStore/CryptoProStore.ts
> +  public filterCertificateList = (
Не понял зачем этот метод.
Если ты хочешь дефолтное поведение сделать, то нужно использовать стратегию в методе getCertificateList

2023-03-31 12:10 UTC, AndTem commented on packages/features/src/cryproPro/services/CryptoProCertificateService/CryptoProCertificateService.ts
>  export class CryptoProCertificateService {
jsdoc нужен

2023-03-31 12:11 UTC, AlexadraLitvinenko commented on packages/features/package.json
> +    "@mui/material": "^5.10.12"
У нас нет в astral/ui Avatar компонента

2023-03-31 12:16 UTC, AndTem commented on packages/features/src/cryproPro/stores/CryptoProStore/CryptoProStore.ts
> +  public getCertificateList = async () => {
Подумал, пока не будем этого делать. Если появится потребность, то добавим states

2023-03-31 12:16 UTC, AndTem commented on packages/features/src/cryproPro/stores/CryptoProStore/CryptoProStore.ts
> +export class CryptoProStore {
И его методов

2023-03-31 12:25 UTC, AndTem commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/AutocompleteListItem/styles.ts
> +export const ItemIcon = styled(ListItemIcon)`
Название компонентов не по [style guide](https://track.astral.ru/soft/wiki/display/FG/React#React-%D0%94%D0%BB%D1%8Fstyledcomponents%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD%D0%BF%D1%80%D0%B8%D1%81%D1%83%D1%82%D1%81%D1%82%D0%B2%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D0%BF%D1%80%D0%B5%D1%84%D0%B8%D0%BA%D1%81-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D1%80%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%BE%D0%B3%D0%BE%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0)

2023-03-31 12:26 UTC, AndTem commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/AutocompleteListItem/AutocompleteListItem.tsx
> +                fontSize={14}
font-size из темы должен браться

2023-03-31 12:26 UTC, AndTem commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/AutocompleteListItem/AutocompleteListItem.tsx
> +                fontWeight={GROUP_FONT_WEIGHT}
из темы должно браться. Используй styled

2023-03-31 12:28 UTC, AndTem commented on packages/features/src/cryproPro/components/SetupCryptoProWorkspaceModal/CryptoproviderInfo/CryptoproviderInfo.tsx
> +          {!workspaceSetupInfo.isPluginInstalled ? (
Вложенный тернарник - зло

2023-03-31 12:28 UTC, AndTem commented on packages/features/src/cryproPro/components/SetupCryptoProWorkspaceModal/SetupCryptoProWorkspaceModal.tsx
> +  handleCloseButtonClick: () => void;
Все обработчики [должны](https://track.astral.ru/soft/wiki/display/FG/React#React-%D0%92%D1%81%D0%B5props%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%B8%D1%81%D0%BF%D1%80%D0%B5%D1%84%D0%B8%D1%81%D0%BA%D0%BE%D0%BCon) начинаться на on

2023-03-31 14:55 UTC, cryzer12 requested changes

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/package.json
> +    "@mui/material": "^5.10.12"
Про аватар жиза, надо реекспортнуть в основном пакете

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/AutocompleteListItem/AutocompleteListItem.tsx
> +                <OverflowTypography variant="div">
а что за variant div??

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/AutocompleteListItem/AutocompleteListItem.tsx
> +                  {inn}&bull;
а там в дизайне такая точка? (я просто не видел дизайн, за точку глаз зацепился)

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/AutocompleteListItem/styles.ts
> +    margin-left: 0 !important;
а без important никак не переопределяется?

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/AutocompleteListItem/styles.ts
> +export const AutocompleteListItemContent = styled(GroupControlLabel)`
а это не ошибка? зачем styled в этом же файле снова styled? нельзя правило просто наверх вынести?

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/CertificatesRenderOptions/CertificatesRenderOptions.tsx
> +        inn={`ИНН: ${certificate.inn} `}
а вот тут разве из transformCertificate возвращается разве не   inn: string | null; тип? вроде инн есть какой то случай, когда нет ИНН в серте, вроде Котович из АО5 о таком кейсе говорил

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/src/cryproPro/components/SetupCryptoProWorkspaceModal/CryptoproviderInfo/CryptoproviderInfo.tsx
> +import { Button, Description, Tooltip } from '@astral/components';
а не astral/ui? и много где так

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/src/cryproPro/constants/operation.ts
> +export const OperationTypeActions = {
и это тоже лишнее

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/src/cryproPro/constants/operation.ts
> +export const OperationTypeConfirmButtonText = {
Вот это похоже тоже не используется как и title

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/src/cryproPro/services/CryptoProCertificateService/CryptoProCertificateService.test.ts
> +  const certificatesList: Certificate[] = [
Может эту константу вынести куда-нибудь? а то тест сложнее читать

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/src/cryproPro/services/CryptoProCertificateService/CryptoProCertificateService.test.ts
> +    const certificates: FormatedCertificate[] = [
и вот эту вместе с ней вынести бы

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/src/cryproPro/services/CryptoProCertificateService/utils/getCertificateExpiresDate/getCertificateExpiresDate.ts
> +    return 'неизвестно';
надо наверно обсудить, а то надпись на серте Действует до неизвестно звучит не очень ux

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/src/cryproPro/services/CryptoProCertificateService/utils/getCertificateOwnerShortName/getCertificateOwnerShortName.ts
> +    return 'Неизвестно';
и тут тоже или прочерки обычно или вообще не показывать, возможно к дизайнерам вопросы

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/src/cryproPro/services/CryptoProCertificateService/utils/getCertificateType/getCertificateType.ts
> +      return 'ИП';
у тебя вроде enum появился для этих констант

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/src/cryproPro/services/CryptoProSignService/CryptoProSignService.ts
> +  public signCms = async (
оставлю [ссылчку ](https://github.com/kaluga-astral/services/tree/main/packages/cryptopro-cades/src/api) на апи методов, чтобы не искать

2023-03-31 14:55 UTC, cryzer12 commented on packages/features/src/cryproPro/stores/CryptoProStore/CryptoProStore.ts
> +  public filterCertificateList = (
@AndTem это же прокси просто (для Деметры той же самой, чтобы в кишки сервиса не лазить), чтобы использовать метод фильтрации (и потом еще добавим сортировки или даже лучше группировки) сертификатов, тебе пришли серты, а тебе надо отфильтровать их по определенному селектору (инн или что еще) для удобства и ты из стора вызываешь метод cert = filter(format(cert)) (для примера кейс написал) и у тебя будет только список необходимых сертов

2023-04-07 07:14 UTC, AlexadraLitvinenko commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/AutocompleteListItem/AutocompleteListItem.tsx
> +                  {inn}&bull;
Угу
https://www.figma.com/file/bflU9hxcjHjifwtb3xvsTg/%D0%9A%D0%AD%D0%94%D0%9E-(%D0%90%D0%BA%D1%82%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9)?node-id=8159-285190&t=gwwwv5gnan4WocM0-0

2023-04-07 07:44 UTC, AlexadraLitvinenko commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/CryptoProCertAutocomplete.stories.tsx
> +        getOptionLabel={(option) => option.subject.commonName as string}
На счет дефолтного отображения схожу к дизайнерам и подниму вопрос на следующем груме, возможность переопределить сейчас есть - getOptionLabel тут в примере для сторибука

2023-04-07 07:53 UTC, AlexadraLitvinenko commented on packages/features/src/cryproPro/services/CryptoProCertificateService/utils/getCertificateExpiresDate/getCertificateExpiresDate.ts
> +    return 'неизвестно';
Окей, обсудим

2023-04-11 06:13 UTC, AndTem requested changes

2023-04-11 06:19 UTC, AndTem commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/AutocompleteListItem/styles.ts
> +    checked && 'background-color: ' + theme.palette.primary[100] + ';'}
читай [style guide](https://track.astral.ru/soft/wiki/pages/viewpage.action?pageId=3557425260#id-%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5%D1%82%D0%B8%D0%BF%D0%BE%D0%B2-%D0%94%D0%BB%D1%8F%D1%81%D0%BA%D0%BB%D0%B5%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%BD%D0%B5%D0%BE%D0%B1%D1%85%D0%BE%D0%B4%D0%B8%D0%BC%D0%BE%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%BE%D0%B2%D1%8B%D0%B9%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD)

2023-04-11 06:55 UTC, AlexadraLitvinenko commented on packages/features/src/cryproPro/components/CryptoProCertFormAutocomplete/CryptoProCertFormAutocomplete.stories.tsx
> +        getOptionLabel={(option) => option.subject.commonName as string}
А если захотят по другому в других проектах выводить?

2023-04-11 06:58 UTC, AndTem commented on packages/features/src/cryproPro/components/CryptoProCertFormAutocomplete/CryptoProCertFormAutocomplete.stories.tsx
> +        getOptionLabel={(option) => option.subject.commonName as string}
@AlexadraLitvinenko Дефолтный getOptionLabel внутри + возможность переопределить

2023-04-11 07:48 UTC, AlexadraLitvinenko commented on packages/features/src/cryproPro/stores/CryptoProStore/CryptoProStore.ts
> +   * @description Форматированный список сертификатов
Для другого проекта, чтоб их интерфейс для сертификатов не потерять и им не пришлось в кишки лезть

2023-04-11 07:50 UTC, AlexadraLitvinenko commented on packages/features/src/cryproPro/components/SetupCryptoProWorkspaceModal/styles.ts
> +export const WorkspaceInfoItem = styled.div`
Он используется в CryptoproviderInfo и в PluginInfo

2023-04-11 07:52 UTC, AlexadraLitvinenko commented on packages/features/src/cryproPro/components/SetupCryptoProWorkspaceModal/PluginInfo/PluginInfo.tsx
> +import { WorkspaceInfoItem } from '../styles';
Так как этот стилизованный компонент переиспользуется в двух компонентах - он вынесен в директорию на один уровень выше

2023-04-11 08:13 UTC, AlexadraLitvinenko commented on packages/features/src/cryproPro/services/CryptoProCertificateService/constants.ts
> +export const formatedCertificatesList: FormatedCertificate[] = [
https://github.com/kaluga-astral/frontend/pull/569#discussion_r1154563995

2023-04-11 08:15 UTC, AndTem commented on packages/features/src/cryproPro/stores/CryptoProStore/CryptoProStore.ts
> +   * @description Форматированный список сертификатов
Это должно быть написано в jsdoc

2023-04-11 08:16 UTC, AndTem commented on packages/features/src/cryproPro/services/CryptoProCertificateService/constants.ts
> +export const formatedCertificatesList: FormatedCertificate[] = [
Либо __stubs__ директория, либо внутри теста. Оставь внутри теста

2023-04-11 08:16 UTC, AndTem commented on packages/features/src/cryproPro/components/SetupCryptoProWorkspaceModal/PluginInfo/PluginInfo.tsx
> +import { WorkspaceInfoItem } from '../styles';
Так он используется только в одном компоненте

2023-04-11 09:26 UTC, AlexadraLitvinenko commented on packages/features/src/cryproPro/services/CryptoProCertificateService/utils/getCertificateType/getCertificateType.ts
> +import { CertificateType } from '../../../../components/CryptoProCertAutocomplete/enums';
Тут enum просто переиспользуется, вынесу его наверх

2023-04-11 09:40 UTC, AlexadraLitvinenko commented on packages/features/src/cryproPro/components/SetupCryptoProWorkspaceModal/SetupCryptoProWorkspaceModal.tsx
> +    workspaceSetupStore
Это не стор, а сервис, название у свойства некорректное - заменю

2023-04-11 09:54 UTC, AlexadraLitvinenko commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/CertificatesRenderOptions/CertificatesOptions.tsx
> +  (disabled: boolean = false) =>
В пропасах mui нет необходимых полей, дешевле сделать каррирование, чем переопределять renderOption для автокомплита своего

2023-04-11 10:07 UTC, AlexadraLitvinenko commented on packages/features/src/cryproPro/components/SetupCryptoProWorkspaceModal/PluginInfo/PluginInfo.tsx
> +import { WorkspaceInfoItem } from '../styles';
В PluginInfo и в CryptoproviderInfo

2023-04-11 10:09 UTC, AndTem commented on packages/features/src/cryproPro/components/SetupCryptoProWorkspaceModal/SetupCryptoProWorkspaceModal.tsx
> +    workspaceSetupStore
А зачем тут сервис? Это должна быть просто view без прямого взаимодействия с сервисами

2023-04-11 10:41 UTC, AndTem commented on packages/features/src/cryproPro/components/CryptoProCertAutocomplete/CertificatesRenderOptions/CertificatesOptions.tsx
> +  (disabled: boolean = false) =>
Я понял, это функция, которая компонент должна возвращать.
Удобнее для восприятия было бы перенести эту функцию прямо в тот комопонент, где это сейчас вызывается

2023-04-11 14:07 UTC, AlexadraLitvinenko commented on packages/features/src/cryproPro/components/SetupCryptoProWorkspaceModal/SetupCryptoProWorkspaceModal.tsx
> +    workspaceSetupStore
А откуда она будет получать актуальную информацию о криптопровайдере? Вне этого компонента вести взаимодействие с сервисом внутри каждого проекта?

2023-04-11 14:45 UTC, AndTem requested changes

2023-04-11 14:45 UTC, AndTem commented on packages/features/src/cryproPro/components/CryptoProProvider/CryptoProProvider.tsx
> +            cryptoProStore.isRequestSetupWorkspace &&
isRequestSetupWorkspace не должен быть true, если isPluginInstalled === false. Логика размазывается сейчас

2023-04-12 11:53 UTC, AndTem approved these changes

2023-04-12 12:06 UTC, merged