feat(UIKIT-543, FormCheckbox): Добавлен проп hideHelperText
kaluga-astral/frontend pull request #572
Opened 2023-04-05 14:15 UTC by yar-stun

2023-04-05 14:23 UTC, AndTem requested changes

2023-04-05 14:23 UTC, AndTem commented on packages/form/src/FormCheckbox/FormCheckbox.tsx
> +  hideHelperText?: boolean;
Необходимо jsdoc описание

2023-04-06 05:13 UTC, AndTem approved these changes

2023-04-10 12:15 UTC, StanislavDa approved these changes

2023-04-10 12:24 UTC, merged