refactor(UIKIT-181): Рефакторинг ButtonBase, Button, IconButton
kaluga-astral/frontend pull request #588
Opened 2023-05-15 13:24 UTC by vinokurov-and

2023-05-16 06:55 UTC, sk-iv commented on packages/components/src/Button/Button.tsx
> +import { WithoutEmotionSpecific } from '../types';
импортируется тип, возможно это явно надо указать `import type { WithoutEmotionSpecific } from '../types';`

2023-05-16 07:12 UTC, sk-iv commented on packages/components/src/IconDropdownButton/IconDropdownButton.tsx
> +import { IconButton, IconButtonProps } from '../IconButton';
`import { IconButton, type IconButtonProps } from '../IconButton';`

2023-05-16 07:14 UTC, sk-iv commented on packages/components/src/PageHeader/PageHeader.tsx
> +import { ButtonProps } from '../Button';
`import type { ButtonProps } from '../Button';`

2023-05-16 07:30 UTC, sk-iv commented on packages/components/src/theme/components/MuiLoadingButton.ts
> +import { ButtonProps, ButtonStates } from '../../Button';
`import { type ButtonProps, ButtonStates } from '../../Button';`

2023-05-16 08:11 UTC, sk-iv approved these changes

2023-05-17 15:18 UTC, AndTem requested changes

2023-05-17 15:18 UTC, AndTem commented on packages/components/src/theme/components/MuiButtonBase.ts
> +      fontFamily: 'Ubuntu, serif',
theme.typography.fontFamily

2023-05-19 07:26 UTC, AndTem approved these changes

2023-05-22 08:13 UTC, AndTem approved these changes

2023-05-22 08:19 UTC, merged