feat(UIKIT-628,ui,Description): Добавлены пропсы justifyContent и leader
kaluga-astral/frontend pull request #589
Opened 2023-05-16 12:15 UTC by olewka40

2023-05-16 13:31 UTC, AndTem requested changes

2023-05-16 13:34 UTC, AndTem commented on packages/components/src/Description/styles.ts
> +  margin-right: ${({ theme }) => theme.spacing(1)};
На макет отступ в 8 px

2023-05-17 04:35 UTC, olewka40 commented on packages/components/src/Description/styles.ts
> +export const DashedSeparator = styled.div`
DescriptionDashedSeparator ?

2023-05-17 04:38 UTC, olewka40 commented on packages/components/src/Description/Name/Name.tsx
> +      {leader && <DashedSeparator />}
![image](https://github.com/kaluga-astral/frontend/assets/35649223/53b30cf8-ac92-4183-994a-aecd10427e9f)
так ?

2023-05-17 06:13 UTC, AndTem commented on packages/components/src/Description/styles.ts
> +export const DashedSeparator = styled.div`
Да

2023-05-17 07:56 UTC, AndTem requested changes

2023-05-17 07:56 UTC, AndTem commented on packages/components/src/Description/Description.tsx
> +   * пропс justifyContent, который позиционирует элементы либо по разным краям, либо по левому краю
```suggestion
   * Позиционирует элементы либо по разным краям, либо по левому краю
```

2023-05-17 07:59 UTC, olewka40 commented on packages/components/src/Description/Name/Name.tsx
> +        {children}:&nbsp;
тогда без лидера надо убирать пробел, а с ним оставлять, тк текст будет вплотную при старте

2023-05-18 07:14 UTC, lordniken commented on packages/components/src/Description/styles.ts
> +    justifyContent ? justifyContent : 'start'};
Этот тернарник для чего тут? Если `start` это default value лучше перенести его в деструктуризацию пропсов на уровне компонента

2023-05-18 07:25 UTC, lordniken approved these changes

2023-05-18 07:36 UTC, merged