feat(UIKIT-758,ui,DataGrid): Ячейки приведены к единой начальной высоте 44px
kaluga-astral/frontend pull request #590
Opened 2023-05-17 09:10 UTC by StanislavDa

2023-05-17 09:15 UTC, AndTem requested changes

2023-05-17 09:15 UTC, AndTem commented on packages/components/src/theme/components/MuiTableCell.ts
> +        height: 44,
Не minHeight?

2023-05-17 09:17 UTC, StanislavDa commented on packages/components/src/theme/components/MuiTableCell.ts
> +        height: 44,
minHeight не работает. Я проверял, если контент ячейки больше 44px, то эта ячейка растягивается по высоте

2023-05-17 09:23 UTC, AndTem commented on packages/components/src/theme/components/MuiTableCell.ts
> +        height: 44,
Оставь комментарий почему именно 44px

2023-05-17 09:28 UTC, StanislavDa commented on packages/components/src/theme/components/MuiTableCell.ts
> +        height: 44,
дык потому что в дизайн-системе 44px, думаешь, стоит указать?

2023-05-17 09:43 UTC, AndTem commented on packages/components/src/theme/components/MuiTableCell.ts
> +        height: 44,
Стоит оставить коммент для чего эта высота здесь указана. Какую проблему решает

2023-05-17 09:44 UTC, AndTem commented on packages/components/src/theme/components/MuiTableCell.ts
> +        height: 44,
Понял. Оставь коммент тогда что это минимальная высота ячейки так задается

2023-05-17 09:47 UTC, AndTem approved these changes

2023-05-18 09:07 UTC, cryzer12 approved these changes

2023-05-18 09:15 UTC, merged