feat(UIKIT-514,ui,Checkbox): Добавлено состояние error и сторибук
kaluga-astral/frontend pull request #592
Opened 2023-05-22 09:19 UTC by YrStudenikin

2023-05-22 10:54 UTC, AndTem requested changes

2023-05-22 10:54 UTC, AndTem commented on packages/components/src/Checkbox/Checkbox.stories.tsx
> +      <Checkbox disabled />
Storybook должен быть реализован в соответствии с макетом (в задаче ссылка прикреплена).
Делать по аналогии с [Button](https://github.com/kaluga-astral/frontend/blob/main/packages/components/src/Button/Button.stories.tsx)

2023-05-22 10:54 UTC, AndTem commented on packages/components/src/Checkbox/types.ts
>  export type CheckboxProps = Omit<
Взялся за компонент - проведи рефакторинг.
Типы описаны не по [style guide](https://track.astral.ru/soft/wiki/display/FG/React#React-Typeprops%D0%B4%D0%BB%D1%8F%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD%D0%BD%D0%B0%D1%85%D0%BE%D0%B4%D0%B8%D1%82%D1%81%D1%8F%D0%B2%D1%84%D0%B0%D0%B9%D0%BB%D0%B5%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0)

2023-05-22 10:54 UTC, AndTem commented on packages/components/src/Checkbox/types.ts
> +> & { error?: boolean };
jsdoc нужен

2023-05-22 10:54 UTC, AndTem commented on packages/components/src/Checkbox/styled.tsx
> +import { Checkbox, css } from '@mui/material';
Название файла и компонента не по[ style guide](https://track.astral.ru/soft/wiki/display/FG/React#React-%D0%92%D1%81%D0%B5%D1%81%D1%82%D0%B8%D0%BB%D0%B8%D0%B4%D0%BB%D1%8Freactcomponents%D0%B2%D1%8B%D0%BD%D0%BE%D1%81%D1%8F%D1%82%D1%81%D1%8F%D0%B2%D0%BE%D1%82%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9%D1%84%D0%B0%D0%B9%D0%BBstyles,%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B9%D0%BD%D0%B0%D1%85%D0%BE%D0%B4%D0%B8%D1%82%D1%81%D1%8F%D1%80%D1%8F%D0%B4%D0%BE%D0%BC%D1%81%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%BC%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0)

2023-05-22 10:54 UTC, AndTem commented on packages/form/src/FormCheckbox/FormCheckbox.tsx
> +      <Tooltip
Tooltip в рендере должен быть только если hideHelperText === true. В противном случае нет смысла его рендерить

2023-05-22 11:12 UTC, YrStudenikin commented on packages/form/src/FormCheckbox/FormCheckbox.tsx
> +      <Tooltip
Я как раз воспользовался возможностью рендера тултипа через тайтл. Из доки:

![image](https://github.com/kaluga-astral/frontend/assets/62848436/bc0a73fc-38a4-4843-b6b6-ddad1b248c5d)

Мне кажется в этом случае это более визуально чистое решение

2023-05-22 11:14 UTC, YrStudenikin commented on packages/form/src/FormCheckbox/FormCheckbox.tsx
> +      <Tooltip
Тултипа не будет в dom, проверял

2023-05-22 11:41 UTC, AndTem commented on packages/form/src/FormCheckbox/FormCheckbox.tsx
> +      <Tooltip
ок

2023-05-24 06:59 UTC, AndTem requested changes

2023-05-24 06:59 UTC, AndTem commented on packages/components/src/Checkbox/Checkbox.tsx
> +  /**
коммент не в том месте находится. Должен быть для свойства, а сейчас просто висит в воздухе

2023-05-24 06:59 UTC, AndTem commented on packages/form/src/FormCheckbox/FormCheckbox.stories.tsx
>  const Template: Story = () => {
Давай в этот storybook добавим последний раздел validation из Checkbox.stories.
Позже сделаем CheckboxField, который будет инкапуслировать FormControl, Tooltip и тп

2023-05-24 07:02 UTC, YrStudenikin commented on packages/components/src/Checkbox/Checkbox.tsx
> +  /**
Точно, визуально не обратил внимание

2023-05-24 07:03 UTC, YrStudenikin commented on packages/form/src/FormCheckbox/FormCheckbox.stories.tsx
>  const Template: Story = () => {
в checkbox.stories может переименовать раздел validation -> error state? Как-то так

2023-05-24 07:04 UTC, AndTem commented on packages/form/src/FormCheckbox/FormCheckbox.stories.tsx
>  const Template: Story = () => {
Лучше сделать так, как на макете

2023-05-24 07:20 UTC, YrStudenikin commented on packages/form/src/FormCheckbox/FormCheckbox.stories.tsx
>  const Template: Story = () => {
У нас же в Checkbox нет отображения тултипа и текста, сейчас это в FormCheckbox. А на макетах как раз показан вариант для обычного чекбокса. Тут можно было бы отобразить только состояние error

![image](https://github.com/kaluga-astral/frontend/assets/62848436/ac7f7446-68a2-4383-b557-f6cddbedea16)

2023-05-24 07:57 UTC, AndTem commented on packages/form/src/FormCheckbox/FormCheckbox.stories.tsx
>  const Template: Story = () => {
Не понимаю предмета спора. Навазние раздела?

2023-05-25 07:18 UTC, AndTem approved these changes

2023-05-26 04:07 UTC, StanislavDa approved these changes

2023-05-26 06:24 UTC, merged