feat(UIKIT-442,ConfigProvider): Добавлены в ConfigProvider ссылки на …
kaluga-astral/frontend pull request #595
Opened 2023-05-26 06:38 UTC by sk-iv

…иллюстрации

- оставила возможность переопределить глобальное изображение локально у DataGrid, ContentState

2023-05-26 07:15 UTC, AndTem commented on packages/components/src/ConfigProvider/ConfigProvider.tsx
> +    'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAyNi4wLjMsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxk
Пусть будет также undefined, как и для ошибок. Это braking changes, будем прокидывать в продукте картинку

2023-05-29 12:57 UTC, lordniken commented on packages/components/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> +  title = 'Нет\u00a0данных',
Стоит оставить коммент про неразрывный пробел

2023-05-29 12:57 UTC, lordniken commented on packages/components/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> +  const { noDataImgSrc } = useContext(ConfigContext).imagesMap;
```
const { imagesMap } = useContext(ConfigContext)
```

2023-05-29 15:07 UTC, sk-iv commented on packages/components/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> +  title = 'Нет\u00a0данных',
Оставила коммент выше в 14 строке

2023-05-30 07:20 UTC, AndTem requested changes

2023-05-30 07:20 UTC, AndTem commented on packages/components/src/DataGrid/DataGridNoData/DataGridNoData.tsx
> +  noDataIcon?: string;
Этого пропса не должо быть больше. Заменили на src

2023-05-30 07:20 UTC, AndTem commented on packages/components/src/ContentState/types.ts
>     * Изображение ошибки
добавь коммент, что по дефолту из ConfigProvider забирается

2023-05-30 07:20 UTC, AndTem commented on packages/components/src/ConfigProvider/ConfigProvider.tsx
> +   * @description карта для типовых изображений
Нужно еще пояснение, что эти изображения подставляются в компоненты

2023-05-31 06:40 UTC, AndTem requested changes

2023-05-31 06:40 UTC, AndTem commented on packages/components/src/ConfigProvider/ConfigProvider.tsx
> +   * @description карта для типовых изображений
up

2023-05-31 06:41 UTC, AndTem commented
Добавь, пожалуйста, краткое описание braking changes в описании PR. Чтобы я потом смог быстро migration guide написать

2023-05-31 06:47 UTC, sk-iv commented on packages/components/src/ConfigProvider/ConfigProvider.tsx
> +   * @description карта для типовых изображений
а я же выше в type ImagesMap писала в каких компонентах они используются. Или тут надо написать: 'карта для типовых изображений, которые использубтся в компонентах DataGrid, ContentState'?

2023-05-31 06:49 UTC, AndTem commented on packages/components/src/ConfigProvider/ConfigProvider.tsx
> +   * @description карта для типовых изображений
Как-то так: 'карта для типовых изображений, которые будут использоваться в компонентах ui-kit, отображающие изображения'

2023-05-31 07:49 UTC, AndTem approved these changes

2023-05-31 07:50 UTC, perevezencev approved these changes

2023-05-31 07:52 UTC, merged