feat(UIKIT-782,ui,Typography): Удалены стилевые пропсы из Typography, рефакторинг storybook
kaluga-astral/frontend pull request #602
Opened 2023-06-19 10:02 UTC by agro196

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2023-06-19 10:56 UTC, AndTem requested changes

2023-06-19 10:56 UTC, AndTem commented on packages/components/src/Typography/Typography.tsx
> +  keyof SystemProps<Theme> | 'sx' | 'classes' | 'variantMapping' | 'css'
Добавь комментарий что здесь происходит

2023-06-19 11:46 UTC, agro196 commented on packages/components/src/Typography/Typography.tsx
> +  keyof SystemProps<Theme> | 'sx' | 'classes' | 'variantMapping' | 'css'
Добвил коммент в код, надо было сюда походу?)

2023-06-19 12:35 UTC, AndTem commented on packages/components/src/Typography/Typography.tsx
> +  keyof SystemProps<Theme> | 'sx' | 'classes' | 'variantMapping' | 'css'
Нет, в коде

2023-06-19 12:38 UTC, AndTem commented on packages/components/package.json
> +    "@mui/system": "5.13.5",
Какое-то странное изменение. В main ветке версия: 5.13.0

2023-06-19 12:45 UTC, agro196 commented on packages/components/package.json
> +    "@mui/system": "5.13.5",
<img width="1299" alt="image" src="https://github.com/kaluga-astral/frontend/assets/65020968/d4235ea6-9eb6-4c3b-bb93-28ae9daeb8f3">
если 5.13.0 сделать то крашится при установке зависимостей

2023-06-19 13:01 UTC, AndTem commented on packages/components/package.json
> +    "@mui/system": "5.13.5",
Это локальная проблема. Все пакеты mui должны быть одной версии

2023-06-19 13:12 UTC, agro196 commented on packages/components/package.json
> +    "@mui/system": "5.13.5",
и как в таком случае лучше поступить?

2023-06-19 13:48 UTC, agro196 commented on packages/components/package.json
> +    "@mui/system": "5.13.5",
Так @mui/system нет в main ветке, я когда SystemProps пытался импортировать, всплыло уведомление что mui/system должно быть добавлено в зависимости проекта, и после этого никаких ошибок не было

2023-06-20 06:17 UTC, AndTem commented on packages/components/package.json
> +    "@mui/system": "5.13.5",
А, ты поставил новый пакет. Лучше этого избежать. Есть варианты?

2023-06-20 06:22 UTC, agro196 commented on packages/components/package.json
> +    "@mui/system": "5.13.5",
@AndTem можно попробовать поставить 5.12.3. Это предыдущая версия от 5.13.1, если всё будет без ошибок работать, то гуд, пока только такой вариант приходит в голову

2023-06-20 06:26 UTC, agro196 commented on packages/components/package.json
> +    "@mui/system": "5.13.5",
@AndTem  Когда systemProps импортируешь, то выдаёт ошибку, вебшторм пишет что должен быть установлен пакет в зависимостях

2023-06-20 06:27 UTC, AndTem commented on packages/components/package.json
> +    "@mui/system": "5.13.5",
Без этого типа никак? Установка внутренних пакетов mui усложняет поддержку (все пакеты сразу обновлять придется)

2023-06-20 06:32 UTC, agro196 commented on packages/components/package.json
> +    "@mui/system": "5.13.5",
Сейчас посмотрю как можно по-другому сделать, было решение c Pick вместо Omit, но там ошибка вылетала которую не смог разрешить даже со сторонней помощью, щас подумаю ещё

2023-06-20 06:36 UTC, AndTem commented on packages/components/package.json
> +    "@mui/system": "5.13.5",
Можешь с этой ошибкой придти в наш чат shared, решим

2023-06-20 07:58 UTC, AndTem commented on packages/components/package.json
> +    "@mui/system": "5.13.5",
Как я уже писал, необходимо по возможности, избежать зависимость с system

2023-06-20 08:53 UTC, agro196 commented on packages/components/package.json
> +    "@mui/system": "5.13.5",
@AndTem Сорри, я наверное не правильно объяснил или чего-то не понимаю)У нас в package.json в dependencies есть @mui/material, в нём содержатся все компоненты mui которые мы кастомизируем, и в package.json этого пакета(скрин) уже есть "@mui/system", откуда компоненты mui в том числе как раз берут стилевые пропсы типа justifyContent и прочие, которые нам не нужны. То есть дополнительно устанавливать "@mui/system" мне не надо, он будет обновляться когда будет обновляться @mui/material, проблема лишь в том что линтер ругается и говорит что надо установить "@mui/system" отдельной зависимостью, чего делать не нужно потому что эта зависимость и так уже есть и будет в @mui/material
<img width="483" alt="image" src="https://github.com/kaluga-astral/frontend/assets/65020968/587cf352-18c8-4bf2-a17c-feb0b57fe6a9">

2023-06-20 09:16 UTC, AndTem commented on packages/components/package.json
> +    "@mui/system": "5.13.5",
Линтеры правильно ругается. Пакеты должны быть явно установлены.
Нельзя не лезть в кишки Mui (завязываясь на внутренний пакет system), а просто запекать пропсы или самому написать?

2023-06-20 09:20 UTC, agro196 commented on packages/components/package.json
> +    "@mui/system": "5.13.5",
Оке, понял что так делать плохо, сделаем по-другому)

2023-06-21 11:43 UTC, AndTem requested changes

2023-06-21 11:43 UTC, AndTem commented on packages/components/src/Typography/Typography.tsx
> +    const Component = paragraph ? 'p' : component || 'span';
Это уже реализовано внутри MuiTypography

2023-06-21 11:43 UTC, AndTem commented on packages/components/src/Typography/Typography.tsx
> +export type TypographyProps = TypographyPropsBase & {
Этот тип должен быть generic:
`TypographyProps<TElement extends ElementType = ElementType<'p'>>`

2023-06-21 11:43 UTC, AndTem commented on packages/components/src/Typography/Typography.tsx
> +// import IntrinsicAttributes = React.JSX.IntrinsicAttributes;
лишнее

2023-06-21 11:43 UTC, AndTem commented on packages/components/src/Typography/Typography.tsx
> +// import { WithoutEmotionSpecific } from '../types';
лишнее

2023-06-21 11:57 UTC, sk-iv commented on packages/components/src/Typography/Typography.tsx
> +// import { WithoutEmotionSpecific } from '../types';
тут и ниже импорты закомментированы, наверное их надо удалить?

2023-06-26 08:11 UTC, AndTem commented on packages/components/src/Typography/Typography.tsx
> +//Добавляем нужные нам пропсы из mui и базовые HTML props
Здесь базовые html props уже не добавляются

2023-06-26 08:12 UTC, AndTem commented on packages/components/src/Typography/Typography.tsx
> +  component?: ComponentProp;
Добавь jsdoc

2023-06-26 08:12 UTC, AndTem commented on packages/components/src/Typography/Typography.test.tsx
> +it('Prop:ref: is present', () => {
it должен всегда находится внутри describe

2023-06-26 08:12 UTC, AndTem commented on packages/components/src/Typography/Typography.test.tsx
> +describe('Typography', () => {
два одинаовых descrie

2023-06-26 08:13 UTC, AndTem commented on packages/components/src/Typography/Typography.test.tsx
> +  it('Должен рендерится как h1 когда component="h1"', () => {
Читай [style guide](https://track.astral.ru/soft/wiki/pages/viewpage.action?pageId=3772645403#id-%D0%A2%D0%B5%D1%81%D1%82%D1%8B-React.%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BD%D0%BE%D0%B5%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)

2023-06-26 08:14 UTC, AndTem commented on example/src/modules/DocumentsModule/features/SignerCell/SignerCell.tsx
> +    <Typography variant="small" color={'red'}>
```suggestion
    <Typography variant="small" color="red">
```

2023-06-26 10:28 UTC, AndTem approved these changes

2023-06-26 10:33 UTC, sk-iv approved these changes

2023-06-26 10:36 UTC, merged