feat(UIKIT-779,form): Удалены правила валидации из полей форм
kaluga-astral/frontend pull request #603
Opened 2023-06-30 08:52 UTC by agro196

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2023-07-03 10:40 UTC, AndTem requested changes

2023-07-03 10:40 UTC, AndTem commented on packages/form/package.json
> +    "@astral/validations": "^3.2.2",
Это должно быть devDep потому, что validations используется только для storybook и тестов

2023-07-03 10:59 UTC, AndTem approved these changes

2023-07-04 06:09 UTC, sk-iv approved these changes

2023-07-04 06:11 UTC, merged