feat: Реализован storybook для компонента Tabs в соответствии с макетом
kaluga-astral/frontend pull request #608
Opened 2023-07-06 12:24 UTC by MaksFett

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2023-07-07 14:09 UTC, AlexadraLitvinenko commented
Необходимо исправить название пулл реквеста, для номера задачи использовать UIKIT-443 (это номер задачи с внутренней системы управления задачами)

2023-07-07 14:47 UTC, AlexadraLitvinenko requested changes

2023-07-07 14:47 UTC, AlexadraLitvinenko commented on packages/components/src/Tabs/Tabs.stories.tsx
> +      <br />
Лучше не использовать `<br />`, а добавить отступы в стилях или обернуть в другие компоненты с отступами

2023-07-07 14:47 UTC, AlexadraLitvinenko commented on packages/components/src/Tabs/Tabs.stories.tsx
> +interface TabPanelProps {
Для props лучше использовать тип вместо интерфейса

2023-07-13 17:13 UTC, AlexadraLitvinenko approved these changes

2023-07-13 17:28 UTC, olewka40 approved these changes

2023-07-13 17:48 UTC, merged