feat(UIKIT-764,ui,CheckboxField): Добавлен компонент CheckboxField
kaluga-astral/frontend pull request #626
Opened 2023-07-25 08:44 UTC by YrStudenikin

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2023-07-26 13:25 UTC, AndTem requested changes

2023-07-26 13:25 UTC, AndTem commented on packages/components/src/CheckboxField/CheckboxField.tsx
> +        placement={'bottom-start'}
```suggestion
        placement="bottom-start"
```

2023-07-26 13:25 UTC, AndTem commented on packages/components/src/CheckboxField/CheckboxField.tsx
> +export const CheckboxField = ({
Надо теперь заюзать этот компонент в form. Сейчас дублирование появилось

2023-07-31 06:40 UTC, StanislavDa approved these changes

2023-07-31 06:51 UTC, merged