bug(UIKIT-746,ui,DashboardLayout): Исправление ошибки гидратации
kaluga-astral/frontend pull request #639
Opened 2023-08-04 08:24 UTC by StanislavDa

# Чеклист

- [x] Написать тесты для реализованного функционала
- [x] Описать jsdoc для экспортируемых функций, компонентов
- [x] Описать jsdoc для props экспортируемых компонентов
- [x] Реализовать или обновить storybook для компонента
- [x] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2023-08-04 08:29 UTC, AndTem requested changes

2023-08-04 08:29 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +    const [key, setKey] = useState(TEMP_LOCAL_STORAGE_KEY);
Не понял к чему нужен доп, ключ. Можно же просто collapsedIn в true держать, пока mount не произошел

2023-08-04 08:29 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +    useEffect(() => {
Нужен комментарий зачем все это нужно и как работает со стороны ui

2023-08-04 08:29 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
>  export const Sidebar = forwardRef<HTMLBaseElement, SidebarProps>(
Тест написать надо

2023-08-04 08:56 UTC, StanislavDa commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +    const [key, setKey] = useState(TEMP_LOCAL_STORAGE_KEY);
а как его в true держать, если он внутри хука useLocalStorage достается из localStorage?)

2023-08-04 09:00 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +    const [key, setKey] = useState(TEMP_LOCAL_STORAGE_KEY);
Не доставать из localStorage, пока не произошел mount

2023-08-04 09:01 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +    const [key, setKey] = useState(TEMP_LOCAL_STORAGE_KEY);
Что-то вроде: defaultCollapsedIN || localstorageCollpasedIn

2023-08-04 09:19 UTC, StanislavDa commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +    const [key, setKey] = useState(TEMP_LOCAL_STORAGE_KEY);
чет туплю, типа такого имеется в виду?
<img width="937" alt="image" src="https://github.com/kaluga-astral/frontend/assets/93906455/c18ea041-ea82-4522-8521-5e905e45d3dc">

2023-08-04 09:24 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +    const [key, setKey] = useState(TEMP_LOCAL_STORAGE_KEY);
Зачем тебе лишний key то?
Сделай стейт с флагом. По дефолту true, когда mount произошел кладешь в стейт то, что взял из localStorage

2023-08-04 09:25 UTC, StanislavDa commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +    const [key, setKey] = useState(TEMP_LOCAL_STORAGE_KEY);
я так и сделал, тут просто не видно, что лишнего кея нет =D

2023-08-04 11:49 UTC, AndTem requested changes

2023-08-04 11:49 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.test.tsx
> +  it('Sidebar открытый при true у флага в localstorage', async () => {
еще набо проверить кейс, что он открытый при первом рендере даже когда в localStorage false

2023-08-04 11:49 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +    const [key, setKey] = useState(true);
```suggestion
    const [collapsedIn, seCollapsedIn] = useState(true);
```

2023-08-04 12:03 UTC, StanislavDa commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.test.tsx
> +  it('Sidebar открытый при true у флага в localstorage', async () => {
а это возможно вообще проверить?

2023-08-04 12:22 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.test.tsx
> +  it('Sidebar открытый при true у флага в localstorage', async () => {
Хм, не уверен

2023-08-07 07:47 UTC, StanislavDa commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +    const [key, setKey] = useState(true);
конфликт имен будет, там строчкой ниже флаги с таким названием

2023-08-07 14:26 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +    const [key, setKey] = useState(true);
Не смущает, что в key находится boolean?

2023-08-08 06:50 UTC, StanislavDa commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +    const [key, setKey] = useState(true);
переименовал + поправил тесты. теперь проверяется состояние при монтировании и триггере useEffect

2023-08-08 07:07 UTC, AndTem approved these changes

2023-08-08 07:54 UTC, perevezencev approved these changes

2023-08-08 07:58 UTC, merged