feat(UIKIT-858,ui,Select): Добавлен forwardRef для Select
kaluga-astral/frontend pull request #644
Opened 2023-08-08 12:22 UTC by Awakex

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2023-08-08 12:25 UTC, AndTem requested changes

2023-08-08 12:25 UTC, AndTem commented on packages/components/src/Select/Select.tsx
> +const SelectInner = <Value,>(
Нужен тест, смотри на соседние компоненты

2023-08-08 14:06 UTC, AndTem approved these changes

2023-08-08 14:12 UTC, AndTem approved these changes

2023-08-08 14:34 UTC, lordniken approved these changes

2023-08-09 06:24 UTC, AndTem approved these changes

2023-08-09 06:40 UTC, merged