refactor(UIKIT-706,ui,DatePicker): Добавлен проп inputRef
kaluga-astral/frontend pull request #647
Opened 2023-08-14 04:02 UTC by aesarantsev

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2023-08-14 05:25 UTC, Ofigelov commented
А какой смысл этих изменений? почему нельзя использовать имеющийся вариант с forwardRef?
если мы это мерджим, то для DatePicker.tsx функционал с forwardRef просто станет мертвым

2023-08-14 06:02 UTC, Ofigelov requested changes

2023-08-14 06:02 UTC, Ofigelov commented on packages/components/src/DatePicker/DatePicker.tsx
> +    const ref = useForwardedRef(forwardedRef);
судя по типам, все рефы HTMLInputElement, но конкретно этот передается в div, т.е. должен быть HTMLDivElement

2023-08-14 06:26 UTC, aesarantsev commented on packages/components/src/DatePicker/DatePicker.tsx
> +    const ref = useForwardedRef(forwardedRef);
Поправил

2023-08-14 06:29 UTC, Ofigelov approved these changes

2023-08-15 07:06 UTC, perevezencev approved these changes

2023-08-15 08:04 UTC, merged