feat(UIKIT-808,ui,Accordion): Реализован компонент Accordion
kaluga-astral/frontend pull request #652
Opened 2023-08-16 09:03 UTC by aesarantsev

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2023-08-16 14:21 UTC, AndTem requested changes

2023-08-16 14:21 UTC, AndTem commented on packages/components/src/Accordion/Accordion.stories.tsx
> +export const IsOpen = () => {
```suggestion
export const Controlled = () => {
```

2023-08-16 14:21 UTC, AndTem commented on packages/components/src/Accordion/Accordion.tsx
> +export type AccordionProps = PropsWithChildren & {
PropsWithChildren - это generic

2023-08-16 14:21 UTC, AndTem commented on packages/components/src/Accordion/Accordion.tsx
> +  startAdorment: React.ReactNode;
optional должен быть

2023-08-16 14:21 UTC, AndTem commented on packages/components/src/Accordion/Accordion.tsx
> +  isOpen?: boolean;
Аккордион же должен закрывать по нажатию на хедер. Значит должен быть onChange prop

2023-08-16 14:21 UTC, AndTem commented on packages/components/src/Accordion/Accordion.tsx
> +    const ref = useForwardedRef(forwardedRef);
это лишнее

2023-08-16 14:21 UTC, AndTem commented on packages/components/src/Accordion/Accordion.tsx
> +  isOpen?: boolean;
Давай на isExpanded заменим (как в mui)

2023-08-16 14:21 UTC, AndTem commented on packages/components/src/Accordion/styles.ts
> +export const AccordionHeader = styled(Grid)`
по семантике это должен быть header + role=button

2023-08-16 14:24 UTC, AndTem requested changes

2023-08-16 14:24 UTC, AndTem commented on packages/components/src/Accordion/Accordion.tsx
> +   * @description Заголовок
storybook игнорит при генерации доки @description. Надо удалить

2023-08-17 06:07 UTC, AndTem requested changes

2023-08-17 06:07 UTC, AndTem commented on packages/components/src/Accordion/Accordion.tsx
> +          <AccordionContentWrapper $withStartAdorment={hasStartAdorment}>
$ зачем?

2023-08-17 06:07 UTC, AndTem commented on packages/components/src/Accordion/Accordion.tsx
> +  title: string;
может summary?

2023-08-17 06:07 UTC, AndTem commented on packages/components/src/Accordion/Accordion.tsx
> +  titleProps?: TypographyProps;
Не уверен, что стоит это добавлять. Если хочешь кастом, то прокидываешь в summary компонент.
P.S. сразу не заметил

2023-08-17 07:47 UTC, StanislavDa approved these changes

2023-08-17 07:56 UTC, merged