doc(UIKIT-371,ui,Select): Реализован storybook
kaluga-astral/frontend pull request #654
Opened 2023-08-18 07:27 UTC by maksimmolofeev

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2023-08-18 08:19 UTC, AndTem requested changes

2023-08-18 08:19 UTC, AndTem commented on packages/components/src/Select/Select.stories.tsx
> +const meta: Meta<typeof Select> = {
сразу для form еще добавить надо

2023-08-18 08:19 UTC, AndTem commented on packages/components/src/Select/Select.stories.tsx
> +export const Variants = () => {
у нас доступен только Outlined вариант. Надо удалить эту story (и жеалтельно на уровне типов выпилить пропс)

2023-08-18 08:19 UTC, AndTem commented on packages/components/src/Select/Select.stories.tsx
> +      // @ts-ignore
этого быть не должно

2023-08-18 08:19 UTC, AndTem commented on packages/components/src/Select/Select.stories.tsx
> +        {renderSingleOptions()}
Не используй такие функции в рендере. Копируй руками map.
Из-за этого в storybook в блоке code не понятно как писать options

2023-08-18 08:19 UTC, AndTem commented on packages/components/src/Select/Select.stories.tsx
> +      <Select
Зафиксируй ширину колонок, а то при выборе значения ширина скачет

2023-08-18 09:45 UTC, maksimmolofeev commented on packages/components/src/Select/Select.stories.tsx
> +export const Variants = () => {
+

2023-08-21 07:08 UTC, AndTem requested changes

2023-08-21 07:08 UTC, AndTem commented on packages/form/src/FormSelect/FormSelect.stories.tsx
> +const meta: Meta<typeof FormSelect> = {
Нет ссылки на select. Смотри как сделан FormTextField

2023-08-21 07:08 UTC, AndTem commented on packages/form/src/FormSelect/FormSelect.stories.tsx
> +export const Example = () => {
Смотри как сделан FormTextField. FormStoryContainer больше не используем

2023-08-21 07:08 UTC, AndTem commented on packages/form/src/FormSelect/FormSelect.stories.tsx
> +export const Example = () => {
И тут в story еще кастомный options, надо убрать

2023-08-21 07:08 UTC, AndTem commented on packages/components/src/Select/Select.stories.tsx
> +const meta: Meta<typeof Select> = {
Не хватает кейса с кастомными Options

2023-08-21 07:08 UTC, AndTem commented on packages/components/src/Select/Select.stories.tsx
> +export const Loading = () => {
Здесь выбор option не работает

2023-08-21 12:00 UTC, AndTem approved these changes

2023-08-24 09:59 UTC, StanislavDa approved these changes

2023-08-24 11:02 UTC, merged