doc(UIKIT-794,ui,Fab): Реализован storybook
kaluga-astral/frontend pull request #656
Opened 2023-08-22 14:05 UTC by IgorBabikov

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2023-08-22 14:27 UTC, sk-iv commented on packages/components/src/Fab/Fab.stories.tsx
> +export const Сircular = () => (
тут скоркк всего надо назвать по наименованию свойства: Variant

2023-08-22 14:29 UTC, sk-iv commented on packages/components/src/Fab/Fab.stories.tsx
> +export const Disabled = () => (
```suggestion
export const States = () => (
```

2023-08-23 07:25 UTC, sk-iv approved these changes

2023-08-23 07:32 UTC, AndTem requested changes

2023-08-23 07:32 UTC, AndTem commented on packages/components/src/Fab/Fab.stories.tsx
> +const meta: Meta<typeof Fab> = {
Смотри как сделано в TextField, добавь ссылки на figma и guide. Пока пустые

2023-08-23 07:32 UTC, AndTem commented on packages/components/src/Fab/Fab.stories.tsx
>      <Stack gap={4}>
Замени Stack на наш Grid

2023-08-23 07:32 UTC, AndTem commented on packages/components/src/Fab/Fab.stories.tsx
> +    {svg}
Замени везде {svg} на <LikeOutlineMd />

2023-08-23 07:32 UTC, AndTem commented on packages/components/src/Fab/Fab.stories.tsx
> +export const States = () => (
Назови просто disabled и active убери, такого состояния нет

2023-08-23 07:32 UTC, AndTem commented on packages/components/src/Fab/Fab.stories.tsx
> +export const Colors = () => (
На мобильном разрешении верстка кривая

2023-08-23 08:35 UTC, IgorBabikov commented on packages/components/src/Fab/Fab.stories.tsx
> +    {svg}
На что именно заменить ?

2023-08-23 11:05 UTC, IgorBabikov commented on packages/components/src/Fab/Fab.stories.tsx
> +    {svg}
На что именно заменить ?

2023-08-23 11:07 UTC, AndTem commented on packages/components/src/Fab/Fab.stories.tsx
> +    {svg}
на << LikeOutlineMd />

2023-08-24 14:33 UTC, AndTem requested changes

2023-08-24 14:33 UTC, AndTem commented on packages/components/src/Fab/Fab.stories.tsx
> +
Лишняя пустая строка

2023-08-24 14:33 UTC, AndTem commented on packages/components/src/Fab/Fab.stories.tsx
> +export const Sizes = () => (
Отцентрируй на мобильном разрешении. То же касается и других кейсов

2023-08-25 05:22 UTC, AndTem commented on packages/components/src/Fab/Fab.stories.tsx
> +export const Sizes = () => (
Через styled добавь

2023-08-28 07:29 UTC, merged