feat(UIKIT-896,ui,Select): Добавляет hideHelperText
kaluga-astral/frontend pull request #661
Opened 2023-09-01 07:08 UTC by Awakex

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-09-01 11:06 UTC, AndTem requested changes

2023-09-01 11:06 UTC, AndTem commented on packages/components/src/Select/Select.tsx
> +  hideHelperText?: boolean;
нужен jsdoc

2023-09-01 11:06 UTC, AndTem commented on packages/components/src/Select/Select.test.tsx
> +  it('Props:helperText: hideHelperText: helperText не отображается', () => {
```suggestion
  it('Props:hideHelperText=true: helperText не отображается', () => {
```

2023-09-04 07:57 UTC, AndTem requested changes

2023-09-04 07:57 UTC, AndTem commented on packages/components/src/Select/Select.tsx
> +   * Успешно
Максимально бесполезное описание.
Нужно писать что делает пропс. А сейчас ты просто перевел его на русский.

2023-09-05 08:33 UTC, AndTem approved these changes

2023-09-05 09:37 UTC, lordniken approved these changes

2023-09-06 06:34 UTC, merged