feat(UIKIT-837,ui,Grid):  Добавленна поддержка строковых значения для columns и rows
kaluga-astral/frontend pull request #670
Opened 2023-09-09 06:46 UTC by Ofigelov

# Чеклист

- [ x ] Описать jsdoc для экспортируемых функций, компонентов
- [ x ] Описать jsdoc для props экспортируемых компонентов
- [ x ] Реализовать или обновить storybook для компонента
- [ x ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2023-09-11 08:12 UTC, AndTem requested changes

2023-09-11 08:12 UTC, AndTem commented on packages/components/src/Grid/Grid.stories.tsx
> +    <Grid columns="auto 1fr" spacing={2}>
сделай для нового функионала кейсы в новом формате storybook

2023-09-11 08:12 UTC, AndTem commented on packages/components/src/Grid/types.ts
> +   * @description Количество равных колонок,
Убери "@description". Они не читаются storybook и не попадают потом в описание

2023-09-11 08:14 UTC, Ofigelov commented on packages/components/src/Grid/Grid.stories.tsx
> +    <Grid columns="auto 1fr" spacing={2}>
для этого надо переделать весь сторибук компонента, а это уже тянет на отдельную задачу.

2023-09-11 08:19 UTC, AndTem commented on packages/components/src/Grid/Grid.stories.tsx
> +    <Grid columns="auto 1fr" spacing={2}>
Почему? Тебе надо просто сделать отдельную story под строковые columns и row, которая будет эеспортироваться из файла.
Потом будет проще рефакторить

2023-09-11 12:57 UTC, AndTem commented on packages/components/src/Grid/Grid.stories.tsx
> +export const StringRows = () => {
Добавь описание вроде:Prop rows можно задать как css правило из css-grid

2023-09-14 06:32 UTC, AndTem approved these changes

2023-09-14 06:40 UTC, StanislavDa approved these changes

2023-09-14 06:40 UTC, merged