doc(UIKIT-531, ui, DataGrid): Обновлен Storybook
kaluga-astral/frontend pull request #686
Opened 2023-10-05 08:30 UTC by agro196

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-10-05 08:38 UTC, AndTem commented on packages/components/src/DataGrid/DataGrid.stories.tsx
> +      noDataPlaceholder={<NoDataStub />}
Есть дефолтное отображение noData. Картинка берется из ConfigProvider. Надо это описать

2023-10-05 08:39 UTC, AndTem commented on packages/components/src/DataGrid/DataGrid.stories.tsx
> +  const ACTIONS_WITH_LOADER: Actions<DataType> = {
В сторях почему то action cell для первых строк нет

2023-10-05 08:58 UTC, agro196 commented on packages/components/src/DataGrid/DataGrid.stories.tsx
> +      noDataPlaceholder={<NoDataStub />}
в ConfigProvider дефолтный src для noData картинки пустой, то есть сейчас по дефолту мы видим только текст "Нет данных", добавить сюда путь на картинку из public? 
<img width="606" alt="image" src="https://github.com/kaluga-astral/frontend/assets/65020968/6840528e-b610-4b6b-b88a-056cfc0a66ae">

2023-10-05 09:00 UTC, agro196 commented on packages/components/src/DataGrid/DataGrid.stories.tsx
> +      noDataPlaceholder={<NoDataStub />}
а хотя нет, это ж для сторибука папка

2023-10-05 09:00 UTC, AndTem commented on packages/components/src/DataGrid/DataGrid.stories.tsx
> + * DataGrid без пагинации
Еще не хватает кейса с сортировкой

2023-10-05 09:00 UTC, AndTem commented on packages/components/src/DataGrid/DataGrid.stories.tsx
> + * DataGrid без пагинации
Первой сторей должен быть example: https://github.com/kaluga-astral/frontend/blob/main/CONTRIBUTING.md#example

2023-10-05 12:26 UTC, AndTem requested changes

2023-10-05 12:32 UTC, agro196 commented on packages/components/src/DataGrid/DataGrid.stories.tsx
> +            const regex = /([^\d]+)(\d+)/;
Ну там поле documentName некорректно сортируется если одно правило для всех полей юзать, поэтому для него отдельное условие, ну или цифры убрать из названий документов и юзать одно правило, тут смысл был в том чтобы визуально сортировка работала для каждого поля, алгоритм то у каждого свой будет и зачастую это на бэке делается. Можно оставить так? или как лучше тогда поступить?

2023-10-05 12:44 UTC, AndTem commented on packages/components/src/DataGrid/DataGrid.stories.tsx
> +            const regex = /([^\d]+)(\d+)/;
Ну ок

2023-10-05 12:44 UTC, AndTem approved these changes

2023-10-06 06:55 UTC, sk-iv approved these changes

2023-10-06 07:04 UTC, merged