bug(UIKIT-982): Устранение циклических зависимостей
kaluga-astral/frontend pull request #691
Opened 2023-10-12 15:43 UTC by Ofigelov

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-10-13 06:19 UTC, sk-iv approved these changes

2023-10-13 06:22 UTC, AndTem commented
Твои правки нарушают наш style guide. Обсудим тех. советом проблему, PR пусть пока повисит

2023-10-17 12:43 UTC, AndTem requested changes

2023-10-17 12:43 UTC, AndTem commented on packages/components/src/CheckableTag/styles.ts
> +import { Tag, TagColor, TagProps, TagVariant } from '../Tag';
Здесь же циклическая зависимость сохранилась с импортом TagProps

2023-10-17 12:43 UTC, AndTem commented on packages/components/src/Chevron/styles.tsx
> +})<Pick<ChevronWrapperProps, 'isActive'>>`
Pick тут лишнее

2023-10-17 12:43 UTC, AndTem commented on packages/components/src/Fab/styles.ts
> +  'color' | 'variant'
А все остальныые пропсы MuiFabProps используются?
Тут должен быть либо Pick, либо ручное определение

2023-10-17 12:43 UTC, AndTem commented on packages/components/src/Fab/styles.ts
> +import { FabProps as MuiFabProps } from '@mui/material/Fab/Fab';
Таких импортов быть не должно. Нарушение закона Деметры

2023-10-17 12:43 UTC, AndTem commented on packages/components/src/Radio/Radio.tsx
> +import { RadioProps as MuiRadioProps } from '@mui/material/Radio/Radio';
Импорт неверный. Нарушение закона Деметры

2023-10-17 12:43 UTC, AndTem commented on packages/components/src/Radio/styles.ts
> +import { RadioProps as MuiRadioProps } from '@mui/material/Radio/Radio';
Импорт неверный

2023-10-17 12:43 UTC, AndTem commented on packages/components/src/Radio/styles.ts
> +  'size' | 'color'
Pick должен быть?

2023-10-17 12:43 UTC, AndTem commented on packages/components/src/Tag/styles.ts
> +import { ChipProps as MuiTagProps } from '@mui/material/Chip/Chip';
Импорт неверный

2023-10-17 12:43 UTC, AndTem commented on packages/components/src/Tag/styles.ts
> +  'color' | 'variant' | 'size'
Pick?

2023-10-17 12:43 UTC, AndTem commented on packages/components/src/Tooltip/styles.tsx
> +import { TooltipProps as MuiTooltipProps } from '@mui/material/Tooltip/Tooltip';
Импорт неверный

2023-10-17 13:24 UTC, Ofigelov commented on packages/components/src/CheckableTag/styles.ts
> +import { Tag, TagColor, TagProps, TagVariant } from '../Tag';
неа, это `CheckableTag`, он основывается но простом `Tag`, а сам `Tag` ничего не знает о существовании `CheckableTag`

2023-10-17 13:32 UTC, AndTem approved these changes

2023-10-17 13:57 UTC, merged