Feat/UI kit 980
kaluga-astral/frontend pull request #693
Opened 2023-10-18 09:31 UTC by StanislavDa

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [x] Реализовать или обновить storybook для компонента
- [x] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-10-18 09:35 UTC, Ofigelov commented on packages/components/src/theme/components/MuiMenuItem.ts
> +        '&.Mui-selected': {
как то обсуждали, что нужно завязываться на константах классов, которые импортируются из mui

2023-10-18 09:41 UTC, Ofigelov commented on packages/components/src/theme/components/MuiMenuItem.ts
> +        '&.Mui-selected': {
скорее 
```ts
import { MenuItemClasses } from '@mui/material';

...
  .[`&.${MenuItemClasses.selected`]: {
    foo: 'bar'
  }
...
```

2023-10-18 09:41 UTC, Ofigelov commented on packages/components/src/theme/components/MuiMenuItem.ts
> +        '&.Mui-selected': {
но за точность названия импортируемого объекта не ручаюсь, написал как сам понимаю это )

2023-10-18 09:42 UTC, StanislavDa commented on packages/components/src/theme/components/MuiMenuItem.ts
> +        '&.Mui-selected': {
оки, пробну

2023-10-18 10:59 UTC, AndTem requested changes

2023-10-18 10:59 UTC, AndTem commented on packages/components/src/MenuItem/MenuItem.stories.tsx
> +      <MenuItem selected>
Для selected отдельный кейс должен быть

2023-10-18 11:06 UTC, StanislavDa commented on packages/components/src/MenuItem/MenuItem.stories.tsx
> +      <MenuItem selected>
ага, сделаю. ща заметил типизация из-за forwardRef сломалась - не дает component прокинуть в других местах(

2023-10-19 06:47 UTC, Ofigelov approved these changes

2023-10-19 06:53 UTC, AndTem approved these changes

2023-10-19 08:22 UTC, merged