feat(UIKIT-984,ui,CollapsibleTypography): Добавлен новый компонент CollapsibleTypography
kaluga-astral/frontend pull request #699
Opened 2023-10-19 10:01 UTC by bospur

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-10-19 10:38 UTC, YrStudenikin commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> +          {isOpenCollapse ? 'Скрыть' : 'Показать полностью'}
Текст кнопоки в пропсы, с дефолтными параметрами

2023-10-19 11:26 UTC, YrStudenikin commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.test.tsx
> +  });
Нужно написать тест-кейс что кнопка не появляется при отсутствии переполнения

2023-10-19 11:27 UTC, YrStudenikin commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.test.tsx
> +    expect(screen.getByText('Скрыть')).toBeInTheDocument();
Лучше вообще закинуть текст кнопок в константы, и использовать их как дефолтные параметры в пропсах, так и для тестирования

2023-10-19 11:29 UTC, YrStudenikin commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.test.tsx
> +  it('Prop: rowsCount=1: Появляется кнопка раскрытия ', () => {
Что будет с rowsCount=0? Тест бы не помешал для проверки ожидаемого поведения

2023-10-19 11:42 UTC, YrStudenikin commented on packages/components/src/CollapsibleTypography/styles.ts
> +  height: ${({ currentHeight }) => currentHeight};
Я вижу что ты реализовал через изменение высоты,  со своей кастомной анимацией. 
Обсуждалась ранее реализация сворачивания/разворачивания блока с текстом? Если не используется Collapse, тогда нужно характеристики анимации привести к стандарту кита.  
+ Нужно отправить компонент на ревью дизайнеру

2023-10-19 12:45 UTC, YrStudenikin commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> +          onClick={() => setIsOpenCollaps(!isOpenCollapse)}
Лучше будет что-то вроде одного метода toggleCollapse, который в хуке будет оперировать prevState.
Тут достаточно будет прокинуть коллбэк: ```onClick={toggleCollapse}```

2023-10-19 12:48 UTC, YrStudenikin commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +  const [isCollapsControll, setIsCollapsControll] = useState(true);
Название непонятное. Как вариант - isCollapsable

2023-10-19 12:49 UTC, YrStudenikin commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +  const [initialHight, setInitialHeight] = useState('');
опечатка

2023-10-19 12:50 UTC, YrStudenikin commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +  const [isOpenCollapse, setIsOpenCollaps] = useState(false);
опечатка:  **setIsOpenCollapse**

2023-10-19 12:51 UTC, YrStudenikin commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +  const [isCollapsControll, setIsCollapsControll] = useState(true);
По дефолту должно быть true?

2023-10-23 07:16 UTC, YrStudenikin commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> +      hideButtonText = DEFAULT_HIDE_TEXT,
Названия констант не совсем понятные. Измени на названия как в пропсах)
SHOW_BUTTON_TEXT, HIDE_BUTTON_TEXT

2023-10-23 07:19 UTC, AndTem commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +export const useCollabsible = (forwardedRef?: Ref<HTMLElement>) => {
Сомневаюсь в необходимости хука.
Смотри на Collapse компонент.
Также, если он все таки нужен, то должны быть написаны тесты. Много тестов

2023-10-23 07:21 UTC, YrStudenikin commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.test.tsx
> +  it('Prop: showButtonText={"Какой-то текст"}: Изменяется текст кнопки открытия', async () => {
Допиши тест с кнопкой hide, она ведь тоже с таким же поведением

2023-10-23 07:25 UTC, bospur commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +export const useCollabsible = (forwardedRef?: Ref<HTMLElement>) => {
Collapse  же не скрывает текст по строкам? я нашел у него пропс collapsedSize но он принимает px

2023-10-23 07:28 UTC, AndTem commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +export const useCollabsible = (forwardedRef?: Ref<HTMLElement>) => {
1. Нужен jsdoc. Не понятно что делает хук. Оказывается здесь что-то со строками связано
2. Не вижу ничего про строки

2023-10-23 08:00 UTC, bospur commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +export const useCollabsible = (forwardedRef?: Ref<HTMLElement>) => {
добавил

2023-10-24 07:18 UTC, YrStudenikin commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.test.tsx
> +  it('если контент не переполнен', () => {
Описание ни о чем не говорит. Нужна краткая информация о назначении теста - Кнопка "показать" скрыта, если контент не переполнен. В этом духе

2023-10-24 07:19 UTC, YrStudenikin commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.test.tsx
> +      </CollapsibleTypography>,
Лишний текст для теста. Для наглядности можно оставить одну строку

2023-10-24 07:22 UTC, YrStudenikin commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.test.tsx
> +        suscipit ipsa officia.
Текст дублируется, занимает много места. Можно вынести в переменную

2023-10-24 10:46 UTC, DesignASoft approved these changes

2023-10-25 05:37 UTC, bospur commented
@AndTem ап)

2023-10-25 10:49 UTC, AndTem requested changes

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> +   * Maximum displayed number of lines
Часть на русском, часть на английском

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> +   * @default 1
это указывать не обязательно. storybook потом сам сгенерит defualt

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> +  showButtonText?: string;
С глагола начинаются всегда функции, а это просто string

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> +  hideButtonText?: string;
С глагола начинаются всегда функции, а это просто string

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> +export type CollapsibleElementProps = CollapsibleProps & TypographyProps;
Сделай все одним типов, ни к чему это разбиение

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> + * За основу взята логика компонента OverflowTypography.
Пользователю компнента эта информация ни к чему.
Тут должно быть описано назначение компонента

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> + * Пропс rowsCount определяет максимиально отображаемое колличество строк
Пропс у тебя уже описаны в типе

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> +      ...props,
не в начале ли должен быть spread?

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/styles.ts
> +export const CollapsibleWrapper = styled.div`
Семантически точно div должен быть?

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/styles.ts
> +  display: ${({ isOpenCollapse }) => (isOpenCollapse ? '' : '-webkit-box')};
Почему не flex?
Webkit не во всех браузерах работает, да и плюс автопрефиксер есть для такого

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/styles.ts
> +  -webkit-box-orient: ${({ isOpenCollapse }) =>
Опять webkit

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> + * Компоненту  в пропсах задается rowsCount, который попадает  в стили и устанавливает значение -webkit-line-clamp = rowsCount;
Все, что ты здесь написал дублирует код, который написан ниже.
Здесь должно присутствовать только назначение хука

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> + * Компоненту  в пропсах задается rowsCount, который попадает  в стили и устанавливает значение -webkit-line-clamp = rowsCount;
Если нужны пояснения по коду, то комменты должны оставляться на конкретной строке кода

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +  const [initialHeight, setInitialHeight] = useState('');
Не 0 должен быть по дефолту?

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +  const [currentHeight, setCurrentHeight] = useState('auto');
Не типизированный state. Сейчас string, а по всей видимости это css rule

2023-10-25 10:49 UTC, AndTem commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +      setInitialHeight(clientH + 'px');
Смотри [style guide](https://track.astral.ru/soft/wiki/pages/viewpage.action?pageId=3557425260#id-%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5%D1%82%D0%B8%D0%BF%D0%BE%D0%B2-%D0%94%D0%BB%D1%8F%D1%81%D0%BA%D0%BB%D0%B5%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%BD%D0%B5%D0%BE%D0%B1%D1%85%D0%BE%D0%B4%D0%B8%D0%BC%D0%BE%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%BE%D0%B2%D1%8B%D0%B9%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD)

2023-10-25 10:54 UTC, AndTem requested changes

2023-10-25 10:54 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.test.tsx
> +  it('Prop: showButtonText={"Какой-то текст"}: Изменяется текст кнопки открытия', () => {
```suggestion
  it('Prop: showButtonText: Изменяется текст кнопки открытия', () => {
```

2023-10-25 10:54 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.test.tsx
> +  it('Prop: showButtonText={"Какой-то текст"}: Изменяется текст кнопки открытия', () => {
Не надо в названии указывать строку, которую ты прокидываешь. Она ж может быть любого размера.
Тест кейс должен просто говорить что умеет компонент

2023-10-25 10:54 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.test.tsx
> +  it('Click control button: При нажатии на кнопку "Показать" меняется состояние', async () => {
```suggestion
  it(При нажатии на кнопку "Показать" отображается весь текст', async () => {
```

2023-10-26 05:55 UTC, bospur commented on packages/components/src/CollapsibleTypography/styles.ts
> +  display: ${({ isOpenCollapse }) => (isOpenCollapse ? '' : '-webkit-box')};
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp
Честно говоря , я не знаю другого способа построчного обрезанию при мощи только css.
Опирался на логику OverflowTypography

2023-10-26 13:07 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> +export const DEFAULT_ROWS_COUNT = 1;
Другие константы ничем не отличаются от этой

2023-10-26 13:08 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> +   * @description опорная единица по которой определяется максимиально отображаемое колличество строк
Максимиально отображаемое колличество строк

2023-10-26 13:10 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> +export type CollapsibleProps = {
Этот тип не нужно экспортировать

2023-10-26 13:12 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> +   * @default 1
Комментарии, которые оставляет ревьюер обычно нацелены не только на конкретную строку кода.
Ревьюер подразумевает, что все подобные случае также будут исправлены

2023-10-26 13:13 UTC, AndTem commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> + * @description Хук используется для управления логикой открытия/скрытия
Открытия/скрытия чего?

2023-10-26 13:15 UTC, AndTem commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +  useEffect(() => {
Не понятно что здесь происходит и как жто связано со строками текста. Нужны комментарии. Ты их оставлял до этого, но не в том месте

2023-10-26 13:16 UTC, AndTem commented
@bospur Storybook почему то не парсит @description jsdoc, надо везде просто удалить этот тэг

2023-10-27 06:42 UTC, AndTem commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +      // нужно сохранить изначальную клиентскую высоту компонента, что бы можно было к ней вернуться
лишний комментарий

2023-10-27 06:42 UTC, AndTem commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +      // если нет, то кнопка не нужна
лишний комментарий

2023-10-27 06:43 UTC, AndTem commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +      // Возвращаем изначальное состояние
лишний комментарий

2023-10-27 06:43 UTC, AndTem commented on packages/components/src/CollapsibleTypography/hooks/useCollapsible/useCollabsible.ts
> +      // нужно сохранить изначальную клиентскую высоту компонента, что бы можно было к ней вернуться
Комментарии необходимо оставлять там, где есть сложная логика. Здесь из названия метода и так понятно что происходит

2023-10-27 06:44 UTC, AndTem commented on packages/components/src/CollapsibleTypography/CollapsibleTypography.tsx
> +export const CollapsibleTypography = forwardRef<
Не сделал экспорт компонента из пакета. Сейчас он будет недоступен продуктам

2023-10-30 08:53 UTC, AndTem approved these changes

2023-10-30 09:03 UTC, merged