feat(UIKIT-799,OverflowTypography): Реализация сторибук
kaluga-astral/frontend pull request #701
Opened 2023-10-20 06:30 UTC by Ofigelov

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [x] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-10-20 06:40 UTC, sk-iv commented on packages/components/src/OverflowTypography/OverflowTypography.stories.tsx
> +/**
сейчас во все стори добавляют, даже если они пустые:
### [Figma]()
### [Guide]()

2023-10-20 07:29 UTC, sk-iv approved these changes

2023-10-23 07:11 UTC, AndTem commented on packages/components/src/OverflowTypography/OverflowTypography.stories.tsx
> +    <div style={{ width: '600px' }}>
Для мобильного разрешения твоя верстка не готова: https://github.com/kaluga-astral/frontend/blob/main/CONTRIBUTING.md#%D0%B4%D0%B5%D1%84%D0%BE%D0%BB%D1%82%D0%BD%D0%B0%D1%8F-%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%BA%D0%B0-%D0%BA%D0%BE%D0%BD%D1%82%D0%B5%D0%B9%D0%BD%D0%B5%D1%80%D0%B0

2023-10-23 12:09 UTC, AndTem requested changes

2023-10-23 12:09 UTC, AndTem commented on packages/components/src/OverflowTypography/OverflowTypography.stories.tsx
> + * Вариация ```Typography``` элемента, с автоматической проверкой на переполнение текстового контента, и если есть переполнение, то тогда добавляется кастомизируемая обертка ```Tooltip```.
Сделай ссылку на typography. Смотри как сделано в formTextField

2023-10-23 12:09 UTC, AndTem commented on packages/components/src/OverflowTypography/OverflowTypography.stories.tsx
> + * Prop ```rowsCount``` Означает число строк, после которого текст будет обрезаться, и добавляться многоточие. По умолчанию равен '1'.
```suggestion
 * Prop ```rowsCount``` задает число строк, после которого текст будет обрезаться, и добавляться многоточие. По умолчанию равен '1'.
```

2023-10-23 12:09 UTC, AndTem commented on packages/components/src/OverflowTypography/OverflowTypography.stories.tsx
> +const meta: Meta<typeof OverflowTypography> = {
С гридами какой-то прикол у компонента. Не стоит ли сделать кейс с ними?

2023-10-23 12:19 UTC, Ofigelov commented on packages/components/src/OverflowTypography/OverflowTypography.stories.tsx
> +const meta: Meta<typeof OverflowTypography> = {
Его сложно воспроизвести, иногда срабатывает, иногда нет. Мы его в последнее время не встречаем, хотя и не ограничиваем себя в использовании гридов.

2023-10-23 12:28 UTC, AndTem approved these changes

2023-10-23 12:29 UTC, merged