feat(UIKIT-798,ui,MaskField): Реализует storybook
kaluga-astral/frontend pull request #702
Opened 2023-10-20 13:17 UTC by IlyaKhazan

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-10-20 13:20 UTC, Ofigelov approved these changes

2023-10-23 07:03 UTC, AndTem commented
Название PR неверное. Тут storybook для Grid

2023-10-23 07:09 UTC, AndTem requested changes

2023-10-23 07:09 UTC, AndTem commented on packages/components/src/MaskField/MaskField.stories.tsx
> +export const Placeholder = () => (
Здесь два кейса в одном.
Должен быть отдельный кейс, что поддердивается маска с буквами

2023-10-23 07:09 UTC, AndTem commented on packages/components/src/MaskField/MaskField.stories.tsx
> +    <Stack>
Все эти обертки не нужны.
https://github.com/kaluga-astral/frontend/blob/main/CONTRIBUTING.md#%D0%B4%D0%B5%D1%84%D0%BE%D0%BB%D1%82%D0%BD%D0%B0%D1%8F-%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%BA%D0%B0-%D0%BA%D0%BE%D0%BD%D1%82%D0%B5%D0%B9%D0%BD%D0%B5%D1%80%D0%B0

2023-10-23 07:09 UTC, AndTem commented on packages/components/src/MaskField/MaskField.stories.tsx
>        <MaskField
Нужно сделать кейс на пропс unmask и сказать что по дефолту в value попадают данные без маски

2023-10-23 07:09 UTC, AndTem commented on packages/components/src/MaskField/MaskField.stories.tsx
> +const meta: Meta<typeof MaskField> = {
Зацепи в этом PR storybook для FormMaskField сразу

2023-10-23 12:29 UTC, AndTem approved these changes

2023-10-23 12:30 UTC, AndTem commented
@IlyaKhazan создай баг на тему того, что пропсы не генерируются для компонента

2023-10-23 12:42 UTC, IlyaKhazan commented
> @IlyaKhazan создай баг на тему того, что пропсы не генерируются для компонента

Создал

2023-10-23 13:23 UTC, merged