feat(UIKIT-674,ui,OutdatedReleasePlaceholder): Добавлена обработка ошибок chunk
kaluga-astral/frontend pull request #706
Opened 2023-10-23 14:40 UTC by cryzer12

# Чеклист

- [x] Написать тесты для реализованного функционала
- [x] Описать jsdoc для экспортируемых функций, компонентов
- [x] Описать jsdoc для props экспортируемых компонентов
- [x] Реализовать или обновить storybook для компонента
- [x] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [x] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-10-25 06:29 UTC, StanislavDa commented on packages/ui/README.md
> +- Компонент ErrorBoundary перехватывает ошибку устаревших билдов и корректно её обрабатывает, для того, что отобразилось изображение, необходимо в ConfigProvider указать prop ```images.outdatedReleas
"для того, чтобЫ отобразилось"

2023-10-25 08:55 UTC, StanislavDa approved these changes

2023-10-26 09:08 UTC, AndTem requested changes

2023-10-26 09:08 UTC, AndTem commented on packages/components/src/ConfigProvider/ConfigProvider.tsx
> +   * @description изображение при ошибке при обновлении продукта (используется в ContentState/ErrorBoundary)
Сделай более явный коммент. Ошибка загрузки чанков

2023-10-26 09:08 UTC, AndTem commented on packages/components/src/OutdatedReleasePlaceholder/OutdatedReleasePlaceholder.tsx
> +  const handleRefreshButtonClick = () => {
```suggestion
  const handleClickRefresh = () => {
```

2023-10-26 09:08 UTC, AndTem commented on packages/components/src/ErrorBoundary/enums.ts
> +export enum TypeError {
Обрати внимание, не экспортируется ли из пакета этот enum и другие типы.
Если да, то либо их не надо экспортировать, либо переименовать

2023-10-26 09:08 UTC, AndTem commented on packages/components/src/ErrorBoundary/types.ts
> +export type State = {
Мне кажется, что этот тип можно в компоненте описать

2023-10-26 09:08 UTC, AndTem commented on packages/components/src/ErrorBoundary/ErrorBoundary.tsx
>    public state: State = {
Тесты надо бы написать

2023-10-26 09:12 UTC, AndTem commented on packages/components/src/OutdatedReleasePlaceholder/OutdatedReleasePlaceholder.stories.tsx
> +  title: 'Components/OutdatedReleasePlaceholder',
Предлагаю все placeholder в один раздел положить.
Components/Placeholders/...

2023-10-26 14:22 UTC, cryzer12 commented on packages/components/src/ErrorBoundary/enums.ts
> +export enum TypeError {
не экспортируется, только сам компонент наружу смотрит

2023-10-27 08:12 UTC, AndTem requested changes

2023-10-27 08:12 UTC, AndTem commented on packages/components/src/ConfigProvider/ConfigProvider.tsx
> +   * @description изображение при ошибке загрузки актуальных чанков (используется в ContentState/ErrorBoundary)
Storybook игнорирует @description тэги, надо удалить. В contributing добавим эту инфу или пофиксим storybook

2023-10-27 08:12 UTC, AndTem commented on packages/components/src/ErrorBoundary/ErrorBoundary.test.tsx
> +  it.each<[string, ReactNode]>([
Я считаю, что надо два отдельных it написать. В данном случае it.each только усложнит поддержку

2023-10-27 08:12 UTC, AndTem commented on packages/components/src/ErrorBoundary/ErrorBoundary.test.tsx
> +        <BuggyButton />
Усложненный тест с нажатием кнопок и доп. логикой. Сделать просто тестовый компонент который сразу при рендере выбрасывает нужно исключение. Так будет менее хрупкий и более поддерживаемый тест

2023-10-27 08:12 UTC, AndTem commented on packages/components/src/OutdatedReleasePlaceholder/OutdatedReleasePlaceholder.stories.tsx
> +  title: 'Components/Placeholders/OutdatedReleasePlaceholder',
Я бы в Components/Placeholders вложил бы еще компонент Placeholder

2023-10-27 08:16 UTC, cryzer12 commented on packages/components/src/OutdatedReleasePlaceholder/OutdatedReleasePlaceholder.stories.tsx
> +  title: 'Components/Placeholders/OutdatedReleasePlaceholder',
Вот тут не уверен, кажется что компонент базовый и готовая реализация этого компонента разные вещи, нужно подумать

2023-10-27 08:16 UTC, cryzer12 commented on packages/components/src/ErrorBoundary/ErrorBoundary.test.tsx
> +        <BuggyButton />
он падает сразу, не работает

2023-10-27 08:17 UTC, cryzer12 commented on packages/components/src/ErrorBoundary/ErrorBoundary.test.tsx
> +        <BuggyButton />
только может если по таймеру, если ошибка раньше первого рендера, ErrorBoundary не обработает исключение, в тестах уж точно, но я посмотрел вроде в стори такая же история

2023-10-27 08:20 UTC, cryzer12 commented on packages/components/src/ConfigProvider/ConfigProvider.tsx
> +   * @description изображение при ошибке загрузки актуальных чанков (используется в ContentState/ErrorBoundary)
А что на замену? просто текст оставить?

2023-10-27 08:20 UTC, cryzer12 commented on packages/components/src/ErrorBoundary/ErrorBoundary.test.tsx
> +  it.each<[string, ReactNode]>([
мне кажется вот именно тут мы покрываем один и тот же кейс, просто двумя способами, each как раз это решение, варианты разных ошибок - разные кейсы, а тут одна и та же проблема, просто входные данные разные, но проверки 1 в 1, но сделать два не проблема, просто расширять если мы не все ошибки чанков покрыли проще было бы так

2023-10-27 08:21 UTC, AndTem commented on packages/components/src/ConfigProvider/ConfigProvider.tsx
> +   * @description изображение при ошибке загрузки актуальных чанков (используется в ContentState/ErrorBoundary)
Да

2023-10-27 08:21 UTC, AndTem commented on packages/components/src/ErrorBoundary/ErrorBoundary.test.tsx
> +  it.each<[string, ReactNode]>([
Уверен, что расширять проще? Я вот сходу не смог разобраться что к чему

2023-10-27 13:11 UTC, AndTem approved these changes

2023-10-27 14:51 UTC, merged