test(UIKIT-991,ui,TextField): Доработан тест
kaluga-astral/frontend pull request #707
Opened 2023-10-24 06:56 UTC by Jek-Konservator

# Чеклист

- [X] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-10-24 07:26 UTC, sk-iv commented on packages/components/src/TextField/TextField.test.tsx
> +      <ThemeProvider theme={theme}>
вроде бы renderWithTheme уже использует ThemeProvider внутри, проверить вроде бы ThemeProvider избыточен

2023-10-24 07:31 UTC, Jek-Konservator commented on packages/components/src/TextField/TextField.test.tsx
> +      <ThemeProvider theme={theme}>
Проверил они и правда были избыточными, убрал

2023-10-24 07:37 UTC, AndTem commented on packages/components/src/TextField/TextField.test.tsx
> +    expect(screen.getByText('Обязательно')).toHaveStyle({
НИКОГДА не тестируем css в компонентом тестировании.

2023-10-24 07:45 UTC, AndTem commented on packages/components/src/TextField/TextField.test.tsx
> +  it('Prop:label: отображается label', () => {
Протестируй еще ref

2023-10-24 07:45 UTC, AndTem commented on packages/components/src/TextField/TextField.test.tsx
> +import { theme } from '@astral/tests/src/theme';
Импорт в кишки не напрягает?

2023-10-24 11:57 UTC, Jek-Konservator commented on packages/components/src/TextField/TextField.test.tsx
> +    expect(screen.getByText('Обязательно')).toHaveStyle({
Убрал тестирование css

2023-10-24 11:57 UTC, Jek-Konservator commented on packages/components/src/TextField/TextField.test.tsx
> +  it('Prop:changeValue: меняется значение input при вводе текста', () => {
Переписал тест на проверку onChange

2023-10-24 11:58 UTC, Jek-Konservator commented on packages/components/src/TextField/TextField.test.tsx
> +  it('Prop:label: отображается label', () => {
Добавил тест ref

2023-10-24 12:00 UTC, Jek-Konservator commented on packages/components/src/TextField/TextField.test.tsx
> +import { expect, it } from 'vitest';
Удалил импорт expect

2023-10-24 12:00 UTC, Jek-Konservator commented on packages/components/src/TextField/TextField.test.tsx
> +import { theme } from '@astral/tests/src/theme';
Исчезло т.к. нет потребности

2023-10-24 12:13 UTC, AndTem requested changes

2023-10-24 12:13 UTC, AndTem commented on packages/components/src/TextField/TextField.test.tsx
> +  it('Prop:ref: меняется значение input при вводе текста', () => {
Текст не соответсвует тестируемому кейсу

2023-10-24 12:13 UTC, AndTem commented on packages/components/src/TextField/TextField.test.tsx
> +    expect(FormHelperTextContent).toHaveBeenCalledWith(
Тест не должен знать о подробностях реализации тестируемой системы

2023-10-24 15:34 UTC, Jek-Konservator commented on packages/components/src/TextField/TextField.test.tsx
> +  it('Prop:ref: меняется значение input при вводе текста', () => {
Исправил

2023-10-24 15:35 UTC, Jek-Konservator commented on packages/components/src/TextField/TextField.test.tsx
> +    expect(FormHelperTextContent).toHaveBeenCalledWith(
Удалил проверки success и error т.к. не смог написать тест без использования подробностей реализации

2023-10-27 06:58 UTC, AndTem requested changes

2023-10-27 06:58 UTC, AndTem commented on packages/components/src/FormHelperText/FormHelperTextContent/FormHelperTextContent.tsx
> +        <FormHelperTextSuccessIcon aria-label="FormHelperTextContentSuccessIcon" />
Ты неправильно применил aria атрибут. Читай: https://doka.guide/a11y/aria-label/

2023-10-27 06:58 UTC, AndTem commented on packages/components/src/FormHelperText/FormHelperTextContent/FormHelperTextContent.tsx
> +        <FormHelperTextSuccessIcon aria-label="FormHelperTextContentSuccessIcon" />
Я изучил вопрос и здесь aria атрибут применить не получится. А добавлять data-testid - антипаттерн.
Предлагаю все таки в тесте на ошибку и success проверять, что просто отображается текст

2023-10-27 06:59 UTC, AndTem commented on packages/components/src/TextField/TextField.test.tsx
> +import { expect, it } from 'vitest';
up

2023-10-27 07:04 UTC, Jek-Konservator commented on packages/components/src/FormHelperText/FormHelperTextContent/FormHelperTextContent.tsx
> +        <FormHelperTextSuccessIcon aria-label="FormHelperTextContentSuccessIcon" />
Удалил атрибут и его проверку

2023-10-27 07:30 UTC, AndTem commented on packages/components/src/TextField/TextField.test.tsx
> +import { expect, it } from 'vitest';
up

2023-10-27 07:33 UTC, Jek-Konservator commented on packages/components/src/TextField/TextField.test.tsx
> +import { expect, it } from 'vitest';
Добавил что бы ide подсвечивала методы и забыл убрать

2023-10-27 08:00 UTC, AndTem commented on packages/components/src/TextField/TextField.test.tsx
> +import { expect, it } from 'vitest';
it туда же относится: https://vitest.dev/config/#globals

2023-10-27 08:38 UTC, sk-iv approved these changes

2023-10-27 08:42 UTC, merged