feat(UIKIT-1004,ui,DashboardLayout): Добавлена возможность управления организациями
kaluga-astral/frontend pull request #711
Opened 2023-10-25 13:11 UTC by StanislavDa

# Чеклист

- [x] Написать тесты для реализованного функционала
- [x] Описать jsdoc для экспортируемых функций, компонентов
- [x] Описать jsdoc для props экспортируемых компонентов
- [x] Реализовать или обновить storybook для компонента
- [x] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [x] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-10-25 13:16 UTC, perevezencev approved these changes

2023-10-25 13:19 UTC, perevezencev commented on packages/components/src/DashboardLayout/DashboardLayout.stories.tsx
> +    menuOrganization: {
organizationMenu

2023-10-25 13:19 UTC, perevezencev commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +      <HeaderNav>
Для HeaderNav нельзя эти стили объявить?

2023-10-25 13:19 UTC, perevezencev commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +      <HeaderNav>
Точно ли тут вообще грид нужон?

2023-10-25 13:22 UTC, StanislavDa commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +      <HeaderNav>
Наверн в HeaderNav можно эти стили перетащить, а грид нужон для отсутпов)

2023-10-25 13:34 UTC, perevezencev commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +      <HeaderNav>
flex + gap = збс

2023-10-26 09:16 UTC, AndTem requested changes

2023-10-26 09:16 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +  organizationMenu?: MenuOrganizationProps | null;
зачем тут null?

2023-10-26 09:16 UTC, AndTem commented on packages/components/src/MenuOrganization/MenuOrganization.test.tsx
> +} from './MenuOrganization.stories';
Такой связи быть не должно.
Лучше продублировать или создать файл типа: MenuOrganizations.stubs.ts

2023-10-26 09:17 UTC, StanislavDa commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +  organizationMenu?: MenuOrganizationProps | null;
думаешь, не нужно даже на всякий случай?)

2023-10-26 09:18 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.tsx
> +  organizationMenu?: MenuOrganizationProps | null;
не нужен конечно

2023-10-26 09:34 UTC, AndTem approved these changes

2023-10-26 09:51 UTC, merged