doc(UIKIT-1000,ui,DataGrid): Отображает массивы и обработчики в блок…
kaluga-astral/frontend pull request #712
Opened 2023-10-25 15:09 UTC by IlyaKhazan

…е storybook Show code

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [x] Реализовать или обновить storybook для компонента
- [x] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-10-26 05:30 UTC, AndTem requested changes

2023-10-26 05:30 UTC, AndTem commented on packages/components/src/DataGrid/DataGrid.stories.tsx
> +  const data: DataType[] = [
Сделай для data функцию генерации данных, чтобы в самом компоненте был просто вызов этой функции.
Но чтобы shape объекта data было видно

2023-10-26 09:21 UTC, AndTem commented
И смотри как правильно ветки именовать в contributing.md

2023-10-26 09:22 UTC, AndTem approved these changes

2023-10-26 09:22 UTC, AndTem commented on packages/components/src/DataGrid/DataGrid.stories.tsx
> +  return Array(DATA_ARRAY_LENGTH)
Array.from({ length: }).map(() => {})

2023-10-27 06:53 UTC, YrStudenikin approved these changes

2023-10-27 06:59 UTC, merged