feat(UIKIT-351,ui,StepSlider): Новый компонент анимированного переключения компонентов
kaluga-astral/frontend pull request #714
Opened 2023-10-27 10:48 UTC by Ofigelov

# Чеклист

- [x] Написать тесты для реализованного функционала
- [x] Описать jsdoc для экспортируемых функций, компонентов
- [x] Описать jsdoc для props экспортируемых компонентов
- [x] Реализовать или обновить storybook для компонента
- [x] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-10-30 09:06 UTC, AndTem requested changes

2023-10-30 09:06 UTC, AndTem commented on packages/components/src/StepSlider/StepSlider.tsx
> +   * @description флаг, определяющий необходимость элемента растягиваться на всю доступную ширину
И так понятно, что флаг. Можно просто: растягивает на всю ширину

2023-10-30 09:06 UTC, AndTem commented on packages/components/src/StepSlider/StepSlider.tsx
> +  const containerRef = useRef<HTMLDivElement>(
1. Не понятно зачем тут body. Нужен коммент
2. При ssr такой код упадет

2023-10-30 09:06 UTC, AndTem commented on packages/components/src/StepSlider/StepSlider.stories.tsx
> + * Компонент предназначенный для анимированного переключения активного компонента
Допиши пример где может быть полезно

2023-10-30 09:09 UTC, AndTem commented on packages/components/src/StepSlider/StepSlider.stories.tsx
> +              first
Запихни в каждый step по два инпута (работать им не обязательно) или других компнента любых, чтобы выглядело более наглядно

2023-10-30 09:11 UTC, AndTem commented
Заметил, что step, который был хоть раз открыт больше не анманутится - это может быть проблемой, если используем для больших форм компонент

2023-10-30 09:23 UTC, Ofigelov commented on packages/components/src/StepSlider/StepSlider.tsx
> +          key={`${keyId}_${index}`}
не, просто id тут не прокатит, реакт будет ругаться что в массиве элементы с повторяющимися ключами.

2023-10-30 09:25 UTC, Ofigelov commented
> Заметил, что step, который был хоть раз открыт больше не анманутится - это может быть проблемой, если используем для больших форм компонент

Для его анмаунта можно модифицировать пропсы

```
slideProps={{
         unmountOnExit: false,
      }}
```

2023-10-30 09:28 UTC, Ofigelov commented on packages/components/src/StepSlider/StepSlider.tsx
> +  const containerRef = useRef<HTMLDivElement>(
1. просто фолбэк, чтобы делать на одну проверку меньше
2. добавлю защиту в виде`?`

2023-10-30 10:01 UTC, AndTem commented
> > Заметил, что step, который был хоть раз открыт больше не анманутится - это может быть проблемой, если используем для больших форм компонент
> 
> 
> 
> Для его анмаунта можно модифицировать пропсы
> 
> 
> 
> ```
> 
> slideProps={{
> 
>          unmountOnExit: true,
> 
>       }}
> 
> ```

Можно по дефолту true?

2023-10-30 10:04 UTC, AndTem approved these changes

2023-10-30 10:21 UTC, AndTem approved these changes

2023-11-01 05:53 UTC, sk-iv approved these changes

2023-11-01 05:53 UTC, merged