feat(UIKIT-946,form,CodeField): Добавлены компоненты CodeField и FormCodeField
kaluga-astral/frontend pull request #729
Opened 2023-11-01 14:12 UTC by JetBlackCodes

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-11-02 07:12 UTC, YrStudenikin commented
Кода в файле `CodeField.tsx` получилось очень много, логика сложная для чтения и ревью.  
Давай начнем с того, что нужно разделить код.  
Логику Digit нужно вынести в отдельный компонент `CodeFieldDigits` или вроде того.  
`ResendButton` вряд ли должен что-то знать о таймере, компоненты тоже нужно разделить

2023-11-02 07:12 UTC, YrStudenikin commented on packages/components/src/CodeField/CodeField.tsx
Кода в файле `CodeField.tsx` получилось очень много, логика сложная для чтения и ревью.  
Давай начнем с того, что нужно разделить код.  
Логику Digit нужно вынести в отдельный компонент `CodeFieldDigits` или вроде того.  
`ResendButton` вряд ли должен что-то знать о таймере, компоненты тоже нужно разделить

2023-11-02 08:06 UTC, YrStudenikin commented on packages/components/src/hooks/useTimer/useTimer.ts
> +  isFormatHHMMSS?: boolean;
Не используется

2023-11-02 08:09 UTC, YrStudenikin commented on packages/components/src/hooks/useTimer/useTimer.ts
Нужно описать jsdoc тут и в остальных местах

2023-11-02 08:09 UTC, YrStudenikin commented on packages/components/src/hooks/useTimer/useTimer.ts
> +  onStep?: (time: number) => void;
JsDoc

2023-11-02 08:10 UTC, YrStudenikin commented on packages/components/src/hooks/useTimer/useTimer.ts
> +type UseTimerParams = {
JsDoc

2023-11-14 06:46 UTC, JetBlackCodes commented on packages/components/src/hooks/useTimer/useTimer.ts
> +  isFormatHHMMSS?: boolean;
Убрала

2023-11-14 06:46 UTC, JetBlackCodes commented on packages/components/src/hooks/useTimer/useTimer.ts
> +type UseTimerParams = {
Добавила

2023-11-14 06:49 UTC, JetBlackCodes commented on packages/components/src/CodeField/CodeField.tsx
Вынесла логику в хуки, остальное попробовала, но кажется излишним. Можем обсудить

2023-11-18 06:41 UTC, YrStudenikin commented
Нашел баг: Если заполнить все ячейки и продолжать вводить, последнее значение будет изменяться. Скорее всего нужно снимать фокус если были введены все значения


https://github.com/kaluga-astral/frontend/assets/62848436/2cfe12f7-cd46-4172-8715-4ff8afbaebca

2023-11-18 06:49 UTC, YrStudenikin commented
Я думаю что нельзя позволять начинать ввод с любой ячейки если поле пустое. Смотрел примеры подобных компонентов, как правило, при клике на любую ячейку фокус смещается на первую


https://github.com/kaluga-astral/frontend/assets/62848436/01764d9f-19fa-43bd-a87c-a28aa2dcd78b

2023-11-18 06:53 UTC, YrStudenikin commented on packages/components/src/CodeField/CodeField.tsx
> +export type CodeFieldInputProps = {
Input в названии лишний

2023-11-18 06:55 UTC, YrStudenikin commented on packages/components/src/CodeField/CodeField.tsx
> +  disabled?: boolean;
Наименования не по style guide

2023-11-18 06:55 UTC, YrStudenikin commented on packages/components/src/CodeField/ResendСodeButton/ResendСodeButton.tsx
> +  loading: boolean;
Наименования не по style guide

2023-11-18 06:56 UTC, YrStudenikin commented on packages/components/src/CodeField/CodeField.tsx
> +  isError?: boolean;
Наименования не по style guide

2023-11-21 10:39 UTC, StanislavDa commented on packages/components/src/CodeField/CodeField.tsx
> +              value={value ?? ''}
Если просто value оставить, что-то сломается?

2023-11-21 10:39 UTC, StanislavDa commented on packages/components/src/CodeField/CodeField.tsx
> +            <Digit
CodeFieldDigit

2023-11-21 10:39 UTC, StanislavDa commented on packages/components/src/CodeField/CodeField.tsx
> +              ref={(el) => el && (inputRefs.current[index] = el)}
лучше в функцию вынести. Типа, ref={setRef}

2023-11-21 10:39 UTC, StanislavDa commented on packages/components/src/CodeField/hooks/useCodeState/useCodeState.ts
> +    if (onComplete) {
Не особо понятно что должен делать onComplete. Если это метод для отправки полностью заполненного кода на проверку бэку, то почему он вызывается каждый раз при заполнении кода?

2023-11-21 10:39 UTC, StanislavDa commented on packages/components/src/CodeField/hooks/useCodeState/useCodeState.ts
> +      case KEYBOARD_KEYS.arrowUp:
Для чего нужна обработка нажатий на стрелки вверх-вниз? Если их убрать, то что-то сломается?

2023-11-21 14:05 UTC, JetBlackCodes commented on packages/components/src/CodeField/hooks/useCodeState/useCodeState.ts
> +      case KEYBOARD_KEYS.arrowUp:
В предыдущей реализации можно было стрелками вверх/вниз переключаться между полями, что было как-то странно.
Сейчас влияет только на положение курсора внутри инпута, думаю действительно можно убрать

2023-11-21 14:06 UTC, AndTem commented on packages/components/src/hooks/useTimer/useTimer.ts
> +export const useTimer = (
Может лучше взять готовую либу? Например, https://usehooks.com/usecountdown

2023-11-21 14:08 UTC, AndTem commented on packages/components/src/CodeField/CodeField.test.tsx
> +describe('CodeField', () => {
Необходимо увеличить количество тест кейсов: отработка onComplete, например

2023-11-21 14:09 UTC, AndTem commented on packages/components/src/CodeField/CodeField.stories.tsx
> +/**
Нужно краткое назначение компонента

2023-11-21 14:12 UTC, AndTem commented on packages/components/src/CodeField/styles.ts
> +export const CodeFieldDigitsWrapper = styled.div`
Не ul разве?

2023-11-21 14:13 UTC, AndTem commented on packages/components/src/CodeField/index.ts
> +export { KEYBOARD_KEYS } from './constants';
Все эти константы не нужны вне компонента

2023-11-21 14:15 UTC, JetBlackCodes commented on packages/components/src/CodeField/CodeField.tsx
> +              value={value ?? ''}
в текущей реализации можно убрать

2023-11-21 14:16 UTC, AndTem commented on packages/components/src/hooks/useTimer/useTimer.ts
> +export const useTimer = (
Потому что готовая либа уже протестирована

2023-11-24 11:14 UTC, JetBlackCodes commented on packages/components/src/CodeField/CodeField.tsx
> +              value={value ?? ''}
Поправка, убрать нельзя)
Эта штука отвечает за то, чтобы в инпуте было только то, что и в value. Иначе визуально можно писать что угодно в инпут: буквы, знаки и т.д., хотя в value они отсеиваются

2023-11-24 12:38 UTC, JetBlackCodes commented on packages/components/src/CodeField/CodeField.tsx
> +  time?: number;
codeLength согласна, сделаю обязательным.
а вот на счет time, если время не передается, то отображается код без кнопки перезапроса. 
Разрулить еще одним пропсом?

![image](https://github.com/kaluga-astral/frontend/assets/48980301/6915aee2-f27d-4eb8-8f5e-455486e6a6cb)

2023-11-24 12:47 UTC, JetBlackCodes commented on packages/components/src/CodeField/CodeField.tsx
> +  time?: number;
c codeLength согласна, а вот time наверное не стоит делать обязательным, т.к. есть вариант отображения без таймера, будет странно передавать время, когда оно не отображается

2023-12-01 13:36 UTC, AndTem requested changes

2023-12-01 13:36 UTC, AndTem commented on packages/components/src/CodeField/CodeField.tsx
> +      el && (inputRefs.current[index] = el);
Ты знаешь как работает оператор &&? Сделай через if конструкцию

2023-12-01 13:36 UTC, AndTem commented on packages/components/src/CodeField/hooks/useCodeState/useCodeState.ts
> +    newCodeValue[deleteIndex] = '';
я бы эту операцию вынес в отдельный метод и тогда комментарии были бы не нужны

2023-12-01 13:36 UTC, AndTem commented on packages/components/src/CodeField/hooks/useCodeState/useCodeState.ts
> +    let newCodeValue = [...codeValue];
Эта строка и ниже по факту относится к setCodeValue, но ты почему-то еще дублируешь в каждом месте, где вызывается setCodeValue

2023-12-01 13:36 UTC, AndTem commented on packages/components/src/CodeField/hooks/useCodeState/useCodeState.ts
> +      keyCode <= KEYBOARD_KEYS.endDigit
если вынесешь это условие в отдельную константу справильным названием, то это очень облегчит понимание

2023-12-01 13:36 UTC, AndTem commented on packages/components/src/CodeField/hooks/useCodeState/useCodeState.ts
> +      setCodeValue(Array.from({ length: codeLength }));
Почему не явное: setCodeValue([])? А лучше вообще метод clearCodeValue

2023-12-01 13:36 UTC, AndTem commented on packages/components/src/CodeField/hooks/useFocusIndex/useFocusIndex.ts
> + * @description предоставляет методы работы с фокусом на инпутах
Почему тогда не useFocusInput?

2023-12-01 13:36 UTC, AndTem commented on packages/components/src/hooks/useTimer/useTimer.ts
> +export const useTimer = (
up

2023-12-01 13:36 UTC, AndTem commented on packages/components/src/CodeField/CodeField.stories.tsx
> +/**
up

2023-12-01 13:36 UTC, AndTem commented on packages/components/src/index.ts
> +export * from './CodeField';
Сделай, пожалуйста, эксопрт конкретных сущностей. Это необходимо, чтобы не вытаскивать лишнего из кита

2023-12-01 13:36 UTC, AndTem commented on packages/components/src/utils/date/format/formatSecondsToTime/formatSecondsToTime.ts
> +export const formatSecondsToTime = (seconds: number): string => {
Intl.DateTimeFormat('ru', { second: "numeric", minute: "numeric",}).format(new Date())

2023-12-01 13:38 UTC, AndTem commented
Состояние loading конечно вызывает печаль.
<img width="1054" alt="image" src="https://github.com/kaluga-astral/frontend/assets/23665108/dcc25ff2-dbf6-4004-8441-2c12f327cc42">

В рамках mvp ок, но тут должен быть [content loader](https://www.npmjs.com/package/react-content-loader).
Создай иницитиву отдельную на это

2023-12-05 08:17 UTC, JetBlackCodes commented on packages/components/src/CodeField/hooks/useCodeState/useCodeState.ts
> +      setCodeValue(Array.from({ length: codeLength }));
Потому что мне пустое значение для этого поля не [], а ['','','','','','']

Вынесла в clearCodeValue

2023-12-12 06:45 UTC, JetBlackCodes commented on packages/components/src/hooks/useTimer/useTimer.ts
> +export const useTimer = (
1) Конкретно эта либа основывается на экспериментал реакте
2) Поискала другие либы, у них есть проблемка: ни в одном апи не нашла описание возможности динамически менять время таймера, а нам это нужно по бизнес-логике на проектах

2023-12-12 10:15 UTC, AndTem commented on packages/components/src/CodeField/CodeField.stories.tsx
> +      onComplete={() => alert('onComplete вызывается, когда поле заполнено')}
Текст из alert напиши как коммент к OnComplete, чтобы появилось описание в docs

2023-12-12 10:15 UTC, AndTem commented on packages/components/src/CodeField/styles.ts
> +  gap: 12px;
Отступы через theme.spacing

2023-12-12 10:15 UTC, AndTem commented on packages/components/src/CodeField/styles.ts
> +  padding: 18px 25px;
Отступы через theme.spacing

2023-12-12 10:15 UTC, AndTem commented on packages/components/src/CodeField/hooks/useCodeState/useCodeState.ts
> +  useEffect(() => {
А этот useEffect не ломает логику, если есть initialValue?

2023-12-12 10:15 UTC, AndTem commented on packages/components/src/CodeField/hooks/useCodeState/useCodeState.ts
> +      keyCode <= KEYBOARD_KEYS.endDigit
up

2023-12-12 10:19 UTC, AndTem requested changes

2023-12-12 10:19 UTC, AndTem commented on packages/components/src/utils/date/format/formatSecondsToTime/formatSecondsToTime.test.ts
> +  it('0 секунд', () => {
Названия тест кейсов конечно удручающие. Сделай через it.each

2023-12-12 10:19 UTC, AndTem commented on packages/components/src/hooks/useTimer/useTimer.ts
> +  let timerId: ReturnType<typeof setInterval> | null = null;
при перерендере ты потеряешь id

2023-12-12 16:10 UTC, StanislavDa approved these changes

2023-12-12 16:45 UTC, YrStudenikin commented on packages/components/src/hooks/useTimer/useTimer.ts
> +export const useTimer = (
Вот еще вариант
https://github.com/bradgarropy/use-countdown

2023-12-14 08:30 UTC, JetBlackCodes commented on packages/components/src/utils/date/format/formatSecondsToTime/formatSecondsToTime.test.ts
> +  it('0 секунд', () => {
удалено, заменено на библиотеку

2023-12-14 08:31 UTC, JetBlackCodes commented on packages/components/src/CodeField/ResendСodeButton/ResendСodeButton.tsx
> +        restartTimer();
исправлено

2023-12-14 08:31 UTC, JetBlackCodes commented on packages/components/src/CodeField/ResendСodeButton/ResendСodeButton.tsx
> +  time,
исправлено на resendTimeout

2023-12-14 10:56 UTC, JetBlackCodes commented on packages/components/src/CodeField/CodeField.stories.tsx
> +      onComplete={() => alert('onComplete вызывается, когда поле заполнено')}
![image](https://github.com/kaluga-astral/frontend/assets/48980301/e01b9051-01fd-46d9-a940-e922b2ceb04a)
там есть описание вот такое

2023-12-14 10:59 UTC, AndTem commented on packages/components/src/CodeField/CodeField.stories.tsx
> +      onComplete={() => alert('onComplete вызывается, когда поле заполнено')}
Посмотри на story со стороны пользователя. Не понятно к чему оно и что надо сделать без коммента

2023-12-14 11:07 UTC, JetBlackCodes commented on packages/components/src/CodeField/hooks/useCodeState/useCodeState.ts
> +  useEffect(() => {
для initialValue конечно вызовется разок, но мне кажется это не должно быть проблемой

2023-12-14 11:08 UTC, JetBlackCodes commented on packages/components/src/hooks/useTimer/useTimer.ts
> +export const useTimer = (
Переписала с использованием библиотеки, которую Ярослав предложил, она гораздо удобнее, там даже форматтер встроенный есть

2023-12-14 11:13 UTC, JetBlackCodes commented on packages/components/src/CodeField/CodeField.stories.tsx
> +      onComplete={() => alert('onComplete вызывается, когда поле заполнено')}
Не сразу поняла, что речь про историю. Добавила комент

2023-12-14 11:16 UTC, JetBlackCodes commented on packages/components/src/CodeField/hooks/useCodeState/useCodeState.ts
> +      keyCode <= KEYBOARD_KEYS.endDigit
вынесла в константу

2023-12-18 06:58 UTC, YrStudenikin commented on packages/components/package.json
> +    "react-use": "^17.4.0",
Библиотека не используется, насколько вижу

2023-12-18 07:11 UTC, YrStudenikin commented on packages/components/src/CodeField/CodeField.tsx
> +export const CodeField = forwardRef<HTMLInputElement, CodeFieldProps>(
Съехала верстка, видимо из-за дефолтных отступов ul, на макетах отступов нет

<img width="424" alt="image" src="https://github.com/kaluga-astral/frontend/assets/62848436/b4a826ca-a880-4a23-9aa0-24ce67faf56e">

2023-12-18 08:11 UTC, AndTem commented
@JetBlackCodes тесты упали https://github.com/kaluga-astral/frontend/pull/729/checks?check_run_id=19636324208

2023-12-18 08:12 UTC, AndTem commented on packages/components/src/CodeField/CodeField.stories.tsx
> +      onComplete={() => alert('onComplete вызывается, когда поле заполнено')}
Закинь в alert value

2023-12-18 08:13 UTC, AndTem commented on packages/components/package.json
> +    "react-use": "^17.4.0",
используется в другом функционале

2023-12-18 08:17 UTC, AndTem commented on packages/components/src/CodeField/ResendСodeButton/ResendСodeButton.tsx
> +        .finally(() => setResendCodeLoading(false));
Вызов finally не отключает выброс исключению дальше. То есть у тебя здесь при reject вспылвет ошибка и крашнется компонент

2023-12-20 07:24 UTC, YrStudenikin approved these changes

2023-12-20 07:29 UTC, JetBlackCodes commented on packages/components/src/CodeField/CodeField.stories.tsx
> +      onComplete={() => alert('onComplete вызывается, когда поле заполнено')}
сделала

2023-12-20 07:29 UTC, JetBlackCodes commented on packages/components/src/CodeField/ResendСodeButton/ResendСodeButton.tsx
> +        .finally(() => setResendCodeLoading(false));
поправила

2023-12-20 07:45 UTC, AndTem approved these changes

2023-12-20 07:45 UTC, AndTem commented on packages/components/src/CodeField/CodeField.stories.tsx
> +      <button onClick={() => setTimeout(5)}>5s</button>
Не патриотично. Замени на кнопки из ui-kit

2023-12-20 08:31 UTC, merged