bug(UIKIT-985,ui,autocomplete): Исправлен размер иконки для очистки а…
kaluga-astral/frontend pull request #731
Opened 2023-11-03 13:06 UTC by Cabagemage

…втокомплита

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-11-03 13:13 UTC, YrStudenikin approved these changes

2023-11-03 13:36 UTC, AndTem requested changes

2023-11-03 13:36 UTC, AndTem commented on packages/components/src/theme/components/MuiAutocomplete.ts
>          '>svg': {
У иконки нет className, на который можно подвязаться? А то верстка хрупкая получается

2023-11-03 14:14 UTC, Cabagemage commented on packages/components/src/theme/components/MuiAutocomplete.ts
>          '>svg': {
Я посмотрю

2023-11-07 12:48 UTC, StanislavDa approved these changes

2023-11-08 06:47 UTC, merged