feat(UIKIT-1016,features,ProductSwitcher): Добавлены виджеты продуктов
kaluga-astral/frontend pull request #735
Opened 2023-11-08 12:48 UTC by cryzer12

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-11-09 06:12 UTC, AndTem requested changes

2023-11-09 06:12 UTC, AndTem commented on packages/features/src/productSwitcher/utils/formatIdentityProducts/formatIdentityProducts.ts
> +export const formatIdentityProducts = (
У тебя formatIdentityProducts - это по факту приватный метод getIdentityProducts. Я бы его инкапсулировал в getIdentityProducts и написал тест именно для getIdentityProducts, чтобы тест был более надежный

2023-11-09 06:12 UTC, AndTem commented on packages/features/src/productSwitcher/utils/formatIdentityProducts/formatIdentityProducts.test.ts
> +  it('formatIdentityProducts форматирует список продуктов identity в формат для виджета продуктов', () => {
```suggestion
  it('Форматирует список продуктов identity в формат для виджета продуктов', () => {
```

2023-11-09 06:12 UTC, AndTem commented on packages/features/src/productSwitcher/components/IdentityProductSwitcher/IdentityProductSwitcher.tsx
> +  const [tenants, setTenants] = useState<IdentityTenantsDTO[]>();
Предлагаю всю логику вынести в хук

2023-11-09 06:12 UTC, AndTem commented on packages/features/src/productSwitcher/components/IdentityProductSwitcher/IdentityProductSwitcher.tsx
> +        onClick={handleShowProducts}
Считаю, что async функцию в onClick пробрасывать не хорошо

2023-11-09 06:12 UTC, AndTem commented on packages/features/src/productSwitcher/components/IdentityProductSwitcher/IdentityProductsSwitcher.test.tsx
> +describe('IdentityProductSwitcher', () => {
Проверки на обработку статусов не хватает (loading, error)

2023-11-09 06:12 UTC, AndTem commented on packages/features/src/productSwitcher/components/IdentityProductSwitcher/IdentityProductSwitcher.stub.ts
> +const mockImage =
В данном случае отдельный файл stub не нужен потому, что эти данные используются только в story

2023-11-09 06:12 UTC, AndTem commented on packages/features/src/productSwitcher/components/IdentityProductSwitcher/IdentityProductsSwitcher.test.tsx
> +  it('При открытие виджета, список экосистем отображается корректно', async () => {
Очень абстрактное название кейса.
Здесь больше подходит: При открытии виджета в поповере отображается список продуктов

2023-11-09 06:12 UTC, AndTem commented on packages/features/src/productSwitcher/components/AstralProductSwitcher/AstralProductSwitcher.stories.tsx
> + * Внутри себя содержит всю логику получения, форматирования и отображения продуктов из Identity
В storybook надо бы указать к кому идти, чтобы получить инфу по url и tenant

2023-11-09 06:12 UTC, AndTem commented on packages/components/src/ProductSwitcher/ProductSwitcher.stories.tsx
>  export default {
Предлагаю здесь сделать ссылку на новые виджеты.
Типа написать, что это абстрактный компонент, но вам скорее всего нужен другой, готовый

2023-11-09 06:41 UTC, cryzer12 commented on packages/components/src/ProductSwitcher/ProductSwitcher.stories.tsx
>  export default {
хорошая идея

2023-11-09 15:01 UTC, cryzer12 commented on packages/features/src/productSwitcher/components/IdentityProductSwitcher/IdentityProductSwitcher.stub.ts
> +const mockImage =
просто не хочется лишних 150 строчек держать вместе со сторей, кажется они больше мешаться будут, не?

2023-11-09 15:02 UTC, cryzer12 commented on packages/features/src/productSwitcher/components/IdentityProductSwitcher/IdentityProductSwitcher.tsx
> +        onClick={handleShowProducts}
а в чем проблема?

2023-11-09 15:11 UTC, cryzer12 commented on packages/features/src/productSwitcher/utils/formatIdentityProducts/formatIdentityProducts.ts
> +export const formatIdentityProducts = (
просто кажется, что тестирование чистой функции форматтера проще, чем тестирование функции с сайдэффектами + в которой необходимо делать моки запросов. А моки запросов, для разных возможных кейсов с различными результатами еще сложнее, можно поковырять, просто стоит оно того? намного ли надежнее становится так? просто сейчас getIdentityProducts это по факту сам fetch, который можно не тестировать, а все остальное это форматтер + в одном месте парс json из даты, что уменьшает надежность

2023-11-09 15:14 UTC, cryzer12 commented on packages/features/src/productSwitcher/components/IdentityProductSwitcher/IdentityProductsSwitcher.test.tsx
> +  it('При открытие виджета, список экосистем отображается корректно', async () => {
в чат отписал

2023-11-10 06:48 UTC, AndTem commented on packages/features/src/productSwitcher/components/IdentityProductSwitcher/IdentityProductsSwitcher.test.tsx
> +  it('При открытие виджета, список экосистем отображается корректно', async () => {
Тогда просто - При открытие виджета отображается список экосистем

2023-11-10 12:53 UTC, AndTem requested changes

2023-11-10 12:53 UTC, AndTem commented on packages/features/package.json
> +    "@astral/icons": "*",
icons содержится внутри ui

2023-11-10 12:53 UTC, AndTem commented on packages/features/src/productSwitcher/components/IdentityProductSwitcher/IdentityProductSwitcher.tsx
> +import { ErrorFillSm, ProductsFillMd } from '@astral/icons';
Из astral/ui этот импорт должен быть

2023-11-10 12:53 UTC, AndTem commented on packages/features/src/productSwitcher/components/IdentityProductSwitcher/styles.ts
> +export const WidgetMenu = styled(Menu)`
Названия копонентов не по [style guide](https://track.astral.ru/soft/wiki/display/FG/React#React-%D0%94%D0%BB%D1%8Fstyledcomponents%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD%D0%BF%D1%80%D0%B8%D1%81%D1%83%D1%82%D1%81%D1%82%D0%B2%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D0%BF%D1%80%D0%B5%D1%84%D0%B8%D0%BA%D1%81-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D1%80%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%BE%D0%B3%D0%BE%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0)

2023-11-10 13:12 UTC, AndTem approved these changes

2023-11-10 13:31 UTC, StanislavDa approved these changes

2023-11-10 14:42 UTC, merged