feat(UIKIT-1029,utils): Вынесен пакет с утилами
kaluga-astral/frontend pull request #736
Opened 2023-11-08 14:28 UTC by cryzer12

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-11-09 12:18 UTC, AndTem requested changes

2023-11-09 12:18 UTC, AndTem commented on packages/utils/README.md
> +Например ```formatPhoneToView```, которая преобразует строку
Сделай подраздел ## formatPhoneToView и напиши мини доку для этой утилы.
Можешь посмотреть как сделано [здесь](https://www.npmjs.com/package/@astral/validations#date)

2023-11-09 12:18 UTC, AndTem commented on packages/utils/README.md
> +Данный пакет предназначен для выноса общих функций и утилит.
```suggestion
Утилиты и функции общего назначения.
```

2023-11-09 12:18 UTC, AndTem commented on packages/utils/src/index.ts
> +export * from './date';
Функции date пока оставляем в compnents DatePicker. Надо обсудить на груминге формат утил и их актуалность

2023-11-09 12:18 UTC, AndTem commented on packages/utils/src/index.ts
> +export * from './date';
Создать, пожалуйста, задачу на обсуждение этого вопроса

2023-11-09 12:18 UTC, AndTem commented on packages/utils/vitest.config.ts
> +export default createVitestConfig({ useJsDOM: true });
```suggestion
export default createVitestConfig({ useJsDOM: false });
```

2023-11-09 12:18 UTC, AndTem commented on packages/utils/src/index.ts
> +export * from './phone';
Не будем совершать ошибок прошлого - делаем экспорт конкретных функций и типов

2023-11-09 12:18 UTC, AndTem commented on packages/utils/pack.js
> +  files: ['declarations.d.ts'],
Лишнее

2024-05-16 07:55 UTC, mfrolov89 commented on packages/utils/package.json
> +    "remeda": "^1.40.1"
Говорили про фиксацию версий используемых пакетов, думаю здесь нужно так же фиксировать

2024-05-16 07:55 UTC, mfrolov89 commented on packages/utils/src/phone/formatPhoneToView/formatPhoneToView.ts
> + * @param {options} isStartWithPlus - начинать с +7 или с 8
думаю стоит указать явно, что при этой опции телефон будет начинаться с +7, а так не совсем понятно что она делает

2024-05-16 08:05 UTC, Kostayne approved these changes

2024-05-27 06:21 UTC, mfrolov89 approved these changes

2024-05-27 13:58 UTC, merged