chore: Обновлены stylelint, commitlint, eslint
kaluga-astral/frontend pull request #738
Opened 2023-11-10 11:24 UTC by gadji9

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-11-10 11:59 UTC, AndTem requested changes

2023-11-10 11:59 UTC, AndTem commented on .eslintrc
> +    "@typescript-eslint/consistent-type-imports": "error"
Конфиг должен использоваться как есть и не модифицироваться. В этом и есть смысл стандартизации

2023-11-10 11:59 UTC, AndTem commented on package.json
> +    "@astral/eslint-config-react-ts": "^1.8.0",
Все конфиги должны быть обновлены до второй последней версии

2023-11-10 11:59 UTC, AndTem commented on package.json
> +    "prettier": "^2.8.8",
Последняя версия ж 3

2023-11-10 11:59 UTC, AndTem commented on package.json
> +    "stylelint": "^14.16.1",
15 последняя версия

2023-11-10 13:57 UTC, AndTem requested changes

2023-11-10 13:57 UTC, AndTem commented on commander/package.json
> +    "@astral/eslint-config-node": "^1.8.0"
```suggestion
    "@astral/eslint-config-node": "^2.0.0"
```

2023-11-10 13:58 UTC, AndTem commented
В CI ошибки при установке зависимостей

2023-11-16 08:33 UTC, Ofigelov commented on packages/components/src/CollapsibleTypography/styles.ts
> +  display: ${({ isOpenCollapse }) => (isOpenCollapse ? '' : 'flex')};
а это тут зачем?

2023-11-16 09:01 UTC, Ofigelov commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/styles.ts
> +  &:nth-of-type(${({ lengthInRow }) => lengthInRow}n + 1) {
эти строчки тоже как то автолинтером перенеслись?
если нет, то лучше вернуть, т.к. стили каскадные, и перекрывают стили заданные ранее, т.е. порядок селекторов важен

2023-11-16 09:09 UTC, Ofigelov commented on packages/components/src/OverflowTypography/styles.ts
> +  display: ${({ hasMultipleRows }) => (hasMultipleRows ? 'flex' : '')};
тут тоже не к месту, `-webkit-box` нужен для обрезки строчек, просто с флексом работать не будет

2023-11-17 07:59 UTC, gadji9 commented on packages/components/src/DatePicker/DateCalendar/DateCalendarGridBtn/styles.ts
> +  &:nth-of-type(${({ lengthInRow }) => lengthInRow}n + 1) {
Авто-линтер сам перенес. Я только два файла стилей поменял, изменил -webkit-box на flex

2023-11-17 08:00 UTC, gadji9 commented on packages/components/src/CollapsibleTypography/styles.ts
> +  display: ${({ isOpenCollapse }) => (isOpenCollapse ? '' : 'flex')};
Eslint ругается на -webkit-box

2023-11-17 09:14 UTC, gadji9 commented on packages/components/src/OverflowTypography/styles.ts
> +  display: ${({ hasMultipleRows }) => (hasMultipleRows ? 'flex' : '')};
Вернул -webkit-box, и сверху поставил /* stylelint-disable-next-line */

2023-11-17 09:19 UTC, Ofigelov approved these changes

2023-11-20 10:55 UTC, lordniken commented on packages/components/src/ActionCell/ActionCell.stories.tsx
> +import { ActionCell } from './ActionCell';
Зачем дублировать импорты? почему не

```
import { ActionCell, type Actions } from './ActionCell';
```

2023-11-24 12:22 UTC, closed without merging