feat(UIKIT-873,ui,NotificationList): Добавлен компонент NotificationList
kaluga-astral/frontend pull request #739
Opened 2023-11-14 07:24 UTC by max-cepelev

# Чеклист

- [*] Написать тесты для реализованного функционала
- [*] Описать jsdoc для экспортируемых функций, компонентов
- [*] Описать jsdoc для props экспортируемых компонентов
- [*] Реализовать или обновить storybook для компонента
- [*] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [*] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-11-14 10:20 UTC, DesignASoft commented
уведомления считаются прочитанными, если пользователь открыл NotificationList и закрыл его. При этом Прочитанными будут только те уведомления, которые попали в поле зрения на странице. Те уведомления, которые были под скроллом и пользователь их не видел, должны остаться не прочитанными
Также уведомление становится прочитанным, если пользователь перешел по кнопке действия в нем

Кнопка Отметить все как прочитанные находится в правом нижнем углу модалки и имеет фиксированное положение.

В Storybook для вариантов With button этой кнопки нет, в варианте with icon есть кнопка отметить как прочитанное есть в каждом непрочитанном уведомлении. Со стороны дизайна такие варианты не рассматривались

2023-11-15 02:07 UTC, aesarantsev commented on packages/components/src/NotificationList/NotificationListItem/NotificationListItem.tsx
> +  if (onNotificationVisible && isUnread && !!entry?.isIntersecting) {
Тут точно нужно приводить `isIntersecting` к `Boolean`? Он и так вроде им является. Если да, то нужно так делать:
`Boolean(entry?.isIntersecting)`
[Style guide](https://track.astral.ru/soft/wiki/pages/viewpage.action?pageId=3557425260#id-%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5%D1%82%D0%B8%D0%BF%D0%BE%D0%B2-%D0%9F%D1%80%D0%B8%D0%BF%D1%80%D0%B5%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8%D1%82%D0%B8%D0%BF%D0%BE%D0%B2%D0%B2Boolean%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D0%B5%D1%82%D1%81%D1%8F%D1%8F%D0%B2%D0%BD%D0%BE%D0%B5%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5)

2023-11-15 02:07 UTC, aesarantsev commented on packages/components/src/NotificationList/hooks/useIntersectionObserver.ts
> +    const hasIOSupport = !!window.IntersectionObserver;
`Boolean(window.IntersectionObserver)`

2023-11-15 05:04 UTC, max-cepelev commented on packages/components/src/NotificationList/NotificationListItem/NotificationListItem.tsx
> +  if (onNotificationVisible && isUnread && !!entry?.isIntersecting) {
Да, это лишнее

2023-11-17 08:22 UTC, max-cepelev commented
> Для варианта with links в notification list нет кнопки "Отметить все как прочитанные" Для without tabs - при закрытии окна и при нажатии "Отметить все как прочитанные" счетчик не меняется

Кнопка "Отметить все как прочитанные" сделана опциональной, т.к. в реализации ЭДО ее, скорее всего не будет, поэтому ее там специально нет. В without tabs пример сделан только для демонстрации, что есть такой вариант. Но логику добавлю. Вообще, логика обработки прочитанных уведомлений вынесена из компонента, т.к. предполагается, что она на каждом проекте может быть разной. У нас в ЭДО она будет реализована при переходе в определенный раздел.

2023-11-20 07:15 UTC, AndTem requested changes

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.stories.tsx
> +export const WithLinks = () => {
WithActions.
И добавить пояснение текстом, что в для уведомления можно прокинуть любой компонент в футер

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.stories.tsx
> +export const WithoutTabs = () => {
Нужно пояснение текстом при каких условиях табы не отображаются

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.stories.tsx
> +const meta: Meta<typeof NotificationList> = {
Нужна отдельная story с демонстрацией прочтения уведомления и пояснением текстом как это работает

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/NotificationListItem/NotificationListItem.test.tsx
> +describe('NotificationListItem', () => {
Писать тест нужно только для верхнеуровненого компонента, для вложенных не имеет смысла

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/NotificationListItem/NotificationListItem.tsx
> +export type NotificationListItemProps = {
Переиспользуй тип Notification для определения пропсов

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/NotificationListItem/NotificationListItem.tsx
> +  if (onViewNotification && isUnread && entry?.isIntersecting) {
Очень странно, что у тебя вызов даже не обернут в useEffect

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/NotificationListItem/styles.ts
> +  & svg {
Привязаться к конкретному компоненту, классу нельзя? Верстка сейчас хрупкая

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/NotificationListItem/hooks/useIntersectionObserver.ts
> +export function useIntersectionObserver(
Используй хук из react-use https://github.com/streamich/react-use/blob/master/docs/useIntersection.md

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.tsx
> +import { NotificationListTabs } from './NotificationListTabs/NotificationListTabs';
Забыл сделать index файл

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/constants.ts
> +export const NOTIFICATION_PRIORITIES = {
Enum бы лучше подошел

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/NotificationListTabs/NotificationListTabs.tsx
> +    <StyledTabs value={isUnreadOnly ? 0 : 1} onChange={onToggleUnreadOnly}>
Не понятно что за 0 и 1

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/NotificationListTabs/NotificationListTabs.tsx
> +export const NotificationListTabs = ({
Подозреваю, что табы могут отличаться от проекта к проекта.
Поэтому лучше придумать расширяемый интерфейс. Например, сделать так, чтобы табы можно было прокидывать отдельным компонентом или конфигурировать из вне.
Я сейчас говорю просто про то, что надо заранее себе помочь

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.tsx
> +export const NotificationList = ({
Предлагаю сделать еще один компонент - NotificationsWidget | NotificationsManager (название примерное), в который будет инкапсулирована кнопка с badge

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/styles.ts
> +  & .MuiPaper-root {
используй classes константы из mui

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.tsx
> +          <IconButton variant="text" onClick={onSettingsButtonClick}>
Этой кнопки может не быть. Нужен флаг isShowSettingsButton + возможность прокинуть любой контент в header

2023-11-20 07:15 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.tsx
> +  noDataImgSrc?: string;
alt тоже ведь нужен

2023-11-20 07:20 UTC, AndTem commented on packages/components/src/NotificationList/styles.ts
> +  & .MuiPaper-root {
https://github.com/kaluga-astral/frontend/blob/main/packages/components/src/theme/components/MuiMenuItem.ts#L13

2023-11-20 07:24 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.stories.tsx
> +  const handleRead = (id: string | number) => {
И логика вызова unred при закрытии модалки тоже должны быть инкапсулирована в компонент

2023-11-20 07:46 UTC, max-cepelev commented on packages/components/src/NotificationList/types.ts
> +  isUnread?: boolean;
Флаг нужен для отображения непрочитанных уведомлений в общем списке, т.к. в нем могут быть и прочитанные и нет.

2023-11-20 07:49 UTC, max-cepelev commented on packages/components/src/NotificationList/NotificationList.stories.tsx
> +  const handleRead = (id: string | number) => {
Да, сомневался в этом моменте, инкапсулировать или нет. Посчитал, что логика обработки непрочитанных сообщений на проектах может быть разной. Перенесу тогда в компонент.

2023-11-20 08:42 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.stories.tsx
> +  const handleRead = (id: string | number) => {
Она действительно может быть разной, но можно будет просто добавить mode или reason в будущем

2023-11-20 12:26 UTC, max-cepelev commented on packages/components/src/NotificationList/NotificationListItem/styles.ts
> +  & svg {
Сделал сначала, чтобы можно было передать Icon, т.к. в старом макете на ЭДО именно иконки. Вынес priority сюда, чтобы передавать pririty color и в иконку и в статус. Но потом убрал, т.к. нет в shared макете, поэтому перенесу props в ListItemPriority.

2023-11-24 07:45 UTC, max-cepelev commented on packages/components/src/NotificationList/NotificationList.tsx
> +      listRef.current.scrollTop = 0;
Пробовал сделать отдельный контейнер для каждого списка, чтобы scroll был для каждого свой. Но результат не сильно отличается, поэтому оставил пока как было, scrollTop убрал, возможно отдельной задачей нужно будет обсудить и сделать.

2023-11-24 07:48 UTC, max-cepelev commented on packages/components/src/NotificationList/NotificationList.tsx
> +export const NotificationList = ({
Заведу инициативу, и отдельной задачей сделаю, есть несколько моментов обсудить.

2023-11-27 00:23 UTC, aesarantsev approved these changes

2023-11-27 07:24 UTC, AndTem commented
Тригерни design review

2023-11-27 07:50 UTC, AndTem requested changes

2023-11-27 07:50 UTC, AndTem commented on packages/components/src/DialogHeader/styles.ts
> +   * @type boolean
Я уже писал, что type не надо описывать и default в принципе тоже

2023-11-27 07:50 UTC, AndTem commented on packages/components/src/DialogHeader/styles.ts
>    align-items: center;
Эта правка не приеведет к багам верстки в продуктах?

2023-11-27 07:50 UTC, AndTem commented on packages/components/src/DialogHeader/DialogHeader.tsx
> +export type DialogHeaderProps = DialogHeaderContentProps & {
DialogHeaderProps не должен зависеть от пропсов styled. Любок изменения styled будет влечь за собой изменение API и braking changes.
Также у тебя сейчас в корне появлися пропс spacing, который семантически вообще не понятно к чему относится

2023-11-27 07:50 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.tsx
> +   * @default false
deafult ты указываешь в коде. Не за чем дублировать

2023-11-27 07:50 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.tsx
> +  isInitialUnreadOnly?: boolean;
С новым описанием стало лучше.
Текущее решение кажется не гибким. Лучше сделать через intersection:
listType: 'new' | 'unread'

2023-11-27 07:50 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.tsx
> +export const NotificationList = ({
Не вижу обработки статусов: loading, error.
Данные же могут загружаться долго или с ошибкой

2023-11-27 07:50 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.tsx
> +  const tabIndex = isUnreadOnly ? 0 : 1;
tabIndex - это зарезервированный термин. И здесь это не то

2023-11-27 07:50 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.stories.tsx
> +  const handleClose = (viewedIds: (number | string)[]) => {
Сделай id только string и не будет проблем с типобезопасностью

2023-11-27 07:50 UTC, AndTem commented on packages/components/src/NotificationList/NotificationListSettingsButton/NotificationListSettingsButton.tsx
> +  if (!onClick) {
Нарушение принципы единственной ответственности.
Решать нужно ли рендериться компоненту или нет необходимо компоненту, который рендерит NotificationListSettingsButton

2023-11-27 07:50 UTC, AndTem commented on packages/components/src/NotificationList/NotificationListEmpty/NotificationListEmpty.tsx
> +  noDataImgAlt = 'Нет уведомлений',
Почитай ка что такое alt и что в нем должно быть написано: https://doka.guide/html/img/#alt

2023-11-27 07:50 UTC, AndTem commented on packages/components/src/NotificationList/NotificationListEmpty/NotificationListEmpty.tsx
> +    <Container>
Читай [style guide](https://track.astral.ru/soft/wiki/display/FG/React#React-%D0%94%D0%BB%D1%8Fstyledcomponents%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD%D0%BF%D1%80%D0%B8%D1%81%D1%83%D1%82%D1%81%D1%82%D0%B2%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D0%BF%D1%80%D0%B5%D1%84%D0%B8%D0%BA%D1%81-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D1%80%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%BE%D0%B3%D0%BE%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0)

2023-11-27 07:50 UTC, AndTem commented on packages/components/src/NotificationList/NotificationListTabs/styles.ts
> +export const StyledTabs = styled(Tabs)`
Читай [style guide](https://track.astral.ru/soft/wiki/display/FG/React#React-%D0%94%D0%BB%D1%8Fstyledcomponents%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD%D0%BF%D1%80%D0%B8%D1%81%D1%83%D1%82%D1%81%D1%82%D0%B2%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D0%BF%D1%80%D0%B5%D1%84%D0%B8%D0%BA%D1%81-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D1%80%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%BE%D0%B3%D0%BE%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0)

2023-11-27 07:50 UTC, AndTem commented on packages/components/src/SideDialog/SideDialog.stories.tsx
> +import { Alert, Button, Divider, Grid, IconButton, Tag, Typography } from '..';
Импортов .. быть не должно

2023-11-27 07:50 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.tsx
> +        noDataImgSrc={noDataImgSrc}
Забери по дфеоту эти пропсы из ConfigProvider

2023-11-27 07:50 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.stories.tsx
> +/**####Использование IntersectionObserver
Для пользователя ui-kit это не важная информация.
Важная информация - уведомления помечаются прочитанными, когда попадают во viewport и потом id пердаются при закрытии.
Детали реализации здесь описывать не нужно (потом еще будет доку вечно переделывать при рефакторинге)

2023-11-27 08:15 UTC, max-cepelev commented on packages/components/src/DialogHeader/styles.ts
>    align-items: center;
Нет, там до этого был LegacyGrid, в котором был spacing={2}

2023-11-27 08:17 UTC, max-cepelev commented on packages/components/src/NotificationList/NotificationList.tsx
> +export const NotificationList = ({
ContentState здесь можно использовать?

2023-11-27 08:20 UTC, AndTem commented on packages/components/src/DialogHeader/styles.ts
>    align-items: center;
Хм, мне github неверный diff показал

2023-11-27 08:23 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.tsx
> +export const NotificationList = ({
Да

2023-11-27 08:26 UTC, max-cepelev commented on packages/components/src/SideDialogHeader/SideDialogHeader.tsx
> +export type { DialogHeaderProps as SideDialogHeaderProps } from '../DialogHeader';
Добавил пример с использованием SideDialogHeader в storybook SideDialog, нужно его перенести в SideDialogHeader?

2023-11-27 10:52 UTC, max-cepelev commented on packages/components/src/NotificationList/NotificationListEmpty/NotificationListEmpty.tsx
> +  noDataImgAlt = 'Нет уведомлений',
Согласно описанию, картинки делятся на смысловые и декоративные. И декоративные картинки описывать не нужно. В нашем случае изображение явно декоративное, нужен ли alt здесь в принципе?

2023-11-27 11:50 UTC, max-cepelev commented on packages/components/src/NotificationList/NotificationList.tsx
> +  isInitialUnreadOnly?: boolean;
Флагу isInitialUnreadOnly можно передать логику unreadNotification === 0, чтобы не выводить пустой список, удобно ли будет делать это с listType: 'new' | 'unread'?

2023-12-01 12:56 UTC, AndTem commented on packages/components/src/SideDialogHeader/SideDialogHeader.tsx
> +export type { DialogHeaderProps as SideDialogHeaderProps } from '../DialogHeader';
Да, можно просто продублировать кейс

2023-12-01 13:10 UTC, AndTem approved these changes

2023-12-01 13:10 UTC, AndTem commented on packages/components/src/NotificationList/NotificationListItem/NotificationListItem.tsx
> +      {isDeleteButtonVisible ? (
isDeleteButtonVisible && <Listiem

Так проще и лучше читается

2023-12-01 13:10 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.tsx
> +          imgSrc: imagesMap.defaultErrorImgSrc,
Должно браться либо из пропсов, либо из контекста

2023-12-01 13:10 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.tsx
> +  isInitialUnreadOnly?: boolean;
А если добавиться еще один таб, что делать?

2023-12-05 08:18 UTC, max-cepelev commented on packages/components/src/NotificationList/NotificationList.tsx
> +          imgSrc: imagesMap.defaultErrorImgSrc,
imagesMap берется из ConfigContext, а из imagesMap берем источники для изображений состояния

2023-12-05 11:18 UTC, DesignASoft approved these changes

2023-12-05 11:25 UTC, merged