bug(UIKIT-1041,ui,DatePicker): Исправлен баг с появлением popover при disabled
kaluga-astral/frontend pull request #742
Opened 2023-11-20 10:22 UTC by YrStudenikin

… disabled

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-11-20 10:24 UTC, Ofigelov approved these changes

2023-11-21 06:22 UTC, AndTem requested changes

2023-11-21 06:22 UTC, AndTem commented on packages/components/src/DatePicker/DatePicker.test.tsx
> +    const inputWrapper = document.querySelector('div[tabindex="-1"]')!;
Очень хрупкий тест получился из-за этого селектора

2023-11-21 06:22 UTC, AndTem commented on packages/components/src/DatePicker/DatePickerInput/DatePickerInput.tsx
> +  const handleFocusWrapper = useMemo(
А нельзя просто в div прокинуть атрибут disabled? Или через css pointer event выключить

2023-11-21 07:07 UTC, YrStudenikin commented on packages/components/src/DatePicker/DatePickerInput/DatePickerInput.tsx
> +  const handleFocusWrapper = useMemo(
disabled для div не поддерживается  
А pointer-events не будет работать потому что есть потомки, у которых нет этого свойства. Например label  

<img width="589" alt="image" src="https://github.com/kaluga-astral/frontend/assets/62848436/5d553ccc-b0bf-4b0f-a980-f226ffdd68d2">

2023-11-21 07:08 UTC, YrStudenikin commented on packages/components/src/DatePicker/DatePicker.test.tsx
> +    const inputWrapper = document.querySelector('div[tabindex="-1"]')!;
Добавил атрибут aria-disabled

2023-11-21 07:14 UTC, AndTem approved these changes

2023-11-21 07:16 UTC, merged