doc(UIKIT-928,ui,DashboardLayout): Storybook для DashboardLayout
kaluga-astral/frontend pull request #743
Opened 2023-11-20 10:53 UTC by maksimmolofeev

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-11-22 09:17 UTC, YrStudenikin commented
Поскольку DashboardLayout реализован подходом compound components, отдельно он из себя мало что представляет: 
<img width="258" alt="image" src="https://github.com/kaluga-astral/frontend/assets/62848436/f0be982f-96f3-483c-b70f-7bd070b7d934">


Я считаю, что необходимо реализовать полноценный сторибук, в котором будут описаны все входящие компоненты в DashboardLayout по отдельности. Как пример:
<img width="292" alt="image" src="https://github.com/kaluga-astral/frontend/assets/62848436/94bc1218-ab9b-4c59-9686-a358bb35bff5">

Где каждый отдельный компонент будет стандартно описан имея информацию, основные пропсы и т.д.

@AndTem Если не трудно, дополни мнением

2023-11-22 09:18 UTC, YrStudenikin commented
#

> Поскольку DashboardLayout реализован подходом compound components, отдельно он из себя мало что представляет: <img alt="image" width="258" src="https://user-images.githubusercontent.com/62848436/284849563-f0be982f-96f3-483c-b70f-7bd070b7d934.png">
> 
> Я считаю, что необходимо реализовать полноценный сторибук, в котором будут описаны все входящие компоненты в DashboardLayout по отдельности. Как пример: <img alt="image" width="292" src="https://user-images.githubusercontent.com/62848436/284848363-94bc1218-ab9b-4c59-9686-a358bb35bff5.png">
> 
> Где каждый отдельный компонент будет стандартно описан имея информацию, основные пропсы и т.д.
> 
> @AndTem Дополни мнением, пожалуйста

2023-11-22 09:41 UTC, AndTem commented
Согласен с Ярославом.
Надо сделать единую страницу с example, а потом по отдельности для каждого компонента, чтобы было видно пропсы.
Не забывай еще посматривать на show code в сторибуке, там должен находится весь код, который поможет тебе понять как работать с компонентом

2023-11-23 08:17 UTC, YrStudenikin commented
Для вложенных компонентов не хватает описания и отображения пропсов.
Как пример приведу props `product` из  `DashboardLayout.Header`. Хотелось бы увидеть описание и таргетный фокус на этом пропсе (и на других основных тоже).

[Тут](https://main--61baeff6f06230003a88ef8a.chromatic.com/?path=/docs/components-pagelayout-pageheader--docs) можно посмотреть на варианты оформления каждого отдельного пропса

2023-11-24 07:50 UTC, YrStudenikin approved these changes

2023-11-27 13:31 UTC, AndTem requested changes

2023-11-27 13:31 UTC, AndTem commented on packages/components/src/DashboardLayout/DashboardLayout.stories.tsx
> + - Header (DashboardLayout.Header)
Сделай ссылки на компонент - [пример](https://github.com/kaluga-astral/frontend/blob/main/packages/form/src/FormTextField/FormTextField.stories.tsx#L14)

2023-11-27 13:31 UTC, AndTem commented on packages/components/src/DashboardLayout/DashboardLayout.stories.tsx
> +    <DashboardLayout>
У сторей сейчас большие отступы по краям получаются. Сделай так, чтобы компонент растягивался на всю ширину, которая ему предоставлена

2023-11-27 13:31 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.stories.tsx
> + * DashboardLayout.Header - данный компонет может включать в себя информацию о продукте(product), переключатель продуктов(productSwitcher), профиль пользователя(profile) и меню организаций(organizati
Лишняя информация про то, что он может в себя включать. Ниже ты все. это описываешь. Тут еще придется и при добавлении новых фич сюда описание добавлять

2023-11-27 13:31 UTC, AndTem commented on packages/components/src/DashboardLayout/DashboardLayout.stories.tsx
> + * ### [Guide]()
На макеты ссылки пропустил везде

2023-11-27 13:31 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.stories.tsx
> + * product - содержит информацию о продукте
Этот комментарий и все ниже не несут никакой смысловой нагрузки. Названия сторей говорят сами за себя

2023-11-27 13:31 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.stories.tsx
> +    <DashboardLayoutWrapper>
Может везде Sidebar Добавить? А то выглядт header странно в отрыве от других компонентов (он отдельно жить и не должен)

2023-11-27 13:31 UTC, AndTem commented on packages/components/src/DashboardLayout/Main/Main.stories.tsx
> +      <DashboardLayout.Main>Main Content</DashboardLayout.Main>
Отрендери header и sidebar

2023-11-27 13:31 UTC, AndTem commented on packages/components/src/DashboardLayout/Main/Main.stories.tsx
> + * DashboardLayout.Main - компонент с основным контентом дашборда, состоит из элементов передаваемых в children.
```suggestion
 * DashboardLayout.Main - содержит основной контент приложения.
```

2023-11-27 13:31 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.stories.tsx
> +    <DashboardLayout>
Добавь header везде

2023-11-27 13:31 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.stories.tsx
> + - menu - описание меню, содержит в себе items - пункты меню
безполезное оприсание

2023-11-27 13:31 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.stories.tsx
> + - header - контент заголовка sidebar
```suggestion
 header может содержать любой контент
```

2023-11-27 13:31 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.stories.tsx
> + - header - контент заголовка sidebar
И отдельный кейс сделай для SidebarButton

2023-11-27 13:31 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.stories.tsx
> +export const Header = () => {
```suggestion
export const CustomHeader = () => {
```

2023-11-27 13:31 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.stories.tsx
> + * DashboardLayout.Sidebar - компонент боковой панели дашборда.
Напиши здесь, что Sidebar автоматически сворачивается на небольших разрешениях.
Состояние сворачивается запоминается в localStorage

2023-11-27 13:32 UTC, AndTem commented
Добавь еще кейс управления  сворачиваем/разворачиваем Sidebar руками из вне

2023-11-27 13:56 UTC, maksimmolofeev commented on packages/components/src/DashboardLayout/DashboardLayout.stories.tsx
> + - Header (DashboardLayout.Header)
добавил

2023-11-27 13:57 UTC, maksimmolofeev commented on packages/components/src/DashboardLayout/DashboardLayout.stories.tsx
> + - Header (DashboardLayout.Header)
добавил

2023-11-27 14:07 UTC, maksimmolofeev commented on packages/components/src/DashboardLayout/Header/Header.stories.tsx
> + * DashboardLayout.Header - данный компонет может включать в себя информацию о продукте(product), переключатель продуктов(productSwitcher), профиль пользователя(profile) и меню организаций(organizati
готово

2023-11-27 14:08 UTC, maksimmolofeev commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.stories.tsx
> + - menu - описание меню, содержит в себе items - пункты меню
убрал

2023-11-27 14:12 UTC, maksimmolofeev commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.stories.tsx
> +export const Header = () => {
исправил

2023-11-27 14:39 UTC, maksimmolofeev commented on packages/components/src/DashboardLayout/Header/Header.stories.tsx
> +    <DashboardLayoutWrapper>
добавил

2023-11-27 14:43 UTC, maksimmolofeev commented on packages/components/src/DashboardLayout/Main/Main.stories.tsx
> +      <DashboardLayout.Main>Main Content</DashboardLayout.Main>
готово

2023-11-27 14:54 UTC, maksimmolofeev commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.stories.tsx
> +    <DashboardLayout>
добавил

2023-11-27 14:58 UTC, maksimmolofeev commented on packages/components/src/DashboardLayout/Main/Main.stories.tsx
> + * DashboardLayout.Main - компонент с основным контентом дашборда, состоит из элементов передаваемых в children.
готово

2023-11-27 15:27 UTC, maksimmolofeev commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.stories.tsx
> + - header - контент заголовка sidebar
готово

2023-11-28 04:51 UTC, maksimmolofeev commented on packages/components/src/DashboardLayout/DashboardLayout.stories.tsx
> +    <DashboardLayout>
готово

2023-12-01 12:50 UTC, AndTem approved these changes

2023-12-01 12:50 UTC, AndTem commented on packages/components/src/DashboardLayout/Header/Header.stories.tsx
> + * DashboardLayout.Header - верхняя часть дашборда
Забавный комментарий. Он просто не нужен

2023-12-08 11:23 UTC, merged