feat(UIKIT-621,ui,EmailField): Добавляет компоненты EmailField и Form…
kaluga-astral/frontend pull request #760
Opened 2023-12-07 14:22 UTC by IlyaKhazan

…EmailField

# Чеклист

- [x] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [x] Реализовать или обновить storybook для компонента
- [x] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-12-07 14:28 UTC, AndTem requested changes

2023-12-07 14:28 UTC, AndTem commented on packages/components/src/EmailField/EmailField.tsx
> +export const EmailField = forwardRef<HTMLDivElement, EmailFieldProps>(
Тебе надо просто взять наш TextField готовый и сделать ему prop type="email"

2023-12-08 07:08 UTC, YrStudenikin commented on packages/components/src/EmailField/EmailField.test.tsx
> +describe('EmailField', () => {
Из тестов нужно оставить только проверку на type="email"

2023-12-08 09:28 UTC, IlyaKhazan commented on packages/components/src/index.ts
> +export * from './EmailField';
> Забыл сделать экспорт для form

Для FormEmailField?

2023-12-08 10:12 UTC, YrStudenikin commented on packages/components/src/index.ts
> +export * from './EmailField';
С недавнего времени нужно делать конкретные экспорты сущностей из пакетов, чтобы не вытягивать наружу лишнее

![image](https://github.com/kaluga-astral/frontend/assets/62848436/110ab253-a973-499f-b4e6-62b867bd466d)

2023-12-08 10:17 UTC, YrStudenikin commented on packages/form/src/index.ts
> +export * from './FormEmailField';
Правило для всех пакетов)

2023-12-08 10:25 UTC, AndTem approved these changes

2023-12-08 10:32 UTC, YrStudenikin approved these changes

2023-12-08 10:39 UTC, merged