feat(UIKIT-792,ui,Dialog): Добавлен storybook
kaluga-astral/frontend pull request #767
Opened 2023-12-14 08:37 UTC by KVPlotnikov

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-12-14 09:39 UTC, AndTem commented on packages/components/src/Dialog/Dialog.stories.tsx
> + * В хедере диалогового окна могут добавляться дополнительные элементы. Они могут добавляться к заголовку или закрепляться по правому краю.
Прердыдущий кейс с subtitile - это и есть custom header

2023-12-14 09:42 UTC, AndTem commented
Переименуй название PR: feat -> doc

2023-12-14 09:44 UTC, AndTem requested changes

2023-12-14 09:44 UTC, AndTem commented on packages/components/src/Dialog/Dialog.stories.tsx
> +export const HeaderWithSubtitle = () => {
Напиши - CustomTitle

2023-12-14 09:44 UTC, AndTem commented on packages/components/src/Dialog/Dialog.stories.tsx
> +export const HeaderWithSubtitle = () => {
Subtitle сейчас как будто реалзован в ките. Прокинь просто в title тэг, например

2023-12-14 10:10 UTC, AndTem approved these changes

2023-12-14 13:50 UTC, YrStudenikin commented
Не хватает кейса с DialogActions

2023-12-14 13:51 UTC, YrStudenikin commented on packages/components/src/Dialog/Dialog.stories.tsx
> +};
Не хватает кейса с DialogActions

2023-12-14 13:58 UTC, KVPlotnikov commented on packages/components/src/Dialog/Dialog.stories.tsx
> +};
Уточни пожалуйста, какого конкретно кейса? Из фигмы Custom footer dialog left где чекбокс ? Сейчас невозможно без костылей разместить контент в Actions по левому краю, так DialogActions оборачивает в грид и выравнивает по правому краю, что не даёт первому из переданных чайлдов  растянуться на всю оставшуюся ширину и выровняться по левому краю

2023-12-14 14:08 UTC, YrStudenikin commented on packages/components/src/Dialog/Dialog.stories.tsx
> +};
Может тогда назвать не custom footer а DialogActions?

2023-12-14 14:15 UTC, KVPlotnikov commented on packages/components/src/Dialog/Dialog.stories.tsx
> +};
Согласен, стоит переименовать, но так как у нас есть компонент DialogActions и он используется в этом файле, будет конфликт имен, думаю стоит назвать типа MoreDialogActions

2023-12-14 14:18 UTC, YrStudenikin commented on packages/components/src/Dialog/Dialog.stories.tsx
> +};
`DialogActions as DialogActionsComponent` как вариант

2023-12-14 14:18 UTC, AndTem commented
@KVPlotnikov надо для всех связанных с Dialog компонентов сделать свои маленькие стори и вложить их в общий раздел. По аналогии с [DashboardLayout](https://main--61baeff6f06230003a88ef8a.chromatic.com/?path=/docs/components-dashboardlayout--docs)

2023-12-19 07:28 UTC, AndTem commented on packages/components/src/Dialog/Dialog.stories.tsx
> + * Когда требуется, чтобы пользователи взаимодействовали с приложением, но без перехода на новую страницу и прерывания рабочего процесса пользователя, нужно использовать Dialog.
Добавь сюда ссылки на связанные компоненты, как [здесь](https://main--61baeff6f06230003a88ef8a.chromatic.com/?path=/docs/components-dashboardlayout--docs)

2023-12-19 07:30 UTC, AndTem commented on packages/components/src/Dialog/Dialog.stories.tsx
> +export const CustomTitle = () => {
Предлагаю сюда еще добавить CustomHeader, который будет ссылаться на другую стори

2023-12-19 07:31 UTC, AndTem commented on packages/components/src/Dialog/Dialog.stories.tsx
> +const meta: Meta<typeof Dialog> = {
Предалагаю в стори Dialog скопировать стори из связанных компонентов с ссылками на них (CustomHeader, DialogActions...).
В стори компонентов при этом оставить example как есть

2023-12-19 07:44 UTC, AndTem approved these changes

2023-12-19 11:17 UTC, YrStudenikin approved these changes

2023-12-19 11:24 UTC, merged