doc(UIKIT-626,ui,SideDialog): Добавлен storybook
kaluga-astral/frontend pull request #772
Opened 2023-12-20 09:54 UTC by KVPlotnikov

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [x] Реализовать или обновить storybook для компонента
- [x] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-12-20 10:10 UTC, Ofigelov commented
Чет в хроматике сторибуки как то бедно выглядят, или может я куда то [не туда смотрю](https://www.chromatic.com/component?appId=61baeff6f06230003a88ef8a&csfId=components-sidedialog-sidedialogcontent&buildNumber=2581&k=6582ba38c77aad10af4a93bc-1200px-interactive-true&h=12&b=-1)?

2023-12-20 10:53 UTC, KVPlotnikov commented
> Чет в хроматике сторибуки как то бедно выглядят, или может я куда то [не туда смотрю](https://www.chromatic.com/component?appId=61baeff6f06230003a88ef8a&csfId=components-sidedialog-sidedialogcontent&buildNumber=2581&k=6582ba38c77aad10af4a93bc-1200px-interactive-true&h=12&b=-1)?

Ты смотрел на SideDialogContent, вот основная стори 
https://www.chromatic.com/component?appId=61baeff6f06230003a88ef8a&csfId=components-sidedialog--example&buildNumber=2581&k=6582ba38c77aad10af4a93b7-1200px-interactive-true&h=22&b=-18

2023-12-28 11:22 UTC, AndTem requested changes

2023-12-28 11:22 UTC, AndTem commented on packages/components/src/SideDialog/SideDialog.stories.tsx
> +import { SideDialogActions as SideDialogActionsComponent } from '../SideDialogActions';
Сделай именно SideDialogActions, чтобы в stories было понятно что за компонент

2023-12-28 11:35 UTC, AndTem approved these changes

2023-12-28 11:35 UTC, merged