feat(UIKIT-1069,ui,Tab): Исправлены стили
kaluga-astral/frontend pull request #774
Opened 2023-12-21 04:34 UTC by wan6sta

# Чеклист

- [x] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [x] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2023-12-21 05:47 UTC, YrStudenikin commented on packages/components/src/Tab/styles.ts
> +export type TabProps = WithoutEmotionSpecific<MuiTabProps>;
типы нужно вынести в файл с компонентом

2023-12-21 05:54 UTC, wan6sta commented on packages/components/src/Tab/styles.ts
> +export type TabProps = WithoutEmotionSpecific<MuiTabProps>;
поправил

2023-12-25 06:58 UTC, YrStudenikin approved these changes

2023-12-28 11:11 UTC, AndTem requested changes

2023-12-28 11:11 UTC, AndTem commented on packages/components/src/Tab/styles.ts
> +  margin-right: 16px;
Отступы через spacing

2023-12-29 08:52 UTC, AndTem commented on packages/components/src/Tab/styles.ts
> +export const StyledTab = styled(Tab)<TabProps>`
```suggestion
export const StyledRoot = styled(Tab)<TabProps>`
```

2024-01-09 06:03 UTC, AndTem approved these changes

2024-01-09 06:06 UTC, merged