refactor(UIKIT-929,components,Description): Изменение storybook
kaluga-astral/frontend pull request #780
Opened 2023-12-25 06:06 UTC by wan6sta

# Чеклист

- [x] Реализовать или обновить storybook для компонента
- [x] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2023-12-25 06:35 UTC, Ofigelov commented on packages/components/src/Description/Description.stories.tsx
> + */
Не хватает описания как общего, так и для пропсов. Вроде же в старом варианте есть тексты, можно их использовать, если для чего не хватает, тоже неплохо бы добавить

2023-12-25 06:37 UTC, AndTem commented on packages/components/src/Description/Description.stories.tsx
> + */
@Ofigelov описание для пропсов генерирутся в API разделе. Конкретизируй, что ты хочешь получить

2023-12-25 06:44 UTC, Ofigelov commented on packages/components/src/Description/Description.stories.tsx
> + */
Мне казалось что имеющееся описание в сторибуке не является лишним, и переделки сторибука нужны просто для конвертации к нужному формату. Вроде было бы удобно видеть какое-то описание сразу при открытии страницы, нежели искать его внизу в api.

2023-12-25 06:46 UTC, AndTem commented on packages/components/src/Description/Description.stories.tsx
> + */
@Ofigelov такие вещи необходимо обсуждать на грумингах, а не в комментариях PR.

2023-12-25 06:55 UTC, Ofigelov approved these changes

2023-12-25 07:02 UTC, AndTem commented
Измени нажвание PR refactor -> doc

2023-12-25 07:03 UTC, AndTem commented
Префикс example убери везде

2023-12-25 07:06 UTC, AndTem requested changes

2023-12-25 07:06 UTC, AndTem commented on packages/components/src/Description/Description.stories.tsx
> +export const ExampleSpaceBetween = () => {
JusctifyContent

2023-12-25 07:06 UTC, AndTem commented on packages/components/src/Description/Description.stories.tsx
> +export const ExampleSpaceBetweenWithLeader = () => {
Просто Leader

2023-12-25 07:06 UTC, AndTem commented on packages/components/src/Description/Description.stories.tsx
> +export const ExampleSpaceBetweenWithLeader = () => {
Напиши коммент в виде jsdoc, что leadr добавляет dashed строку.
[Пример](https://github.com/kaluga-astral/frontend/blob/main/packages/components/src/Grid/Grid.stories.tsx#L55)

2023-12-25 07:07 UTC, AndTem commented on packages/components/src/Description/Description.stories.tsx
> +export const ExampleSpaceBetweenWithLeader = () => {
И перенеси эту story выше, сражу под example

2023-12-26 11:22 UTC, AndTem requested changes

2023-12-26 11:22 UTC, AndTem commented on packages/components/src/Description/Description.stories.tsx
> +export const Interaction: Story = {
Сломанная story

2023-12-26 12:04 UTC, AndTem commented on packages/components/src/Description/Description.stories.tsx
> +export const Example = () => {
Сделай для всех story ширину побольше, чтобы было лучше видно как работают props (только чтобы на мобиле тоже норм выглядело)

2023-12-28 11:10 UTC, merged