bug(UIKIT-871, ui, Button): Исправлена типизация, когда тип компонент…
kaluga-astral/frontend pull request #797
Opened 2024-01-16 09:09 UTC by gadji9

…а Link из react-route

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-01-17 13:51 UTC, AndTem commented on packages/components/src/types.ts
> +export type FixedForwardRef = <T, P = {}>(
Не продублировал [этот](https://github.com/kaluga-astral/frontend/blob/main/packages/components/src/forwardRefWithGeneric/forwardRefWithGeneric.ts) код?

2024-01-18 06:01 UTC, gadji9 commented on packages/components/src/types.ts
> +export type FixedForwardRef = <T, P = {}>(
Продублировал. Исправил

2024-01-22 12:27 UTC, AndTem requested changes

2024-01-22 12:27 UTC, AndTem commented on packages/components/src/Button/Button.tsx
> +type ForwardedRefButton = <TComponent extends ElementType>(
Это лишний тип. Тебе достаточно просто сделать как здесь: https://github.com/kaluga-astral/frontend/blob/main/packages/components/src/Select/Select.tsx#L42

2024-01-22 12:27 UTC, AndTem commented on packages/components/src/Button/Button.tsx
> +const UnwrappedButton: ForwardedRefButton = (props, ref) => {
Сам компонент должен быть generic

2024-01-25 07:56 UTC, AndTem commented on packages/components/src/Button/Button.tsx
> +    ComponentPropsWithRef<
Для чего этот тип?

2024-01-25 07:57 UTC, AndTem commented on packages/components/src/Button/Button.tsx
> +  ref: ForwardedRef<HTMLButtonElement>,
```suggestion
  ref: ForwardedRef<TComponent>,
```

2024-01-25 12:25 UTC, gadji9 commented on packages/components/src/Button/Button.tsx
> +  ref: ForwardedRef<HTMLButtonElement>,
ElementType is not assignable to type HTMLButtonElement.
Мне кажется нет ничего плохого если захардкодить HTMLButtonElement. У Mui тоже стоит HTMLButtonElement для Button

2024-01-25 12:38 UTC, gadji9 commented on packages/components/src/Button/Button.tsx
> +    ElementType extends TComponent ? 'button' : TComponent
Не совсем понял.
Так?  & ComponentPropsWithRef<'button'>;

Если так то мы не вытащим типы из передаваемого в проп component комопнента

2024-01-25 12:39 UTC, gadji9 commented on packages/components/src/Button/Button.tsx
> +  ref: ForwardedRef<HTMLButtonElement>,
А понял

2024-01-25 12:47 UTC, AndTem commented on packages/components/src/Button/Button.tsx
> +export type ButtonProps<TComponent extends ElementType = ElementType> = Omit<
```suggestion
export type ButtonProps<TComponent extends ElementType ='button'> = Omit<
```

2024-01-25 13:47 UTC, gadji9 commented on packages/components/src/Button/Button.tsx
> +export type ButtonProps<TComponent extends ElementType = ElementType> = Omit<
Есть проблема. Если установить button по дефолту. То если не передавать дженерик в ButtonProps то проп component может принимать только строку 'button', т.к TComponent = 'button'. И поэтому в проп component нельзя передавать реакт компоненты. Мне больше нравится решение которое есть сейчас, оно удобнее и не нужно парится из-за типов

2024-01-25 13:53 UTC, AndTem commented on packages/components/src/Button/Button.tsx
> +export type ButtonProps<TComponent extends ElementType = ElementType> = Omit<
А просто продублировать дефолтное значение в дженерике компонента не прокатит?

2024-01-25 14:00 UTC, AndTem approved these changes

2024-01-26 10:06 UTC, StanislavDa approved these changes

2024-01-26 11:38 UTC, mfrolov89 approved these changes

2024-01-26 13:08 UTC, merged