feat(UIKIT-1183,ui,BottomDrawer): Реализован компонент BottomDrawer
kaluga-astral/frontend pull request #804
Opened 2024-01-25 13:15 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-01-25 13:50 UTC, AndTem commented on packages/components/src/BottomDrawer/BottomDrawer.tsx
> +export type BottomDrawerProps = {
А такой API сметчится с dialog?
Там как минимум title - ReactNode

2024-01-25 14:00 UTC, mfrolov89 commented on packages/components/src/BottomDrawer/BottomDrawer.tsx
> +export type BottomDrawerProps = {
Не проверял пока совместимость, когда делал думал больше о каком-нибудт поповере или меню, где нужен простой текстовый заголовок. Допилю тогда и проверю

2024-01-25 14:01 UTC, AndTem commented on packages/components/src/BottomDrawer/styles.ts
> +  .MuiPaper-root {
С className надо работать [так](https://github.com/kaluga-astral/frontend/blob/main/packages/components/src/theme/components/MuiDialog.ts#L10)

2024-01-25 14:04 UTC, AndTem commented on packages/components/src/BottomDrawer/styles.ts
> +    border-radius: 8px 8px 0 0;
Нужно делать через theme.shape

2024-01-25 14:08 UTC, AndTem commented on packages/components/src/BottomDrawer/ButtomDrawer.test.tsx
> +  it('Prop:title: значение, переданное в drawerTitle, отображается', () => {
Прочитай про [формат тетс-кейсов](https://industrious-search-cdf.notion.site/dac1e9ff807f4fa1a48150a0d609d530).
У меня есть задача в квартале на рефакторинг всех тест-кейсов в репе, поэтому смотреть на текущие не стоит.

Разве что на этот компонент: https://github.com/kaluga-astral/frontend/blob/main/packages/components/src/Accordion/Accordion.test.tsx

2024-01-26 08:20 UTC, mfrolov89 commented on packages/components/src/BottomDrawer/styles.ts
> +  .MuiPaper-root {
Если делать через тему, то необходимо будет завязываться на класс с положением дровера, а не на рут + стилизовать только для мобилки. Не слишком ли это громоздко будет? Хотел как-то уточнить как раз этот момент, потому что не всегда очевидно может быть что на уровне темы, а что на уровне компонента стилизовать, а в доках инфу не встречал

2024-01-26 08:48 UTC, mfrolov89 commented on packages/components/src/BottomDrawer/styles.ts
> +  height: ${({ drawerHeaderHeight }) => `${drawerHeaderHeight}px`};
Были сомнения на его счет, но оставил его, так как он есть в SwipeableDrawer (который для мобилок как мне кажется и создавался). Думал что у вас были причины в его добавлении

2024-01-26 10:11 UTC, StanislavDa approved these changes

2024-01-26 10:11 UTC, StanislavDa commented on packages/components/src/BottomDrawer/BottomDrawer.stories.tsx
> +import Button from '@mui/material/Button';
Мб я что-то пропустил, почему импорт идет из mui вместо компонетов кита?)

2024-01-26 10:17 UTC, AndTem commented on packages/components/src/BottomDrawer/styles.ts
> +  .MuiPaper-root {
Не понял при чем тут тема. Classname как константы надо забирать из mui

2024-01-26 10:18 UTC, AndTem commented on packages/components/src/BottomDrawer/BottomDrawer.stories.tsx
> +import { styled } from '@mui/material/styles';
Из кит надо забирать styled

2024-01-26 10:20 UTC, AndTem commented
Ветку неправильно назвал. Читай [доку](https://github.com/kaluga-astral/docs/blob/main/GIT.md#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B)

2024-01-26 10:22 UTC, AndTem commented on packages/components/src/BottomDrawer/styles.ts
> +  height: ${({ drawerHeaderHeight }) => `${drawerHeaderHeight}px`};
Я явных причин не вижу сейчас

2024-01-26 12:19 UTC, mfrolov89 commented on packages/components/src/BottomDrawer/styles.ts
> +  .MuiPaper-root {
Понял. Обратил внимание на местоположение файла по ссылке

2024-01-26 12:30 UTC, AndTem commented on packages/components/src/BottomDrawer/BottomDrawer.stories.tsx
> +import Button from '@mui/material/Button';
@mfrolov89 надо ориентироваться на свежие стори (ты просто попал на древнюю)

2024-01-30 12:57 UTC, mfrolov89 commented on packages/components/src/BottomDrawer/BottomDrawer.tsx
> +export type BottomDrawerProps = {
title поправил, так же удалил isMountedOnHide, который не поддерживается другими компонентами и имеет аналог в виде keepMounted, который одинаков для всех компонентов

2024-01-30 13:34 UTC, AndTem requested changes

2024-01-30 13:34 UTC, AndTem commented on packages/components/src/BottomDrawer/BottomDrawer.tsx
> +  title?: JSX.Element | JSX.Element[] | string;
```suggestion
  title?: ReactNode;
```

2024-01-30 13:34 UTC, AndTem commented on packages/components/src/BottomDrawer/BottomDrawer.tsx
> +  title?: JSX.Element | JSX.Element[] | string;
Так не подойдет?

2024-01-30 13:34 UTC, AndTem commented on packages/components/src/BottomDrawer/ButtomDrawer.test.tsx
> +    vi.clearAllMocks();
Для spy clearAllMocks вызывать не нужно

2024-01-30 13:34 UTC, AndTem commented on packages/components/src/BottomDrawer/ButtomDrawer.test.tsx
> +    const onCloseMockFn = vi.fn();
```suggestion
    const onCloseSpy = vi.fn();
```

2024-01-30 13:34 UTC, AndTem commented on packages/components/src/BottomDrawer/ButtomDrawer.test.tsx
> +    const onCloseMockFn = vi.fn();
https://industrious-search-cdf.notion.site/Astral-Frontend-Unit-Testing-Style-Guide-bb6ec75b67a449f68bc8eebd36d6fec8#7c2081d070a744a7aa62a914454de2f3

2024-01-30 13:34 UTC, AndTem commented on packages/components/src/BottomDrawer/BottomDrawer.stories.tsx
> +          Наполнение с переполнением
Считаю, что это должна быть отдельная story

2024-01-30 13:34 UTC, AndTem commented on packages/components/src/BottomDrawer/BottomDrawer.stories.tsx
> +          drawerHeaderHeight={56}
Дефолтное значение же вроде и так 56

2024-01-30 13:38 UTC, mfrolov89 commented on packages/components/src/BottomDrawer/BottomDrawer.tsx
> +  title?: JSX.Element | JSX.Element[] | string;
Взял описание типа из Dialog

2024-01-31 10:05 UTC, AndTem approved these changes

2024-01-31 10:22 UTC, merged