feat(UIKIT-265,ui,DataGridInfinite): Реализован DataGridInfinite
kaluga-astral/frontend pull request #808
Opened 2024-01-31 07:40 UTC by agro196

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-02-01 08:28 UTC, mfrolov89 requested changes

2024-02-01 08:28 UTC, mfrolov89 commented on packages/components/src/DataGridInfinite/DataGridInfinite.test.tsx
> +    expect(currentSort).toEqual({ fieldId: 'name', sort: 'desc' });
достаточно много проверок в рамках одного теста, лучше разделить, можно сгруппировать через вложенный describe

2024-02-01 08:28 UTC, mfrolov89 commented on packages/components/src/DataGridInfinite/styles.ts
> +import { DataGridContainer } from '../DataGrid/styles';
возможно стоит вынести DataGridContainer, потому что импортировать из стилей другого компонента это очень не очевидно
@AndTem что думаешь?

2024-02-01 08:28 UTC, mfrolov89 commented on packages/components/src/Table/TableBody/TableBody.tsx
> +export const TableBody = forwardRef(function TableBody(
стрелочная функция

2024-02-01 08:28 UTC, mfrolov89 commented on packages/components/src/DataGridInfinite/DataGridInfiniteScrollButton/DataGridInfiniteScrollButton.tsx
> +  const handleClick = debounce(
зачем нужен debounce для клика?

2024-02-01 08:28 UTC, mfrolov89 commented on packages/components/src/DataGridInfinite/DataGridInfiniteScrollButton/DataGridInfiniteScrollButton.tsx
> +export interface StickyButtonProps extends ButtonProps {
export type StickyButtonProps ... + Intersection Types

2024-02-01 08:28 UTC, mfrolov89 commented on packages/components/src/DataGrid/DataGridHead/DataGridHead.tsx
> +import { DataGridInfiniteHead } from '../../DataGridInfinite/styles';
Получается циклическая зависимость: ты забираешь компонент из стилей DataGridInfinite, а потом используешь эту шапку в DataGridInfinite

2024-02-01 08:31 UTC, AndTem commented on packages/components/src/DataGridInfinite/styles.ts
> +import { DataGridContainer } from '../DataGrid/styles';
Думаю, что из DataGrid надо через индексный файл реэкспортнуть то, что необходимо в DataGridInfinite.
А в корнем index пакета сделай экспорт конкретных компонентов, типов и тп (чтобы лишнее из пакета не вышло)

2024-02-01 08:34 UTC, AndTem commented on packages/components/src/DataGridInfinite/DataGridInfinite.test.tsx
> +    expect(currentSort).toEqual({ fieldId: 'name', sort: 'desc' });
Подозреваю, Андрей просто скопировал тесты из DataGrid. Задача по рефакторингу тестов может быть объемной.
@agro196 примени полученные от Максима комментарии к новым тестам, а остальное я потом зарефакторю ()https://track.astral.ru/soft/browse/UIKIT-1082

2024-02-01 08:37 UTC, AndTem requested changes

2024-02-01 08:37 UTC, AndTem commented on packages/components/src/DataGridInfinite/DataGridInfiniteScrollButton/styles.ts
> +    vertical ? vertical + ':' + theme.spacing(4) + ';' : ''}
Читай [style guide](https://track.astral.ru/soft/wiki/pages/viewpage.action?pageId=3557425260#id-%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5%D1%82%D0%B8%D0%BF%D0%BE%D0%B2-%D0%94%D0%BB%D1%8F%D1%81%D0%BA%D0%BB%D0%B5%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%BD%D0%B5%D0%BE%D0%B1%D1%85%D0%BE%D0%B4%D0%B8%D0%BC%D0%BE%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%BE%D0%B2%D1%8B%D0%B9%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD)

2024-02-01 08:37 UTC, AndTem commented on packages/components/src/DataGridInfinite/DataGridInfiniteScrollButton/DataGridInfiniteScrollButton.tsx
> +  const handleClick = debounce(
+ этот debounce работать не будет. При каждом перерендере будет заново инициализироваться

2024-02-01 08:40 UTC, AndTem requested changes

2024-02-01 08:40 UTC, AndTem commented on packages/components/src/DataGridInfinite/faker.ts
> +const makeRandomDate = () => {
fakerjs заюзать может просто?
https://github.com/kaluga-astral/vite-boilerplate/blob/main/data/sources/bookNetworkSources/faker.ts

2024-02-01 08:40 UTC, AndTem commented on packages/components/src/DataGridInfinite/faker.ts
> +      id: String(i + 1),
faker не подойдет?
https://github.com/kaluga-astral/vite-boilerplate/blob/main/data/sources/bookNetworkSources/faker.ts

2024-02-27 09:12 UTC, mfrolov89 requested changes

2024-02-27 09:12 UTC, mfrolov89 commented on packages/components/src/DataGridInfinite/DataGridInfinite.tsx
> +            <DataGridHead<Data, SortField>
не вижу пока сценария использования, чтобы DataGridHead c флагом isInfinite использовался отдельно. Думаю что можно обойтись локальной стилизайцией DataGridHead в рамках DataGridInfinity

2024-02-27 11:31 UTC, agro196 commented on packages/components/src/DataGridInfinite/DataGridInfiniteScrollButton/styles.ts
> +  ${({ theme, vertical, horizontal }) =>
Оставил проверку на vertical так как в зависимости от расположения кнопки(снизу/сверху) требуется разные отступы из-за шапки

2024-02-27 11:46 UTC, agro196 commented on packages/components/src/DataGridInfinite/DataGridInfinite.tsx
> +            <DataGridHead<Data, SortField>
Дело в том что просто променять стили недостаточно, в случае когда у нас DataGrid то мы возвращаем в качестве рутового компонента TableHead - это тег thead, в случае когда у нас DataGridInfinite то мы используем проп isInfinite и возвращаем TableRow так как thead нам уже добавит virtuoso и thead не может быть вложен в thead

2024-02-27 11:46 UTC, agro196 commented on packages/components/src/DataGridInfinite/DataGridInfinite.tsx
> +            <DataGridHead<Data, SortField>
<img width="404" alt="image" src="https://github.com/kaluga-astral/frontend/assets/65020968/45903c62-2e99-40f6-82c1-3683b38e66bc">

2024-02-28 08:12 UTC, mfrolov89 requested changes

2024-02-28 08:12 UTC, mfrolov89 commented on packages/components/src/index.ts
> +  DataGridColumns,
стоит добавить type для типов

2024-02-28 08:12 UTC, mfrolov89 commented on packages/components/src/DataGridInfinite/DataGridInfinite.tsx
> +          computeItemKey={(index) => `item-${index}`}
думал он возвращает option и можно по keyId получить уникальный ключ, а в такой вариации не вижу профита, думаю что можно удалить

2024-02-28 08:18 UTC, mfrolov89 commented on packages/components/src/DataGridInfinite/DataGridInfinite.test.tsx
> +  it('Props:columns: отображаются названия колонок', () => {
Названия колонок отображаются

2024-02-28 08:19 UTC, mfrolov89 commented on packages/components/src/DataGridInfinite/DataGridInfinite.test.tsx
> +  it('Элементы рендерятся в таблице', async () => {
Элементы отображаются в таблице

2024-02-28 08:20 UTC, mfrolov89 commented on packages/components/src/DataGridInfinite/DataGridInfinite.test.tsx
> +  it('Props:options=[]: отображается placeholder', async () => {
Placeholder отображается при отсутствии данных

2024-02-28 08:35 UTC, AndTem commented on packages/components/src/DataGridInfinite/DataGridInfinite.stories.tsx
> + * Бесконечный скролл. Данные отображаются вертикальным списком, количество записей определяется командой разработки в рамках конкретной таблицы, следующие записи из БД подтягиваются в таблицу при ис
```suggestion
 * Таблица с бесконечным скроллом
```

2024-02-28 08:36 UTC, AndTem commented on packages/components/src/DataGridInfinite/DataGridInfinite.stories.tsx
> + *
Добавь ссылку на DataGrid и напиши, что DataGridInfinite умеет тоже самое что и DataGrid

2024-02-28 13:23 UTC, mfrolov89 commented on packages/components/src/DataGridInfinite/DataGridInfinite.test.tsx
> +  it('По клику на head cell вызывается onSort', async () => {
```suggestion
  it('OnSort вызывается при нажатии на head cell ', async () => {
```

2024-02-28 13:26 UTC, agro196 commented on packages/components/src/DataGridInfinite/DataGridInfinite.test.tsx
> +  it('По клику на head cell вызывается onSort', async () => {
Поправил

2024-02-28 13:27 UTC, mfrolov89 commented on packages/components/src/DataGridInfinite/DataGridInfinite.test.tsx
> +  it('Есть доступ к данным из row по клику на строку', async () => {
```suggestion
  it('Данные, содержащиеся в row, передаются в onRowClick при нажатии на строку', async () => {
```

2024-02-28 13:31 UTC, agro196 commented on packages/components/src/DataGridInfinite/DataGridInfinite.test.tsx
> +  it('Есть доступ к данным из row по клику на строку', async () => {
исправил

2024-02-28 13:56 UTC, AndTem commented on example/src/shared/ui/theme/theme.ts
> -export const theme = createTheme({ brand: Brand.SIGN, fontsUrls });
Brand.DEFAULT

2024-02-28 13:56 UTC, AndTem approved these changes

2024-02-29 06:25 UTC, mfrolov89 approved these changes

2024-03-05 12:00 UTC, merged