feat(UIKIT-1177,ui,PageLayout): Реализовать адаптив для компонента PageLayout
kaluga-astral/frontend pull request #812
Opened 2024-02-01 11:33 UTC by mfrolov89

…geLayout

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-02-01 12:12 UTC, AndTem commented
Выравнивание кнопок на мобиле кривое, если кнопку с троеточием убрать:
<img width="371" alt="Снимок экрана 2024-02-01 в 15 10 28" src="https://github.com/kaluga-astral/frontend/assets/23665108/13b38680-88de-4fc7-9feb-ac0f9511fea1">

2024-02-01 12:14 UTC, AndTem requested changes

2024-02-01 12:14 UTC, AndTem commented on packages/components/src/PageHeader/styles.ts
> +    padding: ${({ theme }) => theme.spacing(4)};-
```suggestion
    padding: ${({ theme }) => theme.spacing(4)};
```

2024-02-01 12:14 UTC, AndTem commented on packages/components/src/PageHeader/PageHeader.tsx
> +      <MobileHeaderWrapper>
Он ведь и на десктопе рендерится. Префикс Mobile лишний

2024-02-01 12:30 UTC, AndTem requested changes

2024-02-01 12:30 UTC, AndTem commented on packages/components/src/PageHeader/styles.ts
> +    position: fixed;
Должно быть sticky, иначе контент, который внизу страницы будет всегда закрыт футером

2024-02-01 12:47 UTC, mfrolov89 commented on packages/components/src/PageHeader/PageHeader.tsx
> +      <MobileHeaderWrapper>
Ага, рендерится, но по факту за счет display: contents он становится "прозрачным" и не учитывается, поэтому подумал что проще сразу подсветить в названии что он начинает играть роль только для мобилок + wrapper'ы тут уже есть становится сложно придумать толковое название, чтобы глядя на код понять что это такое) Но могу убрать префикс мобилки если ты все таки за такой вариант)

2024-02-01 12:48 UTC, AndTem commented on packages/components/src/PageHeader/PageHeader.tsx
> +      <MobileHeaderWrapper>
Ok, оставляй

2024-02-01 12:49 UTC, mfrolov89 commented on packages/components/src/PageHeader/styles.ts
> +    position: fixed;
Попробую, но как вариант можно нижний отступ для PageContentWrapper указать

2024-02-01 12:57 UTC, mfrolov89 commented on packages/components/src/PageHeader/styles.ts
> +    box-shadow: 0 -1px 10px 0 rgb(7 45 87 / 10%);
в теме такой не нашел, новую не стал на тот момент добавлять, так как неясно куда ее прикрутить.
В elevation числовые ключи, и тень у всех направлена вниз, тут же наоборот, т.е нельзя пойти по пути увеличения значения ключа, например задав elevation[600]. При таком значении по логике мы бы ожидали что просто разброс тени будет еще больше, а не сменится ее направленность. Если есть мысли куда прикрутить и как назвать, то было бы класно

2024-02-06 13:45 UTC, AndTem approved these changes

2024-02-08 07:10 UTC, aesarantsev approved these changes

2024-02-08 07:11 UTC, merged