feat(UIKIT-1189,ui,NotificationList): Добавить footerContent в NotificationList
kaluga-astral/frontend pull request #814
Opened 2024-02-05 05:53 UTC by max-cepelev

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-02-05 07:34 UTC, mfrolov89 requested changes

2024-02-05 07:34 UTC, mfrolov89 commented on packages/components/src/NotificationList/NotificationList.tsx
> +        <NotificationListFooter isVisible={isFooterVisible && !isEmptyData}>
Почему скрытие элемента реализовано через css? Кажется правильнее использовать услованый рендер и не добавлять ненужные элементы в dom

2024-02-05 07:34 UTC, mfrolov89 commented on packages/components/src/NotificationList/NotificationList.tsx
> +  isFooterVisible?: boolean;
А почему используется подход с доп.флагом? Можно завязываться на значение footerContent, апи компонента будет проще, при использовании этого функционала нужно будет прокидывать меньше пропсов, что так же является плюсом. Мне трудно представить кейс когда в footerContent что-то прикинут и при этом не захотят это вывоводить. Возможно это вопрос к @AndTem

2024-02-05 07:34 UTC, mfrolov89 commented on packages/components/src/NotificationList/NotificationList.stories.tsx
> +          isFooterVisible={unreadNotifications.length > 0}
Описал комменты по этому флагу в компоненту, и вот тут как раз странный кейс на мой взгляд.
Если не рассматривать конкретно это условие, а брать в целом, то у нас нет единой точки для управления состоянием: логика может быть указана как в этом флаге + она зашита уже в сам компонент, что противоречит на мой взгляд наличию этого пропса. Разработичик не прокинул этот пропс, но футер скрыт, почему футер не отрендерился он не поймет, пока не посмотрит во внутреннее устройство компонента.

Если рассматривать конкретно это условие, то кажется что оно покрывается внутренней логикой компонента и тут лишнее

2024-02-05 08:56 UTC, max-cepelev commented on packages/components/src/NotificationList/NotificationList.tsx
> +        <NotificationListFooter isVisible={isFooterVisible && !isEmptyData}>
Изменю на условный рендеринг, хотя в этом случае особой оптимизации не получим.

2024-02-05 09:06 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.tsx
> +  isFooterVisible?: boolean;
В данном случае, согласен с @mfrolov89. Флаг не нужен

2024-02-05 09:09 UTC, AndTem requested changes

2024-02-05 09:09 UTC, AndTem commented on packages/components/src/NotificationList/styles.ts
> +export const NotificationListFooter = styled('div', {
```suggestion
export const NotificationListFooter = styled('footer', {
```

2024-02-05 09:11 UTC, mfrolov89 commented on packages/components/src/NotificationList/NotificationList.tsx
> +        <NotificationListFooter isVisible={isFooterVisible && !isEmptyData}>
Помимо оптимизации тут момент про еще то, что так проще, ненужно типизировать в стилях компонент, писать условия

2024-02-05 12:31 UTC, AndTem requested changes

2024-02-05 12:31 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.tsx
> +  const isTabsVisible = Boolean(unreadNotifications);
Не обязательно создавать для этого отдельную константу, но если считаешь, что так нагляднее или условие может расшириться, то ок

2024-02-05 12:31 UTC, AndTem commented on packages/components/src/NotificationList/NotificationList.test.tsx
> +  it('NotificationListFooter виден только при наличии footerContent', () => {
```suggestion
  it('Footer виден только при наличии footerContent', () => {
```

2024-02-05 17:42 UTC, max-cepelev commented on packages/components/src/NotificationList/NotificationList.tsx
> +  const isTabsVisible = Boolean(unreadNotifications);
isTabsVisible оставил, т.к. условие может дополняться в будущем

2024-02-06 04:21 UTC, AndTem approved these changes

2024-02-06 07:00 UTC, max-cepelev commented on packages/components/src/NotificationList/NotificationList.stories.tsx
> +            unreadNotifications.length && (
Тут немного по другому, isEmptyData это когда совсем нет сообщений, а тут кейс такой, чтобы не отображать кнопку Отметить все как прочитанные при отсутствии непрочитанных сообщений

2024-02-06 07:16 UTC, mfrolov89 approved these changes

2024-02-06 07:17 UTC, merged