feat(UIKIT-1122,ui,DashboardLayout): Реализовать адаптив для компонента DashboardLayout
kaluga-astral/frontend pull request #817
Opened 2024-02-07 13:42 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-02-07 13:56 UTC, AndTem commented
Замечания по UI:

- У лого размер текста не соответствует макетам
- У бергер-кнопки слева отступ, который виден при клике. Надо растянуть кнопку, чтобы не было miss click:
<img width="123" alt="Снимок экрана 2024-02-07 в 16 53 37" src="https://github.com/kaluga-astral/frontend/assets/23665108/3ea9ac7e-7539-46c4-93b1-f62de78db929">

2024-02-07 14:05 UTC, AndTem requested changes

2024-02-07 14:05 UTC, AndTem commented on packages/components/src/DashboardLayout/SidebarToggler/SidebarToggleButton/SidebarToggleButton.tsx
>  import { MenuOffOutlineMd, MenuOnOutlineMd } from '@astral/icons';
На макете иконка для мобилы другая (просто крестик)

2024-02-07 14:05 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/styles.ts
> +    min-width: ${({ collapsedIn }) => (collapsedIn ? '100vw' : '0px')};
Анимация лагает по понятным причинам (освежи знания про критический путь рендера и relayout).
Надо делать через transform (выезд слева) и блокировать sidebar через inert

2024-02-07 14:07 UTC, AndTem commented on packages/components/src/DashboardLayout/DashboardLayout.stories.tsx
>                return <Logo />;
Добавь в example PageLayout, а то смотриться не очень понятно

2024-02-07 14:10 UTC, mfrolov89 commented on packages/components/src/hooks/index.ts
> +export * from './useViewportType';
Должно эспортироваться. Решил добавить сюда, так как почти наверняка придется использовать в проектах. Могу пока убрать и добавим реэкспорт при необходимости

2024-02-07 14:11 UTC, mfrolov89 commented on packages/components/src/DashboardLayout/SidebarToggler/SidebarToggleButton/SidebarToggleButton.tsx
>  import { MenuOffOutlineMd, MenuOnOutlineMd } from '@astral/icons';
Да, отписал на макете коммент, попробую на стороне дизайне оставить десктопную

2024-02-07 14:23 UTC, mfrolov89 commented
> Замечания по UI:
> 
> * У лого размер текста не соответствует макетам
> * У бергер-кнопки слева отступ, который виден при клике. Надо растянуть кнопку, чтобы не было miss click:
> 
> <img alt="Снимок экрана 2024-02-07 в 16 53 37" width="123" src="https://private-user-images.githubusercontent.com/23665108/303003522-3ea9ac7e-7539-46c4-93b1-f62de78db929.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMTU4MjYsIm5iZiI6MTcwNzMxNTUyNiwicGF0aCI6Ii8yMzY2NTEwOC8zMDMwMDM1MjItM2VhOWFjN2UtNzUzOS00NmM0LTkzYjEtZjYyZGU3OGRiOTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE0MTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZjJhMjljY2JmNjJlN2QwYmFhNzQ1YWYxNTU1ZWYxODNlNDZkYWJkOTVmMWNkOGM4YTdlNTBlMjljM2NiNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f8TN-SRkIw6hlrKUzV-s8N-oA79QVMJHyp6qiYmSE-4">

1. Лого, это компонент Product, поэтому его не трогал.
2. По бургеру отступ делал как на макете, при нажатии визуально он становится виден, согласен, не знаю насколько это плохо, может у дизайнеров узнать мнение (например Владу написать)? По случайное нажатие немного не понял, как оно тут может произойти?

2024-02-08 12:32 UTC, AndTem commented on packages/components/src/DashboardSidebarProvider/DashboardSidebarProvider.tsx
> + * @param {string} localStorageKey название ключа в localStorage
Это лишнее, В ts инфа уже указана

2024-02-08 12:34 UTC, AndTem commented on packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> +        {...{ inert: isMobile && !collapsedIn ? '' : undefined }}
```suggestion
        inert={isMobile && !collapsedIn ? '' : undefined}
```

2024-02-08 12:35 UTC, AndTem commented on packages/components/src/DashboardSidebarProvider/DashboardSidebarProvider.tsx
> +  handleTogglerChange: () => void;
up

2024-02-08 12:35 UTC, mfrolov89 commented on packages/components/src/DashboardSidebarProvider/DashboardSidebarProvider.tsx
> + * @param {string} localStorageKey название ключа в localStorage
Думаешь нужно удалить? Такое описание по всему пакету используется, да и тут речь не только про тип, но и про человеческое описание что за параметр

2024-02-08 12:37 UTC, AndTem commented on packages/components/src/DashboardSidebarProvider/DashboardSidebarProvider.tsx
> + * @param {string} localStorageKey название ключа в localStorage
Описание пропсов должно находится в типе Props

2024-02-08 13:30 UTC, AndTem commented on packages/components/src/DashboardSidebarProvider/DashboardSidebarProvider.tsx
> +    if (matches) {
Эта ветка на мобиле тоже не должна работать.
Можно сделать два хука: useMobileBlaBla и useDescktopBlaBla.
А в компоненте по if выбирать поведение

2024-02-08 13:30 UTC, AndTem commented on packages/components/src/DashboardSidebarProvider/DashboardSidebarProvider.tsx
> +    if (matches) {
Эо позволит от if большого количества отказаться

2024-02-08 13:31 UTC, AndTem commented
Отображается footer при открытом sidebar:
![photo_2024-02-08 16 31 14](https://github.com/kaluga-astral/frontend/assets/23665108/709eeed3-708e-4d65-a65c-bcc326e386b6)

2024-02-09 08:52 UTC, AndTem requested changes

2024-02-09 08:52 UTC, AndTem commented on packages/components/src/DashboardSidebarProvider/hooks.ts
Файл не соответсвует style guide: https://track.astral.ru/soft/wiki/display/FG/React#React-%D0%95%D1%81%D0%BB%D0%B8%D0%B2%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B5%D0%B5%D1%81%D1%82%D1%8Chooks,%D0%BD%D0%B5%D0%BE%D0%B1%D1%85%D0%BE%D0%B4%D0%B8%D0%BC%D0%BE%D0%B2%D1%8B%D0%BD%D0%B5%D1%81%D1%82%D0%B8%D0%B8%D1%85%D0%B2%D0%B4%D0%B8%D1%80%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D1%8Ehooks

2024-02-09 08:52 UTC, AndTem commented on packages/components/src/DashboardSidebarProvider/DashboardSidebarProvider.tsx
> +  const useSidebar = isMobile ? useMobileSidebar : useDesktopSidebar;
Из-за этого сейчас падает компонент при изменении разрешения...
Либо что-то другое придумать необходимо, либо вернуть как было, но просто в хук вынести логику

2024-02-09 09:27 UTC, AndTem commented on packages/components/src/DashboardSidebarProvider/hooks/useSidebar/useSidebar.ts
> +type UseDesktopHook = (localStorageKey: string) => ReturnedSidebarHook;
```suggestion
type UseSidebarHook = (localStorageKey: string) => ReturnedSidebarHook;
```

2024-02-09 09:29 UTC, AndTem commented
Тесты упали

2024-02-09 10:42 UTC, AndTem approved these changes

2024-02-09 10:51 UTC, merged