feat(UIKIT-972): В palette добавлены цвета для link
kaluga-astral/frontend pull request #820
Opened 2024-02-09 11:33 UTC by nikita11044

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-02-12 05:56 UTC, mfrolov89 approved these changes

2024-02-12 14:40 UTC, mfrolov89 requested changes

2024-02-12 14:40 UTC, mfrolov89 commented on packages/components/src/theme/palette/componentsColors/linkColors/index.ts
> +export const linkColors = {
нужно вынести в отдельный файл  linkColors, в индексном должен быть только реэкспорт

2024-02-12 14:40 UTC, mfrolov89 commented on packages/components/src/theme/palette/componentsColors/index.ts
> +export const componentsColors = {
в отдельный файл componentsColors, здесь только реэкспорт

2024-02-19 09:22 UTC, mfrolov89 commented on packages/components/src/theme/palette/componentsColors/componentsColors.ts
> +export type ComponentsColors = typeof componentsColors;
Нужно явно описать типы, в том чилсе и для linkColors. Типизация тут должна выступать как ограничитель, чтобы нельзя было добавить что-то лишнее в тему

2024-02-20 07:30 UTC, mfrolov89 approved these changes

2024-02-20 07:34 UTC, Ofigelov approved these changes

2024-02-20 07:45 UTC, merged