bug(UIKIT-1226,ui,Autocomplete): Решение ошибки с потерей фокуса
kaluga-astral/frontend pull request #822
Opened 2024-02-09 12:28 UTC by cryzer12

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-02-12 06:57 UTC, mfrolov89 approved these changes

2024-02-13 12:17 UTC, StanislavDa approved these changes

2024-02-19 09:06 UTC, mfrolov89 requested changes
Стоит добавить тест на этот кейс

2024-03-05 07:14 UTC, mfrolov89 approved these changes

2024-03-05 07:22 UTC, merged