feat(UIKIT-763,ui,DataGrid): Не отображать кнопки сортировки, если нет данных или одна запись
kaluga-astral/frontend pull request #824
Opened 2024-02-10 10:09 UTC by MaksFett

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-02-12 07:26 UTC, mfrolov89 requested changes
1. Необходимо поправить название, нужно сократить, не прошла проверка
2. Упали тесты. Нужно покрыть данный кейс тестами и поправить упавшие тесты

2024-02-12 07:26 UTC, mfrolov89 commented on packages/components/src/DataGrid/DataGrid.tsx
> +  }, [rows]);
нужно добавить columns

2024-02-12 07:26 UTC, mfrolov89 commented on packages/components/src/DataGrid/DataGrid.tsx
> +      return columns.map((column) => {column.sortable = false; return column})
форматирование не по стандарту, должен был отработать линтер

2024-02-12 07:26 UTC, mfrolov89 commented on packages/components/src/DataGrid/DataGrid.tsx
> +      return columns.map((column) => {column.sortable = false; return column})
лучше записать как => ({ ...column, sortable: false })

2024-02-15 10:51 UTC, mfrolov89 commented on packages/components/src/DataGrid/DataGrid.test.tsx
> +  it('Props:columns:sortable: не отображается иконка сортировки', () => {
Стоит поправить названия тестов в соответсвии с гайдом https://industrious-search-cdf.notion.site/dac1e9ff807f4fa1a48150a0d609d530

2024-02-16 07:27 UTC, mfrolov89 approved these changes
Стоит еще раз посмотреть гайд по тестам, в названиях тестов не указываются Props:...

Рефакторинг названия тестов будет оформлен отдельной задачей

2024-02-16 10:18 UTC, AlexadraLitvinenko approved these changes

2024-02-16 11:22 UTC, merged