feat(UIKIT-1179): Реализовать адаптив для компонента Dialog
kaluga-astral/frontend pull request #825
Opened 2024-02-12 13:27 UTC by nikita11044

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-02-12 13:52 UTC, Ofigelov requested changes

2024-02-12 13:52 UTC, Ofigelov commented on packages/components/src/DialogActions/DialogActions.tsx
> +        <Grid container spacing={disableSpacing ? 0 : 2}>
container не обязательный, если использовать spacing или что либо связанное с цсс гридом

2024-02-12 13:52 UTC, Ofigelov commented on packages/components/src/DialogContent/styles.ts
> +export const MuiDialogContentStyled = styled(
Styled постфикс по стайл гайду запрещен

2024-02-12 14:53 UTC, Ofigelov requested changes

2024-02-12 14:53 UTC, Ofigelov commented on packages/components/src/DialogContent/styles.ts
> +export const StyledMuiDialogContent = styled(
От того что styled стал префиксом вместо постфикса не решает проблему. Читай стайл гайд.

2024-02-13 06:28 UTC, mfrolov89 requested changes

2024-02-13 06:28 UTC, mfrolov89 commented on packages/components/src/BottomDrawer/BottomDrawer.tsx
> +      {title && (
от наличия или отсутствия заголовка не должно зависеть отображение шапки, так как основной способ закрытие окна, это нажатие на кнопку, кторая расположена в этой шапке

2024-02-13 06:28 UTC, mfrolov89 commented on packages/components/src/DialogActions/DialogActions.tsx
> +  if (isMobile) {
тут достаточно подменять часть пропсов у грида, а не полностью описывать реализацию компонента.

const gridProps = isMobile ? {...} : {...};

2024-02-13 06:28 UTC, mfrolov89 commented on packages/components/src/DialogContent/styles.ts
> +export const StyledMuiDialogContent = styled(
DialogContentRoot

2024-02-14 10:23 UTC, mfrolov89 commented on packages/components/src/DialogActions/styles.ts
> +  shouldForwardProp: (prop) => prop !== 'isMobile',
isMobile нужен для каких то условий в самом компоненте, например условный ренедеринг
В стилях нужно использовать медиа выражения из темы:

  ${({ theme }) => theme.breakpoints.down('sm')} {
....
}

2024-02-14 12:18 UTC, mfrolov89 commented on packages/components/src/DialogActions/styles.ts
> +import { styled } from '../styles/styled';
import { styled } from '../styles';

2024-02-14 12:22 UTC, mfrolov89 commented on packages/components/src/BottomDrawer/BottomDrawer.tsx
> +      {title && (
up! Договорились что пока не скрываем хедер при отсутствии title

2024-02-14 15:07 UTC, Ofigelov approved these changes

2024-02-15 07:22 UTC, merged