feat(UIKIT-1148,ui,ProgressBar): Реализован компонент ProgressBar
kaluga-astral/frontend pull request #836
Opened 2024-02-15 10:41 UTC by ddanilov-it

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-02-16 05:32 UTC, aesarantsev commented on packages/components/src/ProgressBar/ProgressBar.tsx
> +  currentProgress?: number;
Наверное пропс стоит сделать обязательным

2024-02-16 05:32 UTC, aesarantsev commented on packages/components/src/ProgressBar/ProgressBar.tsx
> +      <Title>Progress bar</Title>
Title и соответственно контейнер не нужен

2024-02-16 05:32 UTC, aesarantsev commented on packages/components/src/ProgressBar/ProgressBar.tsx
> +        sx={{
sx пропс мы не используем. Вся стилизация должна делаться через тему вот тут
packages/components/src/theme/components.
Посмотри как это сделано для других компонентов. Здесь нужно сделать аналогично, и убрать пропс sx

2024-02-16 05:32 UTC, aesarantsev commented on packages/components/src/ProgressBar/ProgressBar.tsx
> +  currentProgress?: number;
В MUI вижу, что они принимают только один пропс - `value`, который может быть от 0 до 100. Давай сделаем также. Оставим один пропс `currentProgress` и переименуем его в `value`. 
`maxProgress `- уберем

2024-02-16 05:32 UTC, aesarantsev commented on packages/components/src/ProgressBar/index.ts
> +export * from './ProgressBar';
Также необходимо экспортировать компонент в файле packages/components/src/index.ts

2024-02-19 03:50 UTC, aesarantsev approved these changes

2024-02-19 03:50 UTC, aesarantsev commented on packages/components/src/theme/components/MuiLinearProgress.ts
> +      backgroundColor: '#6746eb',
Здесь нужно использовать цвет из theme.palette.primary['800'].
Это нужно т.к. у различных продуктов отличаются цветовые схемы интерфеса. По этому берем цвет из темы, которая для каждого продукта своя

2024-02-19 03:50 UTC, aesarantsev commented on packages/components/src/theme/components/MuiLinearProgress.ts
> +  styleOverrides: {
Нужно еще дополнительно изменить цвет незаполненной части прогресс-бара. Сейчас она не соответствует макету

2024-02-19 03:50 UTC, aesarantsev commented on packages/components/src/theme/components/MuiLinearProgress.ts
> +      backgroundColor: '#6746eb',
Тут можно пощелкать разные темы продуктов:
![image](https://github.com/kaluga-astral/frontend/assets/47385491/4e0f2992-512d-41c1-abfd-eae499d3a5c5)

2024-02-19 03:50 UTC, aesarantsev commented on packages/components/src/theme/components/MuiLinearProgress.ts
> +  styleOverrides: {
Использовать theme.palette.grey[300]

2024-02-19 07:25 UTC, aesarantsev approved these changes

2024-02-19 07:51 UTC, mfrolov89 requested changes

2024-02-19 07:51 UTC, mfrolov89 commented on packages/components/src/ProgressBar/ProgressBar.tsx
> +   * Текущий прогресс загрузки (от 0 до 100, обязательный)
Текущий прогресс загрузки, значения от 0 до 100

Писать про обязательность излишне

2024-02-19 09:01 UTC, mfrolov89 approved these changes

2024-02-20 06:27 UTC, merged