Feat/UI kit 1181
kaluga-astral/frontend pull request #839
Opened 2024-02-16 13:45 UTC by nikita11044

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-02-19 07:28 UTC, mfrolov89 requested changes
1. Необходимо поправить название ПР
2. Нужно откатить все правки по MenuOrganization, компонент сейчас не актуален и должен быть удален из кита (на это есть отдельная задача)

2024-02-19 07:28 UTC, mfrolov89 commented on packages/components/src/Menu/Menu.tsx
> +export const Menu = ({ children, onClose, open, ...restProps }: MenuProps) => {
Нужно расширить пропсы, добавав опциональный title

2024-02-19 07:55 UTC, mfrolov89 commented on packages/components/src/Menu/Menu.tsx
> +  title?: JSX.Element | JSX.Element[] | string;
тут лучше сразу ограничиться только строкой

2024-02-20 09:36 UTC, StanislavDa approved these changes

2024-02-20 09:41 UTC, merged