feat(UIKIT-1119,ui,DataList): Реализован компонент DataList
kaluga-astral/frontend pull request #843
Opened 2024-02-19 12:23 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-02-20 07:37 UTC, AndTem requested changes

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataList/DataList.stories.tsx
> +      setIsEndReached(true);
Криво сейчас работает story из-за того, что isEndReached true, а данные еще можно подгрузить

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataList/DataList.stories.tsx
> +        onRetry={() => undefined}
Прокинул бы для прилия incrementData

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataList/DataList.stories.tsx
> +  const [slicedData, setSlicedData] = useState<MockDate[]>([]);
```suggestion
  const [slicedData, setSlicedData] = useState<MockData[]>([]);
```

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataList/DataList.stories.tsx
> +    .fill(null)
При создании через Array.from вызывать fill не нужно

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataList/DataList.tsx
> +  noDataPlaceholder?: React.ReactNode;
https://kaluga-astral.github.io/style-guide/docs/rules/react/react-namespace

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataList/DataList.tsx
> +  listItem: (props: T) => ReactNode;
Может лучше renderItem?
И нужен еще доступ к index здесь: renderItem: (dataItem, index) => ReactNode

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataList/DataList.tsx
> +export const DataList = <T extends Record<string, unknown>>({
```suggestion
export const DataList = <TDataItem extends Record<string, unknown>>({
```

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataList/DataList.tsx
> +export type DataListProps<T> = {
```suggestion
export type DataListProps<TDataItem extends ...> = {
```

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataList/DataList.tsx
> +        imgAlt: 'Что-то пошло не тиак',
https://doka.guide/a11y/how-to-describe-pictures/

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataList/DataListEndData/DataListEndDate.tsx
> +export const DataListEndDate = ({ endOfScrollMsg }: Props) => (
```suggestion
export const DataListEndData = ({ endOfScrollMsg }: Props) => (
```

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataList/DataListEndData/DataListEndDate.tsx
> +export const DataListEndDate = ({ endOfScrollMsg }: Props) => (
```suggestion
export const DataListEndDate = ({ endOfScrollMsg = END_OF_SCROLL_MESSAGE }: Props) => (
```

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataList/DataListEndData/styles.ts
> +export const DataListNoDataRoot = styled.li`
Сделай сразу нейминг по новому формату: https://kaluga-astral.github.io/style-guide/docs/rules/react/styled#%D0%BD%D0%B5%D0%B9%D0%BC%D0%B8%D0%BD%D0%B3-styled-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataList/DataListLoader/styles.ts
> +export const DataListLoaderRoot = styled.li`
Можно li вынести на уровень корневого компонета, чтобы не дублировать стили

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataListitem/DataListItem.tsx
> +  <DataListItemRoot onClick={onClick}>{children}</DataListItemRoot>
В 90% случаев это будет ссылка, а не кнопка.
Нужен механизм, похожий с Button, чтобы можно было прокинуть Link роутера

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataList/index.ts
> +export * from './DataList';
Забыл экспорт из пакета сделать

2024-02-20 07:37 UTC, AndTem commented on packages/components/src/DataList/DataList.test.tsx
> +describe('DataList', () => {
Для onRetry надо еще кейс добавить

2024-02-20 07:38 UTC, AndTem commented on packages/components/src/DataList/DataList.test.tsx
> +describe('DataList', () => {
И для onEndReached

2024-02-21 14:08 UTC, mfrolov89 commented on packages/components/src/DataList/DataList.tsx
> +        imgAlt: 'Что-то пошло не тиак',
тут нет возможности описать как в доке, они там я бы сказал борща дали, целое сочинение. Проблема в том  что изображение на проектах разное, если у нас на макетах экран, с крестиком в красном круге, то где-то будут котики. С плейсхолдером при отсутствии данных тоже проблема. Даже нет пока идей как нормально описать неизвестно что...
Можно добавить пропсы и переложить ответственность на разработчиков, которые будут использовать этот компонент, но кажется что многие забъют на это, тем более что пропсы не обязательны у плейсхолдера.

2024-02-22 13:49 UTC, AndTem commented
Linter упал

2024-02-22 13:54 UTC, AndTem approved these changes

2024-02-22 13:54 UTC, AndTem commented on packages/components/src/DataList/DataList.tsx
> +  itemContent: (
Может все таки renderItem? Потому, что напрямую компонент в этот пропс не кинешь (а по названию как будто кинешь)

2024-02-22 13:54 UTC, AndTem commented on packages/components/src/DataList/constants.ts
> +export const ITEM_CLASSNAME = 'datalist_item';
не надо префикс astral/ui добавить, чтобы потенциального пересечения не было в продукте?

2024-02-22 14:07 UTC, mfrolov89 commented on packages/components/src/DataList/DataList.tsx
> +  itemContent: (
в том то и дело что можно) у нас есть контейнер в виде li, у нам ничто не мешает туда кинуть просто текст, оно не упадет же) renderItem это в моем понимании как раз таки история про полное замещение элемента списка, может ошибаюсь. Если ты все таки думаешь что тут лучше renderItem, то давай переименуем)

2024-02-22 14:08 UTC, mfrolov89 commented on packages/components/src/DataList/constants.ts
> +export const ITEM_CLASSNAME = 'datalist_item';
были мысли, но не знал делаете ли вы так. Добавлю префикс, думаю можно его стандартизировать и закрепить в доке

2024-02-22 14:11 UTC, AndTem commented on packages/components/src/DataList/DataList.tsx
> +  itemContent: (
Ты не сможешь кинуть потому, что у функции сигнатура не соответсвует FunctionComponent.
Сделать так не выйдет: itemContent={<MyItem}

2024-02-22 14:12 UTC, AndTem commented on packages/components/src/DataList/constants.ts
> +export const ITEM_CLASSNAME = 'datalist_item';
Нужно просто сделать фабрику createClassname и тогда дока будет не нужна

2024-02-22 14:15 UTC, mfrolov89 commented on packages/components/src/DataList/DataList.tsx
> +  itemContent: (
я немного про другое, мы можем технически кинуть такое содержимое:
({ name }) => name

или

({ name, date }) => (
<>
    <h5>{name}</h5>
    <span>{date}</span>
</>
)

Т.е пропс говорит о том что содержимое будет прокинуто во внуть некого контейнера, в нашем случе li. А renderItem, это уже история про то, что мы обязаны использовать контейнер

2024-02-22 14:21 UTC, mfrolov89 commented on packages/components/src/index.ts
> +export * from './DataList';
Можешь уточнить о чем тут речь? Экспортируем только DataList и его тип, больше из него наружу вроде тоже не нужно отдавать

2024-02-22 14:39 UTC, merged