popover
kaluga-astral/frontend pull request #850
Opened 2024-02-26 09:51 UTC by BazhinaJuliannaaa

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-02-26 11:55 UTC, Ofigelov approved these changes

2024-02-26 21:07 UTC, mfrolov89 requested changes
Необходимо разобраться с линтером и отформатировать весь код

2024-02-26 21:07 UTC, mfrolov89 commented on packages/components/src/Popover/Popover.stories.tsx
> +export const MouseOnTypography = () => {
1. Пример не рабочий
2. Это не совсем корректный кейс для поповера, исходим из того что поповер открывается по клику

2024-03-01 08:37 UTC, mfrolov89 requested changes

2024-03-01 08:37 UTC, mfrolov89 commented on packages/components/src/Popover/Popover.stories.tsx
> +  gap: 10px;
задай через theme.spacing()

2024-03-01 08:37 UTC, mfrolov89 commented on packages/components/src/Popover/Popover.stories.tsx
> +  const handleClick = (event: MouseEvent<HTMLButtonElement>) => {
не несет никакой смысловой нагрузки, можно по месту использовать setAnchorEl, как это сделано в handleClose

2024-03-01 08:37 UTC, mfrolov89 commented on packages/components/src/Popover/Popover.stories.tsx
>  const PopoverContainer = styled(LegacyGrid)`
LegacyGrid является устаревшим и его не желатьно использовать, можно использовать div

2024-03-05 06:22 UTC, mfrolov89 approved these changes

2024-03-05 07:14 UTC, merged