bug(UIKIT-1260,ui,createTheme): Исправлено расширение темы через options
kaluga-astral/frontend pull request #851
Opened 2024-02-26 10:13 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-02-26 10:38 UTC, Ofigelov commented on packages/components/src/utils/external.ts
> +export { uniqBy, prop, debounce, mergeDeep as merge } from 'remeda';
а зачем нужна подмена mergeDeep в merge? этоже разные хелперы, и используется только в одном месте, и наружу из кита не уходит

2024-02-26 10:39 UTC, AndTem requested changes

2024-02-26 10:39 UTC, AndTem commented on packages/components/src/utils/external.ts
> +export { uniqBy, prop, debounce, mergeDeep as merge } from 'remeda';
Сомнительное переименование. Лучше просто переименовать везде в mergeDeep

2024-02-26 10:39 UTC, AndTem commented on packages/components/src/theme/baseTheme/baseTheme.ts
> +    ? (merge(themeOptions, options as Record<string, unknown>) as ThemeOptions)
merge не generic?

2024-02-26 10:45 UTC, mfrolov89 commented on packages/components/src/utils/external.ts
> +export { uniqBy, prop, debounce, mergeDeep as merge } from 'remeda';
в рамках remeda разные, но в лодаше merge работает с глубоким копированием. Кажется что так удобнее, чтобы при замене библиотек не менять названия функций в местах использования

2024-02-26 10:46 UTC, mfrolov89 commented on packages/components/src/utils/external.ts
> +export { uniqBy, prop, debounce, mergeDeep as merge } from 'remeda';
Отписал выше, но похоже большинство  за вариант без переименования)

2024-02-26 10:46 UTC, AndTem commented on packages/components/src/utils/external.ts
> +export { uniqBy, prop, debounce, mergeDeep as merge } from 'remeda';
Очевидность производимой операции перевешивает

2024-02-27 07:06 UTC, Ofigelov approved these changes

2024-02-27 07:13 UTC, merged