Feat/UI kit 629
kaluga-astral/frontend pull request #852
Opened 2024-02-27 11:12 UTC by ddanilov-it

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-02-27 11:22 UTC, aesarantsev commented on packages/components/src/FlowButton/FlowButton.stories.tsx
> + * FlowButton — это кнопка, которая запускает потоки.
Думаю лучше как-то так: Это кнопка для запуска/продолжения пользовательского сценария

2024-02-27 11:22 UTC, aesarantsev commented on packages/components/src/FlowButton/FlowButton.stories.tsx
> +  <FlowButton targetText="Далее" disabled={false} color="primary">
disabled пропс тут вроде не нужен

2024-02-27 11:22 UTC, aesarantsev commented on packages/components/src/FlowButton/FlowButton.stories.tsx
> +export const Example = () => (
Добавь еще сценарий использования пропса targetText (для примера указать другой текст в нем)

2024-02-28 09:25 UTC, mfrolov89 requested changes
1. Необходимо добавить сторю Colors и вывести кнопки во всех цветовых вариациях
2 Название PR не соответствует формату

2024-02-28 09:25 UTC, mfrolov89 commented on packages/components/src/FlowButton/FlowButton.stories.tsx
> +export const Skip = () => (
```suggestion
export const TargetText = () => (
```

2024-02-28 12:14 UTC, aesarantsev requested changes

2024-02-28 12:14 UTC, aesarantsev commented on packages/components/src/FlowButton/FlowButton.stories.tsx
> +      Синий цвет
Лучше вместо "Синий цвет" указать "primary". Так при взгляде на сторю будет понятно, какой цвет нужно использоваться в коде. Плюс цвет для каждого варианта может поменяться (синий может стать зеленым, если поменять тему)

2024-02-28 12:14 UTC, aesarantsev commented on packages/components/src/FlowButton/FlowButton.stories.tsx
> +export const Colors = () => (
Тут можно указать наименование, полностью соответствующее наименованию пропса (Color)

2024-02-28 12:39 UTC, aesarantsev approved these changes

2024-02-29 06:42 UTC, mfrolov89 approved these changes

2024-02-29 06:44 UTC, merged