feat(UIKIT-844,ui,Typography): Исправляет типизацию в Typography
kaluga-astral/frontend pull request #858
Opened 2024-03-01 11:56 UTC by agro196

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-03-01 11:58 UTC, agro196 commented
https://track.astral.ru/soft/browse/UIKIT-844

2024-03-01 12:07 UTC, AndTem requested changes

2024-03-01 12:07 UTC, AndTem commented on packages/components/src/Typography/Typography.tsx
>        if (colorName) {
Предлагаю вынести логку в хук и написать на нее тест.
А то высокий шанс отказа в этом месте

2024-03-01 12:07 UTC, AndTem commented on packages/components/src/theme/palette/palette.ts
> +      900: '#E64343',
А зачем нужно указывать эти цвета руками? В brandColors они же есть всегда

2024-03-01 12:42 UTC, agro196 commented on packages/components/src/theme/palette/palette.ts
> +      900: '#E64343',
Здесь не понял( Можешь привести пример как должно быть?

2024-03-01 12:45 UTC, AndTem commented on packages/components/src/theme/palette/palette.ts
> +      900: '#E64343',
А лучше get error() { return this.red }

2024-03-05 07:44 UTC, AndTem requested changes

2024-03-05 07:44 UTC, AndTem commented on packages/components/src/Typography/hooks/useTypographyColor/useTypographyColor.test.ts
> +  it('Возвращает цвет #072D57', () => {
Почитай про[ нейминг тест-кейсов](https://industrious-search-cdf.notion.site/dac1e9ff807f4fa1a48150a0d609d530#3978cc1bab894520b091a18e258733f9).

В твоем случае можно сделать it.each, через который ты проверишь все возможные входные и выходные значения

2024-03-05 07:44 UTC, AndTem commented on packages/components/src/Typography/hooks/useTypographyColor/useTypographyColor.test.ts
> +      expect(colorFunction).toBe('#072D57');
```suggestion
      expect(colorFunction).toBe(theme.grey);
```

2024-03-05 07:44 UTC, AndTem commented on packages/components/src/Typography/hooks/useTypographyColor/useTypographyColor.test.ts
> +      expect(colorFunction).toBe('#072D57');
Тесты будут сейчас падать при смене темы

2024-03-05 07:44 UTC, AndTem commented on packages/components/src/Typography/hooks/useTypographyColor/useTypographyColor.tsx
> +export const useTypographyColor = ({
Почему бы в самом хуке не достатоть theme из контекста и не возвращать функцию из useMemo?
Сейчас неоправданно сложная схема

2024-03-05 07:44 UTC, AndTem commented on packages/components/src/Typography/hooks/useTypographyColor/useTypographyColor.test.ts
> +    expect(result.current).toBeDefined();
Используешь антипаттерн: ["Проверка разных результатов в одном тест-кейсе (множественный блок assert из AAA)"](https://industrious-search-cdf.notion.site/15e733a20ce04f7e84ad566e70a78f29?pvs=25#ee4867d41765445dbd50f78c22db770a)

2024-03-05 12:30 UTC, agro196 commented on packages/components/src/Typography/hooks/useTypographyColor/useTypographyColor.tsx
> +export const useTypographyColor = ({
Сейчас вроде нет контекста для темы, его где-то отдельно создать?

2024-03-05 13:14 UTC, AndTem commented on packages/components/src/Typography/hooks/useTypographyColor/useTypographyColor.tsx
> +export const useTypographyColor = ({
useTheme хук есть

2024-03-06 10:32 UTC, agro196 commented on packages/components/src/Typography/hooks/useTypographyColor/useTypographyColor.tsx
> +export const useTypographyColor = ({
Не могу понять почему так происходит. Хук в итоге выглядит таким образом

2024-03-06 11:34 UTC, agro196 commented on packages/components/src/Typography/hooks/useTypographyColor/useTypographyColor.tsx
> +export const useTypographyColor = ({
<img width="1209" alt="image" src="https://github.com/kaluga-astral/frontend/assets/65020968/6bcb82ad-5354-4b71-a205-ef2f5446d90b">

2024-03-07 10:57 UTC, AndTem requested changes

2024-03-07 10:57 UTC, AndTem commented on packages/components/src/Typography/hooks/useTypographyColor/useTypographyColor.test.tsx
> +  ])('Цвет %s валиден при передаче в хук', (color, expectedColor) => {
Используешь [антипаттерны тестирования](https://industrious-search-cdf.notion.site/15e733a20ce04f7e84ad566e70a78f29#7f1f5e7fbac84e558e916075fb5e4726).

Правильно: Для color="%s" устанавливается цвет из темы "%s"

2024-03-07 11:22 UTC, AndTem commented on packages/components/src/Typography/hooks/useTypographyColor/useTypographyColor.test.tsx
> +  ])('Для color=%s устанавливается цвет из темы %s', (color, expectedColor) => {
Читай [style guide](https://kaluga-astral.github.io/style-guide/docs/rules/tests/it-each).
В своем комменте я как раз указал двойные ковычки

2024-03-07 11:29 UTC, AndTem approved these changes

2024-03-07 12:12 UTC, mfrolov89 requested changes

2024-03-07 12:12 UTC, mfrolov89 commented on packages/components/src/theme/palette/palette.ts
> +        'Цвет "info" больше не используется, используйте другие цвета.',
думаю можно указать, что можно использовать primary, так как они совпадали

2024-03-07 12:13 UTC, mfrolov89 commented on packages/components/src/Typography/hooks/useTypographyColor/useTypographyColor.tsx
> +type UseTypographyColorProps = {
https://kaluga-astral.github.io/style-guide/docs/rules/react/hooks#%D1%82%D0%B8%D0%BF-%D0%B2%D1%85%D0%BE%D0%B4%D0%BD%D1%8B%D1%85-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2-%D1%85%D1%83%D0%BA%D0%B0-%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD-%D0%B8%D0%BC%D0%B5%D1%82%D1%8C-%D0%BF%D0%BE%D1%81%D1%82%D1%84%D0%B8%D0%BA%D1%81-params

2024-03-11 07:23 UTC, mfrolov89 approved these changes

2024-03-11 07:25 UTC, merged