feat(UIKIT-983): Реализован Link
kaluga-astral/frontend pull request #860
Opened 2024-03-01 14:55 UTC by Uvoi

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-03-02 13:56 UTC, maksimmolofeev commented on packages/components/src/Link/styles.ts
> +  color: ${DEFAULT};
для передачи размера шрифта, отступов, цвета используется [theme](https://main--61baeff6f06230003a88ef8a.chromatic.com/?path=/docs/components-theme-theme--docs), посмотри в других компонентах как это делается.

2024-03-02 13:56 UTC, maksimmolofeev commented on packages/components/src/Link/Link.tsx
> +        <span>{children}</span>
а span тут точно нужен? Может без него сделать?

2024-03-02 13:56 UTC, maksimmolofeev commented on packages/components/src/Link/Link.tsx
> +        style={{
Все стили нужно выносить в styles.
Мне кажется Grid здесь не очень подходит, может лучше будет просто div, с display: flex?

2024-03-06 08:41 UTC, mfrolov89 requested changes

2024-03-06 08:41 UTC, mfrolov89 commented on packages/components/src/Link/Link.stories.tsx
> +/**
Нужно добавить описание компонента

2024-03-06 08:41 UTC, mfrolov89 commented on packages/components/src/Link/Link.tsx
> +  endAddon?: LinkAddon;
Иконка для ссылки является стандартизированной и пока не придвидится использование каких-то кастомных изображений. В связи с этим стоит зашить иконку в компонент Link.  Для управления отображением иконки можно использовать пропс withAdornment, а для ее положения position = start | end. По дефолту указать какое-то базовое расположение

2024-03-06 08:41 UTC, mfrolov89 commented on packages/components/src/Link/styles.ts
> +  &:active {
переопределение для базового компонента нужно сделать через **Overrides** theme/components

2024-03-06 08:41 UTC, mfrolov89 commented on packages/components/src/Link/styles.ts
> +  padding: ${theme.spacing(0.5, 0.25, 0.5, 0)};
не вижу необходимости в отступах + на макетах тоже этого не заметил

2024-03-06 08:41 UTC, mfrolov89 commented on packages/components/src/Link/styles.ts
> +import { theme } from '@astral/tests/src/theme';
тему не импортируем

2024-03-06 08:41 UTC, mfrolov89 commented on packages/components/src/Link/styles.ts
> +    gap: ${theme.spacing(1)};
```suggestion
    gap: ${({ theme }) => theme.spacing(1)};
```

С темой в styled компонентах работаем так

2024-03-06 08:41 UTC, mfrolov89 commented on packages/components/src/Link/Link.tsx
> +import { type LinkProps as MuiLinkProps } from '@mui/material/Link';
```suggestion
import { type LinkProps as MuiLinkProps } from '@mui/material';
```

2024-03-06 08:41 UTC, mfrolov89 commented on packages/components/src/Link/Link.tsx
> +      <div>
Кажется что div лишний и можно центрировать через стилизацию 'a'

2024-03-11 07:19 UTC, mfrolov89 requested changes

2024-03-11 07:19 UTC, mfrolov89 commented on packages/components/src/Link/Link.test.tsx
> +    renderWithTheme(<Link children={label} withAdornment="start" />);
```suggestion
    renderWithTheme(<Link withAdornment="start">Link</Link>);
```

+ не указал href, смотри ошибки в ci

2024-03-11 07:19 UTC, mfrolov89 commented on packages/components/src/Link/styles.ts
> +  .MuiSvgIcon-root {
обращаемся к классам mui иначе, используй svgIconClasses. Пример можно посмотреть в BottomDrawer

2024-03-23 15:54 UTC, Uvoi commented on packages/components/src/Link/styles.ts
> +  .MuiSvgIcon-root {
Не совсем понял как именно изменить, не нашел примера в BottomDrawer

2024-03-25 13:14 UTC, maksimmolofeev approved these changes

2024-03-25 14:16 UTC, maksimmolofeev approved these changes

2024-03-25 14:16 UTC, maksimmolofeev commented on packages/components/src/Link/Link.test.tsx
> +  it('Иконка слева отображается', () => {
Сразу не заметил, каждый тест-кейс должен строиться по формуле
it('ПРЕДМЕТ_ТЕСТИРОВАНИЯ + ОЖИДАЕМЫЙ_РЕЗУЛЬТАТ + УСЛОВИЕ')
Поэтому должно быть "Иконка слева отображается при withAdornment="start""
В следующем тесте так же

2024-03-25 14:30 UTC, mfrolov89 commented on packages/components/src/Link/Link.test.tsx
> +import { Link } from '.';
```suggestion
import { Link } from './Link';
```

2024-03-25 14:47 UTC, mfrolov89 approved these changes

2024-03-26 09:01 UTC, merged