feat(UIKIT-1124,ui,WelcomeScreen): Добавлен компонент приветственного экрана
kaluga-astral/frontend pull request #861
Opened 2024-03-04 06:10 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-03-04 06:21 UTC, YrStudenikin commented on packages/components/src/WelcomeScreen/constants.ts
> +export const SESSION_KEY = 'astralui-session';
Есть предложение в styleguide добавить раздел с именованием ключей для хранилищ браузера, т.к. уже не первый раз вижу разные варианты

2024-03-04 06:22 UTC, AndTem commented on packages/components/src/WelcomeScreen/constants.ts
> +export const SESSION_KEY = 'astralui-session';
@YrStudenikin предложения необходимо оформлять на доске frontend.shared

2024-03-04 07:57 UTC, AndTem commented
- В Example Storybook в рандомное время отображается ошибка

2024-03-04 08:11 UTC, AndTem requested changes

2024-03-04 08:11 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.tsx
> +        isShowLoader ? <CircularProgress color="primary" /> : <></>
А нужно тут условие? Без isLoading loadingContent отображаться не будет

2024-03-04 08:11 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.tsx
> +      errorState={{ errorList: [''], onRetry }}
Error надо пропсом принимать

2024-03-04 08:11 UTC, AndTem commented on packages/components/src/WelcomeScreen/constants.ts
> +export const FIRST_STEP_DURATION_MS = 2400;
Я считаю, что анимация сейчас слишком затянутая

2024-03-04 08:11 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.tsx
> +    const isExistSession = Boolean(sessionStorage.getItem(SESSION_KEY));
sessionStorage может быть недоступен в браузере из-за пользовательских политик.
Здесь в таком случае произойдет exception.
Можно завести отдельную задачу на реализацию SessionStorageService

2024-03-04 08:11 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.test.tsx
> +describe('WelcomeScreen', () => {
Не хватает теста на:
- отображение текста Добро пожаловать
- Отображение/не отображение при взаимоедйствии с sessionStorage
- отображение имени пользователя

2024-03-04 08:11 UTC, AndTem commented on packages/components/src/WelcomeScreen/styles.ts
> +  height: 100dvh;
У dvh очень слабая поддержка. Необходимо fallback делать.
Можно через media query чекать доступность фичи

2024-03-04 08:11 UTC, AndTem commented on packages/components/src/WelcomeScreen/styles.ts
> +  animation: ${fadeFirstStep} ${FIRST_STEP_DURATION_MS}ms linear;
Время для анимаций есть в теме в transitions. Может от туда и брать их?

2024-03-04 08:11 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.stories.tsx
> +export const Example = () => {
Добавь children DashboardLayout.
И после этого ты поймешь, что этот скрин работает криво: при исчезании логотип будет как будто перескакивать.
Считаю, что  расположение и размер лого в WelcomeScreen второго эатапа должен совпадать с хедеров в DashboardLayout

2024-03-04 08:11 UTC, AndTem commented on packages/components/src/WelcomeScreen/styles.ts
> +const appearText = keyframes`
```suggestion
const appearTextKeyframe = keyframes`
```

2024-03-04 08:11 UTC, AndTem commented on packages/components/src/WelcomeScreen/styles.ts
> +  margin-top: -15vh;
Стрельнет этот vh.
В процентах нельзя или в других единицах измерения?

2024-03-04 08:11 UTC, AndTem commented
Не хватает анимации при пропадании WelcomeScreen. Сейчас ее нет

2024-03-04 08:20 UTC, mfrolov89 commented on packages/components/src/WelcomeScreen/WelcomeScreen.tsx
> +        isShowLoader ? <CircularProgress color="primary" /> : <></>
Это для условие, реализующее задержку отображения лоадера в 300мс

2024-03-04 08:34 UTC, mfrolov89 commented on packages/components/src/WelcomeScreen/styles.ts
> +  height: 100dvh;
<img width="1533" alt="Снимок экрана 2024-03-04 в 11 33 56" src="https://github.com/kaluga-astral/frontend/assets/47597207/eb94a98e-5733-49f2-8528-c5162bc827a8">

2024-03-04 08:43 UTC, AndTem commented on packages/components/src/WelcomeScreen/styles.ts
> +  height: 100dvh;
Поддерджка с 23 года начинается. А у Android с 24

2024-03-04 09:03 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.tsx
> +        isShowLoader ? <CircularProgress color="primary" /> : <></>
Тогда нужен коммент

2024-03-04 10:00 UTC, mfrolov89 commented on packages/components/src/WelcomeScreen/styles.ts
> +  animation: ${fadeFirstStep} ${FIRST_STEP_DURATION_MS}ms linear;
Сейчас посмотрел указанные там значения: там нет подходящего.
Даже если бы оно и было, то это небезопасно.  У нас не определены эти значения, в mui они могут и поменяться в любой момент. По хорошему нужно тогда на уровне темы все это стандартизировать и согласовать с дизайнерами.

2024-03-05 07:33 UTC, AndTem commented
@mfrolov89 Тесты упали и storybook

2024-03-05 07:37 UTC, AndTem requested changes

2024-03-05 07:37 UTC, AndTem commented on packages/components/src/WelcomeScreen/hooks/useWelcomeScreenStates/useWelcomeScreenStates.ts
> +export const useWelcomeScreenStates = ({
Может просто useLogic назвать?
Будет соответсвовать style guide даже

2024-03-05 14:16 UTC, merged