feat(UIKIT-1227,ui,Feedback): Реализован виджет для обратной связи
kaluga-astral/frontend pull request #873
Opened 2024-03-15 11:54 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-03-15 12:00 UTC, mfrolov89 commented on packages/components/src/Feedback/Feedback.tsx
> +  const [rating, setRating] = useState<number | null>();
есть мысли что лучше использовать тут форму, а не хранить состояния  в стейтах, но не уверен что компонент тогда сможет находится в папке components, думаю что может потянуть на features

2024-03-18 06:56 UTC, AndTem requested changes

2024-03-18 06:56 UTC, AndTem commented on packages/components/src/Feedback/hooks/useInterval/useInterval.ts
> +export const useInterval: UseIntervalHook = (callback, ms) => {
Может взять готовый из react-use: https://github.com/streamich/react-use/blob/master/docs/useInterval.md?

2024-03-18 06:56 UTC, AndTem commented on packages/components/src/Feedback/hooks/useTimer/useTimer.ts
> +export const useTimer: UseTimerHook = (seconds, endTimerHook) => {
Готовое из react-use не подойдет? https://github.com/streamich/react-use/blob/master/docs/useTimeout.md

2024-03-18 06:56 UTC, AndTem commented on packages/components/src/Feedback/Feedback.tsx
> +  const [rating, setRating] = useState<number | null>();
Я думаю, что использовать astral/form для этого компонента излишне - просто раздуется размер.
Но сам тэг form надо конечно использовать здесь, что сабмит по enter работал

2024-03-18 06:56 UTC, AndTem commented on packages/components/src/Feedback/Feedback.tsx
> +    rating?: number | null;
При каких обстоятельствах rating может быть optional?
Такого по идеи быть не должно

2024-03-18 06:56 UTC, AndTem commented on packages/components/src/Feedback/Feedback.tsx
> +                  onChange={(event) => setFeedback(event.target.value)}
Style Guide нарушен: https://kaluga-astral.github.io/style-guide/docs/rules/react/logic#%D0%B7%D0%B0%D0%BF%D1%80%D0%B5%D1%89%D0%B5%D0%BD%D0%B0-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%BE%D0%B2-%D0%B2-jsx

2024-03-18 06:56 UTC, AndTem commented on packages/components/src/Feedback/styles.ts
> +  right: 20px;
Отступы через spacing

2024-03-18 06:56 UTC, AndTem commented on packages/components/src/Feedback/styles.ts
> +  padding: 8px;
spacing

2024-03-18 06:56 UTC, AndTem commented on packages/components/src/Feedback/styles.ts
> +  gap: 16px;
spacing

2024-03-18 06:56 UTC, AndTem commented on packages/components/src/Feedback/styles.ts
> +  margin-top: 8px;
spacing

2024-03-18 06:56 UTC, AndTem commented on packages/components/src/Feedback/styles.ts
> +  gap: 24px;
spacing

2024-03-18 06:56 UTC, AndTem commented on packages/components/src/Feedback/styles.ts
> +  max-height: ${({ isShow }) => (isShow ? '200px' : '0px')};
Почему бы не заюзать Grow, Collapse и тп.
Мы тут опять лагающую анимацию получаем

2024-03-18 06:56 UTC, AndTem commented on packages/components/src/Feedback/EmojiRaiting/constants.ts
> +  '&#128544;',
Уверен, что это должны быть не иконки?
Emoji на разных ОС будут выглядеть по разному

2024-03-18 06:56 UTC, AndTem commented on packages/components/src/Feedback/Feedback.tsx
> +export const Feedback = ({
Экспорт из пакета забыл

2024-03-18 06:56 UTC, AndTem commented on packages/components/src/Rating/Rating.tsx
> +      getLabelText={(value: number) => hints[value - 1]}
https://kaluga-astral.github.io/style-guide/docs/rules/react/logic#%D0%B7%D0%B0%D0%BF%D1%80%D0%B5%D1%89%D0%B5%D0%BD%D0%B0-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%BE%D0%B2-%D0%B2-jsx

2024-03-18 06:56 UTC, AndTem commented on packages/components/src/Feedback/Feedback.tsx
> +            <StyledEmojiRating
Заметка: необходимо заложиться на то, что количество иконок может быть разное. В CSAT их 5, а в других может быть другое количество.
Надо пока просто сделать так, чтобы потом было просто расширить компонент

2024-03-18 07:02 UTC, AndTem commented
Замечания по UI/UX:
- Нужна анимация появления виджета - Grow норм
- Анимация при hover на emoji подлагивает
- Считаю, что для tooltip нужен отступ
<img width="395" alt="Снимок экрана 2024-03-18 в 09 58 18" src="https://github.com/kaluga-astral/frontend/assets/23665108/35c62de7-5f6e-4b16-b6d9-58a8df99d762">
- А нужна кнопка "отправить", если нет textField? Может просто тыкнул на иконку и все?
- Не уверен, что виджет должен закрываться по клику на backdrop. Это же не модалка

2024-03-18 07:03 UTC, AndTem commented on packages/components/src/Feedback/Feedback.tsx
> +export const Feedback = ({
Мне кажется, что более подходит FeedbackWidget или FeedbackPanel

2024-03-18 07:09 UTC, mfrolov89 commented on packages/components/src/Feedback/Feedback.tsx
> +export const Feedback = ({
Он экспортируется из пакета
<img width="572" alt="Снимок экрана 2024-03-18 в 10 09 00" src="https://github.com/kaluga-astral/frontend/assets/47597207/29c0d1ad-adbc-4a89-8daf-189de94c90d9">

2024-03-18 07:15 UTC, mfrolov89 commented on packages/components/src/Feedback/EmojiRaiting/constants.ts
> +  '&#128544;',
Не уверен на 100%. В начале как раз планировал иконки использовать, но со стороны дизайна постоянно звучало что это emoji, поэтому и решил остановиться на такой реализации. Уточню отдельно и посмотрю как это смотрится в других ОС

2024-03-18 08:23 UTC, mfrolov89 commented on packages/components/src/Feedback/hooks/useTimer/useTimer.ts
> +export const useTimer: UseTimerHook = (seconds, endTimerHook) => {
useTimeout не подойдет, он один раз вызывает перерендер, по истечению заданного времени

2024-03-19 08:52 UTC, mfrolov89 commented
Обсуждали наличие кнопки отправки при короткой версии оценки (без текстового поля), пришли к тому что кнопка нужна. Аргументы за отправку по кнопке:
- в продукте может быть несколько таких опросников, один полный, другой короткий, и будет очень странно что в одном кнопка есть, в другом нет.
- пользователь нажимая на кнопку отправить подтверждает свое действие, исключаем случайный нажатия, когда он по ошибке нажал на какую-то оценку и без кнопки уже не сможет изменить свое решение

2024-03-19 08:58 UTC, AndTem requested changes

2024-03-19 08:58 UTC, AndTem commented on packages/components/src/FeedbackPanel/FeedbackPanel.tsx
> +              <Form>
Тут должен быть onSubmit, а не в submit button

2024-03-19 08:58 UTC, AndTem commented on packages/components/src/FeedbackPanel/FeedbackPanel.tsx
> +    rating: number | null;
При каких обстоятельствах в onSubmit может прижти рейтинг с null?
По моему это некорректная логика

2024-03-19 08:58 UTC, AndTem commented on packages/components/src/FeedbackPanel/hooks/useTimer/useTimer.ts
> +import { useInterval } from 'react-use';
Реэкспорт через hooks в корне надо делать, чтобы был DI

2024-03-19 08:58 UTC, AndTem commented on packages/components/src/Feedback/styles.ts
> +  right: 20px;
up

2024-03-19 08:58 UTC, AndTem commented on packages/components/src/FeedbackPanel/EmojiRaiting/icons/HappyEmojiIcon.tsx
> +    width="1em"
width и height вроде как эти пропсы дефолтные

2024-03-19 08:58 UTC, AndTem commented on packages/components/src/FeedbackPanel/EmojiRaiting/icons/HappyEmojiIcon.tsx
> +    xmlns="http://www.w3.org/2000/svg"
Тоже дефолтный пропс кажется

2024-03-19 09:04 UTC, mfrolov89 commented on packages/components/src/FeedbackPanel/EmojiRaiting/icons/HappyEmojiIcon.tsx
> +    xmlns="http://www.w3.org/2000/svg"
посмотрю, в генерируемых иконках они везде пробрасываются, брал за основу от туда

2024-03-19 09:05 UTC, AndTem commented
Комментарии по UI:
- Ощущение лагающей анимации при наведении на иконки. Скорее всего дело в tooltip (может быть таймер поставить на тултип, чтобы появлялся после увеличения иконки)

2024-03-19 09:06 UTC, AndTem commented
И раз уж про анимации начали говорить, то неплохо было бы добавить хотя бы Fade при появлении Success Placeholder, а то при поялвении есть анимация, а потом ее нет

2024-03-19 09:13 UTC, AndTem commented
> И раз уж про анимации начали говорить, то неплохо было бы добавить хотя бы Fade при появлении Success Placeholder, а то при поялвении есть анимация, а потом ее нет

Это опциальный коммент.
Если делать Fade, то для высоты виджета надо сделать transition

2024-03-20 08:16 UTC, AndTem approved these changes

2024-03-20 12:44 UTC, merged