bug(UIKIT-1017,components,CheckboxField): Добавил выравнивание по вер…
kaluga-astral/frontend pull request #889
Opened 2024-03-26 12:36 UTC by Kostayne

…тикали

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-03-26 14:47 UTC, mfrolov89 reviewed
bug(UIKIT-1017,ui,CheckboxField)
https://github.com/kaluga-astral/frontend/blob/main/CONTRIBUTING.md

2024-03-26 14:55 UTC, Kostayne commented
> bug(UIKIT-1017,ui,CheckboxField) https://github.com/kaluga-astral/frontend/blob/main/CONTRIBUTING.md

CheckboxField находится в components, так что ui там быть не должно, а вот description коммита стоит поменять

2024-03-26 15:12 UTC, mfrolov89 commented
> > bug(UIKIT-1017,ui,CheckboxField) https://github.com/kaluga-astral/frontend/blob/main/CONTRIBUTING.md
> 
> CheckboxField находится в components, так что ui там быть не должно, а вот description коммита стоит поменять

Посмотри доку, там определен определенный перечень scope. Components там нет, есть ui, который как раз и обозначает сomponents, сопутствующие примеры там есть. О исторических причинах такого нейминга наверняка не подскажу, но скорее всего дело в краткости и простоте написания. При это учитывай что длина названия тоже ограничена. Если считаешь что нужно вводить другой нейминг, то давай отдельно обсуждать.

2024-03-26 16:05 UTC, Kostayne commented
Наткнулся на сообщение от husky: 
"✖   scope must be one of [components, features, form, icons, ui, server, UIKIT-XXXX] [function-rules/scope-enum]".

Если скоупы перечисленные в нем неактуальны, то нужно обновить @astral/commitlint-config

2024-03-27 12:37 UTC, mfrolov89 requested changes
Задача была на компонент Checkbox. У CheckboxField есть такая же проблема, которую ты исправляешь, на запроса на это не было

2024-03-27 13:21 UTC, Kostayne commented
> Задача была на компонент Checkbox. У CheckboxField есть такая же проблема, которую ты исправляешь, на запроса на это не было

Сам по себе чекбокс не содержит лейбл, это видно по коду самого чекбокса и коду в сторибуке. Там для подобных целей используется FormControlLabel, его менять определенно точно не стоит, тк вместо чекбокса он может содержать RadioButton, этот случай мы затрагивать не должны. 

Именно поэтому и был затронут CheckboxField

2024-03-28 13:08 UTC, mfrolov89 approved these changes

2024-03-29 12:34 UTC, merged