bug(UIKIT-1115,ui,Autocomplete): Добавлено сокрытие кнопки очистки при пустом инпуте
kaluga-astral/frontend pull request #892
Opened 2024-03-26 16:10 UTC by Kostayne

До этого кнопка "очистить" отображалась постоянно.

# Чеклист

- [X] Написать тесты для реализованного функционала
- [X] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2024-03-27 06:45 UTC, YrStudenikin commented
Нужно дополнить тесты

2024-03-27 08:25 UTC, Kostayne commented
> Нужно дополнить тесты

Done

2024-03-27 09:19 UTC, mfrolov89 commented on packages/form/src/FormAutocomplete/FormAutocomplete.test.tsx
> +  it('Prop:disableClearable=false: Прячет кнопку резета, если инпут пуст', async () => {
В новых тестах нужно использовать названия по новому стандарту, иначе мы увеличиваем тех.долг

2024-03-27 09:29 UTC, Kostayne commented on packages/form/src/FormAutocomplete/FormAutocomplete.test.tsx
> +  it('Prop:disableClearable=false: Прячет кнопку резета, если инпут пуст', async () => {
обновил все старые навзания в тестах компнонента

2024-03-27 10:03 UTC, mfrolov89 requested changes

2024-03-27 10:03 UTC, mfrolov89 commented on packages/form/src/FormAutocomplete/FormAutocomplete.tsx
> +  const disableClearable = !Boolean(fieldProps.value)
Эту логику необходимо переместить  в Autocomplete, проблема кроется в value, в данном случае в defaultValue. В FormAutocomplete в примерах c freeSolo defaultValue = пустой строке, что трактуется компонентом как наличия значения.

2024-03-27 10:03 UTC, mfrolov89 commented on packages/form/src/FormAutocomplete/FormAutocomplete.test.tsx
> -  it('Prop:inputRef: Фокус на поле после клика на Submit', async () => {
Стоит поправить описание, из описания непонятно что происходит с фокусом на поле: появляется или пропадает

2024-03-28 09:38 UTC, mfrolov89 commented
bug(UIKIT-1115,ui,FormAutocomplete) => bug(UIKIT-1115,ui,Autocomplete)

2024-03-28 09:40 UTC, Kostayne commented
> bug(UIKIT-1115,ui,FormAutocomplete) => bug(UIKIT-1115,ui,Autocomplete)

updated

2024-03-28 09:42 UTC, AndTem requested changes

2024-03-28 09:42 UTC, AndTem commented on packages/form/src/FormAutocomplete/FormAutocomplete.test.tsx
> +  it('Кнопка сброса скрыта, если инпут пуст', async () => {
Тесты по кнопке скрытия должны быть в Autocomplete потому, что функционал находится именно там

2024-03-28 09:42 UTC, AndTem commented on packages/form/src/FormAutocomplete/FormAutocomplete.test.tsx
> +    await waitFor(() => {
Для нужен waitFor? Без него по идеи должно работать все

2024-03-28 09:42 UTC, AndTem commented on packages/form/src/FormAutocomplete/FormAutocomplete.stories.tsx
> +      <FormAutocomplete<FormFreeValues, IOption, true, boolean, true>
Зачем на boolean заменил?

2024-03-28 09:44 UTC, mfrolov89 commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +  it('В инпут сетится label после выбора option при multiple=true', async () => {
```suggestion
  it('В инпут сетится label после выбора option', async () => {
```

Компоненту не пробрасывается multiple

2024-03-28 10:35 UTC, Kostayne commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +  it('В инпут сетится label после выбора option при multiple=true', async () => {
> it('В инпут сетится label после выбора option при multiple=true', async () => {
>   it('В инпут сетится label после выбора option', async () => {

Много раз пришлось прописывать multiple=true, к этой строке писал уже почти на автомате. Пофикшено =)

2024-03-28 10:36 UTC, Kostayne commented on packages/form/src/FormAutocomplete/FormAutocomplete.stories.tsx
> +      <FormAutocomplete<FormFreeValues, IOption, true, boolean, true>
Нужно было для manual тестов, убрал изменение

2024-03-28 10:36 UTC, Kostayne commented on packages/form/src/FormAutocomplete/FormAutocomplete.test.tsx
> +    await waitFor(() => {
Копипаст с ранее написанного, уже убрано

2024-03-28 10:37 UTC, AndTem approved these changes

2024-03-28 13:06 UTC, mfrolov89 requested changes

2024-03-28 13:06 UTC, mfrolov89 commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +  it('При options=[] отображается плейсхолдер', async () => {
В начале необходимо указывать объект тестирования

2024-03-28 13:06 UTC, mfrolov89 commented on packages/components/src/Autocomplete/Autocomplete.tsx
> +  const getIsInputEmpty = (val: unknown): boolean => {
какую проблему решает данная функция? Если задача была обрабоать режим мултиввода, когда имеем массив, то можно в самом начале оставить проверку на массив, а ниже стандартное приведение к boolean value

2024-03-28 13:06 UTC, mfrolov89 commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +  it('В options отображаются чекбоксы при multiple=true', async () => {
```suggestion
  it('Чекбоксы отображаются в options при multiple=true', async () => {
```

2024-03-29 13:15 UTC, mfrolov89 requested changes
не вижу комментарий, но писал ранее что нужно в сторибуке Autocomplete сделать компоненты контролируемыми

2024-03-29 13:15 UTC, mfrolov89 commented on packages/components/src/Autocomplete/Autocomplete.tsx
> +    // пользователь может ввести 0
Эта проверка лишняя, если пользователь введет число, то это будет приведено к строке.
Любая не пустая строка даст true. Нет смысла пытаться как то отдельно обработать ввод 0 пользователем

2024-03-29 13:15 UTC, mfrolov89 commented on packages/components/src/Autocomplete/Autocomplete.tsx
> +  const getIsInputEmpty = (): boolean => {
```suggestion
  const checkIsInputEmpty = (): boolean => {
```

https://kaluga-astral.github.io/style-guide/docs/rules/naming/functions

2024-03-29 13:53 UTC, mfrolov89 approved these changes

2024-03-29 14:05 UTC, merged