feat(UIKIT-1286,ui,ScrollToTopButton): Добавлена общая кнопка скролла наверх
kaluga-astral/frontend pull request #894
Opened 2024-03-27 12:25 UTC by Kostayne

# Чеклист

- [X] Описать jsdoc для props экспортируемых компонентов
- [X] Реализовать или обновить storybook для компонента
- [X] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

До этого были 2 отдельные кнопки в DataList & InfiniteDataGrid, выполнуяющие одну и ту же роль.

2024-03-28 13:58 UTC, mfrolov89 requested changes
1. Стоит написать тесты, достаточно  покрыть всего один кейс, что по клику вызывается onClick

2. Нужно добавить импорт компонента из пакета

2024-03-28 13:58 UTC, mfrolov89 commented on packages/components/src/ScrollToTopButton/ScrollToTopButton.tsx
> +  const handleClick = useCallback(
Не несет в себе никакого смысла, напрямую стоит пробросить onClick

2024-03-28 13:58 UTC, mfrolov89 commented on packages/components/src/ScrollToTopButton/ScrollToTopButton.tsx
> +  isLoading,
Кнопка прокрутки не может иметь состояния загрузки, так же как и не может быть заблокорована, она либо отображается, либо нет

2024-03-28 13:58 UTC, mfrolov89 commented on packages/components/src/ScrollToTopButton/styles.ts
> +export const ButtonWrapper = styled.div<{
Достаточно спозицицонировать саму кнопку, необходимости в обертки нет

2024-03-29 12:03 UTC, Kostayne commented on packages/components/src/ScrollToTopButton/ScrollToTopButton.tsx
> +  isLoading,
Deleted

2024-03-29 12:03 UTC, Kostayne commented on packages/components/src/ScrollToTopButton/ScrollToTopButton.stories.tsx
> +      <InnerWrapper ref={ref}>
Redesigned

2024-03-29 12:05 UTC, Kostayne commented
> 2. Нужно добавить импорт компонента из пакета

Скоро прилетит еще один коммит

2024-03-29 12:29 UTC, mfrolov89 requested changes

2024-03-29 12:29 UTC, mfrolov89 commented on packages/components/src/index.ts
> +export * from './ScrollToTopButton';
```suggestion
export { ScrollToTopButton, type ScrollToTopButtonProps }  from './ScrollToTopButton';
```

Пока еще нигде не зафиксировано, но для новых пакетов указываем явно экспортируемые сущности. Тем самым четко контролируем что экспортируется из пакета

2024-03-29 12:29 UTC, mfrolov89 commented on packages/components/src/ScrollToTopButton/ScrollToTopButton.tsx
> +export const ScrollToTopButton = ({ disabled, onClick }: ButtonProps) => {
создай тип и экспортируй его
Писал ранее что disabled для этой кнопки сомнителен, нет сценариев когда мы бы ее блокировали

2024-03-29 12:29 UTC, mfrolov89 commented on packages/components/src/ScrollToTopButton/ScrollToTopButton.tsx
> +  ${({ theme }) =>
давай придерживаться одного подхода при описании стилей под мобилу. 

Исходим из концепции desktop first, тему получаем из колбэка у каждого св-ва. Текущий вариант ухудшает восприятие

2024-03-31 21:22 UTC, mfrolov89 requested changes

2024-03-31 21:22 UTC, mfrolov89 commented on packages/components/src/ScrollToTopButton/ScrollToTopButton.tsx
> +export type ScrollToTopButtonProps = ButtonProps;
```suggestion
export type ScrollToTopButtonProps = Pick<ButtonProps, 'onClick'>;
```

2024-04-01 06:22 UTC, mfrolov89 approved these changes

2024-04-01 06:29 UTC, AndTem requested changes

2024-04-01 06:29 UTC, AndTem commented on packages/components/src/ScrollToTopButton/styles.ts
> +  bottom: 30px;
Все отступы через spacing

2024-04-01 06:31 UTC, Kostayne commented on packages/components/src/ScrollToTopButton/styles.ts
> +  bottom: 30px;
> Все отступы через spacing

Спейсинг кратен четырем, в дизайне стоит 30. Задача по дизайну уже создана, ждем резолва?

2024-04-01 09:51 UTC, AndTem approved these changes

2024-04-01 09:58 UTC, merged