feat(UIKIT-1355,ui,WelcomeScreen): Добавлен пропс autoStart, который запускает анимацию сразу при рендере
kaluga-astral/frontend pull request #895
Opened 2024-03-27 13:38 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-03-27 13:54 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.tsx
> +  autoStart?: boolean;
А isLoading === false и isError === false не являются признаком автостарта?

2024-03-27 13:55 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.tsx
> +  autoStart?: boolean;
Тест нужен

2024-03-27 13:57 UTC, Kostayne approved these changes

2024-03-27 14:16 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.tsx
> +  autoStart?: boolean;
Ну или может добавить флаг isSuccessLoadData?
Так будет более понятно потребителю

2024-03-27 14:38 UTC, mfrolov89 commented on packages/components/src/WelcomeScreen/WelcomeScreen.tsx
> +  autoStart?: boolean;
isError = false само собой является условием для запуска, так как флаг не говорит о том, что мы игнорируем ошибки. Мысли были такие, чтобы явно сказать, что компонент может запускаться сам после монтирования, без всяких loading.

Не топлю сильно против isSuccessLoadData, но увидя такой флаг, я бы мог только догадываться какие действия он выполняет и какую логику меняет в поведении. Вроде логично, что указав isSuccessLoadData = true, разработчики скорее всего заложили логику что анимация начнется сразу, но это тоже не очень очевидно.

В общем я не против поменять, но если у тебя есть сомнения, то можем еще подумать или провести мини опрос в тех.дирекции

2024-03-27 14:43 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.tsx
> +  autoStart?: boolean;
Я на это смотрю с такой позиции: показываем мы анимацию только после успешной загрузки данных.
Потребителю компонента все равно как оно там внутри работает, он и не должен этого знать (autoStart как будто как раз раскрывает механизм внутренний).
Также, через обязательный  isSuccessLoadData мы получаем полный контроль над UI паттерном в продуктах, а autoStart дает различные возмодности для костылей и кастома.

Если isSuccessLoadData при первом рендере true, то значит надо начинать анимацию

2024-03-27 14:44 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.tsx
> +  autoStart?: boolean;
У тебя сейчас баг в фичу превратился. А это ведь именно баг, непродуманный кейс

2024-03-27 14:46 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.tsx
> +  autoStart?: boolean;
Настаивать тут тоже не буду. Можешь обсудить с фронтами, которые используют компонент и принять самостоятельное решение

2024-03-28 06:37 UTC, AndTem requested changes

2024-03-28 06:37 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.tsx
> +   * Позволяет запускает анимацию сразу, применяется когда к моменту рендера компонента данные уже есть
Коммент про анимацию лишний

2024-03-28 06:37 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.stories.tsx
> +export const SuccessLoadData = () => {
У тебя сейчас поведение не изменилось исходной.
Если есть флаг isSucces, то именно на него надо подвязываться для показа анимации. А еще лучше его сделать required

2024-03-28 06:59 UTC, mfrolov89 commented on packages/components/src/WelcomeScreen/WelcomeScreen.stories.tsx
> +export const SuccessLoadData = () => {
флага isSuccess нет, иначе бы небыло смысла заводить isSuccessLoadDate, они ведь про одно и тоже. Изначально вектор был на то, чтобы добавить пропс, который бы игнорировал часть внутренних проверок. C флагом isSuccess тогда нужно переписывать большую часть логики. С одной стороны мне этот вариант нравится:: более понятное название, меньше логики в самом компоненте. Из минусов: это раздутие апи обязательными пропсами, во всех кейсах разработчикам придется чуть больше писать кода. Плюсы перевешивают все равно, переписываем всю реализацию?

2024-03-28 07:01 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.stories.tsx
> +export const SuccessLoadData = () => {
Если команда ЭДО готова к breaking changes, то да

2024-03-28 07:01 UTC, mfrolov89 commented on packages/components/src/WelcomeScreen/WelcomeScreen.stories.tsx
> +export const SuccessLoadData = () => {
И да, если вводим обязательный isSuccess, то это будет отображено в Example и этот пример с флагом можно удалять. Сейчас же этот пример имеет смысл, так как логика изменилась, анимация запускается сразу без лоадеров

2024-03-29 06:36 UTC, AndTem approved these changes

2024-03-29 06:41 UTC, merged