bug(UIKIT-1319,ui,Autocomplete): Placeholder теперь скрывается при выборе одной из опций
kaluga-astral/frontend pull request #899
Opened 2024-03-28 08:12 UTC by Kostayne

# Чеклист
- [X] Написать тесты для реализованного функционала

2024-03-28 12:51 UTC, AndTem requested changes

2024-03-28 12:51 UTC, AndTem commented on packages/components/src/Autocomplete/Autocomplete.tsx
> +  const handleOnChange = useCallback(
Если пользователь что-то изменил, то value изменится.
Считаю, что state тут вообще не нужен дополнительный, просто placeholder: restProps.value ? '' : placaholder

2024-03-28 12:51 UTC, AndTem commented on packages/components/src/WelcomeScreen/WelcomeScreen.stories.tsx
> +export const AutoStart = () => {
У тебя во всех PR лишние изменения. Пофикси

2024-03-28 12:52 UTC, AndTem requested changes

2024-03-29 08:30 UTC, Kostayne commented on packages/components/src/Autocomplete/Autocomplete.tsx
> +  const handleOnChange = useCallback(
Если убрать useState, то в storybook плейсхолдер останется, так что я бы все же оставил onChange.

2024-03-29 08:33 UTC, AndTem commented on packages/components/src/Autocomplete/Autocomplete.tsx
> +  const handleOnChange = useCallback(
В stroybook можно useState заюзать и будет все ок

2024-03-29 10:22 UTC, AndTem requested changes

2024-03-29 10:22 UTC, AndTem commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +  it('Плейсхолдер отображается при пустом списке options', async () => {
Связи между пустым список options и placeholder нет никакой.
Тест бесполезен

2024-03-29 10:22 UTC, AndTem commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +  it('Плейсхолдер не отображается, если выбрана одна из опций при multiple=true', async () => {
Обратный кейс тоже надо обработать

2024-03-29 10:22 UTC, AndTem commented on packages/components/src/Autocomplete/Autocomplete.stories.tsx
> +        getOptionLabel={(params) => params.title}
Давай сразк по style guide делать: https://kaluga-astral.github.io/style-guide/docs/rules/react/logic#%D0%B7%D0%B0%D0%BF%D1%80%D0%B5%D1%89%D0%B5%D0%BD%D0%B0-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%BE%D0%B2-%D0%B2-jsx

2024-03-29 10:29 UTC, Kostayne commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +  it('Плейсхолдер отображается при пустом списке options', async () => {
Окей, теперь буду смотреть имеют ли смысл тесты написанные до меня.

2024-04-01 05:38 UTC, AndTem requested changes

2024-04-01 05:38 UTC, AndTem commented on packages/components/src/Autocomplete/Autocomplete.stories.tsx
> +        getOptionLabel={(params) => params.title}
up

2024-04-01 05:38 UTC, AndTem commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +  it('Label сетится  в инпут после выбора option при multiple=false', async () => {
Точно label?

2024-04-01 05:38 UTC, AndTem commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +  it('Tag из инпута можно удалить при multiple=true', async () => {
Можешь сделать группировку по условию "при multiple=true"

2024-04-01 05:38 UTC, AndTem commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +  it('Ref правильно задается', () => {
Антипаттерн тестирования применяешь: https://industrious-search-cdf.notion.site/15e733a20ce04f7e84ad566e70a78f29#777f45da1132459ab51b6b66bb9a6f18

2024-04-01 05:38 UTC, AndTem commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +    await waitFor(() => {
Опять лишний код. Будь внимательней.
Подобные вещи тратят время в пустую на ревью

2024-04-01 06:26 UTC, mfrolov89 requested changes
Необходимо обновить ветку и решить конфликты. Ф-ция проверки значения на пустоту имеет другое название и реализацию

2024-04-01 10:26 UTC, mfrolov89 commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +  it('Tag из инпута можно удалить при multiple=true', async () => {
А насколько это соответствует текущему правилу с неймингом? Условие вроде как должно быть в конце. @AndTem

2024-04-01 11:10 UTC, Kostayne commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +  it('Tag из инпута можно удалить при multiple=true', async () => {
upvote

2024-04-01 12:08 UTC, AndTem commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +  it('Tag из инпута можно удалить при multiple=true', async () => {
https://industrious-search-cdf.notion.site/dac1e9ff807f4fa1a48150a0d609d530#54786c81e7bc4587ac6ba99c0e1f880b

2024-04-01 12:11 UTC, Kostayne commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +  it('Tag из инпута можно удалить при multiple=true', async () => {
Не понравилась читабельность тестов, решил оставить без группировки

2024-04-01 12:34 UTC, AndTem approved these changes

2024-04-02 06:55 UTC, mfrolov89 commented on packages/components/src/Autocomplete/Autocomplete.tsx
> +        placeholder: checkIsInputEmpty() ? placeholder : '',
по хорошему нет смысла в вызове одной и той же функции дважды, лучше вызвать один раз и записать результат в isInputEmpty. Саму функция  checkIsInputEmpty можно вынести в utils на уровне компонента Autocomplete. Функция в этом случаем должна принимать value. Почему так лучше сделать:
- уменьшения размера кода в компонента
- при каждом перерендере не будем заново создавать ф-цию

2024-04-02 06:58 UTC, mfrolov89 commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +  it('Value принимает значение label после выбора option', async () => {
Стоит поправить название теста
label это подпись к полю, как value может принять значение label?

2024-04-02 07:00 UTC, mfrolov89 commented on packages/components/src/Autocomplete/Autocomplete.test.tsx
> +    const paper = screen.getByTestId('customField');
может input?

2024-04-02 07:18 UTC, mfrolov89 approved these changes

2024-04-02 07:18 UTC, merged