bug(UIKIT-1357,ui,FeedbackPanel): Исправлена ошибка отображения FeedbackPanel
kaluga-astral/frontend pull request #900
Opened 2024-03-28 13:25 UTC by Krvknv

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-03-28 13:32 UTC, AndTem requested changes

2024-03-28 13:32 UTC, AndTem commented on packages/components/src/FeedbackPanel/FeedbackPanel.stories.tsx
> + *При использовании компонента вместе с модальными окнами, не забывайте добавлять им [disableEnforceFocus](https://mui.com/material-ui/react-modal/#focus-trap)
Надо создать отдельную story с жтим описание и демоснтарцией

2024-03-28 13:38 UTC, mfrolov89 commented on packages/components/src/FeedbackPanel/FeedbackPanel.stories.tsx
> + *При использовании компонента вместе с модальными окнами, не забывайте добавлять им [disableEnforceFocus](https://mui.com/material-ui/react-modal/#focus-trap)
А как этот компонент может быть использован вместе с модалкой?

2024-03-28 13:40 UTC, Krvknv commented on packages/components/src/FeedbackPanel/FeedbackPanel.stories.tsx
> + *При использовании компонента вместе с модальными окнами, не забывайте добавлять им [disableEnforceFocus](https://mui.com/material-ui/react-modal/#focus-trap)
если открыт SideDialog, и необходимо открыть окно обратной связи

2024-03-28 13:59 UTC, mfrolov89 commented on packages/components/src/FeedbackPanel/FeedbackPanel.stories.tsx
> + *При использовании компонента вместе с модальными окнами, не забывайте добавлять им [disableEnforceFocus](https://mui.com/material-ui/react-modal/#focus-trap)
Понял, тогда соглашусь что можно описать отдельную сторю WithSideDialog и перед ней указать этот комментарий

2024-03-29 11:28 UTC, mfrolov89 approved these changes

2024-03-29 11:52 UTC, merged