bug(UIKIT-1317,ui,MenuItem): Изменен вертикальный padding
kaluga-astral/frontend pull request #906
Opened 2024-04-03 12:29 UTC by Kostayne

# Чеклист
- [X] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2024-04-03 14:06 UTC, AndTem commented on packages/components/src/MenuItem/MenuItem.tsx
> +type MuiMenuItemT = typeof MuiMenuItem;
А в чем проблема? styled по идеии сам typeof возьмет

2024-04-03 14:07 UTC, mfrolov89 commented on packages/components/src/MenuItem/styles.ts
> +  padding-top: ${({ theme }) => theme.spacing(1)};
MenuItem сейчас стилизован через переопределение стилей styleOverrides в theme, стоит почти все правки сделать там, кроме max-Height, чтобы что-то не сломать

2024-04-03 14:09 UTC, Kostayne commented on packages/components/src/MenuItem/MenuItem.tsx
> +type MuiMenuItemT = typeof MuiMenuItem;
Изначально думал так же, но компилятор говорит что типы не совпадают, наименее костыльным тут был каст к типу

2024-04-05 09:46 UTC, mfrolov89 commented on packages/components/src/MenuItem/styles.ts
> +  max-height: ${({ theme }) => theme.spacing(13)};
Подумал и считаю что  max-height стоит указать непосредственно на уровне автокомплита. Применение компонента MenuItem достаточно обширное и могут быть кейсы, где содержимого больше и этой высоты не хватит

2024-04-05 12:19 UTC, mfrolov89 requested changes

2024-04-05 12:19 UTC, mfrolov89 commented on packages/components/src/MenuItem/MenuItem.tsx
> +import { MenuItem as MuiMenuItem } from '@mui/material';
откати правки, через один импорт из '@mui/material' все получаем

2024-04-05 13:20 UTC, mfrolov89 approved these changes

2024-04-05 13:37 UTC, merged