feat(UIKIT-1280,ui,MenuItem): Добавлен тултип для заблокированных элементов
kaluga-astral/frontend pull request #910
Opened 2024-04-04 14:10 UTC by Cabagemage

…ванных элементов

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-04-17 10:45 UTC, mfrolov89 requested changes
Стоит добавить в сторибук для MenuItem кейс с disabled

2024-05-07 07:11 UTC, mfrolov89 requested changes

2024-05-07 07:11 UTC, mfrolov89 commented on packages/components/src/MenuItem/MenuItem.tsx
> +     * Тип html-элемента
может быть и компонент, а не только html-элемент

2024-05-07 07:11 UTC, mfrolov89 commented on packages/components/src/MenuItem/MenuItem.tsx
> +     * Текст тултипа при заблокированном состоянии тултипа
```suggestion
     * Текст тултипа при заблокированном состоянии 
```

2024-05-07 07:11 UTC, mfrolov89 commented on packages/components/src/MenuItem/MenuItem.tsx
> +     * Текст тултипа при заблокированном состоянии тултипа
Заблокирован MenuItem, а по тексту написано что тултип

2024-05-07 10:35 UTC, mfrolov89 approved these changes

2024-05-07 10:39 UTC, Kostayne approved these changes

2024-05-15 13:52 UTC, merged