feat(UIKIT-1076,ui,Description): Добавлена возможность копирования текста
kaluga-astral/frontend pull request #913
Opened 2024-04-08 13:51 UTC by Kostayne

# Чеклист

- [X] Написать тесты для реализованного функционала
- [X] Реализовать или обновить storybook для компонента
- [X] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2024-04-09 08:54 UTC, mfrolov89 requested changes
1. Иконка должна быть частью строки, ховер должен срабатывать при наведении на эту строку, сейчас у тебя текст отдельно, иконка отдельно
2. При наведении у текста должно быть подчеркивание
3. Курсор должен менять состояние на pointer
4. Отступ между иконкой и текстом не соответсвует макету

2024-04-09 09:43 UTC, mfrolov89 requested changes

2024-04-09 09:43 UTC, mfrolov89 commented on packages/icons/generated-themed-icons/CopyOutlineSm.tsx
> +import { forwardRef } from 'react';
forwardRef на уровне иконок не используется. Можешь отдельно оформить как инициативу

2024-04-09 09:43 UTC, mfrolov89 commented on packages/components/src/Description/Value/styles.ts
> +  flex-direction: ${(props) =>
деструктурируй сразу и добавь в название пропса симовол $, чтобы в dom не попадало как св-во

2024-04-10 09:48 UTC, mfrolov89 requested changes

2024-04-10 09:48 UTC, mfrolov89 commented on packages/components/src/Description/Value/styles.ts
> +  margin-right: ${({ $copyPosition, theme }) =>
Перенеси это правило ниже, чтобы  margin-left и margin-right были под твоим комментарием: /* Добавляем горизонтальный отступ от текста */

2024-04-10 09:48 UTC, mfrolov89 commented on packages/components/src/Description/Description.stories.tsx
> +export const CanCopyLongText = () => {
кейс кажется лишним + кол-ва символов все равно не хватает для переполнения. Думаю стоит поправить другие примеры (Example, Can Copy) где есть "Длинное значение поля", увеличив там там текст, чтобы произошло переполнение

2024-04-10 09:48 UTC, mfrolov89 commented on packages/components/src/Description/Description.stories.tsx
> +        <Description.Name>Название поля</Description.Name>
Раз этот пример про позиционирование, то стоит отобразить и дефолтный вариант

2024-04-10 09:48 UTC, mfrolov89 commented on packages/components/src/Description/Description.stories.tsx
> +export const JustifyContentCanCopy = () => {
```suggestion
export const JustifyContentWithCanCopy = () => {
```

либо можно показать этот пример в рамках  JustifyContent, тут на твое усмотрение

2024-04-10 09:48 UTC, mfrolov89 commented on packages/components/src/Description/Value/Value.tsx
> +    navigator.clipboard.writeText(children?.toString() || '');
возвращает промис, в случае резолва нужно устанавливать  setCopied(true), если произошла ошибка, то стоит в тултипе вывести соответствующий текст, наприме: "не удалось скопировать"

2024-04-10 09:48 UTC, mfrolov89 commented on packages/components/src/Description/Value/Value.tsx
> +      <StyledText {...props}>
```suggestion
      <StyledTypography {...props}>
```

В данном случае думаю лучше назвать компонент так, тогда становится понятно что за пропсы он может принимать

2024-04-10 09:48 UTC, mfrolov89 commented on packages/components/src/Description/Value/styles.ts
> +  font-size: ${({ theme }) => theme.spacing(4)};
возможно стоит указать через фиксированную высоту, а не через font-size с использование spacing. Spacing может измениться, но это не означает что размер иконки тоже должен измениться

2024-04-10 09:51 UTC, Kostayne commented on packages/components/src/Description/Description.stories.tsx
> +export const CanCopyLongText = () => {
Это скорее для локального теста в пределах pr, планирую убрать его перед мерджем

2024-04-10 12:15 UTC, mfrolov89 requested changes

2024-04-10 14:40 UTC, mfrolov89 approved these changes

2024-04-11 07:51 UTC, merged