test(UIKIT-1215,ui,Tag,CheckableTag): Расширены тесты для компонентов
kaluga-astral/frontend pull request #915
Opened 2024-04-09 06:34 UTC by Mayamee

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2024-04-10 11:36 UTC, Kostayne requested changes

2024-04-10 11:36 UTC, Kostayne commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +  it('Компонент получает checked состояние при передаче checked=true через props', () => {
Можно упростить до "Чекбокс отмечается при checked=true"

2024-04-10 11:36 UTC, Kostayne commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +    const sut = <CheckableTag ref={callbackRefSpy} />;
Мы не именуем компоненты как sut в тестах

2024-04-10 11:36 UTC, Kostayne commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +    const sutNode = screen.getByRole('checkbox', { hidden: true });
sutNode => checkbox | checkboxElement

2024-04-10 11:36 UTC, Kostayne commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +    const addonNode = screen.getByTestId(addonTestId);
same, Node => Element

2024-04-10 11:36 UTC, Kostayne commented on packages/components/src/Tag/Tag.test.tsx
> +  it('Rest props перенаправляются в DOM node компонента', () => {
Rest props передаются в аттрибуты DOM элемента

2024-04-10 11:36 UTC, Kostayne commented on packages/components/src/Tag/Tag.test.tsx
> +  it('Возможно передать кастомную иконку удаления при переданном обработчике onDelete', () => {
Кастомная иконка отображается при переданном пропсе onDelete

2024-04-10 11:39 UTC, mfrolov89 requested changes

2024-04-10 11:39 UTC, mfrolov89 commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +  it('Компонент получает checked состояние при передаче checked=true через props', () => {
```suggestion
  it('Компонент получает checked состояние если checked=true', () => {
```

Так будет короче, смысл не потерялся

2024-04-10 11:39 UTC, mfrolov89 commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +  it('Дополнительные компоненты получают checked prop при передаче checked=true через props', () => {
Стоит удалить везде приписку 'через props', не несет в себе большой пользы

2024-04-10 11:39 UTC, mfrolov89 commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +  it('Дополнительные компоненты получают disabled prop при передаче disabled=true через props', () => {
Необходимо проверить, что элемент не доступен для взаимодействия, если disabled=true

2024-04-10 11:39 UTC, mfrolov89 commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +    const sutNode = screen.getByRole('checkbox', { hidden: true });
Для остальных мест тоже стоит поправить по аналогии, указав что за элемент мы получаем

2024-04-10 11:39 UTC, mfrolov89 commented on packages/components/src/CheckableTag/styles.ts
> +export const StyledLabel = styled.label`
Название не корректно, префикс styled используем, если стилизуем какой-то компонент, пример:
export const StyleButton = styled(Button)`


https://kaluga-astral.github.io/style-guide/docs/rules/react/styled

2024-04-10 11:39 UTC, mfrolov89 commented on packages/components/src/Tag/Tag.test.tsx
> +  it('Rest props перенаправляются в DOM node компонента', () => {
Абстрактный кейс, непонятно что мы тестируем в конечном счете

2024-04-10 11:39 UTC, mfrolov89 commented on packages/components/src/Tag/Tag.test.tsx
> +  it('Возможно передать кастомную иконку удаления при переданном обработчике onDelete', () => {
```suggestion
  it('Кастомная иконка удаления отображается при ...', () => {
```

2024-04-10 11:39 UTC, mfrolov89 commented on tests/src/index.ts
> +export * from 'vitest';
не относится к задаче

2024-04-12 13:08 UTC, Mayamee commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +  it('Дополнительные компоненты получают disabled prop при передаче disabled=true через props', () => {
Что имеется ввиду, дополнительный или основной компонент?

2024-04-12 13:40 UTC, Mayamee commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +  it('Дополнительные компоненты получают disabled prop при передаче disabled=true через props', () => {
> Необходимо проверить, что элемент не доступен для взаимодействия, если disabled=true

Что имеется ввиду, дополнительный или основной компонент?

2024-04-17 11:05 UTC, Kostayne requested changes

2024-04-18 06:45 UTC, Mayamee commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +    const handleChangeSpy = vi.fn();
Передаваемые обработчики мы помечаем с префиксом handle
https://kaluga-astral.github.io/style-guide/docs/rules/react/logic#%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%B8-%D1%81-%D0%BF%D1%80%D0%B5%D1%84%D0%B8%D0%BA%D1%81%D0%BE%D0%BC-handle

2024-04-18 07:02 UTC, mfrolov89 commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +    const handleChangeSpy = vi.fn();
Это правило для react, для тестов название начинается с on и имеет посфикс Spy
https://kaluga-astral.github.io/style-guide/docs/rules/tests/test-double (смотри в самом низу)

2024-04-18 10:36 UTC, Kostayne approved these changes

2024-04-19 07:37 UTC, mfrolov89 requested changes

2024-04-19 07:37 UTC, mfrolov89 commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +  it('OnDelete не вызывается при нажатии на иконку удаления, при disabled=true', async () => {
Этот тест не нужен, кнопки удаления не должно быть для этого компонента, вероятна случайно перетекла из базового тега. Она даже отрабатывает не корректно: не блокирует всплытие, в результате чего происходит нажатие и на сам тег.
Создам инициативу чтобы убрать эти пропсы

2024-04-19 07:37 UTC, mfrolov89 commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +  it('Чекбокс получает состояние disabled, если disabled=true', () => {
```suggestion
  it('Тег не доступен для взаимодействия, если disabled=true', () => {
```

2024-04-19 07:37 UTC, mfrolov89 commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +  it('OnChange не вызывается при нажатии на тег, при disabled=true', async () => {
По сути дублирует тест выше, где проверяешь что expect(checkbox).toBeDisabled();

2024-04-19 07:37 UTC, mfrolov89 commented on packages/components/src/CheckableTag/CheckableTag.test.tsx
> +  it('Вложенный компонент отображается при передаче через startAddon', () => {
Предлагаю сгруппирвоать эти 2 теста в describe: 'Вложенный компонент отображается'

2024-04-19 07:37 UTC, mfrolov89 commented on tests/src/constants.ts
> +export const CHECK_INTERACTION_REGEXP = /pointer-events: none/;
Это отдельный пакет, если считаешь что нужно добавить такую константу, то оформи как инициативу и отдельно на грумминге обсудим. Сейчас это нужно удалить

2024-04-19 07:37 UTC, mfrolov89 commented on packages/components/src/Tag/Tag.test.tsx
> +  it('Дополнительный контент отображается, если передан startAddon', () => {
describe "Дополнительный контент отображается"

2024-04-19 07:37 UTC, mfrolov89 commented on packages/components/src/Tag/Tag.test.tsx
> +  it('OnClick не вызывается при нажатии на тег, если disabled=true', async () => {
Замени на тест, что элемент не доступен для взаимодействия, если  disabled=true

2024-04-19 07:40 UTC, AndTem commented on tests/src/constants.ts
> +export const CHECK_INTERACTION_REGEXP = /pointer-events: none/;
Этот пакет не публичный, поэтому можно вносить правки, если необходимо

2024-04-19 07:41 UTC, AndTem commented on packages/components/src/Tag/Tag.test.tsx
> +  it('OnClick не вызывается при нажатии на тег, если disabled=true', async () => {
Странный тест. Просто проверки на toBeDisbled было бы достаточно

2024-04-23 06:05 UTC, Mayamee commented on packages/components/src/Tag/Tag.test.tsx
> +  it('OnClick не вызывается при нажатии на тег, если disabled=true', async () => {
> Странный тест. Просто проверки на toBeDisbled было бы достаточно
У элемента тега нет элемента который мог бы быть с атрибутом disabled, там навешивается pointer-events: none через CSS класс .Mui-disabled

2024-04-23 11:54 UTC, Mayamee commented on packages/components/src/Tag/Tag.test.tsx
> +  it('OnClick не вызывается при нажатии на тег, если disabled=true', async () => {
> Замени на тест, что элемент не доступен для взаимодействия, если disabled=true

Заменил название на:
Тег не доступен для взаимодействия, если disabled=true

2024-04-23 12:27 UTC, merged