feat(UIKIT-1196): Реализован генератор changelog для shared-пакетов
kaluga-astral/frontend pull request #918
Opened 2024-04-10 12:41 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-04-11 05:57 UTC, AndTem requested changes

2024-04-11 05:57 UTC, AndTem commented on changelog-generator/src/index.js
> +const gitlog = require('gitlog').default;
Много логики в генераторе.
Считаю, что должен использоваться ts

2024-04-11 05:57 UTC, AndTem commented on changelog-generator/src/index.js
index файлы используются тольо импорта, экспорта.
Надо переименовать в main, например

2024-04-11 05:57 UTC, AndTem commented on changelog-generator/src/config.js
> +const JIRA_URL = 'https://track.astral.ru/soft/browse/';
Делаем правильно и храним такое в секретах и env

2024-04-11 05:57 UTC, AndTem commented on changelog-generator/src/config.js
> +const CHANGELOG_DIR_PATH = '../changelog';
Странный path (отнсительно чего он?) + символ / только для linux подобных систем работает, надо всегда использовать path.join|path.resolve

2024-04-11 05:57 UTC, AndTem commented on changelog-generator/src/config.js
> +const PERIOD_IN_DAYS = 14;
jsdoc нужен

2024-04-11 05:57 UTC, AndTem commented on changelog-generator/src/utils/parse.js
> +const parseCommit = ({ tag, subject }) => {
Экспортируется parseCommit, а файл называется parse. Это странно

2024-04-11 05:57 UTC, AndTem commented on changelog-generator/src/utils/parse.js
> +const parseCommit = ({ tag, subject }) => {
Тест написать бы. А то потом придется много времени тратить на поддержку

2024-04-11 05:57 UTC, AndTem commented on changelog-generator/src/utils/date.js
Для каждого файла должна быть своя директория с индекс файлом (в style guide не вижу правила, потерялось при миграции)

2024-04-11 05:57 UTC, AndTem commented on changelog-generator/src/services/fileService.js
Для каждого сервис должна быть своя директория и с большой буквы надо называть

2024-04-11 05:57 UTC, AndTem commented on changelog-generator/src/services/fileService.js
> +        console.error('Ошибка при записи файла:', error);
Так, ты законсолил ошибку, а дальше что?
throw error надо делать, не?

2024-04-11 05:57 UTC, AndTem commented on changelog-generator/src/services/markdownService.js
> +/* eslint-disable no-underscore-dangle */
Это правило не просто так включено. Используй private вместо _

2024-04-11 05:57 UTC, AndTem commented on changelog-generator/src/services/telegramService.js
> +module.exports = { TelegramService };
Пустота

2024-04-11 05:57 UTC, AndTem commented on changelog-generator/src/index.js
> +  GROUP_HEADERS,
Мне кажется, что эту константу можно инкапсулироват внутрь MarkdownService

2024-04-11 05:57 UTC, AndTem commented on changelog-generator/src/index.js
> +const results = gitlog({
Ты вынес работу с markdown в сервис, тогда надо сделать тоже самое и для работы с git

2024-04-11 06:28 UTC, mfrolov89 commented on changelog-generator/src/services/telegramService.js
> +module.exports = { TelegramService };
В начале планировалось сразу сделать еще и отправку сообщения в телегу, но сейчас это вынесено в отдульную задачу, оставил как заглушку, потому что следующую задачу возьму в ближайшее время. Можно конечно пока и удалить или оставить коммент, но врядли сюда кто-то полезет кроме меня

2024-04-11 06:29 UTC, mfrolov89 commented on changelog-generator/src/index.js
> +  GROUP_HEADERS,
Она понадобится для генерации сообщения в телеге

2024-04-16 14:01 UTC, AndTem requested changes

2024-04-16 14:02 UTC, AndTem commented
Еще не хватает README и инфы в CONTRIBUTING.md (возможно, в других PR)

2024-04-16 14:02 UTC, AndTem commented
Название PR должно быть chore, иначе будет релиз

2024-04-16 14:39 UTC, mfrolov89 commented on changelog-generator/src/main.ts
> +const filteredParseResults = results.filter((commit) => {
Не стал перемещать, так как правила фильтрации могут меняться по разным причинам, задача GitService вернуть все коммиты в определенном формате, а какие из них нам использовать это не совсем его зона ответственности

2024-04-16 14:41 UTC, mfrolov89 commented on changelog-generator/src/main.ts
> +const lastCommitWithVersion = filteredParseResults.find((commit) =>
думал об этом, но так как он завязан на filteredParseResults не вышло. По filteredParseResults отписал выше.

2024-04-16 14:42 UTC, mfrolov89 commented on changelog-generator/src/services/GitService/GitService.ts
> +    console.log('startDate', startDate, typeof startDate);
упустил консольки =( сейчас поправим

2024-04-17 06:01 UTC, AndTem approved these changes

2024-04-17 06:41 UTC, merged