feat(UIKIT-1076,ui,Placeholder): Стандартизирован размер Placeholder'а
kaluga-astral/frontend pull request #922
Opened 2024-04-11 10:12 UTC by Kostayne

Добавлен prop size, imgWidth & imgHeight теперь deprecated.

# Чеклист
- [X] Описать jsdoc для props экспортируемых компонентов
- [X] Реализовать или обновить storybook для компонента
- [X] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2024-04-11 13:38 UTC, mfrolov89 requested changes

2024-04-11 13:38 UTC, mfrolov89 commented on packages/components/src/Placeholder/Placeholder.tsx
> +type PlaceholderSize = 'sm' | 'md' | 'lg';
Пропиши полные названия: small, large, medium

2024-04-11 13:38 UTC, mfrolov89 commented on packages/components/src/Placeholder/Placeholder.tsx
> +  size = 'md',
в стилях до этого все было задано под small размер, поэтому стоит и указать его по умолчанию, чтобы на продуктах не заметили изменений

2024-04-11 13:38 UTC, mfrolov89 commented on packages/components/src/Placeholder/Placeholder.tsx
> +    switch (size) {
Определи enum  с размерами, далее стоит организовать констаны с параметрами, например
const IMAGE_HEIGHT = {
    [SizeType.Small]: '239px',
    ...
  }
  
  Получается что константы будут точкой для конфигурации.
  
 Все утилы стоит вынести в отдельный файл

2024-04-11 13:38 UTC, mfrolov89 commented on packages/components/src/Placeholder/styles.ts
> +    switch ($size) {
таких конструкций в стилях быть не должно, вынеси в utils.

2024-04-11 13:38 UTC, mfrolov89 commented on packages/components/src/Placeholder/Placeholder.stories.tsx
> +
Добавь дополнительные отступы между компонентами, хотя бы через br, сейчас они очень сильно слеплены друг с другом в сторибуке, не очень удобно смотреть

2024-04-11 14:31 UTC, Kostayne commented
В стилях enum'ы конечно вообще не смотрятся

2024-04-12 06:29 UTC, mfrolov89 commented on packages/components/src/Placeholder/Placeholder.tsx
> +   * Задает общий размер компонента (sm, md, lg)
удали еденицы, тем более что они не верны

2024-04-12 06:35 UTC, mfrolov89 commented on packages/components/src/Placeholder/constants.ts
> +};
```suggestion
} as const;
```
Тогда не нужно будет делать сдезт приведение
 <Title $size={size} variant={TITLE_HEADER_LEVEL[size] as 'h5'}>

2024-04-12 06:40 UTC, mfrolov89 requested changes

2024-04-12 06:40 UTC, mfrolov89 commented on packages/components/src/Placeholder/Placeholder.tsx
> +  // писать size={'small' as PlaceholderProps[size]}
Может тогда записать через константу? Выведешь union на ее основе и проблем с типами тогда не будет

2024-04-12 07:46 UTC, mfrolov89 requested changes

2024-04-12 07:46 UTC, mfrolov89 commented on packages/components/src/Placeholder/Placeholder.tsx
> +  const size = Size[externalSize as keyof typeof Size];
это не работает

2024-04-12 08:56 UTC, mfrolov89 approved these changes

2024-04-12 09:00 UTC, merged