Feat/UI kit 1166
kaluga-astral/frontend pull request #931
Opened 2024-04-24 12:38 UTC by Kostayne

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [X] Описать jsdoc для экспортируемых функций, компонентов
- [X] Описать jsdoc для props экспортируемых компонентов
- [X] Реализовать или обновить storybook для компонента
- [X] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-04-25 08:43 UTC, mfrolov89 requested changes
Отсутствует общий сброс для селекта

2024-04-25 08:43 UTC, mfrolov89 commented on packages/components/src/Select/SelectTagsList/hooks/useLogic/useLogic.ts
> +    const computeOverflow = (el: HTMLDivElement) => {
вынеси из recomputeMaxItems, усложняет чтение кода

2024-04-25 08:43 UTC, mfrolov89 commented on packages/components/src/Select/SelectTagsList/hooks/useLogic/useLogic.ts
> +      .map((c) => c.getBoundingClientRect().width)
```suggestion
      .map((child) => child.getBoundingClientRect().width)
```

2024-04-25 08:43 UTC, mfrolov89 commented on packages/components/src/Select/SelectTagsList/hooks/useLogic/useLogic.ts
> +    const containerStyles = window.getComputedStyle(containerEl);
могут быть проблемы при ssr, объект window будет не доступен

2024-04-25 08:43 UTC, mfrolov89 commented on packages/components/src/Select/SelectTagsList/hooks/useLogic/useLogic.ts
> +    return { label, shrinks, onMouseDown };
почему не onDelete возвращается?

2024-04-25 08:43 UTC, mfrolov89 commented on packages/components/src/Select/SelectTagsList/hooks/useLogic/useLogic.ts
> +    // Кликнули по кнопке удаления
Считаю что нужно пробрасывать onDelete, текущая логика не надежна, хотя пропс и называется deleteIcon, но при желании туда можно прокинуть и текст, например "x"

2024-04-25 08:43 UTC, mfrolov89 commented on packages/components/src/Select/SelectTagsList/hooks/useLogic/useLogic.ts
> +    const observer = new ResizeObserver(() => {
можно сразу деструктурировать

2024-04-25 08:43 UTC, mfrolov89 commented on packages/components/src/Select/SelectTagsList/hooks/useLogic/useLogic.ts
> +    return () => {
return disconect;
Так не лучше?

2024-04-25 08:43 UTC, mfrolov89 commented on packages/components/src/Select/SelectTagsList/hooks/useLogic/useLogic.ts
> +  const recomputeMaxItems = () => {
думаю нужно зарефакторить функцию, разбить ее на логические еденицы

2024-04-25 08:43 UTC, mfrolov89 commented on packages/components/src/Select/SelectTagsList/SelectTagsList.tsx
> +  const { maxItems, tagsContainerRef, getTagProps } = useLogic({
useLogic может возвращать массив тегов для отображения и кол-во скрытых тегов, тогда абсолютно вся логика будет инкапсулирована в хуке

2024-04-25 08:43 UTC, mfrolov89 commented on packages/components/src/Select/SelectTagsList/SelectTag/SelectTag.tsx
> +  label: string | number;
Базовые пропсы тега стоит pick'нуть

2024-04-25 08:43 UTC, mfrolov89 commented on packages/components/src/Select/SelectTagsList/SelectTag/SelectTag.tsx
> +  onMouseDown?: (e: MouseEvent<HTMLDivElement>) => void;
для удаления тега должен быть onDelete

2024-04-25 09:06 UTC, Kostayne commented on packages/components/src/Select/SelectTagsList/hooks/useLogic/useLogic.ts
> +  const [maxItems, setMaxItems] = useState(50);
заменить на selectOptions.length

2024-04-25 13:57 UTC, Kostayne commented on packages/components/src/Select/SelectTagsList/hooks/useLogic/useLogic.ts
> +    return () => {
вылетит exception, не вариант

2024-04-25 13:59 UTC, Kostayne commented on packages/components/src/Select/SelectTagsList/SelectTag/SelectTag.tsx
> +  onMouseDown?: (e: MouseEvent<HTMLDivElement>) => void;
не вариант, хендлер обрабатывает исключительно mouseDown, onDelete здесь будет неправильным именем

2024-04-25 14:25 UTC, Kostayne commented on packages/components/src/Select/SelectTagsList/hooks/useLogic/useLogic.ts
> +    const containerStyles = window.getComputedStyle(containerEl);
Nextjs не даст компоненту отрендерится на сервере если он использует useLayoutEffect, но на всякий оставил проверки в коде

2024-05-03 09:01 UTC, mfrolov89 requested changes

2024-05-03 09:01 UTC, mfrolov89 commented on packages/components/src/Select/SelectTagsList/SelectTag/SelectTag.tsx
> +      onDelete={handleDelete}
Попробуй использовать onDelete для удаления тега. Для этого для onMouseDown нужно указать preventDefault. Тогда onDelete начинает отрабатывать как положено. Но тут возникает проблема с дальнейшим всплытием и при нажатии на тег не раскрывается селект. Для решения этой проблемы можно отслеживать onClick, он будет вызываться только при нажатии на тело тега. Нужно только на onClick организовать раскрытие списка селекта. Всю внутреннюю логику с проверкой на какой элемент произошло нажатие, которая не очень надежна, можно будет удалить

2024-05-03 09:04 UTC, Kostayne commented on packages/components/src/Select/hooks/useLogic.ts
> +  const isNoData = !Boolean(Children.count(children));
этот код был перенесен из компонента и  написан не мной, думаю такие изменения лучше выносить в отдельный таск

2024-05-03 09:06 UTC, Kostayne commented on packages/components/src/Select/hooks/useLogic.ts
> +  const isShowingClearButton = Array.isArray(value) && value.length > 0;
я с этим согласен, но кнопка появилась только при таске на multiple вариант, поэтому решил поставить доп чек, если расширяем на все кейсы, то могу этот чек убрать

2024-05-07 07:50 UTC, mfrolov89 commented on packages/components/src/Select/SelectTagsList/SelectTag/hooks/useLogic/index.ts
> +export * from './useLogic';
useLogic нужно вынести из hooks

https://kaluga-astral.github.io/style-guide/docs/rules/arch/modules/features/logic-hook#%D1%85%D1%83%D0%BA-%D1%81-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BA%D0%BE%D0%B9-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0-%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD-%D0%B8%D0%BC%D0%B5%D1%82%D1%8C-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-uselogic-%D0%B8-%D0%BD%D0%B0%D1%85%D0%BE%D0%B4%D0%B8%D1%82%D1%81%D1%8F-%D0%B2-%D0%BE%D1%82%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9-%D0%B4%D0%B8%D1%80%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%B8

2024-05-07 08:06 UTC, mfrolov89 commented on packages/components/src/Select/styles.ts
> +  width: ${CLEAR_BUTTON_SIZE}px;
зачем тут размеры? кнопка при size="medium" имеет нужные размеры

2024-05-07 08:15 UTC, Kostayne commented on packages/components/src/Select/styles.ts
> +  width: ${CLEAR_BUTTON_SIZE}px;
Это нужно для точной синхронизации с логикой расчета свободного места

2024-05-08 08:34 UTC, mfrolov89 commented on packages/components/src/Select/SelectTagsList/styles.ts
> +  padding-right: ${CLEAR_BUTTON_SIZE}px;
если это единственное место использования константы, то не вижу в ней смысла, явно через spacing указать отступ

2024-05-08 08:38 UTC, mfrolov89 commented on packages/components/src/Select/styles.ts
> +  svg {
Все таки стоит использовать CloseFillSm

2024-05-08 09:58 UTC, mfrolov89 approved these changes

2024-05-13 09:27 UTC, merged