feat(UIKIT-546, NotificationStackContainer): Реализован стек уведомлений
kaluga-astral/frontend pull request #939
Opened 2024-05-02 14:27 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-05-02 14:41 UTC, AndTem commented
Замечания по UI:
- Надо сделать так, чтобы в свернутом стэке отображалось только 3 уведомления (любая цифра). А то сейчас такая картина:
<img width="478" alt="Снимок экрана 2024-05-02 в 17 33 02" src="https://github.com/kaluga-astral/frontend/assets/23665108/d9927bd9-a685-44ab-a9a3-5b7b7b712462">
- При нажатии на крестик в развернутом стэке слишко на долгое время остается "дырка"
- Надо сделать так, чтобы при ховере на кнопку "Скрыть все" стэк не скрывался
- Сейчас при клике на кнопку "Скрыть все" сначала уезжают уведомления или только после некоторого времени кнопка. Надо чтобы вместе
- Считаю, что анимация закрытия по крестику уведомдения должна совпадать с классической анимацией. Сейчас по нажатию на крестик уведомления уезжает вверх, а должны в бок
- Анимация появления текста в высоком уведомлении не синхронизирована с увеличением высота. Сначала стжк раскрывается и увеличивается высота и потом с задержкой появляется контент
- В большом стэке скролл начинается не снизу
<img width="464" alt="Снимок экрана 2024-05-02 в 17 41 22" src="https://github.com/kaluga-astral/frontend/assets/23665108/8e29aba1-306a-4ed2-bafd-4be342436952">

2024-05-02 14:44 UTC, AndTem commented
У уведомлений как будто таймер оставновился (progress не до конца доехал)
<img width="444" alt="Снимок экрана 2024-05-02 в 17 43 38" src="https://github.com/kaluga-astral/frontend/assets/23665108/ddff8b2f-040c-458e-867f-35c10138bea9">

2024-05-02 14:45 UTC, AndTem commented
Думаю, для контйенера со скроллом нужен отступ, чтобы не склеивалась кнопка и карточки
<img width="224" alt="Снимок экрана 2024-05-02 в 17 45 03" src="https://github.com/kaluga-astral/frontend/assets/23665108/163e0528-8032-40a5-8e3b-e5d524ca323c">

2024-05-02 14:54 UTC, mfrolov89 commented
> * Сейчас при клике на кнопку "Скрыть все" сначала уезжают уведомления и только после некоторого времени кнопка. Надо чтобы вместе

Не уверен что получится что-то сделать, там c задержкой вызывается onChange при удалении, соответсвенно мы н сразу узнаем что уведомлений больше нет. Такая проблема была и при использовании хука, для получения кол-ва уведомлений, работает так же с задержкой

2024-05-02 14:58 UTC, mfrolov89 commented
> * При нажатии на крестик в развернутом стэке слишко на долгое время остается "дырка"

Время задержки такое же как и без стека, там аналогичное поведение. Если только пробовать для всех сразу уведомлений это настроить

2024-05-02 15:01 UTC, mfrolov89 commented
> * Надо сделать так, чтобы при ховере на кнопку "Скрыть все" стэк не скрывался

Обсуждал с Владом этот момент, он подтвердил что кнопка не должна участвовать в раскрытии/скрытии стека. Там у каждого варианта свои плюсы и минусы. Если ховер на наведении на кнопку не скрывал стек, то наведение на кнопку будет тригерить разворачивание стека, что вероятно не всегда нужно. Например я просто хочу закрыть все уведомления, а у меня развернется список.

2024-05-02 15:04 UTC, AndTem commented
> > * Надо сделать так, чтобы при ховере на кнопку "Скрыть все" стэк не скрывался
> 
> 
> 
> Обсуждал с Владом этот момент, он подтвердил что кнопка не должна участвовать в раскрытии/скрытии стека. Там у каждого варианта свои плюсы и минусы. Если ховер на наведении на кнопку не скрывал стек, то наведение на кнопку будет тригерить разворачивание стека, что вероятно не всегда нужно. Например я просто хочу закрыть все уведомления, а у меня развернется список.

Речь только про скрытие

2024-05-02 15:05 UTC, mfrolov89 commented
> У уведомлений как будто таймер оставновился (progress не до конца доехал)

При ховере таймеры всех уведомлений останавливаются + я еще забыл скорее всего вернуть нормальное время показа, устанавливал большее для тестов

2024-05-02 15:05 UTC, AndTem commented
> > * Сейчас при клике на кнопку "Скрыть все" сначала уезжают уведомления и только после некоторого времени кнопка. Надо чтобы вместе
> 
> 
> 
> Не уверен что получится что-то сделать, там c задержкой вызывается onChange при удалении, соответсвенно мы н сразу узнаем что уведомлений больше нет. Такая проблема была и при использовании хука, для получения кол-ва уведомлений, работает так же с задержкой

А ты на onclick кнопки подвяжись и тайм-ауты подгони (можно fade для кнопки сделать)

2024-05-02 15:11 UTC, mfrolov89 commented
> > > * Сейчас при клике на кнопку "Скрыть все" сначала уезжают уведомления и только после некоторого времени кнопка. Надо чтобы вместе
> > 
> > 
> > Не уверен что получится что-то сделать, там c задержкой вызывается onChange при удалении, соответсвенно мы н сразу узнаем что уведомлений больше нет. Такая проблема была и при использовании хука, для получения кол-ва уведомлений, работает так же с задержкой
> 
> А ты на onclick кнопки подвяжись и тайм-ауты подгони (можно fade для кнопки сделать)

Это своего рода костыль, который решит проблему только на половину. Если закрывать уведомления через крестик, то это временной лаг останет, кнопка повисит еще какое-то время. И тогда получим 2 разных поведения: при общем закрытии кнопка скроется сразу, а при закрытии через уведомлении с задержкой и это уже 100% можно сказать что баг) В общем не уверен что такой вариант норм, согласен что это не очень выглядит и хорошо бы найти решение, но поведение хотелось бы видеть одинаковое. Может найду еще какие варианты решения.

2024-05-03 06:11 UTC, AndTem commented
Предыдущая версия уведомлений сломалась:
<img width="692" alt="Снимок экрана 2024-05-03 в 09 11 10" src="https://github.com/kaluga-astral/frontend/assets/23665108/994607ce-f56d-4660-a1a8-d03f3d1a4d63">

2024-05-03 06:21 UTC, AndTem commented
По UI:
- Не нужен ли какой-нибудь бэкдроп при раскрытии стэка? Попробуй наложить уведомления на SideModal, например, боюсь, что ui будет смешиваться в кучу
- Название кнопки считаю должно быть не "Скрыть уведомления", а "Закрыть уведомления". Я посчитал, что кнопка скроет мне стэк, а она закрыла уведомления
- Нужен пример того как ведут себя уведомления с таймерами. Кажется, будет очень странно, если они будут незаметно закрываться внутри стэка. Тут либо отдельно их отображать вне стэка, либо вообще от таймеров отказаться
- Виндопользователи не смогу пользоваться скроллом в уведомлениях потому, что при наведении курсора на скроллбар стэк скрывается
- До сих пор считаю, что ховер - не лучший триггер для открытия стэка. Будет много багов с этим связанных. Кнопка "Раскрыть/скрыть" более надежно работает, так в macos и сделано

2024-05-03 06:43 UTC, AndTem requested changes

2024-05-03 06:43 UTC, AndTem commented on packages/components/src/NotificationNext/NotificationNext.stories.tsx
> +export const WithStack = () => {
Нужно добавить кнопки для генерации info и error уведомлений. Чтобы можно было посмотреть как они стэкаются вместе

2024-05-03 06:43 UTC, AndTem commented on packages/components/src/Notification/NotificationTemplate/styles.ts
> +  margin-left: 16px;
spacing

2024-05-03 06:43 UTC, AndTem commented on packages/components/src/Notification/NotificationTemplate/styles.ts
>  export const Wrapper = styled.article<NotificationTemplateProps>`
Скорее всего для Next надо свои стили писать. Потому что сейчас старые уведомления сломаны

2024-05-03 06:43 UTC, AndTem commented on packages/components/src/NotificationNext/utils/getClassNameModifierByVariant.ts
> +import { type Variant } from '../types';
Утила в своей директории должна быть: https://kaluga-astral.github.io/style-guide/docs/rules/utils

2024-05-03 06:43 UTC, AndTem commented on packages/components/src/NotificationNext/utils/notificationTemplatePropsCreator.ts
> +export const notificationTemplatePropsCreator = (
https://kaluga-astral.github.io/style-guide/docs/rules/naming/functions#%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8-%D0%B8-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D1%8B-%D0%BD%D0%B0%D1%87%D0%B8%D0%BD%D0%B0%D1%82%D1%8C%D1%81%D1%8F-%D1%81-%D0%B3%D0%BB%D0%B0%D0%B3%D0%BE%D0%BB%D0%B0

2024-05-03 06:43 UTC, AndTem commented on packages/components/src/NotificationNext/styles.ts
> +  filled: boolean;
Сделал бы сразу через $

2024-05-03 06:43 UTC, AndTem commented on packages/components/src/NotificationNext/NotifacationStackContainerNext/styles.ts
> +    height: 100dvh;
Для поддержки браузеров не надо supports добавить с фэлбэком?

2024-05-03 06:43 UTC, AndTem commented on packages/components/src/NotificationNext/NotifacationStackContainerNext/hooks/useLogic/useLogic.ts
> +export const useLogic = ({
useLogic не надо заворачивать в hooks: https://kaluga-astral.github.io/style-guide/docs/rules/arch/modules/features/logic-hook#%D1%85%D1%83%D0%BA-%D1%81-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BA%D0%BE%D0%B9-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0-%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD-%D0%B8%D0%BC%D0%B5%D1%82%D1%8C-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-uselogic-%D0%B8-%D0%BD%D0%B0%D1%85%D0%BE%D0%B4%D0%B8%D1%82%D1%81%D1%8F-%D0%B2-%D0%BE%D1%82%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9-%D0%B4%D0%B8%D1%80%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%B8

2024-05-03 06:43 UTC, AndTem commented on packages/components/src/NotificationNext/NotifacationStackContainerNext/hooks/useLogic/useLogic.ts
> +  const container = document.querySelector(
На фазе render нельзя производить работу с document

2024-05-03 06:43 UTC, AndTem commented on packages/components/src/NotificationNext/NotifacationStackContainerNext/NotifacationStackContainerNext.tsx
> +  loadedContainerId: Id;
static может? Нужно такое название, которое потом подойдет и для других уведомлений, которые в стэк не должны попасть

2024-05-03 06:43 UTC, AndTem commented on packages/components/src/NotificationNext/NotificationNext.stories.tsx
> +      containerId: 'stack',
В проекте же не придется указывать containerId каждый раз при вызове?

2024-05-03 06:43 UTC, AndTem commented on packages/components/src/NotificationNext/NotificationNext.stories.tsx
> +      <NotificationContainerNext stacked containerId="hide-progress-bar" />
Не понял зачем отдельно StackedContainer и props stacked.
Задумка вроде была такая, чтобы стэк был всегда включен?

2024-05-07 14:21 UTC, Kostayne commented on packages/components/src/NotificationNext/NotifacationStackContainerNext/useLogic/useLogic.ts
> +      return undefined;
думаю undefined здесь лишний, обычного return вполне хватает

2024-05-07 14:21 UTC, Kostayne commented on packages/components/src/NotificationNext/NotifacationStackContainerNext/useLogic/useLogic.ts
> +      const isScroll = container?.scrollHeight > container?.clientHeight;
тут лучше бы подошло needScroll

2024-05-07 14:21 UTC, Kostayne commented on packages/components/src/NotificationNext/NotifacationStackContainerNext/useLogic/useLogic.ts
> +  const isVisibleCloseButton = Boolean(toasts.length);
isCloseButtonVisible | canClose

2024-05-07 14:21 UTC, Kostayne commented on packages/components/src/NotificationNext/NotificationTemplateNext/utils/getActionsDirection/getActionsDirection.ts
> +  const MAP_OF_DIRECTIONS = {
DIRECTIONS_MAP

2024-05-07 14:21 UTC, Kostayne commented on packages/components/src/NotificationNext/NotificationTemplateNext/utils/getNotificationTemplateStyles/getNotificationTemplateStyles.ts
> +  const mapOfStyles = {
stylesMap

2024-05-07 14:21 UTC, Kostayne commented on packages/components/src/NotificationNext/NotifacationStackContainerNext/useLogic/useLogic.ts
> +    const unsubscribe = toast.onChange(handleChange);
OnChange ничего не возвращает, в константе нет смысла.  

Функция handleChange вызывается лишь здесь, лучше заинлайнить весь ее код сюда и дописать коммент над useEffect, чтобы было понятно за что он отвечает.

2024-05-08 08:54 UTC, mfrolov89 commented on packages/components/src/NotificationNext/NotifacationStackContainerNext/useLogic/useLogic.ts
> +    const unsubscribe = toast.onChange(handleChange);
Возвращается коллбэк

https://fkhadra.github.io/react-toastify/listen-for-changes

2024-05-08 09:05 UTC, mfrolov89 commented on packages/components/src/NotificationNext/NotifacationStackContainerNext/useLogic/useLogic.ts
> +      const isScroll = container?.scrollHeight > container?.clientHeight;
Не соглашусь, во первых при такой нейминг не кореектен, необходимо добавить префикс is, во вторых мы узнаем есть ли скролл у контейнера, а не нужен ли он. Имя hasScroll сюда подойдет лучше.

2024-05-08 09:15 UTC, mfrolov89 commented on packages/components/src/NotificationNext/NotifacationStackContainerNext/useLogic/useLogic.ts
> +    }
При сравнении строк отличий в работе нет, просто предпочитаю запись в функциональном стиле

2024-05-08 09:16 UTC, mfrolov89 commented on packages/components/src/NotificationNext/NotifacationStackContainerNext/styles.ts
> +// к примеру добраться до прогресс бара можно только через цсс классы
Оставил его как и был

2024-05-13 09:57 UTC, merged