chore(UIKIT-903): Добавлен Cspeller, ускорен lint-staged
kaluga-astral/frontend pull request #942
Opened 2024-05-13 06:31 UTC by Kostayne

# Чеклист
- [X] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2024-05-13 08:10 UTC, AndTem requested changes

2024-05-13 08:10 UTC, AndTem commented on lint-staged.config.js
> +    (fileNames) =>
Так lint-staged же по-дефолту и запускает для каждого файла команду, если в массива строка указана

2024-05-13 08:10 UTC, AndTem commented on .eslintrc
> +  "extends": ["@astral/eslint-config-react-ts", "plugin:@cspell/recommended"],
cspell будет сильно замедлять eslint, он и так не быстрый.
Не уверен, что нужно чекать комменты потому, что там всегда много жаргонизмов, которые придется постоянно выписывать

2024-05-13 08:10 UTC, AndTem commented on .eslintrc
> +  "plugins": ["@cspell"],
yaspeller у нас как стандарт. Его считаешь, что нужно использовать другой инструмент, то это надо согласовывать ПЕРЕД тем, как начинать реализацию

2024-05-13 08:11 UTC, AndTem commented
Надо было просто скопировать решение: https://github.com/kaluga-astral/vite-boilerplate/blob/main/.yaspeller.json

2024-05-13 08:19 UTC, AndTem commented on .eslintrc
> +  "plugins": ["@cspell"],
Не знал. Тогда ок, давай попробуем.
Но из eslint его я думаю надо убрать, чтобы доп. нагрузку не создавал

2024-05-13 08:22 UTC, Kostayne commented on .eslintrc
> +  "extends": ["@astral/eslint-config-react-ts", "plugin:@cspell/recommended"],
в комментах довольно много грамматических ошибок, так что думаю проверку стоит оставить

Весь ходовой сленг уже используется и поэтому его легко вынести white list, что я собственно и сделал

2024-05-13 08:25 UTC, AndTem commented on .eslintrc
> +  "extends": ["@astral/eslint-config-react-ts", "plugin:@cspell/recommended"],
Попробуем 👍

2024-05-13 08:28 UTC, AndTem requested changes

2024-05-13 08:28 UTC, AndTem commented on changelog-generator/.eslintrc
> +    "@cspell/spellchecker": [
А для чего он выключается везде?

2024-05-13 08:28 UTC, AndTem commented on packages/components/package.json
> +    "@cspell/eslint-plugin": "^8.8.0",
Пакет в корне проекта должен стоять

2024-05-13 08:28 UTC, AndTem commented on project-words.txt
Нельзя файл в директории .cspell загнать, например? Чтобы не валялся просто так в корне? Или имя файла изменить

2024-05-13 08:29 UTC, Kostayne commented on changelog-generator/.eslintrc
> +    "@cspell/spellchecker": [
Решили его использовать только в критических местах

2024-05-13 08:29 UTC, Kostayne commented on project-words.txt
Можно, это не проблема

2024-05-13 11:03 UTC, Kostayne commented on lint-staged.config.js
> +    (fileNames) =>
Не нашел такого в доках и решил проверить так ли это, оказалось что нет. Как я и предполагал, проверялись все файлы пакетов

2024-05-13 11:15 UTC, AndTem commented on lint-staged.config.js
> +    (fileNames) =>
<img width="852" alt="Снимок экрана 2024-05-13 в 14 14 17" src="https://github.com/kaluga-astral/frontend/assets/23665108/5c062e76-61da-4c6d-967e-44c9936f414e">
То есть без fileNames будет вызван eslint src/components/A.ts src/components/B.ts

2024-05-13 11:16 UTC, Kostayne commented on lint-staged.config.js
> +    (fileNames) =>
вот этот тест зафейлился

![image](https://github.com/kaluga-astral/frontend/assets/64432956/fb67a87e-24a5-4a87-a740-5f7d9d8e5525)

2024-05-13 11:17 UTC, Kostayne commented on lint-staged.config.js
> +    (fileNames) =>
![image](https://github.com/kaluga-astral/frontend/assets/64432956/83e8561b-d09d-4062-af1c-9300177d05b6)

2024-05-13 11:20 UTC, Kostayne commented on lint-staged.config.js
> +    (fileNames) =>
Хотя ладно, тут не перенаправляются аргументы, тест некорректен

2024-05-13 11:22 UTC, AndTem commented on lint-staged.config.js
> +    (fileNames) =>
Я понял, проблема в формате команд для workspaes. Ok

2024-05-13 12:20 UTC, AndTem commented
Нужно еще в CI встроить проверку.
Но это можно отдельным PR

2024-05-13 12:21 UTC, Kostayne commented
> Нужно еще в CI встроить проверку. Но это можно отдельным PR

Ага, уже готово

2024-05-13 12:28 UTC, mfrolov89 commented on packages/components/src/Popover/Popover.stories.tsx
> +{
Посмотри сразу этот блок, тут скобки больше похожи на ошибку

2024-05-13 12:55 UTC, mfrolov89 commented on .cspell-ignore
> +// Это явно надо вынести в отдельный рефактор, так как ошибка затрагивает половину кода...
Необходимо завести задачу и разместить тут ссылку

2024-05-13 13:02 UTC, mfrolov89 commented on .cspell.json
> +  "language": "en,ru,la",
la это латынь? Зачем она нам нужна?

2024-05-13 13:03 UTC, Kostayne commented on .cspell.json
> +  "language": "en,ru,la",
это для lorem ipsum

2024-05-13 13:06 UTC, mfrolov89 commented on .cspell.json
> +  "language": "en,ru,la",
Если язык не указать, то он просто игнорирует проверку такого текста или выдает ошибки по нему? Кажется что на проверку такой рыбы можно не обращать внимание, а введение доп.словаря увеличивает нагрузку

2024-05-13 13:12 UTC, Kostayne commented on .cspell.json
> +  "language": "en,ru,la",
Если его не указать, то вылезет много ошибок. Lorem ipsum у нас используется очень часто и постоянно писать комментарии для отключения проверки непрактично, поэтому пускай лучше останется так

2024-05-14 07:47 UTC, mfrolov89 commented on .cspell.json
> +  "dictionaries": ["general"]
думаю стоит расширить следующими словарями: typescript, node, html, css

После этого можно будет немного подчистить список слов из игнора

2024-05-14 07:49 UTC, mfrolov89 commented on .cspell-ignore
> +chahgelog
тут явна опечатка, в коде используется всего в одном месте. Стоит поправить там и убрать из этого списка

2024-05-14 07:56 UTC, Kostayne commented on .cspell-ignore
> +// Популярное псевдо латинское слово, проще вынести в white list
не понимаю о чем ты, зачем забивать words если у нас есть отдельный файл

2024-05-14 07:59 UTC, mfrolov89 commented on .cspell-ignore
> +// Популярное псевдо латинское слово, проще вынести в white list
Тогда к чему твой коммент про white list и что ты под ним подразумеваешь?

2024-05-14 08:05 UTC, Kostayne commented on .cspell-ignore
> +// Популярное псевдо латинское слово, проще вынести в white list
White list - те слова, что могут использоваться и не вызовут ошибку. Whitelist'ом может служить отдельный файл или массив строк в файле конфигурации. Здесь комментарий говорит о том, что латинское слово вынесено в white list во избежание множества комментариев для отключения spell checker'а в коде.

2024-05-14 09:48 UTC, mfrolov89 requested changes

2024-05-14 09:48 UTC, mfrolov89 commented on .cspell-ignore
> +figcaption
проверить на ошибки, если удалить из списка

2024-05-14 09:48 UTC, mfrolov89 commented on .cspell-ignore
> +iframe
проверить на ошибки, если удалить из списка

2024-05-14 09:48 UTC, mfrolov89 commented on .cspell-ignore
> +instanceof
проверить на ошибки, если удалить из списка

2024-05-14 09:48 UTC, mfrolov89 commented on .cspell-ignore
> +nbsp
проверить на ошибки, если удалить из списка

2024-05-14 09:48 UTC, mfrolov89 commented on .cspell-ignore
> +noreferrer
проверить на ошибки, если удалить из списка

2024-05-14 09:48 UTC, mfrolov89 commented on .cspell-ignore
> +tbody
проверить на ошибки, если удалить из списка

2024-05-14 09:48 UTC, mfrolov89 commented on .cspell-ignore
> +tfoot
проверить на ошибки, если удалить из списка

2024-05-14 09:48 UTC, mfrolov89 commented on .cspell-ignore
> +אַחַת
удалить, добавить как локальное исключение

2024-05-14 11:09 UTC, mfrolov89 approved these changes

2024-05-16 07:21 UTC, merged