bug(UIKIT-1458,Profile): Добавлено ограничение ширины профиля
kaluga-astral/frontend pull request #969
Opened 2024-05-21 10:32 UTC by Kostayne

# Чеклист
- [X] Реализовать или обновить storybook для компонента
- [X] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)

2024-05-21 13:11 UTC, mfrolov89 requested changes
<img width="422" alt="Снимок экрана 2024-05-21 в 16 07 59" src="https://github.com/kaluga-astral/frontend/assets/47597207/58f3a64f-73fa-458e-a3b6-7167b761806a">
Отступ справа не соответсвует макету, нет троеточия у обрезанного текста

2024-05-21 13:11 UTC, mfrolov89 commented on packages/components/src/Profile/Profile.tsx
> +          css={{ background: 'red' }}
удали

2024-05-21 13:11 UTC, mfrolov89 commented on packages/components/src/Profile/Profile.tsx
> +          anchorOrigin={{
с позиционирование по умолчанию были проблемы?

2024-05-21 13:11 UTC, mfrolov89 commented on packages/components/src/Profile/styles.ts
> +  width: 100%;
странный набор св-в, укажи вместо них  overflow: hidden;

2024-05-21 13:13 UTC, Kostayne commented on packages/components/src/Profile/Profile.tsx
> +          anchorOrigin={{
да, везде по дефолту будет выравнивание слева

2024-05-22 07:54 UTC, mfrolov89 commented on packages/components/src/Profile/styles.ts
>    display: block;
div по умолчанию и так является блочном элементом, минимальная ширина выглядит как костыль, достатотчно укахзать overflow: hidden

<img width="374" alt="Снимок экрана 2024-05-22 в 10 53 34" src="https://github.com/kaluga-astral/frontend/assets/47597207/bcb295a6-0431-4716-a54f-7557184c1c00">

2024-05-22 07:57 UTC, mfrolov89 commented on packages/components/src/Profile/styles.ts
> +export const MenuContainer = styled.div`
хак не работает, отступ справа не изменяет. Ты не интересовался откуда там вообще этот отступ и должен ли он там быть?
<img width="355" alt="Снимок экрана 2024-05-22 в 10 56 03" src="https://github.com/kaluga-astral/frontend/assets/47597207/a78e2e1e-259f-463b-a8f6-0eef15f64202">

Считаю что эта обертка не нунжна, нужно разбираться с первоначальной причиной отступа. В противном случае достаточно стилизовать Menu

2024-05-22 08:32 UTC, Kostayne commented on packages/components/src/Profile/styles.ts
>    display: block;
display: block писал не я, задачи на рефактор не было, с overflow согласен, видимо  он и в правду может заменить min-width во флекс контейнере

2024-05-22 08:33 UTC, Kostayne commented on packages/components/src/Profile/styles.ts
> +export const MenuContainer = styled.div`
это не хак, отступ справа меняется, там просто потерялся апмерсанд, причина отступа вполне ясна и именно она здесь и резолвится

2024-05-22 08:35 UTC, Kostayne commented on packages/components/src/Profile/styles.ts
> +export const MenuContainer = styled.div`
в дизайне MenuItem отступы 12px с обоих сторон,  а тут 8, стилизацию лучше оставить

2024-05-23 12:57 UTC, Kostayne commented on packages/components/src/Profile/styles.ts
> +export const MenuContainer = styled.div`
откатил отступы, под фикс отступа справа нужно создать отдельный таск, он касается компонента MenuItem

2024-05-23 13:22 UTC, mfrolov89 commented on packages/components/src/Profile/styles.ts
>    display: block;
up

2024-05-23 13:25 UTC, mfrolov89 commented on packages/components/src/Profile/styles.ts
>  export const ProfileDisplayName = styled.span`
почему бы не применить Typography и не указать ему noWrap?  Тогда все новые св-ва будут не нужны. Возможно и часть св-в шрифтов покроется подходящим variant

2024-05-23 13:29 UTC, Kostayne commented on packages/components/src/Profile/styles.ts
>  export const ProfileDisplayName = styled.span`
Ok, why not

2024-05-23 13:31 UTC, mfrolov89 commented on packages/components/src/Profile/styles.ts
> +  span {
начинаю склоняться что на уровне Profile обрезать текст в текущей его реализации не безопасно. В menu может прилететь все что угодоно, с любой версткой. Там может быть другая структура, а можно заверстать и без них.

Возможно достаточно просто в примере обернуть текст в Typograpy с noWrap. Тем самым показать как оно должно быть.

В идеале думаю тут нужно идти по пути Select и инкапсулировать рендер списка.

Твое мнение?

2024-05-23 13:41 UTC, Kostayne commented on packages/components/src/Profile/styles.ts
> +  span {
Да, в этом есть резон. Тогда выпиливаем MenuContainer за ненадобностью и обновляем storybook

2024-05-24 07:12 UTC, mfrolov89 commented on packages/components/src/Profile/Profile.tsx
> +    const menuContainerRef = useRef<HTMLDivElement>(null);
Забыл удалить? Не вижу чтобы использовался

2024-05-24 07:18 UTC, mfrolov89 commented on packages/components/src/Profile/Profile.tsx
> +                <OverflowTypography noWrap>
Тут должен остаться ProfileCredentials, который является просто контейнером, который из стилей ты кстати не удалил. Обрезка текста на этом уровне через OverflowTypography не работает, используй его для ProfileDisplayName и ProfileAnnotation

2024-05-24 07:47 UTC, Kostayne commented on packages/components/src/Profile/Profile.tsx
> +    const menuContainerRef = useRef<HTMLDivElement>(null);
Осталось частичное испольование, выпилил его

2024-05-24 07:48 UTC, Kostayne commented on packages/components/src/Profile/Profile.tsx
> +                <OverflowTypography noWrap>
Да, согласен. Вынес typography в styled чтобы сохранить лаконичность и темизацию шрифта

2024-05-24 08:40 UTC, mfrolov89 approved these changes

2024-05-24 08:40 UTC, merged