@astral/ui | FEA | TextField. Добавлен forwardRef
kaluga-astral/frontend pull request #97
Opened 2022-02-16 13:12 UTC by StanislavDa

2022-02-16 14:33 UTC, perevezencev approved these changes

2022-02-16 14:36 UTC, AndTem commented on packages/ui/src/TextField/TextField.tsx
> +export const TextField = forwardRef<HTMLDivElement>(
Разве не HTMLInputElement?

2022-02-16 14:37 UTC, perevezencev commented on packages/ui/src/TextField/TextField.tsx
> +export const TextField = forwardRef<HTMLDivElement>(
не, он же обернут в div

2022-02-16 14:38 UTC, perevezencev commented on packages/ui/src/TextField/TextField.tsx
> +export const TextField = forwardRef<HTMLDivElement>(
InputProps={{inputRef: ref }}

2022-02-16 14:40 UTC, AndTem commented on packages/ui/src/TextField/TextField.tsx
> +export const TextField = forwardRef<HTMLDivElement>(
@perevezencev думаю, что да, должен быть вариант, который написал

2022-02-16 14:40 UTC, AndTem requested changes
жду правок

2022-02-16 18:44 UTC, perevezencev commented on packages/ui/src/TextField/TextField.tsx
> +        inputRef={ref}
А к `<div class="wrapper"` тогда как получить ref?

2022-02-17 06:28 UTC, AndTem commented on packages/ui/src/TextField/TextField.tsx
> +export const TextField = forwardRef<HTMLDivElement>(
@StanislavDa до этого было правильно. Ref у нас берётся для дива, но если нужен для реф инпуты прикидываемая пропаны как показал Паша

2022-02-17 07:05 UTC, perevezencev approved these changes

2022-02-17 07:34 UTC, AndTem approved these changes

2022-02-17 07:34 UTC, merged