feat(UIKIT-877,TreeLikeList): Реализован компонент TreeLikeList
kaluga-astral/frontend pull request #992
Opened 2024-06-05 14:17 UTC by mfrolov89

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-06-06 06:19 UTC, AndTem requested changes

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/TreeLikeList.tsx
> +export const TreeLikeList = <
Может название другое? Это достаточно странное.
Например, TreeSelect

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/types.ts
> +  multiple?: never;
Мне кажется, что надо сделать два отдельных компонента: один single, другой multiple.
И с точки зрения проектирования будет правильнее и с точки зрения tree shaking + проще будут компоненты

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/types.ts
> +  multiple?: never;
И намного проще будет типизация. Сейчас она неоправданно переусложненеа

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/TreeLikeList.tsx
> +  componentList = 'ul' as TComponentList,
А зачем кому то может понадобиться менять тэг?
Я думаю, что хватит одного пропса renderItem. При использовании rendreProps получится отказаться от сложной типизации с generic (она вообще не нужна тут считаю)

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/types.ts
> +  listProps?: ComponentProps<TComponentList>;
Думаю, что лишнее переусложнение. Сделай renderProps - renderItem и все эти проблемы уйдут

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/TreeItem/useLogic.ts
> +export const useLogic = ({ id, value, onChange }: UseLogicProps) => {
В отдельной директории должен быть https://kaluga-astral.github.io/style-guide/docs/rules/arch/modules/features/logic-hook

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/TreeItem/TreeItem.tsx
> +  children = [],
Пересечение нейминга с children React. Стоит переименовать, чтобы потом путанницы не было

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/CheckedTreeItem/CheckedTreeItem.tsx
> +            onClick={(event) => event.stopPropagation()}
https://kaluga-astral.github.io/style-guide/docs/rules/react/logic#%D0%B7%D0%B0%D0%BF%D1%80%D0%B5%D1%89%D0%B5%D0%BD%D0%B0-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%BE%D0%B2-%D0%B2-jsx

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/CheckedTreeItem/useLogic.ts
> +      return undefined;
Зачем из useEffect возвращать undefined?

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/CheckedTreeItem/useLogic.ts
> +      return undefined;
```suggestion
      return;
```

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/CheckedTreeItem/useLogic.ts
> +      onChange?.((selectedIds) => [...(selectedIds || []), id]);
```suggestion
      onChange?.((selectedIds = []) => [...selectedIds, id]);
```

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/CheckedTreeItem/utils/index.ts
> +export { checkIsIndeterminate } from './checkIsIndeterminate';
Директория utils должна быть внутри директории useLogic потому, что они являются частью имплементации useLogic

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/TreeLikeList.test.tsx
> +  it('Label опции отображается', () => {
```suggestion
  it('Label опции отображаются', () => {
```

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/TreeLikeList.test.tsx
> +  it('OnChange вызывается при изменении состояния', async () => {
```suggestion
  it('OnChange вызывается при выборе item', async () => {
```

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/TreeLikeList.stories.tsx
> +const TREE_LIST_MOCK_DATA = [
```suggestion
const FAKE_TREE_LIST_DATA = [
```

2024-06-06 06:19 UTC, AndTem commented on packages/components/src/TreeLikeList/TreeLikeList.stories.tsx
> +      data={TREE_LIST_MOCK_DATA}
Для каждой story надо опредялть данные внутри story, чтобы в storybook была видна структура данных

2024-06-06 08:19 UTC, mfrolov89 commented on packages/components/src/TreeLikeList/TreeLikeList.stories.tsx
> +      data={TREE_LIST_MOCK_DATA}
Там достаточно объемная константа с данными, не кажется что это наоборот усложнит просмотр story, так как сам пример будет где-то внизу  и нужно проскролить условно 60 строк с моковыми данными?

2024-06-06 08:22 UTC, mfrolov89 commented on packages/components/src/TreeLikeList/TreeItem/TreeItem.tsx
> +  children = [],
Подумаю над этим моментом, брал типовую структуру данных, они идет как в mui, так и в antd

2024-06-06 08:26 UTC, AndTem commented on packages/components/src/TreeLikeList/CheckedTreeItem/useLogic.ts
> +      return undefined;
Смотри коммент ниже. просто return достаточно

2024-06-06 08:27 UTC, AndTem commented on packages/components/src/TreeLikeList/TreeLikeList.stories.tsx
> +      data={TREE_LIST_MOCK_DATA}
Может хоть spread сделать для одного item, чтобы была видна структура

2024-06-06 08:43 UTC, mfrolov89 commented on packages/components/src/TreeLikeList/TreeLikeList.stories.tsx
> +      data={TREE_LIST_MOCK_DATA}
<img width="702" alt="Снимок экрана 2024-06-06 в 11 43 05" src="https://github.com/kaluga-astral/frontend/assets/47597207/ab56169d-f1a0-4125-9e97-5cbe24bbb28a">
Это имеешь в виду?

2024-06-06 08:47 UTC, AndTem commented on packages/components/src/TreeLikeList/TreeLikeList.stories.tsx
> +      data={TREE_LIST_MOCK_DATA}
Почти, добавить туда один элемент

2024-06-06 08:59 UTC, AndTem commented on packages/components/src/TreeLikeList/TreeLikeList.stories.tsx
> +      data={TREE_LIST_MOCK_DATA}
...FAKE_TREE, item: { label: '' }

2024-06-06 09:05 UTC, mfrolov89 commented on packages/components/src/TreeLikeList/types.ts
> +  multiple?: never;
Есть мысли как пошарить стили? Они более чем на 80% общие.
1. Дублировать стили по компонентам, это усложнение поддержки.
2. Определить их только в single и потом импортировать в multi не подойдет точно, зависимости не очевидны.
3. Оформить в виде отдельных компонентов? Это минимум плюсом еще 3 компонета, а может и 4.  Что много и это будет засорять директорию с компонентами, так как все эти компоненты не нужно экспортировать из пакета
4.  Пойти на компромис и оформить базовый item отдельным компонентом, а все остальные стили копировать по компонентам? Дублирующие стили тут остануться только для обертки списков, они простые и их дублирование не создат больших проблем с поддержкой.

4 вариант кажется наиболее оптимальным, что думаешь?

2024-06-06 09:08 UTC, AndTem commented on packages/components/src/TreeLikeList/types.ts
> +  multiple?: never;
Да, согласен

2024-06-07 10:42 UTC, AndTem requested changes

2024-06-07 10:42 UTC, AndTem commented on packages/components/src/TreeList/TreeList.tsx
> +export const TreeList = ({
Можно все, что связано с Tree положить в директорию Tree

2024-06-07 10:42 UTC, AndTem commented on packages/components/src/TreeList/TreeList.stories.tsx
> +  title: 'Components/TreeList',
```suggestion
  title: 'Components/Tree/TreeList',
```

2024-06-07 10:42 UTC, AndTem commented on packages/components/src/TreeList/TreeList.stories.tsx
> +  title: 'Components/TreeList',
Предлагаю сгруппировать

2024-06-07 10:42 UTC, AndTem commented on packages/components/src/index.ts
> +export { TreeItem, type TreeItemProps } from './TreeItem';
Думаю, что пока не надо это экспортировать

2024-06-07 10:42 UTC, AndTem commented on packages/components/src/TreeItem/types.ts
> +export type TreeItemProps<TComponent extends ElementType = ElementType> = {
В данном случае нет необходимости держать props в отдельном файле

2024-06-07 10:42 UTC, AndTem commented on packages/components/src/TreeItem/types.ts
> +   * Содержимое, отображающееся в при раскрытии элемента, если `isRoot` равен `true`
```suggestion
   * Содержимое, отображающееся при раскрытии элемента, если `isRoot` равен `true`
```

2024-06-07 10:42 UTC, AndTem commented on packages/components/src/TreeItem/types.ts
> +   * Содержимое, отображающееся в при раскрытии элемента, если `isRoot` равен `true`
А нужен isRoot тогда? Может чекать children просто?

2024-06-07 10:42 UTC, AndTem commented on packages/components/src/TreeList/types.ts
> +export type TreeListProps = {
Нет необходимости держать пропсы в отдельном файле

2024-06-07 10:42 UTC, AndTem commented on packages/components/src/TreeList/types.ts
> +   * Выбранные значения
```suggestion
   * Выбранное значение
```

2024-06-07 10:42 UTC, AndTem commented on packages/components/src/TreeList/types.ts
> +   * Дочернии элементы
```suggestion
   * Дочерние элементы
```

2024-06-07 10:42 UTC, AndTem commented on packages/components/src/TreeList/types.ts
> +  renderItem?: (id: string, label: ReactNode) => JSX.Element;
Не гибкой API.
Будет гибким, если ты будет кидать в параметр TreeData, а снаружи уже решат что им нужно.
JSX вроде deprecated, не?
Заюзай FunctionComponent<TreeData>

2024-06-07 10:42 UTC, AndTem commented on packages/components/src/MultipleTreeList/types.ts
> +    value: MultipleValue | ((value: MultipleValue) => Array<string>),
Что то странное. Почему onChange может принимать параметром фукнцию?

2024-06-07 10:42 UTC, AndTem commented on packages/components/src/MultipleTreeList/TreeItem/useLogic/useLogic.ts
> +      onChange?.((selectedIds) => [...(selectedIds || []), id]);
```suggestion
      onChange?.((selectedIds = []) => [...selectedIds, id]);
```

2024-06-07 10:42 UTC, AndTem commented on packages/components/src/MultipleTreeList/MultipleTreeList.stories.tsx
> +  return <MultipleTreeList data={fakeData} value={value} onChange={setValue} />;
Есть предложение по переработке API:
Data сделать чтобы принимал любые данные и добавить два пропса:
- idKey
- labelKey

Предполагаю, что использовать в таком варианте будет намного удобнее в форме

2024-06-07 10:43 UTC, AndTem commented on packages/components/src/index.ts
> +export { TreeItem, type TreeItemProps } from './TreeItem';
Соответсвенно и storybook не нужен тогда

2024-06-07 10:45 UTC, AndTem commented on packages/components/src/MultipleTreeList/MultipleTreeList.stories.tsx
> +  return <MultipleTreeList data={fakeData} value={value} onChange={setValue} />;
Не, сложно

2024-06-07 11:29 UTC, mfrolov89 commented on packages/components/src/MultipleTreeList/types.ts
> +    value: MultipleValue | ((value: MultipleValue) => Array<string>),
<img width="1233" alt="Снимок экрана 2024-06-07 в 14 27 37" src="https://github.com/kaluga-astral/frontend/assets/47597207/f314e51e-cb04-43c0-b6d3-013f6d6431e2">

2024-06-07 11:36 UTC, AndTem commented on packages/components/src/MultipleTreeList/types.ts
> +    value: MultipleValue | ((value: MultipleValue) => Array<string>),
SelectedIds - это же value.
У тебя сейчас пользователь компонента может прокинуть функцию, а зачем не понятно

2024-06-07 13:14 UTC, AndTem commented
Ошибки типов

2024-06-07 13:18 UTC, AndTem requested changes

2024-06-07 13:19 UTC, AndTem approved these changes

2024-06-07 13:23 UTC, mfrolov89 commented on packages/components/src/Tree/MultipleTreeList/types.ts
> +  onChange?: Dispatch<SetStateAction<MultipleValue>>;
Согласен, uncontrolled не стал делать, кажется что нет смысла для multiple с чекбоксами

2024-06-10 08:54 UTC, merged