feat(UIKIT-1295): Реализован SearchField
kaluga-astral/frontend pull request #995
Opened 2024-06-07 07:44 UTC by aesarantsev

# Чеклист

- [ ] Написать тесты для реализованного функционала
- [ ] Описать jsdoc для экспортируемых функций, компонентов
- [ ] Описать jsdoc для props экспортируемых компонентов
- [ ] Реализовать или обновить storybook для компонента
- [ ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
- [ ] Запросить ревью у дизайнера, если был изменен ui или создан новый компонент

2024-06-07 10:18 UTC, mfrolov89 requested changes
Забыл добавить реэкспорт в корневой index components

2024-06-07 10:18 UTC, mfrolov89 commented on packages/components/src/SearchField/SearchField.tsx
> +        startAdornment={<SearchOutlineMd />}
цвет иконки не по макету

2024-06-07 10:27 UTC, mfrolov89 requested changes

2024-06-07 10:27 UTC, mfrolov89 commented on packages/components/src/SearchField/SearchField.tsx
> +      margin = 'none',
Пропс сейчас не рабочий, поэтому  можно стилизовать локально TextField и убрать забронированное место под helperText, и оставить todo на задачу с margin.

helperText для поля поиска по идее лишний

2024-06-10 06:33 UTC, aesarantsev commented on packages/components/src/SearchField/SearchField.tsx
> +        startAdornment={<SearchOutlineMd />}
Вроде по макету все 

![image](https://github.com/kaluga-astral/frontend/assets/47385491/4966657f-41e1-4d67-9566-733f6bd6a472)
![image](https://github.com/kaluga-astral/frontend/assets/47385491/ef84b7ee-3fe7-4213-9f7a-0bfa81bffccc)

2024-06-10 07:41 UTC, mfrolov89 commented on packages/components/src/SearchField/SearchField.stories.tsx
> +export const HelperText = () => (
Сторя не актуальна, helperText не отображается

2024-06-10 10:08 UTC, mfrolov89 approved these changes

2024-06-11 04:56 UTC, merged